# Generated by Django 3.1.14 on 2022-01-10 12:21
# corrected by Olivier Le Thanh Duong 20 Jan
# Edited by Bram Jans 2 Oct 2023

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    replaces = [
        ("api_import", "0001_initial"),
        ("api_import", "0002_auto_20181207_1112"),
        ("api_import", "0003_site_is_reference"),
        ("api_import", "0004_auto_20181211_1233"),
        ("api_import", "0005_auto_20181211_1551"),
        ("api_import", "0006_auto_20181212_1005"),
        ("api_import", "0007_auto_20181218_0936"),
        ("api_import", "0008_auto_20181218_1426"),
        ("api_import", "0009_auto_20181218_1438"),
        ("api_import", "0010_auto_20181218_1457"),
        ("api_import", "0011_auto_20181220_1318"),
        ("api_import", "0012_apiimport_json_body"),
        ("api_import", "0013_gpsimport_count"),
        ("api_import", "0014_auto_20190104_1112"),
        ("api_import", "0015_auto_20190104_1231"),
        ("api_import", "0016_auto_20190109_1622"),
        ("api_import", "0017_catch_problem"),
        ("api_import", "0018_auto_20190221_1811"),
        ("api_import", "0019_auto_20190225_1007"),
        ("api_import", "0020_vector_refactor"),
        ("api_import", "0021_auto_20190227_1737"),
        ("api_import", "0022_site_creator"),
        ("api_import", "0023_trap_river"),
        ("api_import", "0024_remove_trap_is_reference"),
        ("api_import", "0025_auto_20190530_0943"),
        ("api_import", "0026_auto_20190531_0744"),
        ("api_import", "0027_auto_20190628_1129"),
        ("api_import", "0028_auto_20190628_1342"),
        ("api_import", "0029_apiimport_has_problem"),
        ("api_import", "0030_extra_info_api_import"),
        ("api_import", "0031_auto_20200721_1125"),
        ("api_import", "0032_auto_20210611_0951"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIImport",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "import_type",
                    models.TextField(
                        blank=True,
                        choices=[("site", "Site"), ("catch", "Catch"), ("target", "Target")],
                        max_length=25,
                        null=True,
                    ),
                ),
                ("json_body", django.contrib.postgres.fields.jsonb.JSONField(default="{}")),
            ],
            options={"db_table": "vector_control_apiimport"},
        ),
        migrations.AlterField(
            model_name="apiimport",
            name="import_type",
            field=models.TextField(
                blank=True,
                choices=[("trap", "Trap"), ("site", "Site"), ("catch", "Catch"), ("target", "Target")],
                max_length=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="apiimport",
            name="import_type",
            field=models.TextField(
                blank=True,
                choices=[
                    ("trap", "Trap"),
                    ("site", "Site"),
                    ("catch", "Catch"),
                    ("target", "Target"),
                    ("orgUnit", "Org Unit"),
                ],
                max_length=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="apiimport",
            name="import_type",
            field=models.TextField(
                blank=True,
                choices=[
                    ("trap", "Trap"),
                    ("site", "Site"),
                    ("catch", "Catch"),
                    ("target", "Target"),
                    ("orgUnit", "Org Unit"),
                    ("instance", "Form instance"),
                ],
                max_length=25,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="apiimport",
            name="has_problem",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="apiimport",
            name="exception",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="apiimport",
            name="headers",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="apiimport",
            name="import_type",
            field=models.TextField(
                blank=True, choices=[("orgUnit", "Org Unit"), ("instance", "Form instance")], max_length=25, null=True
            ),
        ),
        migrations.AlterField(
            model_name="apiimport",
            name="json_body",
            field=models.JSONField(),
        ),
    ]
