# Generated by Django 4.2.22 on 2025-09-07 19:25

import django.db.models.deletion

from django.conf import settings
from django.db import migrations, models

import hat.api_import.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIImport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "import_type",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("orgUnit", "Org Unit"),
                            ("instance", "Form instance"),
                            ("bulk", "Bulk Org Units and Instances"),
                            ("storageLog", "Storage logs"),
                        ],
                        max_length=25,
                        null=True,
                    ),
                ),
                ("json_body", models.JSONField()),
                ("headers", models.JSONField(blank=True, null=True)),
                ("has_problem", models.BooleanField(default=False)),
                ("exception", models.TextField(blank=True, default="")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=hat.api_import.models.api_import_upload_to,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apiimports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "vector_control_apiimport",
            },
        ),
    ]
