# Generated by Django 4.2.11 on 2024-04-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_import", "0002_alter_apiimport_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiimport",
            name="import_type",
            field=models.TextField(
                blank=True,
                choices=[
                    ("orgUnit", "Org Unit"),
                    ("instance", "Form instance"),
                    ("bulk", "Bulk Org Units and Instances"),
                ],
                max_length=25,
                null=True,
            ),
        ),
    ]
