# Generated by Django 4.2.15 on 2024-08-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_import", "0003_alter_apiimport_import_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiimport",
            name="import_type",
            field=models.TextField(
                blank=True,
                choices=[
                    ("orgUnit", "Org Unit"),
                    ("instance", "Form instance"),
                    ("bulk", "Bulk Org Units and Instances"),
                    ("storageLog", "Storage logs"),
                ],
                max_length=25,
                null=True,
            ),
        ),
    ]
