# Generated by Django 4.2.20 on 2025-05-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_import", "0004_alter_apiimport_import_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiimport",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="mobilebulkuploads"),
        ),
    ]
