# Generated by Django 4.2.20 on 2025-05-08 18:05

from django.db import migrations, models

import hat.api_import.models


class Migration(migrations.Migration):
    dependencies = [
        ("api_import", "0005_apiimport_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiimport",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to=hat.api_import.models.bulk_uploads_path),
        ),
    ]
