# Generated by Django 4.2.29 on 2026-03-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_import", "0006_alter_apiimport_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiimport",
            name="app_id",
            field=models.TextField(blank=True, null=False),
        ),
        migrations.AddField(
            model_name="apiimport",
            name="app_version",
            field=models.CharField(blank=True, max_length=25, null=False),
        ),
    ]
