# Generated by Django 4.2.30 on 2026-07-28 14:54

from django.db import migrations, models

import hat.api_import.models
import iaso.utils.models.sized_file_field


class Migration(migrations.Migration):
    dependencies = [
        ("api_import", "0007_apiimport_app_id_apiimport_app_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiimport",
            name="file_size",
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="apiimport",
            name="file",
            field=iaso.utils.models.sized_file_field.SizedFileField(
                blank=True, null=True, upload_to=hat.api_import.models.api_import_upload_to
            ),
        ),
    ]
