# Generated by Django 3.1.12 on 2021-07-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=models.TextField(),
        ),
    ]
