# https://github.com/astral-sh/ruff-pre-commit/tags
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.9.6
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
- repo: local
  hooks:
    - id: eslint
      name: eslint
      language: node
      files: ^hat/assets/js
      types_or: [ javascript, jsx, ts, tsx ]
      entry: npm run fix-lint
      pass_filenames: false