language: python

python:
  - '3.5'

sudo: required
group: edge

# Integration tests are temporarily disabled
# addons:
#   sauce_connect: true

services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION: 1.11.2
    - DOCKER_IMAGE_REPO: 387526361725.dkr.ecr.eu-west-1.amazonaws.com # the url of the repo where we push/pull the image from
    - DOCKER_IMAGE_NAME: sense-hat # the name of the image

before_install:
  # need to happen before first build
  - "./build_scripts/tfx_download.sh"

# Skip install step
install: true

script:
  - "docker-compose run hat test" # && docker-compose run -p 8081:8081 hat test_integration"

after_success:
  - pip install awscli awsebcli
  - "./build_scripts/tfx_upload.sh"
  - "./build_scripts/docker-build.sh"
