language: generic
sudo: required
services:
  - docker
env:
  DOCKER_COMPOSE_VERSION: 1.7.1
before_install:
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -qq --yes --force-yes docker-engine
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - sudo service docker restart
before_script:
  - docker-compose up -d db
script:
  - docker-compose run web flake8
  - docker-compose run web ./manage.py test
