version: '2'
services:
  db:
    image: postgres:9.5
  couchdb:
    image: couchdb:1.6
  redis:
    image: redis:3.2

  # the worker container of the task runner
  rq:
    build: .
    volumes:
      - .:/opt/app
      # shared dir between containers
      - ./shared:/opt/shared
    links:
      - db
      - couchdb
      - redis
    environment:
      - DEBUG=true
      - SECRET_KEY=secret
    command: start_rq

  # the django dev server container
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/opt/app
      # preserve node_modules from the image
      - /opt/app/node_modules
      # shared dir between containers
      - ./shared:/opt/shared
    links:
      - db
      - couchdb
    environment:
      - DEBUG=true
      - SECRET_KEY=secret
    command: start_devweb

  # the jupyter server
  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/opt/app
      # shared dir between containers
      - ./shared:/opt/shared
    links:
      - db
      - couchdb
    environment:
      - DEBUG=true
      - SECRET_KEY=secret
    command: start_jupyter
