services:
    iaso:
        stdin_open: true
        tty: true
        build:
            context: .
            dockerfile: Dockerfile
        image: iaso
        ports:
            - '8081:8081'
        links: &hat_links
            - db
        environment: &hat_environment
            APP_TITLE:
            AUTHENTICATION_ENFORCED: ${AUTHENTICATION_ENFORCED:-false}
            AWS_ACCESS_KEY_ID:
            AWS_SECRET_ACCESS_KEY:
            AWS_STORAGE_BUCKET_NAME:
            CLAMAV_ACTIVE:
            FORUM_PATH:
            CLAMAV_FQDN:
            DB_READONLY_PASSWORD: postgres
            DB_READONLY_USERNAME: postgres
            DEBUG: 'true'
            DEBUG_SQL:
            DISABLE_PASSWORD_LOGINS:
            DNS_DOMAIN:
            EMAIL_BACKEND: 'django.core.mail.backends.console.EmailBackend'
            ENABLE_ANALYTICS:
            ENABLE_GZIP: ${ENABLE_GZIP:-false}
            ENCRYPTED_TEXT_FIELD_KEY: bNqPWD4KdouaH-yxfl7PPdJLbbNt31mnJDwg9IHoGDM=
            ENKETO_API_TOKEN: AZE78974654azeAZE
            ENKETO_DEV: 'true'
            ENKETO_SIGNING_SECRET: supersecret
            ENKETO_URL: http://enketo:8005/
            FAVICON_PATH:
            GOOGLE_API_KEY_BASE64:
            LIVE_COMPONENTS:
            LOGO_PATH:
            LOGIN_LOGO_PATH:
            LQAS_PIPELINE: #Optional: the version of the pipeline to run
            LQAS_PIPELINE_VERSION: # "prod", "staging" or "custom". Use "custom" for local testing
            MAINTENANCE_MODE:
            OH_PIPELINE_TARGET:
            OPENHEXA_TOKEN: #OpenHexa API url
            OPENHEXA_URL: #OpenHexa pipeline ID
            PLUGINS:
            PREPAREDNESS_TEMPLATE_FR_ID:
            PREPAREDNESS_TEMPLATE_ID:
            PYTHONUNBUFFERED: 'true'
            RDS_DB_NAME:
            RDS_HOSTNAME: db
            RDS_PASSWORD: postgres
            RDS_USERNAME: postgres
            SECRET_KEY: secret
            SENTRY_ENVIRONMENT:
            SENTRY_FRONT_ENABLED:
            SENTRY_URL:
            PRODUCT_FRUITS_WORKSPACE_CODE:
            AVAILABLE_LANGUAGES:
            SERVER_URL:
            SHOW_NAME_WITH_LOGO:
            HIDE_BASIC_NAV_ITEMS:
            SUPERSET_ADMIN_PASSWORD:
            SUPERSET_ADMIN_USERNAME:
            SUPERSET_URL:
            TEST_PROD:
            THEME_PRIMARY_BACKGROUND_COLOR: #OpenHexa API token
            THEME_PRIMARY_COLOR:
            THEME_SECONDARY_COLOR:
            USER_MANUAL_PATH:
            WFP_AUTH_ACCOUNT:
            WFP_AUTH_CLIENT_ID:
            WFP_EMAIL_RECIPIENTS_NEW_ACCOUNT:
            USE_CELERY: ${USE_CELERY:-false}
            CELERY_BROKER_URL: ${CELERY_BROKER_URL:-}
            CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND:-}
        logging: &iaso_logging
            driver: 'json-file'
            options:
                max-size: '5k'
        command: start_dev

    db:
        # https://registry.hub.docker.com/r/postgis/postgis
        # Pinning specific minor versions of PostgreSQL and PostGIS is not easy.
        # https://github.com/postgis/docker-postgis/issues/396
        image: postgis/postgis:16-3.5
        logging: *iaso_logging
        ports:
            - '5433:5432'
        environment:
            POSTGRES_DB: ${RDS_DB_NAME}
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres


    # celery worker for wfp plugin
    redis:
        image: redis:7
        ports:
        - "6379:6379"
        profiles: ["celery"]
