                               List of relations
 Schema |                       Name                        | Type  |  Owner   
--------+---------------------------------------------------+-------+----------
 public | account_emailaddress                              | table | postgres
 public | account_emailconfirmation                         | table | postgres
 public | audit_modification                                | table | postgres
 public | auth_group                                        | table | postgres
 public | auth_group_permissions                            | table | postgres
 public | auth_permission                                   | table | postgres
 public | auth_user                                         | table | postgres
 public | auth_user_groups                                  | table | postgres
 public | auth_user_user_permissions                        | table | postgres
 public | django_admin_log                                  | table | postgres
 public | django_cache_table                                | table | postgres
 public | django_comment_flags                              | table | postgres
 public | django_comments                                   | table | postgres
 public | django_content_type                               | table | postgres
 public | django_migrations                                 | table | postgres
 public | django_session                                    | table | postgres
 public | django_site                                       | table | postgres
 public | django_sql_dashboard_dashboard                    | table | postgres
 public | django_sql_dashboard_dashboardquery               | table | postgres
 public | iaso_account                                      | table | postgres
 public | iaso_account_feature_flags                        | table | postgres
 public | iaso_accountfeatureflag                           | table | postgres
 public | iaso_algorithmrun                                 | table | postgres
 public | iaso_assignment                                   | table | postgres
 public | iaso_bulkcreateusercsvfile                        | table | postgres
 public | iaso_commentiaso                                  | table | postgres
 public | iaso_datasource                                   | table | postgres
 public | iaso_datasource_projects                          | table | postgres
 public | iaso_device                                       | table | postgres
 public | iaso_device_projects                              | table | postgres
 public | iaso_deviceownership                              | table | postgres
 public | iaso_deviceposition                               | table | postgres
 public | iaso_entity                                       | table | postgres
 public | iaso_entityduplicate                              | table | postgres
 public | iaso_entityduplicateanalyzis                      | table | postgres
 public | iaso_entitytype                                   | table | postgres
 public | iaso_exportlog                                    | table | postgres
 public | iaso_exportrequest                                | table | postgres
 public | iaso_exportstatus                                 | table | postgres
 public | iaso_exportstatus_export_logs                     | table | postgres
 public | iaso_externalcredentials                          | table | postgres
 public | iaso_featureflag                                  | table | postgres
 public | iaso_form                                         | table | postgres
 public | iaso_form_org_unit_types                          | table | postgres
 public | iaso_formattachment                               | table | postgres
 public | iaso_formpredefinedfilter                         | table | postgres
 public | iaso_formversion                                  | table | postgres
 public | iaso_group                                        | table | postgres
 public | iaso_group_org_units                              | table | postgres
 public | iaso_groupset                                     | table | postgres
 public | iaso_groupset_groups                              | table | postgres
 public | iaso_importgpkg                                   | table | postgres
 public | iaso_instance                                     | table | postgres
 public | iaso_instancefile                                 | table | postgres
 public | iaso_instancelock                                 | table | postgres
 public | iaso_jsondatastore                                | table | postgres
 public | iaso_link                                         | table | postgres
 public | iaso_mapping                                      | table | postgres
 public | iaso_mappingversion                               | table | postgres
 public | iaso_matchingalgorithm                            | table | postgres
 public | iaso_matchingalgorithm_projects                   | table | postgres
 public | iaso_orgunit                                      | table | postgres
 public | iaso_orgunitchangerequest                         | table | postgres
 public | iaso_orgunitchangerequest_new_groups              | table | postgres
 public | iaso_orgunitchangerequest_new_reference_instances | table | postgres
 public | iaso_orgunitreferenceinstance                     | table | postgres
 public | iaso_orgunittype                                  | table | postgres
 public | iaso_orgunittype_allow_creating_sub_unit_types    | table | postgres
 public | iaso_orgunittype_projects                         | table | postgres
 public | iaso_orgunittype_reference_forms                  | table | postgres
 public | iaso_orgunittype_sub_unit_types                   | table | postgres
 public | iaso_page                                         | table | postgres
 public | iaso_page_users                                   | table | postgres
 public | iaso_planning                                     | table | postgres
 public | iaso_planning_forms                               | table | postgres
 public | iaso_profile                                      | table | postgres
 public | iaso_profile_org_units                            | table | postgres
 public | iaso_profile_projects                             | table | postgres
 public | iaso_profile_user_roles                           | table | postgres
 public | iaso_project                                      | table | postgres
 public | iaso_project_feature_flags                        | table | postgres
 public | iaso_project_forms                                | table | postgres
 public | iaso_record                                       | table | postgres
 public | iaso_recordtype                                   | table | postgres
 public | iaso_recordtype_projects                          | table | postgres
 public | iaso_report                                       | table | postgres
 public | iaso_reportversion                                | table | postgres
 public | iaso_sourceversion                                | table | postgres
 public | iaso_storagedevice                                | table | postgres
 public | iaso_storagelogentry                              | table | postgres
 public | iaso_storagelogentry_instances                    | table | postgres
 public | iaso_storagepassword                              | table | postgres
 public | iaso_task                                         | table | postgres
 public | iaso_team                                         | table | postgres
 public | iaso_team_users                                   | table | postgres
 public | iaso_userrole                                     | table | postgres
 public | iaso_workflow                                     | table | postgres
 public | iaso_workflowchange                               | table | postgres
 public | iaso_workflowfollowup                             | table | postgres
 public | iaso_workflowfollowup_forms                       | table | postgres
 public | iaso_workflowversion                              | table | postgres
 public | polio_budgetevent                                 | table | postgres
 public | polio_budgetevent_target_teams                    | table | postgres
 public | polio_budgetfiles                                 | table | postgres
 public | polio_budgetstep                                  | table | postgres
 public | polio_budgetstepfile                              | table | postgres
 public | polio_budgetsteplink                              | table | postgres
 public | polio_campaign                                    | table | postgres
 public | polio_campaigngroup                               | table | postgres
 public | polio_campaigngroup_campaigns                     | table | postgres
 public | polio_campaignscope                               | table | postgres
 public | polio_config                                      | table | postgres
 public | polio_config_users                                | table | postgres
 public | polio_countryusersgroup                           | table | postgres
 public | polio_countryusersgroup_teams                     | table | postgres
 public | polio_countryusersgroup_users                     | table | postgres
 public | polio_destruction                                 | table | postgres
 public | polio_linelistimport                              | table | postgres
 public | polio_mailtemplate                                | table | postgres
 public | polio_notification                                | table | postgres
 public | polio_notificationimport                          | table | postgres
 public | polio_preparedness                                | table | postgres
 public | polio_reasonfordelay                              | table | postgres
 public | polio_round                                       | table | postgres
 public | polio_rounddatehistoryentry                       | table | postgres
 public | polio_roundscope                                  | table | postgres
 public | polio_roundvaccine                                | table | postgres
 public | polio_shipment                                    | table | postgres
 public | polio_spreadsheetimport                           | table | postgres
 public | polio_urlcache                                    | table | postgres
 public | polio_vaccineauthorization                        | table | postgres
 public | polio_workflowmodel                               | table | postgres
 public | socialaccount_socialaccount                       | table | postgres
 public | socialaccount_socialapp                           | table | postgres
 public | socialaccount_socialapp_sites                     | table | postgres
 public | socialaccount_socialtoken                         | table | postgres
 public | spatial_ref_sys                                   | table | postgres
 public | vector_control_apiimport                          | table | postgres
(138 rows)

