insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KASAY', 18.33594, -4.88567, 'camp bulungu', 141);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KASAY', 18.35328, -4.94082, 'camp dibaya', 229);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KASAY', 18.34923, -4.93122, 'camp kibengi', 456);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KASAY', 18.32284, -4.87937, 'camp luzolo', 433);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KASAY', 18.35971, -4.95662, 'camp Mbanza', 160);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KASAY', 18.33918, -4.87796, 'kasay parkin', 1542);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KASAY', 18.31096, -4.883, 'kasay village', 1453);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KASAY', 18.33413, -4.94716, 'kibengi villa', 487);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KASAY', 18.34294, -4.98331, 'mbanza kikumbi', 375);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KASAY', 18.30971, -4.83673, 'Mukilu poste', 174);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KASAY', 18.31533, -4.84312, 'Mukilu village', 536);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KASAY', 18.31962, -4.83216, 'punza 1', 277);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KASAY', 18.29961, -4.83786, 'punza 2', 369);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KASAY', 18.3549, -4.81887, 'PUNZA PLC', 97);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KASAY', 18.31052, -4.96642, 'samba', 354);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZAMBA I', 18.33601, -5.11309, 'gobari 1', 616);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZAMBA I', 18.28017, -5.14202, 'GOBARI 2', 353);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZAMBA I', 18.25841, -5.14506, 'gobari 3', 166);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZAMBA I', 18.15483, -4.97382, 'kazamba wa', 1000);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZAMBA I', 18.16662, -5.04998, 'KIKONDJI GO', 408);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZAMBA I', 18.23775, -5.10074, 'kindambi', 317);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZAMBA I', 18.28474, -4.97845, 'kingwadi', 162);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZAMBA I', 18.24471, -5.0934, 'KINZAMBA C', 251);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZAMBA I', 18.22012, -5.01195, 'KISAMBA MA', 463);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZAMBA I', 18.20311, -4.99819, 'kisambakon', 856);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZAMBA I', 18.27642, -5.04795, 'kobo', 307);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZAMBA I', 18.26202, -4.98548, 'mosango ma', 385);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZAMBA I', 18.32151, -5.00274, 'MOWAKA', 384);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZAMBA I', 18.22223, -5.06932, 'MUTELU', 662);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZAMBA I', 18.13583, -4.95348, 'muboko', 734);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZAMBA I', 18.25189, -5.0395, 'KINZAMBA V', 279);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZAMBA II', 18.00146, -5.04206, 'MOSENGE', 1069);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZAMBA II', 17.99723, -5.1072, 'F.FELO', 139);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZAMBA II', 18.09784, -5.06959, 'F.Kafungu', 70);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZAMBA II', 17.9744, -5.12047, 'F.Kasende', 102);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZAMBA II', 17.9686, -5.11437, 'F.Kimafu', 74);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZAMBA II', 17.96192, -5.11425, 'F.Mukunzu', 90);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZAMBA II', 18.05918, -5.04477, 'F.Tombi', 83);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZAMBA II', 17.99757, -5.06644, 'kikazmba', 430);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZAMBA II', 17.99917, -5.07579, 'kinzambamb', 400);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZAMBA II', 18.05095, -5.05363, 'kilembe', 821);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZAMBA II', 18.00145, -5.12026, 'kindalakiko', 488);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZAMBA II', 17.98117, -5.11169, 'kindalangan', 504);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZAMBA II', 18.03885, -5.10803, 'kingombening', 432);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZAMBA II', 18.03413, -5.09899, 'kingoykisemi', 664);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZAMBA II', 17.99382, -5.08792, 'kinzambacen', 728);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZAMBA II', 17.99943, -5.0785, 'Kinzambafo', 379);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZAMBA II', 18.09018, -5.05658, 'lokosibamba', 801);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZAMBA II', 18.06377, -5.0588, 'lokosibango', 741);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZAMBA II', 17.9824, -5.11961, 'mbulu', 884);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZAMBA II', 18.02458, -5.07172, 'mbushi', 385);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZAMBA II', 18.05345, -5.05203, 'kikwati', 834);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZAMBA II', 18.02785, -5.03039, 'mosengepla', 459);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZAMBA II', 18.03349, -5.07925, 'Mwanakangu', 353);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZAMBA II', 18.0152, -5.05605, 'kipashi', 653);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZAMBA II', 17.93643, -5.16821, 'kipatamusu', 1079);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZAMBA II', 17.94923, -5.14263, 'kivunda', 283);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZAMBA II', 17.99104, -5.13295, 'kibwimba', 1015);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZAMBA II', 17.97565, -5.09955, 'kinzambayeye', 664);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZANDA', 18.11682, -5.36984, 'bangalala', 984);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZANDA', 18.19815, -5.30503, 'camp bankoto', 56);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZANDA', 18.18346, -5.25856, 'kakundji', 430);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZANDA', 18.18875, -5.19622, 'kambu', 57);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZANDA', 18.18324, -5.34289, 'kamingu', 371);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZANDA', 18.15906, -5.26672, 'kanoshi', 240);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZANDA', 18.18285, -5.32675, 'kasodi', 450);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZANDA', 18.19437, -5.21031, 'kihunga', 504);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZANDA', 18.13129, -5.32355, 'KINGOMBE', 468);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZANDA', 18.18685, -5.22739, 'luhemba kafi', 852);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZANDA', 18.14691, -5.29173, 'KINZANDA', 452);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZENZENGO', 17.97137, -5.22838, 'Kiboti', 537);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZENZENGO', 17.96392, -5.29976, 'Kinzenzengo', 750);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZENZENGO', 17.96611, -5.28224, 'Kandondolo', 208);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZENZENGO', 17.9746, -5.32996, 'Kazamba', 260);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZENZENGO', 17.95344, -5.30565, 'Kifungula', 1082);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZENZENGO', 17.97292, -5.23422, 'Kimbimbi', 1175);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZENZENGO', 18.06372, -5.29592, 'Kitombe', 804);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZENZENGO', 18.05863, -5.33734, 'Kitshay', 317);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZENZENGO', 17.96674, -5.24986, 'Kivanda', 734);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZENZENGO', 18.0334, -5.30645, 'Luhemba', 217);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZENZENGO', 17.96794, -5.27783, 'Mukukukandond', 446);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZENZENGO', 18.04867, -5.25582, 'Mulutu', 1008);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KINZENZENGO', 18.03806, -5.32033, 'Mundu', 145);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KIPEMBE', 17.97908, -5.1785, 'KIPEMBE', 1809);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KIPEMBE', 18.05597, -5.21797, 'Bisangi', 167);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KIPEMBE', 17.97333, -5.20252, 'Kimbusi', 227);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KIPEMBE', 17.98238, -5.15395, 'kingombe', 692);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KIPEMBE', 18.03206, -5.15899, 'Kisala', 203);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KIPEMBE', 18.02082, -5.16867, 'KUMBI', 108);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KIPEMBE', 17.97566, -5.21437, 'Nzombi', 1681);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KIPWANGA', 18.28136, -4.95655, 'Ferme mbam', 431);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KIPWANGA', 18.27482, -4.9657, 'Ferme ndunga', 33);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KIPWANGA', 18.18095, -4.91285, 'Kahemba', 94);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KIPWANGA', 18.24546, -4.85511, 'Kazamba', 448);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KIPWANGA', 18.27678, -4.83427, 'Kikakala', 177);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KIPWANGA', 18.20938, -4.85812, 'Kikama', 632);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KIPWANGA', 18.28066, -4.94908, 'Kikwati', 44);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KIPWANGA', 18.27848, -4.8866, 'Kimanu', 325);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KIPWANGA', 18.25511, -4.88992, 'Kindundu', 849);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KIPWANGA', 18.23217, -4.87294, 'Kipwanga', 640);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KIPWANGA', 18.24041, -4.86066, 'Kipwanga CS', 33);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KIPWANGA', 18.20309, -4.95839, 'Koshiavion', 39);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KIPWANGA', 18.22969, -4.94448, 'Koshibalaba', 284);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KIPWANGA', 18.20753, -4.92107, 'Koshibarriere', 776);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KIPWANGA', 18.20771, -4.92102, 'Koshimuluwa', 376);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KIPWANGA', 18.28546, -4.92438, 'Maboki', 388);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KIPWANGA', 18.25888, -4.84961, 'Mbwedi fiot', 790);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KIPWANGA', 18.28209, -4.91684, 'sangi', 229);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KIPWANGA', 18.25118, -4.94555, 'Yoko', 356);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KITAMBO', 18.04922, -4.75417, 'Kitamboplate', 301);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KITAMBO', 18.0441, -4.75549, 'Kitamboposte', 768);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KITAMBO', 18.03916, -4.76459, 'kitambovilla', 343);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KITAMBO', 18.00104, -4.7474, 'Mamboma', 949);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KITAMBO', 18.01272, -4.74472, 'Mwinda', 1708);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KITAMBO', 18.03817, -4.71424, 'kinangulu', 974);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KITAMBO', 18.02902, -4.74876, 'Pasasi', 943);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KUMBI MBWANA', 18.21245, -4.75145, 'Mundanda', 421);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KUMBI MBWANA', 18.21759, -4.76303, 'Sondji', 1028);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KUMBI MBWANA', 18.27451, -4.80489, 'Bagata', 420);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KUMBI MBWANA', 18.22693, -4.78074, 'kamba', 623);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KUMBI MBWANA', 18.20919, -4.79339, 'Kiyansi', 588);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KUMBI MBWANA', 18.25393, -4.78221, 'kumbi poste', 657);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KUMBI MBWANA', 18.25309, -4.7781, 'Kumbivillage', 473);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KUMBI MBWANA', 18.26962, -4.79589, 'kwati', 510);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KUMBI MBWANA', 18.27672, -4.76424, 'Kwaya', 668);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KUMBI MBWANA', 18.24137, -4.74481, 'Mazemba', 398);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KUMBI MBWANA', 18.22809, -4.81806, 'mbwedinene', 668);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KUMBI MBWANA', 18.29691, -4.78336, 'Mibambi', 171);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KUMBI MBWANA', 18.26857, -4.77529, 'Misimbidi', 156);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KUMBI MBWANA', 18.20328, -4.75467, 'Mulondo', 198);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KUMBI MBWANA', 18.27659, -4.78957, 'ngombe', 97);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KUMBI MBWANA', 18.24, -4.81007, 'Nzombi', 50);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KUMBI MBWANA', 18.22612, -4.80109, 'Poste kiyansi', 134);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'KUMBI MBWANA', 18.31486, -4.78168, 'Poste Mibambi', 85);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MANGUNGU', 18.04725, -5.10916, 'Kingoy', 905);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MANGUNGU', 18.09319, -5.0001, 'Kanika', 1574);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MANGUNGU', 18.14407, -5.04978, 'Mushima', 525);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MANGUNGU', 18.07299, -5.09466, 'Butindi', 363);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MANGUNGU', 18.16836, -5.11659, 'Kabeba', 241);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MANGUNGU', 18.04767, -5.16949, 'Kimafu', 272);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MANGUNGU', 18.13203, -5.18672, 'Kimbamba', 170);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MANGUNGU', 18.16856, -5.13601, 'Kimvunzi', 395);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MANGUNGU', 18.16168, -5.10847, 'Kinzasi', 199);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MANGUNGU', 18.11852, -5.15248, 'Luteki', 116);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MANGUNGU', 18.09824, -5.11457, 'M ngunguvilla', 304);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MANGUNGU', 18.10424, -5.11482, 'Mangungu', 30);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MANGUNGU', 18.11547, -5.21531, 'Misongo', 97);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MANGUNGU', 18.08978, -5.14208, 'Mutanunu', 37);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MANGUNGU', 18.15447, -5.08846, 'Ngadi', 243);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MANGUNGU', 18.08987, -4.98472, 'Setuka', 879);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MANGUNGU', 18.06177, -5.18944, 'Vushi', 151);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MANGUNGU', 18.05405, -5.13782, 'Kindinga', 572);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MANGUNGU', 18.08901, -5.15718, 'Mutema', 187);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MOSANGO', 18.04422, -4.82364, 'Kumbibanga', 1071);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MOSANGO', 18.00238, -4.80544, 'Kumbifioti', 286);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MOSANGO', 18.11956, -4.83533, 'C/Kalina', 161);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MOSANGO', 18.12535, -4.82286, 'C/Kibalula', 417);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MOSANGO', 18.12529, -4.83433, 'C/Majorité', 422);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MOSANGO', 18.11256, -4.84331, 'C/Pompe', 6691);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MOSANGO', 18.16315, -4.8288, 'Kibwingi', 206);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MOSANGO', 18.14034, -4.92255, 'Kikondji', 972);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MOSANGO', 17.99923, -4.82716, 'Kimbuku', 240);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MOSANGO', 18.15316, -4.90125, 'Kingwangala', 353);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MOSANGO', 18.03958, -4.82181, 'Kumbimako', 814);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MOSANGO', 18.06745, -4.8237, 'Kwati', 204);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MOSANGO', 18.15204, -4.8645, 'luzasa', 524);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MOSANGO', 18.15389, -4.8048, 'Mbanza', 275);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MOSANGO', 18.11612, -4.88451, 'Mosangosect', 1085);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MOSANGO', 18.12324, -4.8356, 'Mosangovill', 1238);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MUDIAMBU', 18.16922, -4.5944, 'kipasi', 1471);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MUDIAMBU', 18.1402, -4.68094, 'kimbimbi', 660);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MUDIAMBU', 18.15444, -4.69521, 'KONGO', 540);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MUDIAMBU', 18.14824, -4.67906, 'MAVULA', 532);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MUDIAMBU', 18.17224, -4.63909, 'mbambalako', 607);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MUDIAMBU', 18.17182, -4.67523, 'Mbanzamund', 1223);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MUDIAMBU', 18.15126, -4.65989, 'MUDIAMBU', 863);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MUDIAMBU', 18.17027, -4.65264, 'kimwanza', 946);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MUDIAMBU', 18.12564, -4.66251, 'mikwati', 559);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MULUMA', 18.06274, -4.75667, 'Kisala lupa', 975);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MULUMA', 18.13207, -4.731, 'BIBULUKU', 217);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MULUMA', 18.10455, -4.75272, 'bunda', 359);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MULUMA', 18.09531, -4.77085, 'Kindundu', 211);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MULUMA', 18.11208, -4.73318, 'Kivamva vill', 74);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MULUMA', 18.11292, -4.7311, 'kivamvamiss', 469);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MULUMA', 18.11652, -4.72274, 'Mbujingomb', 266);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MULUMA', 18.09231, -4.76303, 'Muluma centr', 1712);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MULUMA', 18.09622, -4.75539, 'Mulumavilla', 143);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MULUMA', 18.07845, -4.77893, 'Mundonda1', 884);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MULUMA', 18.09441, -4.77583, 'Mundonda2', 360);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MULUMA', 18.14642, -4.72137, 'Musumba', 380);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MUWANDA KOSO', 18.1986, -4.79976, 'Kabeba', 561);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MUWANDA KOSO', 18.19098, -4.80957, 'Kabeba 2', 252);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MUWANDA KOSO', 18.17191, -4.73643, 'Kimolo', 209);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MUWANDA KOSO', 18.18044, -4.74751, 'Kimolo2', 77);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MUWANDA KOSO', 18.14573, -4.73171, 'Kisala', 296);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MUWANDA KOSO', 18.18694, -4.84677, 'Kiyamba', 553);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MUWANDA KOSO', 18.17277, -4.80063, 'Matundu', 366);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MUWANDA KOSO', 18.16748, -4.75288, 'muwanda', 125);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MUWANDA KOSO', 18.14392, -4.77925, 'Ngongokahu', 253);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MUWANDA KOSO', 18.14307, -4.7697, 'Ngongokazi', 203);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MUWANDA KOSO', 18.15312, -4.77893, 'Ngongomukw', 614);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MUWANDA KOSO', 18.17539, -4.75839, 'Ngula', 465);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MUWANDA KOSO', 18.19395, -4.81294, 'Polongo', 213);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'MUWANDA KOSO', 18.16865, -4.76067, 'Poste muwanda', 126);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'TUMIKIA', 18.0643, -4.65425, 'Kinzuku', 921);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'TUMIKIA', 18.07616, -4.684, 'Sakambanza', 988);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'TUMIKIA', 18.09542, -4.68961, 'Tumikavilla', 519);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'TUMIKIA', 18.06761, -4.66601, 'Kikasakasa', 161);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'TUMIKIA', 18.08181, -4.71072, 'kimbandanji', 470);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'TUMIKIA', 18.05887, -4.66049, 'KimputuPLC', 206);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'TUMIKIA', 18.12502, -4.69772, 'Kingafioti', 412);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'TUMIKIA', 18.04768, -4.68532, 'Kingoma', 523);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'TUMIKIA', 18.05325, -4.68353, 'Kingomamwa', 282);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'TUMIKIA', 18.07682, -4.63911, 'Kisalangubu', 373);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'TUMIKIA', 18.07307, -4.70424, 'Mabamfu', 243);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'TUMIKIA', 18.10611, -4.67116, 'Mbelo', 263);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'TUMIKIA', 18.14253, -4.70241, 'Mundonda', 263);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'TUMIKIA', 18.09057, -4.68365, 'TUMIKIA MC', 1246);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'YENZI', 18.24575, -4.72142, 'Kimbwalu1', 459);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'YENZI', 18.20618, -4.72532, 'Kayanda', 977);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'YENZI', 18.20072, -4.7087, 'Kibwanga', 321);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'YENZI', 18.16885, -4.7122, 'Kimbandaku', 857);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'YENZI', 18.22497, -4.71927, 'Kimbwalu 2', 279);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'YENZI', 18.1851, -4.69352, 'Kindundubason', 299);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'YENZI', 18.19464, -4.68435, 'Kiseki', 359);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'YENZI', 18.18052, -4.72109, 'Kumbimuziazia', 584);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'YENZI', 18.18729, -4.70589, 'Mbelokibwa', 354);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'YENZI', 18.17277, -4.70868, 'Mbelolufun', 222);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'YENZI', 18.19044, -4.73842, 'Mundonda', 461);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'YENZI', 18.20734, -4.71189, 'Musukubengi', 74);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'YENZI', 18.16308, -4.70789, 'poste Kongo', 139);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'MOSANGO', 'YENZI', 18.20502, -4.70888, 'Yenzi', 490);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'BENGI', 17.75883, -4.46601, 'BENGI', 466);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'BENGI', 17.75261, -4.40136, 'BUKANGA NG', 817);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'BENGI', 17.72727, -4.41615, 'KIBAY', 1467);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'BENGI', 17.72366, -4.47206, 'KINA NG', 471);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'BENGI', 17.76699, -4.447, 'KINDUNDU', 340);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'BENGI', 17.75657, -4.46859, 'KINKWE   NZEY', 140);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'BENGI', 17.71149, -4.4723, 'KISELEDI', 351);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'BENGI', 17.69586, -4.46923, 'MANIE  MIBOTI', 1324);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'BENGI', 17.81046, -4.47592, 'MBANZA  W NS', 349);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'BENGI', 17.745, -4.49224, 'MBAYA', 993);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'BENGI', 17.79166, -4.50798, 'MUWELE', 334);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'BENGI', 17.78764, -4.43904, 'POMBE', 229);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'BILILI', 18.04024, -4.26905, 'BILILI  V', 775);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'BILILI', 18.04501, -4.27504, 'BILILI C', 714);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'BILILI', 18.04651, -4.28809, 'BUZIKI', 2890);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'BILILI', 18.09927, -4.29661, 'KIPUMUSU', 205);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'BILILI', 18.05969, -4.21871, 'KKT MUBW', 1221);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'BILILI', 18.0675, -4.19716, 'MANIE', 1166);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'BILILI', 18.08211, -4.22411, 'MUBWA  M', 1118);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'BILILI', 18.08211, -4.22411, 'MUBWA  NT', 1094);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'BILILI', 18.09915, -4.26322, 'MUNKAYA', 1162);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'BILILI', 18.10271, -4.2665, 'MUWAKA', 212);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'BILILI', 18.09035, -4.28876, 'PUKUSU', 2818);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'BUSEKE', 17.99836, -4.21045, 'BUSEKE', 1480);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'BUSEKE', 18.0172, -4.17665, 'BWATUNDU', 4188);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'BUSEKE', 17.99742, -4.24798, 'DUNGA I', 2040);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'BUSEKE', 18.00331, -4.21851, 'DUNGA II', 509);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'BUSEKE', 17.95863, -4.17431, 'KILAKA', 40);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'BUSEKE', 17.9809, -4.20866, 'LUDALA', 629);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'BUSEKE', 17.99833, -4.18664, 'MIPELENGE', 1383);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'BUSEKE', 17.95808, -4.19155, 'SANGI', 162);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'DUNDA', 17.67538, -4.63624, 'BAKONDA', 313);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'DUNDA', null, null, 'CAMP KIMBA', 57);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'DUNDA', 17.69831, -4.56504, 'DUNDA', 1296);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'DUNDA', 17.68176, -4.5526, 'DUNDA  US', 637);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'DUNDA', 17.67884, -4.64232, 'KIMBIKI', 420);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'DUNDA', 17.67604, -4.6705, 'KIMWELA', 1165);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'DUNDA', 17.69117, -4.6068, 'KINDAMBI', 1117);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'DUNDA', 17.68406, -4.61287, 'KINGOMA', 325);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'DUNDA', 17.66063, -4.67792, 'KISOKO', 976);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'DUNDA', 17.68374, -4.65413, 'KIWILU', 1399);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'DUNDA', 17.69058, -4.56416, 'MUMBANDA', 1194);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'DUNDA', 17.69574, -4.5863, 'TEBA', 481);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'FULA', 17.95209, -4.63758, 'FULA', 1365);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'FULA', 17.97672, -4.59296, 'KAZAMBA', 324);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'FULA', 17.9188, -4.55718, 'KIKONGO', 580);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'FULA', 17.93895, -4.67333, 'KIKONZI MAT', 619);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'FULA', 17.95951, -4.57462, 'KIKONZI MF', 471);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'FULA', 17.96411, -4.61361, 'KIMBANZI', 421);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'FULA', 17.94533, -4.57819, 'KIMBEMBO', 450);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'FULA', 17.93196, -4.60514, 'KIMBULU', 620);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'FULA', 17.97503, -4.57932, 'KIMBUMBA', 470);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'FULA', 17.95377, -4.60368, 'KINGOMBE', 64);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'FULA', 17.90219, -4.60604, 'KINTOTLA', 900);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'FULA', 17.91869, -4.62976, 'KIPALANGA', 522);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'FULA', 17.92015, -4.58384, 'KISANGANI', 272);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'FULA', 17.96537, -4.66431, 'KISEMBO', 1804);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'FULA', 17.90585, -4.65115, 'KISOMBO', 1126);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'FULA', 17.92932, -4.53438, 'MAYUMBU', 120);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'FULA', 17.91861, -4.55887, 'MBANZA MU', 676);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'FULA', 17.97836, -4.59769, 'MIBOTI', 978);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'FULA', 17.95844, -4.64919, 'MITIMITI', 450);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'FULA', 17.97193, -4.6089, 'NGONDI', 3451);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'FULA', 17.91987, -4.55479, 'NZOMBI', 331);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'FULA', 17.97804, -4.55117, 'PONT KAFI', 141);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'FULA', 17.90317, -4.62807, 'SAKAMBANZA', 503);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'FULA', 17.96143, -4.62516, 'YELENGE', 136);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIAMFU', 17.94813, -4.37232, 'BULANGUNGA', 247);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIAMFU', 17.99894, -4.35457, 'KIAMFU  I', 743);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIAMFU', 17.99894, -4.35457, 'KIAMFU LU', 465);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIAMFU', 18.01481, -4.36651, 'KIAMFUII', 517);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIAMFU', 18.00718, -4.3383, 'KIBWARI', 934);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIAMFU', 18.00293, -4.39575, 'KINGONZI', 209);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIAMFU', 17.97892, -4.34791, 'KINZAMBA', 163);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIAMFU', 17.98542, -4.43495, 'KISEMBO', 469);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIAMFU', 18.02057, -4.43227, 'KIZIA I', 923);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIAMFU', 17.9574, -4.41366, 'KULUNGU', 103);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIAMFU', 18.05979, -4.32862, 'MAWA', 394);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIAMFU', 18.02725, -4.37697, 'MITOY CE', 795);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIAMFU', 18.02595, -4.37913, 'MITOY V', 436);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIAMFU', 17.98783, -4.43747, 'MUKOKO  II', 173);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIAMFU', 18.06062, -4.32885, 'MUNDONDA', 1245);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIAMFU', 17.96162, -4.3588, 'NGALANGI', 693);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIAMFU', 17.9768, -4.43299, 'NZOMBI', 460);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIAMFU', 17.9561, -4.40745, 'TETI', 464);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMBINGA', 18.06607, -4.60477, 'B W EZO', 224);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMBINGA', 18.04791, -4.61354, 'BWALA YU', 1045);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMBINGA', 18.06582, -4.56332, 'KAMBOKO', 35);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMBINGA', 18.06151, -4.6012, 'KASOTA', 58);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMBINGA', 18.06001, -4.5793, 'KIBWADI', 565);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMBINGA', 18.04701, -4.58911, 'KIMB ING II', 214);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMBINGA', 18.05454, -4.59356, 'KIMBING  M', 634);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMBINGA', 18.05135, -4.59568, 'KIMBINGA I ', 426);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMBINGA', 18.09286, -4.57456, 'KIMBUMBA', 413);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMBINGA', 18.03886, -4.58697, 'KIMWANZA', 1341);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMBINGA', 18.08276, -4.56569, 'KINDAMBI', 685);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMBINGA', 18.06154, -4.60103, 'KINDONGO', 311);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMBINGA', 18.06601, -4.60647, 'KINDONGO V', 295);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMBINGA', 18.06966, -4.59883, 'KINGULU', 361);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMBINGA', 18.03779, -4.5745, 'KISELELE', 236);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMBINGA', 18.0544, -4.5671, 'MAZINGA', 430);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMBURI', 17.94258, -4.34117, 'C C ROUGE', 231);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMBURI', 17.94938, -4.34014, 'CAMP PARCE', 1771);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMBURI', 17.94725, -4.32426, 'CAMP STAD', 1358);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMBURI', 17.95612, -4.34733, 'KIMANSEKE', 344);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMBURI', 17.99547, -4.31513, 'KIMBURI', 703);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMBURI', 17.9812, -4.28767, 'KINGOMBE', 1271);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMBURI', 17.99345, -4.2962, 'KINKUKU', 844);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMBURI', 17.96018, -4.35195, 'LUBOLO', 559);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMBURI', 17.99873, -4.31657, 'MBAWIMI', 691);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMBURI', 17.97061, -4.33332, 'MOKAMO', 642);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMBURI', 17.94969, -4.32907, 'PUPU', 788);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMBWAYAMU', 17.88609, -4.48811, 'BONDO', 596);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMBWAYAMU', 17.92867, -4.5246, 'BULAMBEMBA', 602);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMBWAYAMU', 17.8435, -4.56093, 'KAZAMBA', 285);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMBWAYAMU', 17.84577, -4.55122, 'KAZAMBA V', 210);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMBWAYAMU', 17.86709, -4.56214, 'KILEMBE', 925);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMBWAYAMU', 17.87139, -4.55978, 'KIMBANDA', 822);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMBWAYAMU', 17.92817, -4.51593, 'KIMBINGA', 315);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMBWAYAMU', 17.87952, -4.53589, 'KIMBWAYAMU', 1273);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMBWAYAMU', 17.83543, -4.51107, 'KINKAMA', 831);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMBWAYAMU', 17.91053, -4.50442, 'KINTULU', 1057);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMBWAYAMU', 17.85958, -4.52371, 'KIPINDI', 596);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMBWAYAMU', 17.90076, -4.49976, 'KISALA BEA', 304);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMBWAYAMU', 17.89291, -4.49967, 'KISALA V', 361);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMBWAYAMU', 17.92264, -4.51937, 'KISANGANI', 571);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMPUTU', 18.05211, -4.65295, 'KIALU B', 1094);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMPUTU', 18.02792, -4.70491, 'KIMBAKALANGA', 138);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMPUTU', 18.05647, -4.64475, 'KIMBIMBI  P', 230);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMPUTU', 18.03166, -4.67791, 'KIMPUTU', 196);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMPUTU', 18.02953, -4.69148, 'KIMPUTU  II', 1049);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMPUTU', 18.03113, -4.67467, 'KIMPUTU I', 1474);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMPUTU', 18.02936, -4.66981, 'KIMPUTU V', 1037);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMPUTU', 18.04132, -4.66388, 'KIPALANGA', 192);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KIMPUTU', 18.05172, -4.6558, 'MUYALU', 261);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KITOY', 17.87799, -4.40494, 'BONDO', 742);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KITOY', 17.85233, -4.35288, 'BUMBA K', 430);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KITOY', 17.76702, -4.35689, 'DIBUNGU', 115);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KITOY', 17.86706, -4.42044, 'KAMBUMBA', 297);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KITOY', 17.7999, -4.37486, 'KIBOKO', 102);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KITOY', 17.79833, -4.37232, 'KIMWANZA', 811);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KITOY', 17.80597, -4.4302, 'KINDAMBI', 154);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KITOY', 17.83523, -4.45624, 'KINGANGU', 299);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KITOY', 17.78247, -4.3419, 'KINZAMBA', 74);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KITOY', 17.77698, -4.40204, 'KISALA M', 446);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KITOY', 17.81803, -4.4041, 'KITOY CIT', 6106);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KITOY', 17.84054, -4.39124, 'KITOY V', 829);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KITOY', 17.84107, -4.33057, 'MALELA', 711);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KITOY', 17.80654, -4.37278, 'MISIMBIDI', 575);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KITOY', 17.85189, -4.34242, 'MOSANGO', 344);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KWAYA', 18.12387, -4.45825, 'BWATUNDU', 1139);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KWAYA', 18.12575, -4.43997, 'DIMBI K', 2128);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KWAYA', 18.0303, -4.45702, 'KIANGA', 744);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KWAYA', 18.09812, -4.44953, 'KIMBUSHI', 1396);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KWAYA', 18.03881, -4.47, 'KINIATI', 138);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KWAYA', 18.03683, -4.42764, 'KIZIA II', 287);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KWAYA', 18.06123, -4.51676, 'KWAYA C', 1729);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KWAYA', 18.07913, -4.49651, 'KWAYA V', 428);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KWAYA', 18.05632, -4.46538, 'LOMBO C', 417);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KWAYA', 18.05174, -4.45501, 'LOMBO K', 117);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KWAYA', 18.06056, -4.46919, 'LOMBO V', 590);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KWAYA', 18.06687, -4.47949, 'LUNDA', 453);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KWAYA', 18.11898, -4.50348, 'MIPELENGE', 850);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KWAYA', 18.09551, -4.51456, 'MUKALA', 290);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KWAYA', 18.06728, -4.50071, 'MUSEKEDI', 125);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KWAYA', 18.03938, -4.43425, 'NGULMUSITU', 753);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'KWAYA', 18.10005, -4.49453, 'TATU', 521);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'LULAU', 17.90292, -4.29417, 'BA LULAU', 838);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'LULAU', 17.93213, -4.31699, 'BRAZA', 361);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'LULAU', 17.90873, -4.27497, 'BULANGUNGA', 395);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'LULAU', 17.93277, -4.23552, 'KIMBI NSAY', 790);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'LULAU', 17.90266, -4.37245, 'KIMPUTU', 606);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'LULAU', 17.90667, -4.3496, 'KIMWA  TWALA', 748);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'LULAU', 17.87857, -4.37235, 'KIMWAZ BOMA', 495);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'LULAU', 17.86903, -4.35384, 'KINGWE    I', 242);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'LULAU', 17.88081, -4.33364, 'KINGWE  II', 255);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'LULAU', 17.9158, -4.29883, 'LULAU', 1265);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'LULAU', 17.87169, -4.30966, 'MBENDE', 1171);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'LULAU', 17.88486, -4.31907, 'MBENDE  POST', 315);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'LULAU', 17.89589, -4.3187, 'MISELE', 328);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'LULAU', 17.85316, -4.28604, 'MUBE', 81);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'LULAU', 17.91271, -4.25348, 'MUSENGE', 386);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'LULAU', 17.86547, -4.27243, 'NGIELE', 151);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'LUWANGA', 18.16008, -4.4931, 'BASAMBA', 851);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'LUWANGA', 18.16216, -4.52611, 'BUSEKE', 563);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'LUWANGA', 18.10401, -4.54653, 'KANZA', 502);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'LUWANGA', 18.13465, -4.54755, 'KIALU  I', 284);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'LUWANGA', 18.13089, -4.55124, 'KIALU  II', 571);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'LUWANGA', 18.09877, -4.5233, 'KIKONZI', 634);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'LUWANGA', 18.15088, -4.55937, 'KILUNDA  I', 471);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'LUWANGA', 18.16616, -4.55571, 'KILUNDA  II', 792);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'LUWANGA', 18.13272, -4.52718, 'KIMBUMBA', 814);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'LUWANGA', 18.15471, -4.52958, 'LUWANGA', 494);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'LUWANGA', 18.16602, -4.51603, 'MBANZIAL', 163);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'LUWANGA', 18.1216, -4.53485, 'ZANGA', 608);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MANDONDO', 17.80792, -4.57332, 'BONGA K', 879);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MANDONDO', 17.8798, -4.60959, 'DONDO HPK', 1062);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MANDONDO', 17.80839, -4.62561, 'KAZAMBA', 163);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MANDONDO', 17.75534, -4.60613, 'KIMBATA  I', 371);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MANDONDO', 17.76295, -4.61632, 'KIMBATA  II', 350);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MANDONDO', 17.84809, -4.65579, 'KINGOMALAKU', 701);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MANDONDO', 17.80987, -4.61052, 'KIVAVA', 179);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MANDONDO', 17.8553, -4.62864, 'MAKALA', 833);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MANDONDO', 17.85485, -4.61038, 'MANDONDO', 2190);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MANDONDO', 17.8403, -4.65331, 'MIHETA', 270);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MANDONDO', 17.79797, -4.62638, 'MIYANZI  II', 353);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MANDONDO', 17.78292, -4.6177, 'MIYANZI I', 479);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MANDONDO', 17.82162, -4.65464, 'MUKANGU', 161);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MANDONDO', 17.81056, -4.60923, 'SAKA  C', 1091);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MANDONDO', 17.82909, -4.61185, 'SAKA V', 407);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MBANZA GOBARI', 18.08279, -4.327, 'KABALA', 166);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MBANZA GOBARI', 18.12855, -4.42808, 'KAMBUMBA', 1075);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MBANZA GOBARI', 18.10192, -4.31751, 'KIMOLO', 3470);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MBANZA GOBARI', 18.07885, -4.43434, 'KINGONGO', 544);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MBANZA GOBARI', 18.07293, -4.41475, 'KITUMBA', 1041);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MBANZA GOBARI', 18.12225, -4.40534, 'LUKALA', 808);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MBANZA GOBARI', 18.11242, -4.41594, 'MBANZ A DIM', 1535);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MBANZA GOBARI', 18.10709, -4.3789, 'MBANZA GO', 577);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MBANZA GOBARI', 18.08814, -4.3601, 'PINZI  I', 2130);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MBANZA GOBARI', 18.11465, -4.39094, 'SAMBASEKE', 748);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MBANZA GOBARI', 18.10888, -4.36959, 'TALANGAY', 639);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MBANZA MFUMU NKENTO', 17.90236, -4.71448, 'FERME KIPATA', 90);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MBANZA MFUMU NKENTO', 17.89166, -4.68743, 'KIMBANGI', 1995);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MBANZA MFUMU NKENTO', 17.88576, -4.70729, 'KINGOMBE H', 678);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MBANZA MFUMU NKENTO', 17.88712, -4.69734, 'KINGOMBE V', 160);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MBANZA MFUMU NKENTO', 17.91164, -4.69924, 'KIWAWA  II', 575);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MBANZA MFUMU NKENTO', 17.94174, -4.6979, 'KIWAWA I', 775);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MBANZA MFUMU NKENTO', 17.94715, -4.74649, 'MATAMAPITA', 524);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MBANZA MFUMU NKENTO', 17.95343, -4.7177, 'MBANZA MF', 2612);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MBANZA MFUMU NKENTO', 17.96087, -4.75746, 'MIKAMBU', 752);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MBANZA MFUMU NKENTO', 17.90001, -4.6815, 'MIMBONDO', 535);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MBANZA WAMBA', 17.8763, -4.45796, 'BONDO M', 333);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MBANZA WAMBA', 17.85315, -4.46869, 'BUMBA', 1185);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MBANZA WAMBA', 17.90137, -4.41032, 'BUYULU', 243);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MBANZA WAMBA', 17.88065, -4.43487, 'KIBINGU', 248);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MBANZA WAMBA', 17.90744, -4.48538, 'KIMPOKO', 156);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MBANZA WAMBA', 17.89894, -4.45687, 'KIMWILU', 328);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MBANZA WAMBA', 17.87471, -4.4534, 'KINKESA', 295);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MBANZA WAMBA', 17.91071, -4.48484, 'KWAYA', 182);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MBANZA WAMBA', 17.89367, -4.4267, 'MAKUKU', 196);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MBANZA WAMBA', 17.91619, -4.42245, 'MBAMBI M', 1614);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MBANZA WAMBA', 17.92112, -4.44847, 'MBAMBI V', 323);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MBANZA WAMBA', 17.92587, -4.44921, 'MBANGI', 677);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MBANZA WAMBA', 17.92951, -4.451, 'MBANZA W', 1633);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MBANZA WAMBA', 17.86562, -4.46626, 'MUKEFU', 150);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MBANZA WAMBA', 17.93648, -4.49784, 'MUSENGE K', 1161);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MBANZA WAMBA', 17.94148, -4.48344, 'MUSENGE KI', 289);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MUKENGI', 18.10899, -4.57889, 'KAZAMBA', 287);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MUKENGI', 18.15275, -4.63366, 'KIKULA ', 387);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MUKENGI', 18.15338, -4.61823, 'MANZOMBI', 932);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MUKENGI', 18.10181, -4.60669, 'MATUNDU  I', 450);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MUKENGI', 18.09913, -4.62881, 'MATUNDUII', 256);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MUKENGI', 18.15211, -4.58351, 'MIBISHI', 1047);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MUKENGI', 18.11519, -4.60411, 'MUKENGI P', 423);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'MUKENGI', 18.13904, -4.59206, 'MUKENGI V', 881);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'PELO KUMBI', 17.8357, -4.67612, 'KINGONDI', 570);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'PELO KUMBI', 17.75848, -4.65195, 'KINZAMBA K', 762);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'PELO KUMBI', 17.78456, -4.64855, 'KINZAMBA S', 595);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'PELO KUMBI', 17.73747, -4.70523, 'KIPALANGA II', 448);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'PELO KUMBI', 17.73933, -4.66791, 'KIPALANGA K', 2134);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'PELO KUMBI', 17.74513, -4.6362, 'MUBIAKI', 1545);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'PELO KUMBI', 17.80187, -4.68251, 'MUNZANGA', 167);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'PELO KUMBI', 17.78965, -4.71609, 'PELO KINDUNDU', 817);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'PELO KUMBI', 17.76619, -4.69144, 'PELO KUMBI', 742);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'YASA', 17.99641, -4.52677, 'BONGA V', 423);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'YASA', 17.98006, -4.51888, 'BWALA YUL V', 935);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'YASA', 17.99851, -4.52486, 'C/BOUTIQUE', 1023);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'YASA', 17.99192, -4.5259, 'C/CKE', 872);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'YASA', 17.99597, -4.52706, 'C/INFIRMIER', 454);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'YASA', 17.99436, -4.52428, 'C/MAFWA', 919);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'YASA', 17.97802, -4.52785, 'C/MANSANGI', 1642);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'YASA', 17.98759, -4.52279, 'C/MULUA', 718);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'YASA', 18.0415, -4.53277, 'KIBOKO', 738);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'YASA', 17.96959, -4.52934, 'KILWENGE', 345);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'YASA', 17.93983, -4.52305, 'KIMBILI  CO', 730);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'YASA', 17.95824, -4.53052, 'KIMBILI V', 466);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'YASA', 18.01109, -4.52571, 'KINA BAMBA ', 612);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'YASA', 18.02768, -4.4819, 'KINA MILUNDU', 508);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'YASA', 17.99593, -4.51542, 'KINZAMBA', 487);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'YASA', 17.99687, -4.53287, 'KISOMBO', 284);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'YASA', 18.02692, -4.53986, 'KIYAMBA', 339);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'YASA', 17.9679, -4.52813, 'MABETI', 432);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'YASA', 18.023, -4.53216, 'MATAMBA', 384);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'YASA', 18.02382, -4.54433, 'MBANZ MU', 1021);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'YASA', 18.00839, -4.48138, 'MBANZA NGANDA', 697);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'YASA', 18.03775, -4.52421, 'MIKULA', 785);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'YASA', 18.01544, -4.52791, 'MUKENGI', 638);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'YASA', 17.98579, -4.45559, 'MUKOKO YASA', 1036);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'YASA', 18.02563, -4.54541, 'MUSENGE', 585);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'YASA', 17.98927, -4.48417, 'NGWAMBE', 927);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'YASA', 17.97234, -4.50849, 'YASA', 836);
insert into cases_location ("province", "ZS", "AS", "longitude", "latitude", "village", "population") values ('BANDUNDU', 'YASA-BONGA', 'YASA', 17.97903, -4.53616, 'ZANGA FINDA ', 487);
