# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-20 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sync', '0013_auto_20171222_1653'),
        ('cases', '0013_auto_20180207_1543'),
        ('geo', '0003_auto_20180106_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.TextField(null=True, verbose_name='Postnom')),
                ('last_name', models.TextField(null=True, verbose_name='Nom de famille')),
                ('first_name', models.TextField(null=True, verbose_name='Prénom')),
                ('sex', models.TextField(choices=[('female', 'Femme'), ('male', 'Homme')], null=True, verbose_name='Sexe')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Age')),
                ('year_of_birth', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Année de naissance')),
                ('mothers_surname', models.TextField(null=True, verbose_name='Nom de la mère')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('CATT', 'CATT'), ('PG', 'PG'), ('ctcwoo', 'ctcwoo'), ('maect', 'maect')], verbose_name='Type')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('result', models.IntegerField(blank=True, choices=[(2, 'Positif'), (1, 'Négatif'), (0, 'Absent'), (-1, 'Manquant')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case')),
                ('images', models.ManyToManyField(to='sync.ImageUpload')),
                ('videos', models.ManyToManyField(to='sync.VideoUpload')),
                ('village', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.Village')),
            ],
        ),
    ]
