# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-21 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_testgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='images',
            field=models.ManyToManyField(blank=True, to='sync.ImageUpload'),
        ),
        migrations.AlterField(
            model_name='test',
            name='videos',
            field=models.ManyToManyField(blank=True, to='sync.VideoUpload'),
        ),
    ]
