# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-21 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0013_auto_20171222_1653'),
        ('patient', '0003_auto_20180221_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='images',
        ),
        migrations.AddField(
            model_name='test',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sync.ImageUpload'),
        ),
        migrations.RemoveField(
            model_name='test',
            name='videos',
        ),
        migrations.AddField(
            model_name='test',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sync.VideoUpload'),
        ),
    ]
