# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-23 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_qcstats_rename'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='type',
            field=models.TextField(choices=[('CATT', 'CATT'), ('PG', 'PG'), ('ctcwoo', 'ctcwoo'), ('maect', 'maect'), ('RDT', 'RDT')], verbose_name='Type'),
        ),
    ]
