# Generated by Django 2.0 on 2018-03-08 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_null_on_AS'),
        ('patient', '0005_qctest_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Team'),
        ),
        migrations.AlterField(
            model_name='test',
            name='result',
            field=models.IntegerField(blank=True, choices=[(4, 'Positif +++'), (3, 'Positif ++'), (2, 'Positif'), (1, 'Négatif'), (0, 'Absent'), (-1, 'Manquant'), (-2, 'Illisible'), (-3, 'Inutilisé')], null=True),
        ),
    ]
