# Generated by Django 2.0 on 2018-05-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_resync_migrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='type',
            field=models.TextField(choices=[('CATT', 'CATT'), ('PG', 'PG'), ('PL', 'PL'), ('CTCWOO', 'CTCWOO'), ('MAECT', 'MAECT'), ('RDT', 'RDT')], verbose_name='Type'),
        ),
    ]
