# Generated by Django 2.0 on 2018-09-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_video_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='image_filename',
            field=models.TextField(blank=True, null=True, db_index=True, verbose_name='Filename for image/picture'),
        ),
        migrations.AddField(
            model_name='test',
            name='video_filename',
            field=models.TextField(blank=True, null=True, db_index=True, verbose_name='Filename for video'),
        ),
        migrations.RunSQL(
            sql='''
            update patient_test pt
            set image_filename = test_catt_picture_filename
            from cases_case cc
            where pt.image_filename is null
            and pt.type='CATT'
            and cc.test_catt_picture_filename is not null
            and pt.form_id=cc.id
            ''',
            reverse_sql=''
        ),
        migrations.RunSQL(
            sql='''
            update patient_test pt
            set image_filename = test_rdt_picture_filename
            from cases_case cc
            where pt.image_filename is null
            and pt.type='RDT'
            and cc.test_rdt_picture_filename is not null
            and pt.form_id=cc.id
            ''',
            reverse_sql=''
        ),
        migrations.RunSQL(
            sql='''
            update patient_test pt
            set video_filename = test_maect_video_filename
            from cases_case cc
            where pt.video_filename is null
            and pt.type='MAECT'
            and cc.test_maect_video_filename is not null
            and pt.form_id=cc.id
            ''',
            reverse_sql=''
        ),
        migrations.RunSQL(
            sql='''
            update patient_test pt
            set video_filename = test_ctcwoo_video_filename
            from cases_case cc
            where pt.video_filename is null
            and pt.type='CTCWOO'
            and cc.test_ctcwoo_video_filename is not null
            and pt.form_id=cc.id
            ''',
            reverse_sql=''
        ),
        migrations.RunSQL(
            sql='''
            update patient_test pt
            set video_filename = test_pg_video_filename
            from cases_case cc
            where pt.video_filename is null
            and pt.type='PG'
            and cc.test_pg_video_filename is not null
            and pt.form_id=cc.id
            ''',
            reverse_sql=''
        ),
        migrations.RunSQL(
            sql='''
            update patient_test pt
            set video_filename = test_pl_video_filename
            from cases_case cc
            where pt.video_filename is null
            and pt.type='PL'
            and cc.test_pl_video_filename is not null
            and pt.form_id=cc.id
            ''',
            reverse_sql=''
        ),
    ]
