# Generated by Django 2.0 on 2018-09-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_test_filename_to_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='image_filename',
            field=models.TextField(blank=True, null=True, verbose_name='Filename for image/picture'),
        ),
        migrations.AlterField(
            model_name='test',
            name='video_filename',
            field=models.TextField(blank=True, null=True, verbose_name='Filename for video'),
        ),
    ]
