# Generated by Django 2.0 on 2018-10-10 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0016_village_is_erased'),
        ('patient', '0010_auto_20180911_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='origin_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.AS'),
        ),
        migrations.AddField(
            model_name='patient',
            name='origin_village',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.Village'),
        ),
        migrations.AddField(
            model_name='test',
            name='traveller_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.AS'),
        ),
    ]
