# Generated by Django 2.0 on 2018-11-07 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0011_travellers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='year_of_birth',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True,
                                                   verbose_name='Année de naissance'),
        ),
        migrations.CreateModel(
            name='PatientDuplicatesPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.SmallIntegerField(null=True)),
                ('algorithm', models.CharField(max_length=10)),
                ('patient1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='patient.Patient')),
                ('patient2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='patient.Patient')),
            ],
            options={
                'permissions': (('reconcile_duplicates', 'Can reconcile duplicates'),),
            },
        ),
        migrations.CreateModel(
            name='PatientIgnoredPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(max_length=10)),
                ('ignored_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='patient.Patient')),
                ('patient2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='patient.Patient')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='patientignoredpair',
            unique_together={('patient1', 'patient2')},
        ),
        migrations.AlterUniqueTogether(
            name='patientduplicatespair',
            unique_together={('patient1', 'patient2')},
        ),
        migrations.RunSQL(sql="create index if not exists idx_patient_patient_names_trgm "
                              " on patient_patient "
                              "    using gin ( "
                              "  first_name gin_trgm_ops, "
                              "  last_name gin_trgm_ops, "
                              "  post_name gin_trgm_ops, "
                              "  mothers_surname gin_trgm_ops "
                              ")", reverse_sql="drop index if exists idx_patient_patient_names_trgm"),
        migrations.RunSQL(sql="create or replace view patient_matching_namesimilarity as "
                              "select p1.id as patient1_id, "
                              "       p2.id as patient2_id, "
                              "       cast(((p1.post_name <-> p2.post_name) "
                              "         + (p1.first_name <-> p2.first_name) "
                              "         + (p1.last_name <-> p2.last_name) "
                              "         + (p1.mothers_surname <-> p2.mothers_surname)) / 4 * 1000 as smallint) "
                              "         as similarity_score, "
                              "       'namesim' as algorithm "
                              "from patient_patient p1, patient_patient p2 "
                              "where p1.first_name % p2.first_name "
                              "and p1.last_name % p2.last_name "
                              "and p1.post_name % p2.post_name "
                              "and p1.mothers_surname % p2.mothers_surname "
                              "and (p1.year_of_birth is null or p2.year_of_birth is null "
                              "     or abs(p2.year_of_birth-p1.year_of_birth)<5) "
                              "and p1.id > p2.id", reverse_sql="drop view if exists patient_matching_namesimilarity"),
        migrations.RunSQL(sql="create or replace view patient_matching_all as "
                              "select patient1_id, patient2_id, similarity_score, algorithm "
                              "from patient_matching_namesimilarity",
                          reverse_sql="drop view if exists  patient_matching_all")

    ]
