# Generated by Django 2.0 on 2018-11-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_patient_duplicates'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDuplicatesView',
            fields=[
                ('similarity_score', models.SmallIntegerField(null=True)),
                ('algorithm', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'patient_matching_all',
                'managed': False,
            },
        ),
    ]
