# Generated by Django 2.0 on 2018-12-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_patient_citext'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='origin_raw_AS',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='origin_raw_ZS',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='origin_raw_village',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.RunSQL(sql="""
            create table patient_to_update as
            select p.id as pid, count(*) as records, count(distinct coalesce(cc.normalized_village_id::text,
            cc.village)) as different_locations, min(cc.id) as min_case_id
            from patient_patient p
              inner join cases_case cc on cc.normalized_patient_id=p.id
            group by p.id
            having count(*)>1 and count(distinct coalesce(cc.normalized_village_id::text, cc.village))>1;
        """, reverse_sql=""),
        migrations.RunSQL(sql="""
            update cases_case cc
              set normalized_patient_id=null
            from cases_case cc_main, patient_to_update ptu
            where cc_main.id=ptu.min_case_id
              and cc.normalized_patient_id=ptu.pid and cc.id<>cc_main.id
        """, reverse_sql=""),
        migrations.RunSQL(sql="""
            update patient_patient pp
            set origin_area_id=cc."normalized_AS_id", origin_village_id=cc.normalized_village_id,
                "origin_raw_AS"=null, "origin_raw_ZS"=null, "origin_raw_village"=null
            from public.cases_case cc
            where cc.normalized_patient_id=pp.id and cc.normalized_village_id is not null
        """, reverse_sql=""),
        migrations.RunSQL(sql="""
            update patient_patient pp
            set origin_area_id=cc."normalized_AS_id", origin_village_id=cc.normalized_village_id,
                "origin_raw_AS"=cc."AS", "origin_raw_ZS"=cc."ZS", "origin_raw_village"=cc.village
            from public.cases_case cc
            where cc.normalized_patient_id=pp.id and cc.normalized_village_id is null
        """, reverse_sql=""),
        migrations.RunSQL(sql="""
            truncate table patient_patientduplicatespair
        """, reverse_sql=""),
        migrations.RunSQL(sql="""
            truncate table patient_patientignoredpair
        """, reverse_sql=""),
        migrations.RunSQL(sql="""
            create table patients_to_delete as select p1.id as p1_id, p2.id as p2_id
            from patient_patient p1 inner join patient_patient p2
            on p1.id>p2.id
            and p1.first_name=p2.first_name
            and p1.last_name=p2.last_name
            and p1.post_name=p2.post_name
            and p1.mothers_surname=p2.mothers_surname
            and p1.origin_area_id=p2.origin_area_id
            and p1.origin_village_id=p2.origin_village_id
            and p1.sex=p2.sex
            and ((p1.year_of_birth is null and p2.year_of_birth is null) or p1.year_of_birth=p2.year_of_birth);
        """, reverse_sql=""),
        migrations.RunSQL(sql="""
            update cases_case cc set normalized_patient_id=p2_id
            from patients_to_delete ptd
            where cc.normalized_patient_id=p1_id;
        """, reverse_sql=""),
        migrations.RunSQL(sql="""
            delete from patient_patient pp 
            where exists (
              select p1_id from patients_to_delete ptd where ptd.p1_id=pp.id
              and not exists (select 1 from public.cases_case where normalized_patient_id=pp.id)
              )
        """, reverse_sql=""),
        migrations.RunSQL(sql="""
            drop table patients_to_delete
        """, reverse_sql=""),
    ]
