# Generated by Django 2.0 on 2018-11-26 14:53
import os

import django.contrib.postgres.fields.citext
from django.db import migrations
current_dir = os.path.abspath(os.path.dirname(__file__))
with open(os.path.join(current_dir, 'views', 'patient_matching_invert.sql'), 'r') as f:
    query_patient_matching_invert = f.read()
with open(os.path.join(current_dir, 'views', 'patient_matching_namesim.sql'), 'r') as f:
    query_patient_matching_namesim = f.read()
with open(os.path.join(current_dir, 'views', 'patient_matching_all.sql'), 'r') as f:
    query_patient_matching_all = f.read()


class Migration(migrations.Migration):

    atomic = True

    dependencies = [
        ('patient', '0015_patient_raw_location'),
    ]

    operations = [
        migrations.RunSQL("drop view if exists patient_matching_all", reverse_sql=query_patient_matching_all),
        migrations.RunSQL("drop view if exists patient_matching_invert", reverse_sql=query_patient_matching_invert),
        migrations.RunSQL("drop view if exists patient_matching_namesimilarity",
                          reverse_sql=query_patient_matching_namesim),
        migrations.RunSQL(query_patient_matching_invert, reverse_sql=""),
        migrations.RunSQL(query_patient_matching_namesim, reverse_sql=""),
        migrations.RunSQL(query_patient_matching_all, reverse_sql=""),
    ]
