# Generated by Django 2.0 on 2018-12-11 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0017_patient_dupe_AS_histosim'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patientduplicatespair',
            unique_together={('patient1', 'patient2', 'algorithm')},
        ),
    ]
