# Generated by Django 2.0 on 2019-01-16 13:43

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0019_auto_20181217_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('medicine', models.TextField(choices=[('none', 'Aucun'), ('pentamidine', 'Pentamidine'), ('melarsoprol', 'Melarsoprol'), ('eflornithine', 'Eflornithine'), ('nect', 'NECT'), ('fexinidazole', 'Fexinidazole'), ('oxaborole', 'Oxaborole')])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('entry_date', models.DateTimeField(blank=True, null=True)),
                ('adverse_effects', models.NullBooleanField()),
                ('dead', models.NullBooleanField()),
                ('lost', models.NullBooleanField()),
                ('success', models.NullBooleanField()),
                ('complete', models.NullBooleanField()),
                ('event', models.NullBooleanField()),
                ('issues', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, choices=[('vomiting', 'vomiting'), ('diarrhea', 'diarrhea'), ('desorientation', 'desorientation'), ('obnubilation', 'obnubilation'), ('behaviour', 'behaviour'), ('coma', 'coma'), ('neuro', 'neuro'), ('convulsion', 'convulsion'), ('septicemy', 'septicemy'), ('acute respiratory failure', 'acute respiratory failure')], max_length=255), blank=True, null=True, size=None)),
                ('location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('incomplete_reasons', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, choices=[('outofstock', 'rupture de stock'), ('abandon', 'abandon'), ('death', 'décès'), ('patientincapacity', 'incapacité du patient')], max_length=255), blank=True, null=True, size=None)),
                ('death_moment', models.TextField(blank=True, choices=[('before', 'Avant traitement'), ('during', 'Pendant traitement'), ('after', 'Après traitement')], null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sync.DeviceDB')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='dead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='death_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='death_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sync.DeviceDB'),
        ),
        migrations.AddField(
            model_name='patient',
            name='death_location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='treatment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient'),
        ),
    ]
