# Generated by Django 2.0 on 2019-02-05 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0020_depistage_passif'),
    ]

    operations = [
        # 15 and 16 Mar 2018, 65K tests were created with lowercase type
        migrations.RunSQL(sql="update patient_test set type=upper(type) where type<>upper(type)", reverse_sql="")
    ]
