# Generated by Django 2.0 on 2019-02-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0021_test_type_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='otherIssues',
            field=models.TextField(blank=True, null=True),
        ),
    ]
