# Generated by Django 2.0 on 2019-02-07 15:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0022_treatment_otherissues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='issues',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, choices=[('vomiting', 'vomiting'), ('diarrhea', 'diarrhea'), ('desorientation', 'desorientation'), ('obnubilation', 'obnubilation'), ('behaviour', 'behaviour'), ('coma', 'coma'), ('neuro', 'neuro'), ('convulsion', 'convulsion'), ('septicemy', 'septicemy'), ('acute respiratory failure', 'acute respiratory failure'), ('other', 'other')], max_length=255), blank=True, null=True, size=None),
        ),
    ]
