# Generated by Django 2.0 on 2019-03-06 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0027_patient_test_team'),
        ('patient', '0027_test_search_indexing'),
    ]

    operations = [
    ]
