# Generated by Django 2.0 on 2019-03-13 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_merge_20190225_0931'),
        ('patient', '0028_merge_20190306_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='tester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
        migrations.RunSQL(sql="update patient_test pt set tester_id = users_profile.id from users_profile inner join auth_user on users_profile.user_id = auth_user.id inner join sync_devicedb on sync_devicedb.last_user_id = auth_user.id  inner join cases_case on cases_case.device_id=sync_devicedb.device_id where pt.form_id = cases_case.id")
    ]
