# Generated by Django 2.0 on 2019-04-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0030_birth_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='level',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
