# Generated by Django 2.0 on 2019-04-03 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0031_test_level'),
    ]

    operations = [
        migrations.RunSQL(sql="""
        update cases_case cc
        set test_catt_level = cast (doc -> 'participant' -> 'screenings' -> 'catt' ->> 'level' as INTEGER)
        from sync_jsondocument jd
        where jd.case_id=cc.id and doc -> 'participant' -> 'screenings' -> 'catt' ->> 'level' is not null
        and cc.test_catt_level is null
        """, reverse_sql=""),
        migrations.RunSQL(sql="""
        update patient_test pt
        set level=cc.test_catt_level
        from cases_case cc
        where cc.id=pt.form_id and pt.type='CATT' and cc.test_catt_level is not null
        and pt.level is null;
        """, reverse_sql="")
    ]
