# Generated by Django 2.0 on 2019-04-19 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0032_test_level_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sync.DeviceDB'),
        ),
    ]
