# Generated by Django 2.0 on 2019-04-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0033_remove_treatment_device_constr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='result',
            field=models.IntegerField(blank=True, choices=[(4, 'Positif +++'), (3, 'Positif ++'), (2, 'Positif'), (1, 'Négatif'), (0, 'Absent'), (-1, 'Manquant'), (-2, 'Illisible'), (-3, 'Inutilisé'), (-4, 'Pas certain')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='type',
            field=models.TextField(choices=[('CATT', 'CATT'), ('PG', 'PG'), ('PL', 'PL'), ('CTCWOO', 'CTCWOO'), ('MAECT', 'MAECT'), ('RDT', 'RDT'), ('SF', 'Sang Frais'), ('SP', 'Ponction Sternale'), ('IFAT', 'ImmunoFluorescence Antibody Test'), ('LCR', 'Liquide CéphaloRachidien'), ('DIL', 'Dil = ou > + à 1/16 en zone hyperendémique'), ('GE', 'Goutte Épaisse'), ('CLINICAL_SICKNESS', 'Malade clinique'), ('LNP', 'Lymph Node Puncture'), ('PARASIT', 'Confirmation parasytologique')], verbose_name='Type'),
        ),
        migrations.RunSQL(sql="""
            update patient_test pt 
            set village_id=cc.normalized_village_id 
            from cases_case cc 
            where cc.id=pt.form_id and pt.village_id is null and cc.normalized_village_id is not null
        """, reverse_sql="")
    ]
