# Generated by Django 2.0 on 2019-06-05 14:09
import os

from django.db import migrations

current_dir = os.path.abspath(os.path.dirname(__file__))
with open(os.path.join(current_dir, 'views', 'patient_matching_invert.sql'), 'r') as f:
    query_patient_matching_invert = f.read()
with open(os.path.join(current_dir, 'views', 'patient_matching_namesim.sql'), 'r') as f:
    query_patient_matching_namesim = f.read()
with open(os.path.join(current_dir, 'views', 'patient_matching_histosim.sql'), 'r') as f:
    query_patient_matching_histosim = f.read()
with open(os.path.join(current_dir, 'views', 'patient_matching_all.sql'), 'r') as f:
    query_patient_matching_all = f.read()


class Migration(migrations.Migration):

    atomic = True

    dependencies = [
        ('patient', '0035_update_as_from_village'),
    ]

    operations = [
        migrations.RunSQL("drop view if exists patient_matching_all", reverse_sql=query_patient_matching_all),
        migrations.RunSQL("drop view if exists patient_matching_invert", reverse_sql=query_patient_matching_invert),
        migrations.RunSQL("drop view if exists patient_matching_namesimilarity",
                          reverse_sql=query_patient_matching_namesim),
        migrations.RunSQL("drop view if exists patient_matching_histosim",
                          reverse_sql=query_patient_matching_histosim),
        migrations.RunSQL(query_patient_matching_invert, reverse_sql=""),
        migrations.RunSQL(query_patient_matching_namesim, reverse_sql=""),
        migrations.RunSQL(query_patient_matching_histosim, reverse_sql=""),
        migrations.RunSQL(query_patient_matching_all, reverse_sql=""),
    ]
