# Generated by Django 2.0 on 2019-06-19 13:22
import sys

from django.db import migrations
from django.db.migrations import RunSQL


class Migration(migrations.Migration):
    dependencies = [
        ('patient', '0037_auto_20190617_0950'),
    ]

    # On test DB, this will fail because it's building the DB app by app and it's only meant to fix a production issue
    if 'test' in sys.argv:
        operations = []
    else:
        operations = [
            # disable users without profiles
            migrations.RunSQL(sql="""
                update auth_user au set is_active=False where not exists (select 1 from users_profile up where up.user_id=au.id);
            """, reverse_sql=RunSQL.noop, elidable=True),

            # recreate missing profiles
            migrations.RunSQL(sql="""
                insert into users_profile
                    (user_id, team_id, phone, institution_id, "userType_id", password_reset, tester_type, level, screening_type)
                    select au.id, null, null, null, null, false, null, null, null
                   from auth_user au where not exists (select 1 from users_profile up2 where up2.user_id=au.id);
            """, reverse_sql=RunSQL.noop, elidable=True),

            # fix test.tester_id
            migrations.RunSQL(sql="""
                update patient_test pt
                set tester_id=up.id
                from cases_case cc
                inner join sync_devicedb ddb on cc.device_id=ddb.device_id
                inner join auth_user au on ddb.last_user_id = au.id
                inner join users_profile up on au.id = up.user_id
                where cc.id = pt.form_id
                and pt.tester_id is null
            """, reverse_sql=RunSQL.noop, elidable=True),

    ]
