# Generated by Django 2.0 on 2019-07-30 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0037_auto_20190617_1006"),
        ("patient", "0039_unused_rename_invalid"),
    ]

    operations = []
