# Generated by Django 2.1.11 on 2019-10-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0040_merge_20190730_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.TextField(blank=True, null=True, verbose_name='Numéro de téléphone'),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de collecte du numéro de téléphone'),
        ),
    ]
