# Generated by Django 2.1.11 on 2019-11-18 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0041_infection_location'),
        ('cases', '0042_pl_stage_step1'),
    ]

    operations = [
        migrations.RunSQL(sql="""
            update patient_test pt
            set level=1
            from cases_case cc
            where cc.id=pt.form_id and pt.type='PL' and level is null and test_pl_result='stage1';
        """, reverse_sql=""),
        migrations.RunSQL(sql="""
            update patient_test pt
            set level=2
            from cases_case cc
            where cc.id=pt.form_id and pt.type='PL' and level is null and test_pl_result='stage2';
        """, reverse_sql=""),
    ]
