# Generated by Django 2.1.11 on 2019-11-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0042_pl_stage_step2'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='origin_country',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
