# Generated by Django 2.1.11 on 2020-04-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0044_test_comment"),
    ]

    operations = [
        migrations.RemoveField(model_name="test", name="note",),
        migrations.AlterField(
            model_name="test",
            name="type",
            field=models.TextField(
                choices=[
                    ("CATT", "CATT"),
                    ("PG", "PG"),
                    ("PL", "PL"),
                    ("CTCWOO", "CTCWOO"),
                    ("MAECT", "MAECT"),
                    ("RDT", "RDT"),
                    ("SF", "Sang Frais"),
                    ("SP", "Ponction Sternale"),
                    ("IFAT", "ImmunoFluorescence Antibody Test"),
                    ("LCR", "Liquide CéphaloRachidien"),
                    ("DIL", "Dil = ou > + à 1/16 en zone hyperendémique"),
                    ("GE", "Goutte Épaisse"),
                    ("CLINICAL_SICKNESS", "Malade clinique"),
                    ("LNP", "Lymph Node Puncture"),
                    ("PARASIT", "Confirmation parasytologique"),
                    ("RESEARCH_PL", "PL de recherche"),
                ],
                verbose_name="Type",
            ),
        ),
        migrations.RunSQL(
            sql="""
insert into patient_test (type, date, result, created_at, updated_at, form_id, village_id, team_id,
 traveller_area_id, hidden, device_id, location, tester_id, comment)
select 'RESEARCH_PL', (doc -> 'participant' -> 'screenings' -> 'research_pl' ->> 'testTime')::timestamptz,
       case when doc -> 'participant' -> 'screenings' -> 'research_pl' ->> 'result' = 'positive' then 2
           when doc -> 'participant' -> 'screenings' -> 'research_pl' ->> 'result' = 'negative' then 1 end,
       (doc -> 'participant' -> 'screenings' -> 'research_pl' ->> 'creationTime')::timestamptz, now(),
       jd.case_id, cc.normalized_village_id, cc.normalized_team_id, null /*traveler*/, false, 
       jd.device_id /* device_id*/,
       st_setsrid(st_makepoint((doc -> 'participant' -> 'screenings' -> 'research_pl' ->> 'longitude')::float,
           (doc -> 'participant' -> 'screenings' -> 'research_pl' ->> 'latitude')::float), 4326) /*location*/,
       up.id /* tester_id */, doc -> 'participant' -> 'screenings' -> 'research_pl' ->> 'confirmationMissingReason'
from (select case_id, max(id) as latest_jd_id from sync_jsondocument group by case_id) latest_jd
inner join sync_jsondocument jd on latest_jd.latest_jd_id=jd.id
inner join cases_case cc on jd.case_id = cc.id
inner join sync_devicedb ddb on doc -> 'participant' -> 'screenings' -> 'research_pl' ->> 'device' = ddb.device_id
inner join users_profile up on up.user_id=ddb.last_user_id
where doc -> 'participant' -> 'screenings' -> 'research_pl' is not null
and doc -> 'participant' -> 'screenings' -> 'research_pl' ->> 'result' <> 'notdone'
and not exists (select 1 from patient_test pt2 where pt2.form_id=jd.case_id and type='RESEARCH_PL')
            """,
            reverse_sql="",
        ),
    ]
