# Generated by Django 2.1.11 on 2020-06-03 13:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0046_auto_20200520_0743"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treatment",
            name="issues",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(
                    blank=True,
                    choices=[
                        ("vomiting", "vomissement"),
                        ("diarrhea", "diarrhée"),
                        ("desorientation", "désorientation"),
                        ("obnubilation", "obnubilation"),
                        ("behaviour", "troubles du comportement"),
                        ("coma", "coma"),
                        ("neuro", "troubles neurologiques"),
                        ("convulsion", "convulsion"),
                        ("septicemy", "septicémie"),
                        (
                            "acute respiratory failure",
                            "inflammation respiratoire aiguë",
                        ),
                        ("other", "autre"),
                    ],
                    max_length=255,
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="medicine",
            field=models.TextField(
                choices=[
                    ("none", "Aucun"),
                    ("pentamidine", "Pentamidine"),
                    ("melarsoprol", "Melarsoprol"),
                    ("eflornithine", "Eflornithine"),
                    ("nect", "NECT"),
                    ("fexinidazole", "Fexinidazole"),
                    ("acoziborole", "Acoziborole"),
                ]
            ),
        ),
    ]
