# Generated by Django 2.1.11 on 2020-06-11 07:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0047_treatment_fix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='issues',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, choices=[('coma', 'coma'), ('convulsion', 'convulsion'), ('desorientation', 'désorientation'), ('diarrhea', 'diarrhée'), ('acute respiratory failure', 'inflammation respiratoire aiguë'), ('obnubilation', 'obnubilation'), ('septicemy', 'septicémie'), ('behaviour', 'troubles du comportement'), ('neuro', 'troubles neurologiques'), ('vomiting', 'vomissement'), ('other', 'autre')], max_length=255), blank=True, null=True, size=None),
        ),
    ]
