# Generated by Django 3.0.3 on 2020-06-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("patient", "0048_treatment_issues_order")]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="type",
            field=models.TextField(
                choices=[
                    ("CATT", "CATT"),
                    ("PG", "PG"),
                    ("PL", "PL"),
                    ("CTCWOO", "CTCWOO"),
                    ("MAECT", "MAECT"),
                    ("RDT", "RDT"),
                    ("SF", "Sang Frais"),
                    ("SP", "Ponction Sternale"),
                    ("IFAT", "ImmunoFluorescence Antibody Test"),
                    ("LCR", "Liquide CéphaloRachidien"),
                    ("DIL", "Dil = ou > + à 1/16 en zone hyperendémique"),
                    ("GE", "Goutte Épaisse"),
                    ("CLINICAL_SICKNESS", "Malade clinique"),
                    ("LNP", "Lymph Node Puncture"),
                    ("PARASIT", "Confirmation parasitologique"),
                    ("RESEARCH_PL", "PL de recherche"),
                    ("iELISA", "iELISA"),
                ],
                verbose_name="Type",
            ),
        )
    ]
