server {
  listen      80;
  server_name  _;

  location /static/ {
    alias /opt/app/static/;
  }

  location / {
    include uwsgi_params;
    uwsgi_pass  unix:/var/run/uwsgi.sock;
    proxy_set_header X-Forwarded-Host $server_name;
    proxy_set_header X-Real-IP $remote_addr;
  }
}
