[uwsgi]
binary-path = /usr/bin/uwsgi
socket = /var/run/uwsgi.sock
chdir = /opt/app/hat/
module = wsgi:application
wsgi-file = /opt/app/hat/wsgi.py
callable = application
uid = www-data
gid = www-data
chmod-socket = 666
chown-socket = www-data
master = True
processes = 5
threads = 2
pidfile = /var/run/uwsgi.pid
touch-reload = /var/run/uwsgi.pid
logto = /var/log/uwsgi.log
plugins = python3
