[uwsgi]
socket = /var/run/uwsgi.sock
#http-socket = 127.0.0.1:80
chdir = /opt/app/
wsgi-file = hat/wsgi.py
uid = www-data
gid = www-data
chmod-socket = 666
chown-socket = www-data
master = True
processes = 5
threads = 2
pidfile = /var/run/uwsgi.pid
touch-reload = /var/run/uwsgi.pid
