# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HatParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=32, unique=True)),
                ('document_date', models.DateTimeField(null=True)),
                ('entry_date', models.DateTimeField(null=True)),
                ('hat_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128, null=True)),
                ('lastname', models.CharField(max_length=128, null=True)),
                ('prename', models.CharField(max_length=128, null=True)),
                ('sex', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('unknown', 'Unknown')], max_length=16)),
                ('age', models.PositiveSmallIntegerField(null=True)),
                ('year_of_birth', models.PositiveSmallIntegerField(null=True)),
                ('mothers_surname', models.CharField(max_length=128, null=True)),
                ('village', models.CharField(max_length=64, null=True)),
                ('province', models.CharField(max_length=64, null=True)),
                ('ZS', models.CharField(max_length=64, null=True)),
                ('AZ', models.CharField(max_length=64, null=True)),
                ('mobile_unit', models.CharField(max_length=128, null=True)),
                ('treatment_center', models.CharField(max_length=128, null=True)),
                ('screening_test_result', models.CharField(choices=[('negative', 'Negative'), ('positive', 'Positive'), ('unknown', 'Unknown')], max_length=16)),
                ('confirmation_test_result', models.CharField(choices=[('negative', 'Negative'), ('positive', 'Positive'), ('unknown', 'Unknown')], max_length=16)),
                ('PL_test_result', models.CharField(choices=[('none', 'None'), ('stage1', 'Stage1'), ('stage2', 'Stage2'), ('unknown', 'Unknown')], max_length=16)),
            ],
            options={
                'permissions': (('import_mdb', 'Can import mdb files'), ('export_full', 'Can export the full dataset as csv'), ('export_anon', 'Can export anonymized data as csv')),
            },
        ),
    ]
