# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hatparticipant',
            name='PL_test_result',
        ),
        migrations.RemoveField(
            model_name='hatparticipant',
            name='confirmation_test_result',
        ),
        migrations.RemoveField(
            model_name='hatparticipant',
            name='screening_test_result',
        ),
        migrations.AddField(
            model_name='hatparticipant',
            name='source',
            field=models.CharField(choices=[('historic', 'Historic'), ('mobile_backup', 'Mobile backup')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='hatparticipant',
            name='test_catt',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='hatparticipant',
            name='test_catt_dilution',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='hatparticipant',
            name='test_catt_total_blood',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='hatparticipant',
            name='test_clinical_sickness',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='hatparticipant',
            name='test_ctcwoo',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='hatparticipant',
            name='test_dil',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='hatparticipant',
            name='test_ge',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='hatparticipant',
            name='test_ifat',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='hatparticipant',
            name='test_lcr',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='hatparticipant',
            name='test_lcr_fr',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='hatparticipant',
            name='test_lcr_scm',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='hatparticipant',
            name='test_lymph_node_puncture',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='hatparticipant',
            name='test_maec',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='hatparticipant',
            name='test_maect',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='hatparticipant',
            name='test_maect_bc',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='hatparticipant',
            name='test_other',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='hatparticipant',
            name='test_parasit',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='hatparticipant',
            name='test_pg',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='hatparticipant',
            name='test_pl',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='hatparticipant',
            name='test_pl_albumine',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='hatparticipant',
            name='test_pl_comments',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='hatparticipant',
            name='test_pl_gb_mm3',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='hatparticipant',
            name='test_pl_lcr',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='hatparticipant',
            name='test_pl_liquid',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='hatparticipant',
            name='test_pl_result',
            field=models.CharField(choices=[('stage1', 'Stage1'), ('stage2', 'Stage2'), ('unknown', 'Unknown')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='hatparticipant',
            name='test_pl_trypanosome',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='hatparticipant',
            name='test_rdt',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='hatparticipant',
            name='test_sf',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='hatparticipant',
            name='test_sternal_puncture',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='hatparticipant',
            name='test_woo',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='hatparticipant',
            name='document_id',
            field=models.CharField(max_length=32),
        ),
    ]
