# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_auto_20160802_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='hatparticipant',
            name='entry_name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
