# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0004_auto_20160808_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='hatparticipant',
            name='treatment_end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='hatparticipant',
            name='treatment_result',
            field=models.CharField(choices=[('recovered', 'Recovered'), ('healthy', 'Healthy'), ('relapse', 'Relapse'), ('disappeared', 'Disappeared'), ('died', 'Died'), ('transferred', 'Transferred'), ('other', 'Other')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='hatparticipant',
            name='treatment_start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
