# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0005_auto_20160810_1006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hatparticipant',
            options={'permissions': (('import', 'Can import data'), ('export', 'Can export data'), ('export_full', 'Can export the full dataset as csv'))},
        ),
        migrations.AlterField(
            model_name='hatparticipant',
            name='test_catt_dilution',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='hatparticipant',
            name='test_catt_total_blood',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='hatparticipant',
            name='test_pl_lcr',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='hatparticipant',
            name='test_pl_liquid',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
