# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-12 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0006_auto_20160810_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='hatparticipant',
            name='treatment_prescribed',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='hatparticipant',
            name='treatment_secondary_effects',
            field=models.NullBooleanField(),
        ),
    ]
