# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0008_auto_20160815_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hatparticipant',
            name='sex',
            field=models.TextField(choices=[('female', 'Female'), ('male', 'Male')], null=True),
        ),
    ]
