# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-22 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0009_auto_20160816_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='hatparticipant',
            name='form_month',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hatparticipant',
            name='form_number',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hatparticipant',
            name='form_year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
