branch-defaults:
  development:
    environment: null
    group_suffix: null
deploy:
  artifact: build_scripts/deploy.zip
global:
  application_name: trypelim-web-staging
  branch: development
  default_ec2_keyname: trypelim-prod
  default_platform: Python 3.6
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: trypelim
  sc: git
  workspace_type: Application
