# Generated by Django 2.0 on 2019-03-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("quality", "0003_auto_20180316_1257")]

    operations = [
        migrations.AddField(
            model_name="check",
            name="comment",
            field=models.TextField(blank=True, null=True),
        )
    ]
