# Generated by Django 2.0 on 2019-03-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("quality", "0004_check_comment")]

    operations = [
        migrations.AddField(
            model_name="check",
            name="level",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (10, "Level 1"),
                    (10, "Positif ++"),
                    (10, "Positif"),
                    (10, "Négatif"),
                ],
                default=10,
                null=True,
            ),
        )
    ]
