# Generated by Django 2.0 on 2019-03-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0005_check_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='level',
            field=models.IntegerField(blank=True, choices=[(10, 'Niveau 1'), (20, 'Niveau 2'), (30, 'Niveau 3'), (40, 'Niveau 4'), (50, 'Niveau 5')], default=10, null=True),
        ),
    ]
