# Generated by Django 2.0 on 2019-03-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0006_auto_20190320_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='has_other_parasite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='check',
            name='is_clear',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='check',
            name='is_confirmed_case',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='check',
            name='is_good_place',
            field=models.BooleanField(default=False),
        ),
    ]
