# Generated by Django 2.0 on 2019-04-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0007_auto_20190328_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='level',
            field=models.IntegerField(blank=True, choices=[(10, 'Niveau 1'), (20, 'Niveau 2'), (30, 'Niveau 3'), (40, 'Niveau 4')], default=10, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='result',
            field=models.IntegerField(blank=True, choices=[(4, 'Positif +++'), (3, 'Positif ++'), (2, 'Positif'), (1, 'Négatif'), (0, 'Absent'), (-1, 'Manquant'), (-2, 'Illisible'), (-3, 'Inutilisé'), (-4, 'Pas certain')], default=-3, null=True),
        ),
    ]
