# Generated by Django 2.0 on 2019-04-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0007_auto_20190328_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='level',
            field=models.IntegerField(blank=True, choices=[(10, 'Niveau 1'), (20, 'Niveau 2'), (30, 'Niveau 3'), (40, 'Niveau 4')], default=10, null=True),
        ),
    ]
