# Generated by Django 2.0 on 2019-05-20 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0008_auto_20190418_1200'),
        ('quality', '0008_other_tests'),
    ]

    operations = [
    ]
