# Generated by Django 2.0 on 2019-06-17 10:07

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.contrib.postgres.fields.citext
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.postgres.operations import CreateExtension, TrigramExtension
from django.db import migrations
from django.contrib.postgres.operations import CITextExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        CreateExtension("postgis"),
        TrigramExtension(),
        CITextExtension(),
        migrations.CreateModel(
            name="OrgLevel",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("short_name", models.CharField(max_length=255)),
                ("level", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrgUnit",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                (
                    "aliases",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.citext.CITextField(blank=True, max_length=255),
                        blank=True,
                        null=True,
                        size=100,
                    ),
                ),
                (
                    "source",
                    models.TextField(
                        choices=[
                            ("snis", "SNIS"),
                            ("ucla", "UCLA"),
                            ("pnltha", "PNL THA"),
                            ("derivated", "Derivated from actual data"),
                        ],
                        null=True,
                    ),
                ),
                ("source_ref", models.TextField(null=True)),
                ("geom", django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326)),
                ("simplified_geom", django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326)),
                (
                    "geom_source",
                    models.TextField(
                        choices=[
                            ("snis", "SNIS"),
                            ("ucla", "UCLA"),
                            ("pnltha", "PNL THA"),
                            ("derivated", "Derivated from actual data"),
                        ],
                        null=True,
                    ),
                ),
                ("geom_ref", models.IntegerField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrgUnitType",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("short_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="orgunit",
            name="org_unit_type",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="iaso.OrgUnitType"),
        ),
        migrations.AddField(
            model_name="orgunit",
            name="parent",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="iaso.OrgUnit"),
        ),
        migrations.AddField(
            model_name="orglevel",
            name="org_unit_type",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="iaso.OrgUnitType"),
        ),
        migrations.AddField(
            model_name="orglevel",
            name="parent",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="iaso.OrgLevel"),
        ),
    ]
