# Generated by Django 4.2.13 on 2025-09-17 13:45

from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0002_feature_flags"),
    ]

    operations = [
        CreateExtension("fuzzystrmatch"),
    ]
