# Generated by Django 2.2.4 on 2019-10-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("iaso", "0002_auto_20191001_1142")]

    operations = [
        migrations.AlterField(model_name="datasource", name="name", field=models.CharField(max_length=255, unique=True))
    ]
