# Generated by Django 2.0 on 2019-06-17 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("iaso", "0002_auto_20190617_1232")]

    operations = [migrations.RenameField(model_name="orglevel", old_name="org_unit_type", new_name="org_unit_types")]
