# Generated by Django 2.0 on 2019-06-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("iaso", "0004_form")]

    operations = [
        migrations.RemoveField(model_name="form", name="org_unit_type"),
        migrations.AddField(
            model_name="form", name="org_unit_types", field=models.ManyToManyField(blank=True, to="iaso.OrgUnitType")
        ),
    ]
