# Generated by Django 2.2.4 on 2019-10-03 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ("iaso", "0004_auto_20191003_1311")]

    operations = [
        migrations.RemoveField(model_name="link", name="algorithm"),
        migrations.CreateModel(
            name="AlgorithmRun",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "algorithm",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="iaso.MatchingAlgorithm"),
                ),
                (
                    "launcher",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="link",
            name="algorithm_run",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="iaso.AlgorithmRun"
            ),
        ),
    ]
