# Generated by Django 2.0 on 2019-06-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("iaso", "0005_auto_20190619_1334")]

    operations = [
        migrations.RemoveField(model_name="orglevel", name="org_unit_types"),
        migrations.RemoveField(model_name="orglevel", name="parent"),
        migrations.RemoveField(model_name="orgunit", name="org_level"),
        migrations.AddField(
            model_name="orgunittype",
            name="sub_unit_types",
            field=models.ManyToManyField(blank=True, to="iaso.OrgUnitType"),
        ),
        migrations.DeleteModel(name="OrgLevel"),
    ]
