# Generated by Django 2.2.4 on 2019-10-04 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("iaso", "0006_auto_20191004_0912")]

    operations = [
        migrations.AddField(
            model_name="algorithmrun",
            name="version_1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="runs_where_destination",
                to="iaso.SourceVersion",
            ),
        ),
        migrations.AddField(
            model_name="algorithmrun",
            name="version_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="runs_where_source",
                to="iaso.SourceVersion",
            ),
        ),
    ]
