# Generated by Django 2.0 on 2019-06-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("iaso", "0006_auto_20190624_0938")]

    operations = [
        migrations.AlterField(
            model_name="orgunittype",
            name="sub_unit_types",
            field=models.ManyToManyField(related_name="super_types", to="iaso.OrgUnitType"),
        )
    ]
