# Generated by Django 2.0 on 2019-06-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("iaso", "0007_auto_20190624_1155")]

    operations = [
        migrations.CreateModel(
            name="FormVersion",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(blank=True, null=True, upload_to="forms/")),
                ("version_id", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Instance",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("form", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.TextField(blank=True, null=True)),
                ("file", models.FileField(blank=True, null=True, upload_to="instances/")),
            ],
        ),
        migrations.RemoveField(model_name="form", name="file"),
        migrations.AlterField(
            model_name="orgunittype",
            name="sub_unit_types",
            field=models.ManyToManyField(blank=True, related_name="super_types", to="iaso.OrgUnitType"),
        ),
        migrations.AddField(
            model_name="instance",
            name="org_unit_types",
            field=models.ManyToManyField(blank=True, to="iaso.OrgUnitType"),
        ),
    ]
