# Generated by Django 2.2.4 on 2019-10-17 20:15

from django.db import migrations, models
import iaso.models


class Migration(migrations.Migration):
    dependencies = [("iaso", "0011_orgunittype_depth")]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="export_id",
            field=models.TextField(blank=True, default=iaso.models.generate_id_for_dhis_2, null=True),
        )
    ]
