# Generated by Django 2.0 on 2019-06-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("iaso", "0011_orgunit_custom")]

    operations = [migrations.AddField(model_name="orgunit", name="validated", field=models.BooleanField(default=True))]
