# Generated by Django 2.1.11 on 2019-10-31 09:41

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("iaso", "0013_auto_20191029_1539")]

    operations = [
        migrations.AddField(
            model_name="orgunit",
            name="catchment",
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        )
    ]
