# Generated by Django 2.2.4 on 2019-08-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("iaso", "0014_account_device_deviceownership_project")]

    operations = [
        migrations.AddField(model_name="instance", name="uuid", field=models.TextField(blank=True, null=True))
    ]
