# Generated by Django 2.1.11 on 2019-11-04 13:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("iaso", "0014_orgunit_catchment"), ("iaso", "0014_record_recordtype")]

    operations = []
