# Generated by Django 2.2.4 on 2019-08-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("iaso", "0015_instance_uuid")]

    operations = [
        migrations.AddField(model_name="instance", name="name", field=models.TextField(blank=True, null=True))
    ]
