# Generated by Django 2.1.11 on 2019-11-28 11:45

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("iaso", "0019_auto_20191127_1602")]

    operations = [
        migrations.AddField(
            model_name="account",
            name="default_version",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="iaso.SourceVersion"
            ),
        )
    ]
