# Generated by Django 2.1.11 on 2019-12-18 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("iaso", "0021_auto_20191203_1302")]

    operations = [
        migrations.AddField(model_name="datasource", name="read_only", field=models.BooleanField(default=True)),
        migrations.AlterField(
            model_name="formversion",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="form_versions", to="iaso.Form"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="org_units",
            field=models.ManyToManyField(blank=True, related_name="groups", to="iaso.OrgUnit"),
        ),
    ]
