# Generated by Django 2.1.11 on 2019-12-17 13:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("iaso", "0021_auto_20191203_1302")]

    operations = [
        migrations.CreateModel(
            name="ExternalCredentials",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField()),
                ("login", models.TextField()),
                ("password", models.TextField()),
                ("url", models.TextField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="credentials", to="iaso.Account"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mapping",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField()),
                ("json", django.contrib.postgres.fields.jsonb.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="formversion",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="form_versions", to="iaso.Form"
            ),
        ),
        migrations.AddField(
            model_name="mapping",
            name="form_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="mappings", to="iaso.FormVersion"
            ),
        ),
        migrations.AddField(
            model_name="datasource",
            name="credentials",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="data_sources",
                to="iaso.ExternalCredentials",
            ),
        ),
        migrations.AlterUniqueTogether(name="mapping", unique_together={("form_version", "name")}),
    ]
