# Generated by Django 2.2.4 on 2019-09-29 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("iaso", "0022_link_matchingalgorithm")]

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="orgunit",
            name="geom_source",
            field=models.TextField(
                blank=True,
                choices=[
                    ("snis", "SNIS"),
                    ("ucla", "UCLA"),
                    ("pnltha", "PNL THA"),
                    ("kemri", "KEMRI"),
                    ("derivated", "Derivated from actual data"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="orgunit",
            name="source",
            field=models.TextField(
                blank=True,
                choices=[
                    ("snis", "SNIS"),
                    ("ucla", "UCLA"),
                    ("pnltha", "PNL THA"),
                    ("kemri", "KEMRI"),
                    ("derivated", "Derivated from actual data"),
                ],
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="SourceVersion",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.IntegerField()),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("data_source", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="iaso.DataSource")),
            ],
        ),
        migrations.AddField(
            model_name="orgunit",
            name="version",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="iaso.SourceVersion"
            ),
        ),
    ]
