# Generated by Django 2.2.4 on 2019-09-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("iaso", "0025_creating_trypelim_source")]

    operations = [
        migrations.AlterField(
            model_name="orgunit", name="source_ref", field=models.TextField(blank=True, db_index=True, null=True)
        ),
        migrations.AlterField(
            model_name="orgunit", name="uuid", field=models.TextField(blank=True, db_index=True, null=True)
        ),
        migrations.AlterField(
            model_name="orgunit", name="validated", field=models.BooleanField(db_index=True, default=True)
        ),
    ]
