# Generated by Django 2.1.11 on 2020-02-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaso', '0031_auto_20200121_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='single_per_period',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
