# Generated by Django 2.1.11 on 2020-02-10 14:55

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("iaso", "0032_auto_20200210_1355"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sent",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, null=True
                    ),
                ),
                (
                    "received",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExportRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "params",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, null=True
                    ),
                ),
                (
                    "result",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, null=True
                    ),
                ),
                ("finished", models.BooleanField(default=False)),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("RUNNING", "Running"),
                            ("EXPORTED", "Exported"),
                            ("ERRORED", "Errored"),
                        ],
                        default="QUEUED",
                    ),
                ),
                ("instance_count", models.IntegerField()),
                ("exported_count", models.IntegerField()),
                ("errored_count", models.IntegerField()),
                ("last_error_message", models.TextField()),
                ("queued_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "launcher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExportStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("RUNNING", "Running"),
                            ("EXPORTED", "Exported"),
                            ("ERRORED", "Errored"),
                        ],
                        default="QUEUED",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "export_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="iaso.ExportLog"
                    ),
                ),
                (
                    "export_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="iaso.ExportRequest",
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="iaso.Instance"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mapping",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                (
                    "mapping_type",
                    models.TextField(
                        choices=[("AGGREGATE", "Aggregate"), ("EVENT", "Event")]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "data_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mappings",
                        to="iaso.DataSource",
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="iaso.Form",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="mappingversion",
            name="form_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mapping_versions",
                to="iaso.FormVersion",
            ),
        ),
        migrations.AddField(
            model_name="exportstatus",
            name="mapping_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="iaso.MappingVersion"
            ),
        ),
    ]
