# Generated by Django 2.1.11 on 2020-02-11 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("iaso", "0033_auto_20200210_1455"),
    ]

    operations = [
        migrations.AddField(
            model_name="mappingversion",
            name="mapping",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="iaso.Mapping",
            ),
        ),
    ]
