# Generated by Django 2.1.11 on 2020-02-11 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("iaso", "0034_mappingversion_mapping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportstatus",
            name="export_log",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="iaso.ExportLog",
            ),
        ),
    ]
