# Generated by Django 2.1.11 on 2020-02-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaso', '0034_form_version_upload_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='period_type',
            field=models.TextField(blank=True, choices=[('YEAR', 'Year'), ('QUARTER', 'Quarter'), ('MONTH', 'Month'), ('SIX_MONTH', 'Six-month'), ('TRACKER', 'Tracker')], null=True),
        ),
    ]
