# Generated by Django 2.1.11 on 2020-02-29 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iaso', '0035_tracker_period_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='iaso.Form'),
        ),
    ]
