# Generated by Django 2.1.11 on 2020-03-06 13:50

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("iaso", "0036_rename_mapping_to_mapping_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sent", django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ("received", django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("http_status", models.IntegerField(blank=True, null=True)),
                ("url", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExportRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("params", django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ("result", django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ("finished", models.BooleanField(default=False)),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("RUNNING", "Running"),
                            ("EXPORTED", "Exported"),
                            ("ERRORED", "Errored"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="QUEUED",
                    ),
                ),
                ("instance_count", models.IntegerField()),
                ("exported_count", models.IntegerField()),
                ("errored_count", models.IntegerField()),
                ("last_error_message", models.TextField()),
                ("queued_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "launcher",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExportStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("RUNNING", "Running"),
                            ("EXPORTED", "Exported"),
                            ("ERRORED", "Errored"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="QUEUED",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("export_logs", models.ManyToManyField(blank=True, to="iaso.ExportLog")),
                (
                    "export_request",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="iaso.ExportRequest"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mapping",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField()),
                ("mapping_type", models.TextField(choices=[("AGGREGATE", "Aggregate"), ("EVENT", "Event")])),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "data_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="mappings", to="iaso.DataSource"
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="iaso.Form"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="instance", name="last_export_success_at", field=models.DateTimeField(blank=True, null=True)
        ),
        migrations.AlterField(
            model_name="mappingversion",
            name="form_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="mapping_versions", to="iaso.FormVersion"
            ),
        ),
        migrations.AddField(
            model_name="exportstatus",
            name="instance",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="iaso.Instance"),
        ),
        migrations.AddField(
            model_name="exportstatus",
            name="mapping_version",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="iaso.MappingVersion"),
        ),
        migrations.AddField(
            model_name="mappingversion",
            name="mapping",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="iaso.Mapping",
            ),
        ),
    ]
