# Generated by Django 2.1.11 on 2020-02-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iaso", "0036_auto_20200213_1347"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="last_export_success_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
