# Generated by Django 2.1.11 on 2020-03-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaso', '0036_protect_instance_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='periods_after_allowed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='form',
            name='periods_before_allowed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.TextField(default='Untitled form'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form',
            name='period_type',
            field=models.TextField(choices=[('YEAR', 'Year'), ('QUARTER', 'Quarter'), ('MONTH', 'Month'), ('SIX_MONTH', 'Six-month'), ('TRACKER', 'Tracker')], default='TRACKER'),
        ),
        migrations.AlterField(
            model_name='form',
            name='single_per_period',
            field=models.BooleanField(default=False),
        ),
    ]
