# Generated by Django 2.1.11 on 2020-03-17 14:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("iaso", "0037_export_request_models"), ("iaso", "0036_instance_deleted")]

    operations = []
