# Generated by Django 2.1.11 on 2020-02-17 13:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("iaso", "0037_instance_last_export_success_at"),
    ]

    operations = [
        migrations.RemoveField(model_name="exportstatus", name="export_log",),
        migrations.AddField(
            model_name="exportlog",
            name="http_status",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exportlog",
            name="url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exportstatus",
            name="export_logs",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
