# Generated by Django 2.1.11 on 2020-04-08 13:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("iaso", "0038_merge_20200317_1456")]

    operations = [
        migrations.AddField(
            model_name="formversion",
            name="form_descriptor",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        )
    ]
