# Generated by Django 2.1.11 on 2020-02-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iaso", "0038_auto_20200217_1356"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportstatus",
            name="export_logs",
            field=models.ManyToManyField(blank=True, to="iaso.ExportLog"),
        ),
    ]
