# Generated by Django 2.1.11 on 2020-04-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("iaso", "0039_formversion_form_descriptor")]

    operations = [migrations.AddField(model_name="form", name="derived", field=models.BooleanField(default=False))]
