# Generated by Django 2.1.11 on 2020-04-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("iaso", "0040_form_derived")]

    operations = [
        migrations.AlterField(
            model_name="mapping",
            name="mapping_type",
            field=models.TextField(choices=[("AGGREGATE", "Aggregate"), ("EVENT", "Event"), ("DERIVED", "Derived")]),
        )
    ]
