# Generated by Django 2.1.11 on 2020-04-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("iaso", "0043_auto_20200428_0650")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="org_units",
            field=models.ManyToManyField(blank=True, related_name="iaso_profile", to="iaso.OrgUnit"),
        )
    ]
