# Generated by Django 2.1.11 on 2020-05-05 12:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("iaso", "0045_orgunit_creator"), ("iaso", "0044_profile_org_units")]

    operations = []
