# Generated by Django 2.1.11 on 2020-05-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("iaso", "0046_merge_20200505_1214")]

    operations = [
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="feature_flags",
            field=models.ManyToManyField(blank=True, related_name="_project_feature_flags_+", to="iaso.FeatureFlag"),
        ),
    ]
