# Generated by Django 2.1.11 on 2020-05-21 09:29

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("iaso", "0046_merge_20200505_1214")]

    operations = [
        migrations.AlterField(
            model_name="instance",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(blank=True, dim=3, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name="orgunit",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(blank=True, dim=3, null=True, srid=4326),
        ),
    ]
