# Generated by Django 2.1.11 on 2020-05-22 14:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("iaso", "0047_take_some_altitude"), ("iaso", "0047_feature_flags")]

    operations = []
