# Generated by Django 2.1.11 on 2020-06-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("iaso", "0052_fix_period_before_after")]

    operations = [
        migrations.AlterField(
            model_name="mapping",
            name="mapping_type",
            field=models.TextField(
                choices=[
                    ("AGGREGATE", "Aggregate"),
                    ("EVENT", "Event"),
                    ("EVENT_TRACKER", "Event Tracker"),
                    ("DERIVED", "Derived"),
                ]
            ),
        )
    ]
