# Generated by Django 2.1.11 on 2020-06-16 12:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("iaso", "0053_org_unit_path"), ("iaso", "0055_merge_20200616_1215")]

    operations = []
