# Generated by Django 2.1.11 on 2020-06-29 14:59

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("iaso", "0057_orgunit_multipoly")]

    operations = [
        migrations.AlterField(
            model_name="orgunit",
            name="catchment",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="orgunit",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="orgunit",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, dim=3, geography=True, null=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="orgunit",
            name="simplified_geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
    ]
