# Generated by Django 2.1.11 on 2020-06-16 12:23

from django.db import migrations
import django.contrib.gis.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("iaso", "0057_orgunit_multipoly"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orgunit",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                null=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="orgunit",
            name="simplified_geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                null=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="orgunit",
            name="catchment",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                null=True, srid=4326
            ),
        ),
    ]
