# Generated by Django 3.0.3 on 2020-08-11 14:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("iaso", "0058_orgunit_multipoly")]

    operations = [
        migrations.RemoveField(model_name="orgunit", name="latitude"),
        migrations.RemoveField(model_name="orgunit", name="longitude"),
    ]
