# Generated by Django 3.0.3 on 2020-11-12 12:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0063_form_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="instancefile",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="form",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
