# Generated by Django 3.0.3 on 2020-12-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("iaso", "0066_merge_20201208_1115")]

    operations = [
        migrations.AlterField(model_name="deviceownership", name="end", field=models.DateTimeField(null=True))
    ]
