# Generated by Django 3.0.3 on 2020-12-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("iaso", "0067_auto_20201209_1333")]

    operations = [
        migrations.AlterField(
            model_name="device", name="imei", field=models.CharField(blank=True, max_length=250, null=True)
        )
    ]
