# Generated by Django 3.0.7 on 2021-01-12 20:07

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("iaso", "0069_deviceposition_transport"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("progress_value", models.IntegerField(default=0)),
                ("end_value", models.IntegerField(default=100)),
                ("result", django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ("finished", models.BooleanField(default=False)),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="iaso.Account")),
                (
                    "launcher",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        )
    ]
