# Generated by Django 3.0.7 on 2021-01-18 15:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("iaso", "0073_auto_20210118_1525")]

    operations = [migrations.RemoveField(model_name="task", name="task_name")]
