# Generated by Django 3.0.7 on 2021-01-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0076_auto_20210122_1610"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportrequest",
            name="status",
            field=models.TextField(
                choices=[
                    ("QUEUED", "Queued"),
                    ("RUNNING", "Running"),
                    ("EXPORTED", "Exported"),
                    ("ERRORED", "Errored"),
                    ("SKIPPED", "Skipped"),
                    ("KILLED", "Killed"),
                    ("SUCCESS", "Success"),
                ],
                default="QUEUED",
            ),
        ),
        migrations.AlterField(
            model_name="exportstatus",
            name="status",
            field=models.TextField(
                choices=[
                    ("QUEUED", "Queued"),
                    ("RUNNING", "Running"),
                    ("EXPORTED", "Exported"),
                    ("ERRORED", "Errored"),
                    ("SKIPPED", "Skipped"),
                    ("KILLED", "Killed"),
                    ("SUCCESS", "Success"),
                ],
                default="QUEUED",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("QUEUED", "Queued"),
                    ("RUNNING", "Running"),
                    ("EXPORTED", "Exported"),
                    ("ERRORED", "Errored"),
                    ("SKIPPED", "Skipped"),
                    ("KILLED", "Killed"),
                    ("SUCCESS", "Success"),
                ],
                default="QUEUED",
                max_length=40,
            ),
        ),
    ]
