# Generated by Django 3.0.7 on 2021-02-03 17:45

import django.contrib.postgres.fields
import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0077_auto_20210125_1528"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="label_keys",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.citext.CITextField(blank=True, max_length=255),
                blank=True,
                null=True,
                size=100,
            ),
        ),
    ]
