# Generated by Django 3.0.7 on 2021-02-04 06:13

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0078_form_label_keys"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="external_token",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
