# Generated by Django 3.0.7 on 2021-02-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0079_project_external_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="external_user_id",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
