# Generated by Django 3.0.7 on 2021-03-24 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0082_exportrequest_continue_on_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="default_version",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="iaso.SourceVersion"
            ),
        ),
    ]
