# Generated by Django 3.0.7 on 2021-04-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0083_datasource_default_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="formversion",
            name="end_period",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="formversion",
            name="start_period",
            field=models.TextField(blank=True, null=True),
        ),
    ]
