# Generated by Django 3.0.7 on 2021-04-15 21:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0084_form_deleted_at"),
        ("iaso", "0084_auto_20210402_1458"),
    ]

    operations = []
