# Generated by Django 3.0.14 on 2021-05-22 10:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0085_merge_20210415_2144"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BulkOperation",
        ),
    ]
