# Generated by Django 3.0.14 on 2021-05-26 16:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0086_delete_bulkoperation"),
        ("iaso", "0086_add_version_constraints"),
    ]

    operations = []
