# Generated by Django 3.0.14 on 2021-05-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0087_merge_20210526_1646"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="domain",
            field=models.CharField(blank=True, choices=[("POLIO", "Polio")], max_length=10, null=True),
        ),
    ]
