# Generated by Django 3.0.14 on 2021-06-04 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("iaso", "0088_group_domain"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField()),
                ("content", models.TextField(blank=True, null=True)),
                ("slug", models.SlugField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ManyToManyField(blank=True, related_name="pages", to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
