# Generated by Django 3.0.14 on 2021-06-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0089_page"),
    ]

    operations = [
        migrations.RenameField(
            model_name="page",
            old_name="user",
            new_name="users",
        ),
        migrations.AlterField(
            model_name="page",
            name="slug",
            field=models.SlugField(max_length=1000, unique=True),
        ),
    ]
