# Generated by Django 3.1.12 on 2021-06-14 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0092_auto_20210611_0951"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportGPKG",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="gpkg_import/")),
                ("version_number", models.IntegerField()),
                ("data_source", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="iaso.datasource")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="iaso.project")),
            ],
        ),
    ]
