# Generated by Django 3.1.12 on 2021-06-15 13:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0093_importgpkg"),
        ("iaso", "0093_commentiaso"),
    ]

    operations = []
