# Generated by Django 3.1.12 on 2021-06-28 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iaso', '0097_add_account_feature_flag_catchment_20210624_0808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgunit',
            options={'ordering': ('path',)},
        ),
        migrations.AddField(
            model_name='project',
            name='country_org_unit_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_org_unit', to='iaso.orgunittype'),
        ),
        migrations.AddField(
            model_name='project',
            name='district_org_unit_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_org_unit', to='iaso.orgunittype'),
        ),
    ]
