# Generated by Django 3.1.12 on 2021-06-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iaso", "0098_auto_20210628_1523"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgunittype",
            name="type",
            field=models.CharField(
                blank=True, choices=[("COUNTRY", "Country"), ("DISTRICT", "District")], max_length=8, null=True
            ),
        ),
    ]
