# Generated by Django 3.1.12 on 2021-06-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0097_add_account_feature_flag_catchment_20210624_0808"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgunittype",
            name="category",
            field=models.CharField(
                blank=True, choices=[("COUNTRY", "Country"), ("DISTRICT", "District")], max_length=8, null=True
            ),
        ),
    ]
