# Generated by Django 3.1.12 on 2021-07-02 08:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0099_orgunittype_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-created_at"]},
        ),
    ]
