# Generated by Django 3.1.12 on 2021-07-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iaso", "0100_auto_20210702_0835"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalcredentials",
            name="sync",
            field=models.TextField(
                choices=[("no", "Not synced"), ("daily", "Daily"), ("weekly", "Weekly")], default="no"
            ),
        ),
    ]
