# Generated by Django 3.1.12 on 2021-08-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0101_page_needs_authentication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importgpkg",
            name="version_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
