# Generated by Django 3.1.12 on 2021-07-12 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iaso", "0101_page_needs_authentication"),
        ("iaso", "0101_externalcredentials_sync"),
    ]

    operations = []
