# Generated by Django 3.1.12 on 2021-08-27 13:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0102_auto_20210802_1612"),
        ("iaso", "0102_page_type"),
    ]

    operations = []
