# Generated by Django 3.1.12 on 2021-08-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0104_seed_form_possible_fields_20210825_0949"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="possible_fields",
            field=models.JSONField(
                blank=True,
                help_text="Questions present in all versions of the form, as a flat list.Automatically updated on new versions.",
                null=True,
            ),
        ),
    ]
