# Generated by Django 3.1.12 on 2021-09-06 13:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0103_merge_20210827_1341"),
        ("iaso", "0105_auto_20210825_1015"),
    ]

    operations = []
