# Generated by Django 3.1.14 on 2022-01-02 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("iaso", "0111_oldversioninstance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="oldversioninstance",
            name="user",
        ),
        migrations.AddField(
            model_name="instance",
            name="user",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to="auth.user"),
            preserve_default=False,
        ),
    ]
