# Generated by Django 3.1.14 on 2022-01-17 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0112_entity_entitytype"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entity",
            options={"verbose_name_plural": "Entities"},
        ),
        migrations.RemoveField(
            model_name="entity",
            name="entity_type",
        ),
        migrations.AddField(
            model_name="entity",
            name="entity_type",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="iaso.entitytype"
            ),
        ),
    ]
