# Generated by Django 3.1.14 on 2022-01-17 13:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0112_auto_20220110_0925"),
        ("iaso", "0112_auto_20220110_1503"),
    ]

    operations = []
