# Generated by Django 3.1.14 on 2022-01-03 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iaso", "0114_auto_20220102_2135"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OldVersionInstance",
        ),
    ]
