# Generated by Django 3.1.14 on 2022-01-03 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("iaso", "0115_delete_oldversioninstance"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="last_modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="last_modified_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
