# Generated by Django 3.1.14 on 2022-01-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0117_auto_20220124_1735"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="deleted_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
