# Generated by Django 3.1.14 on 2022-01-26 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0118_entity_deleted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="attributes",
            field=models.OneToOneField(
                blank=True,
                default=10939,
                help_text="instance",
                on_delete=django.db.models.deletion.PROTECT,
                to="iaso.instance",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="entity",
            name="entity_type",
            field=models.ForeignKey(
                blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to="iaso.entitytype"
            ),
            preserve_default=False,
        ),
    ]
