# Generated by Django 3.1.14 on 2022-01-26 16:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0113_add_account_feature_flag_quarter"),
        ("iaso", "0118_entity_deleted_at"),
    ]

    operations = []
