# Generated by Django 3.1.14 on 2022-03-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0123_merge_20220126_1921"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="dhis2_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
