# Generated by Django 3.1.14 on 2022-02-17 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0123_merge_20220126_1921"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgunittype",
            name="form_defining",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="iaso.form"
            ),
        ),
    ]
