# Generated by Django 3.1.14 on 2022-03-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0124_orgunitaslocationcache"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchingalgorithm",
            name="projects",
            field=models.ManyToManyField(blank=True, related_name="match_algos", to="iaso.Project"),
        ),
    ]
