# Generated by Django 3.1.14 on 2022-03-04 15:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0124_orgunitaslocationcache"),
        ("iaso", "0124_orgunittype_form_defining"),
    ]

    operations = []
