# Generated by Django 3.1.14 on 2022-03-07 11:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0124_orgunitaslocationcache"),
        ("iaso", "0113_merge_20220117_1306"),
    ]

    operations = []
