# Generated by Django 3.1.14 on 2022-03-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0125_merge_20220304_1510"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="powerbi_filters",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="powerbi_group_id",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="powerbi_report_id",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="page",
            name="type",
            field=models.CharField(
                choices=[("RAW", "Raw html"), ("TEXT", "Text"), ("IFRAME", "Iframe"), ("POWERBI", "PowerBI report")],
                default="RAW",
                max_length=40,
            ),
        ),
    ]
