# Generated by Django 3.1.14 on 2022-03-17 13:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0125_auto_20220307_1632"),
        ("iaso", "0125_merge_20220304_1510"),
    ]

    operations = []
