# Generated by Django 3.1.14 on 2022-03-04 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("iaso", "0125_merge_20220303_1339"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgunit",
            name="instance_defining",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="iaso.instance"
            ),
        ),
    ]
