# Generated by Django 3.1.14 on 2022-03-06 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iaso", "0125_merge_20220304_1344"),
        ("iaso", "0126_orgunit_instance_defining"),
    ]

    operations = []
