# Generated by Django 3.1.14 on 2022-03-23 10:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0126_merge_20220317_1305"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrgunitAsLocationCache",
        ),
    ]
