# Generated by Django 3.1.14 on 2022-03-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0126_auto_20220309_1553"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="powerbi_group_id",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="page",
            name="powerbi_report_id",
            field=models.TextField(blank=True, null=True),
        ),
    ]
