# Generated by Django 3.1.14 on 2022-03-22 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iaso", "0127_merge_20220322_1012"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="dhis2_id",
        ),
    ]
