# Generated by Django 3.1.14 on 2022-03-28 05:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0128_orgunit_instance_defining"),
        ("iaso", "0128_auto_20220324_1212"),
    ]

    operations = []
