# Generated by Django 3.1.14 on 2022-04-01 14:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0125_merge_20220307_1107"),
        ("iaso", "0129_merge_20220328_0559"),
    ]

    operations = []
