# Generated by Django 3.1.14 on 2022-03-29 08:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0127_delete_orgunitaslocationcache"),
        ("iaso", "0129_merge_20220328_0559"),
    ]

    operations = []
