# Generated by Django 3.1.14 on 2022-04-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0129_merge_20220328_0559"),
    ]

    operations = [
        migrations.AddField(
            model_name="importgpkg",
            name="description",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
