# Generated by Django 3.1 on 2022-04-12 11:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0130_importgpkg_description"),
        ("iaso", "0131_merge_20220412_0752"),
    ]

    operations = []
