# Generated by Django 3.1.14 on 2022-04-18 13:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0132_merge_20220412_1136"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orgunittype",
            old_name="form_defining",
            new_name="reference_form",
        ),
    ]
