# Generated by Django 3.1.14 on 2022-04-13 11:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0130_merge_20220401_1428"),
        ("iaso", "0130_merge_20220410_1802"),
        ("iaso", "0132_merge_20220412_1136"),
    ]

    operations = []
