# Generated by Django 3.1.14 on 2022-04-19 07:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0133_auto_20220418_1321"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orgunit",
            old_name="instance_defining",
            new_name="reference_instance",
        ),
    ]
