# Generated by Django 3.1.14 on 2022-05-16 08:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0136_auto_20220511_0925"),
        ("iaso", "0134_merge_20220510_1428"),
    ]

    operations = []
