# Generated by Django 3.2.13 on 2022-05-19 09:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0134_team"),
        ("iaso", "0137_merge_20220516_0832"),
    ]

    operations = []
