# Generated by Django 3.2.13 on 2022-05-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0139_planning"),
    ]

    operations = [
        migrations.RenameField(
            model_name="planning",
            old_name="end_date",
            new_name="ended_at",
        ),
        migrations.RenameField(
            model_name="planning",
            old_name="start_date",
            new_name="started_at",
        ),
        migrations.AlterField(
            model_name="planning",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
