# Generated by Django 3.2.13 on 2022-05-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0140_auto_20220519_1249"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planning",
            name="ended_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="planning",
            name="started_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
