# Generated by Django 3.2.13 on 2022-05-30 08:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0139_bulkcreateusercsvfile_account"),
        ("iaso", "0140_auto_20220519_1249"),
    ]

    operations = []
