# Generated by Django 3.2.13 on 2022-05-30 08:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0141_auto_20220520_1239"),
        ("iaso", "0141_merge_20220530_0808"),
    ]

    operations = []
