# Generated by Django 3.2.13 on 2022-05-30 11:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0142_assignment"),
        ("iaso", "0142_merge_20220530_0856"),
    ]

    operations = []
