# Generated by Django 3.2.13 on 2022-06-08 09:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0143_add_microplanning_feature_flag"),
        ("iaso", "0144_alter_assignment_options"),
    ]

    operations = []
