# Generated by Django 3.2.13 on 2022-06-09 13:30

from django.db import migrations
import django_ltree.fields


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0145_merge_20220608_0900"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="path",
            field=django_ltree.fields.PathField(blank=True, null=True, unique=True),
        ),
    ]
