# Generated by Django 3.2.13 on 2022-07-05 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iaso", "0150_instance_validations_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="instance",
            old_name="validations_status",
            new_name="validation_status",
        ),
    ]
