# Generated by Django 3.2.14 on 2022-07-18 13:59

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0150_profile_home_page"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={"base_manager_name": "all_objects"},
        ),
        migrations.AlterModelManagers(
            name="group",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
