# Generated by Django 3.2.13 on 2022-07-18 10:13

from django.db import migrations


def create_feature_flags(apps, schema_editor):
    FeatureFlag = apps.get_model("iaso", "FeatureFlag")
    FeatureFlag.objects.create(code="CHECK_POSITION_FOR_FORMS", name="Mobile: Check right location.")


def destroy_feature_flags(apps, schema_editor):
    FeatureFlag = apps.get_model("iaso", "FeatureFlag")
    FeatureFlag.objects.filter(code="CHECK_POSITION_FOR_FORMS").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0150_profile_home_page"),
    ]

    operations = [
        migrations.RunPython(create_feature_flags, destroy_feature_flags),
    ]
