# Generated by Django 3.2.13 on 2022-07-07 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("iaso", "0151_rename_validations_status_instance_validation_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstanceLockTable",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("is_locked", models.BooleanField(default=False)),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                (
                    "top_org_unit",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="iaso.orgunit"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
