# Generated by Django 3.2.14 on 2022-08-22 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("iaso", "0152_project_min_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstanceLock",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("locked_at", models.DateTimeField(auto_now_add=True)),
                ("unlocked_at", models.DateTimeField(blank=True, null=True)),
                ("instance", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="iaso.instance")),
                (
                    "locked_by",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "top_org_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="instance_lock", to="iaso.orgunit"
                    ),
                ),
                (
                    "unlocked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
