# Generated by Django 3.2.15 on 2022-08-19 13:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0152_merge_0151_auto_20220718_1013_0151_auto_20220718_1359"),
        ("iaso", "0152_project_min_version"),
    ]

    operations = []
