# Generated by Django 3.2.13 on 2022-07-08 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iaso', '0153_instancelocktable_instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancelocktable',
            name='top_org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instance_lock', to='iaso.orgunit'),
        ),
    ]
