# Generated by Django 3.2.13 on 2022-07-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iaso", "0154_alter_instancelocktable_top_org_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instance",
            name="validation_status",
            field=models.CharField(
                blank=True,
                choices=[("LOCKED", "locked"), ("REVIEWED", "reviewed")],
                default="",
                max_length=255,
                null=True,
            ),
        ),
    ]
