# Generated by Django 3.2.14 on 2022-08-16 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0155_alter_entitytype_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="attributes",
            field=models.OneToOneField(
                blank=True,
                help_text="instance",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attributes",
                to="iaso.instance",
            ),
        ),
    ]
