# Generated by Django 3.2.14 on 2022-08-17 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0156_auto_20220817_0910"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entity",
            name="instances",
        ),
        migrations.AddField(
            model_name="instance",
            name="entity",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="iaso.entity"
            ),
        ),
    ]
