# Generated by Django 3.1.14 on 2022-07-15 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iaso", "0150_profile_home_page"),
        ("iaso", "0157_instancelocktable_created_at"),
    ]

    operations = []
