# Generated by Django 3.1.14 on 2022-07-15 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iaso", "0158_merge_20220715_1514"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instance",
            name="validation_status",
        ),
    ]
