# Generated by Django 3.2.14 on 2022-08-17 12:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0156_alter_entity_attributes"),
        ("iaso", "0158_alter_instance_entity"),
    ]

    operations = []
