# Generated by Django 3.2.14 on 2022-08-19 12:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0152_project_min_version"),
        ("iaso", "0159_merge_20220817_1233"),
    ]

    operations = []
