# Generated by Django 3.2.14 on 2022-08-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0160_merge_20220819_1239"),
    ]

    operations = [
        migrations.AddField(
            model_name="entitytype",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
