# Generated by Django 3.2.15 on 2022-09-01 10:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0161_merge_20220829_0920"),
        ("iaso", "0161_rename_fields_detail_view_entitytype_fields_detail_info_view"),
    ]

    operations = []
