# Generated by Django 3.2.15 on 2022-09-02 10:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0161_alter_account_name"),
        ("iaso", "0162_merge_20220901_1052"),
    ]

    operations = []
