# Generated by Django 3.2.14 on 2022-09-02 16:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0162_merge_20220901_0953"),
        ("iaso", "0162_merge_20220901_1052"),
    ]

    operations = []
