# Generated by Django 3.2.15 on 2022-09-06 11:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0163_merge_0153_instancelock_0162_merge_20220901_1052"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="instancelock",
            options={"ordering": ["-locked_at"]},
        ),
    ]
