# Generated by Django 3.2.14 on 2022-09-08 14:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0163_merge_20220902_1037"),
        ("iaso", "0165_merge_20220906_1200"),
    ]

    operations = []
