# Generated by Django 3.2.15 on 2022-09-13 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iaso", "0165_merge_20220908_1357"),
        ("iaso", "0167_merge_20220909_1207"),
    ]

    operations = []
