# Generated by Django 3.2.15 on 2022-09-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iaso", "0167_merge_20220909_1207"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="source_created_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="instance",
            name="source_updated_at",
            field=models.DateTimeField(null=True),
        ),
    ]
