# Generated by Django 3.2.15 on 2022-09-20 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iaso", "0168_auto_20220920_1459"),
    ]

    operations = [
        migrations.RunSQL(sql="update iaso_instance set source_created_at=created_at where source_created_at is null"),
        migrations.RunSQL(
            sql="update iaso_instance set source_updated_at = updated_at where source_updated_at is null"
        ),
    ]
