# Generated by Django 3.2.15 on 2022-09-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iaso", "0170_auto_20220920_1531"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgunit",
            name="source_created_at",
            field=models.DateTimeField(blank=True, help_text="Creation time on the client device", null=True),
        ),
        migrations.AddField(
            model_name="orgunit",
            name="source_updated_at",
            field=models.DateTimeField(blank=True, help_text="Update time on the client device", null=True),
        ),
    ]
