# Generated by Django 3.2.15 on 2022-10-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0175_storagelogentry_status_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="storagedevice",
            name="status_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
