# Generated by Django 3.2.15 on 2022-11-14 06:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0176_storagedevice_status_updated_at"),
    ]

    operations = []
