# Generated by Django 3.2.15 on 2022-11-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0178_remove_beneficiary_user_perm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="period_type",
            field=models.TextField(
                blank=True,
                choices=[
                    ("DAY", "Day"),
                    ("MONTH", "Month"),
                    ("QUARTER", "Quarter"),
                    ("SIX_MONTH", "Six-month"),
                    ("YEAR", "Year"),
                ],
                null=True,
            ),
        ),
    ]
