# Generated by Django 3.2.15 on 2022-12-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0180_workflow_workflowchange_workflowfollowup_workflowversion"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workflowchange",
            old_name="workflow",
            new_name="workflow_version",
        ),
        migrations.RenameField(
            model_name="workflowfollowup",
            old_name="workflow",
            new_name="workflow_version",
        ),
        migrations.AlterField(
            model_name="workflowversion",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("UNPUBLISHED", "Unpublished"), ("PUBLISHED", "Published")],
                default="DRAFT",
                max_length=12,
            ),
        ),
    ]
