# Generated by Django 3.2.15 on 2022-11-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaso', '0180_workflowversion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowversion',
            name='name',
            field=models.CharField(default='No Name', max_length=50),
        ),
    ]
