# Generated by Django 3.2.15 on 2022-12-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0181_auto_20221208_1104"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowfollowup",
            name="condition",
            field=models.JSONField(default=dict),
        ),
    ]
