# Generated by Django 3.2.15 on 2022-12-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0183_set_storagedevice_status_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storagedevice",
            name="status_updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
