# Generated by Django 3.2.15 on 2022-11-25 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iaso', '0183_workflowversion_reference_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflowfollowup',
            old_name='conditions',
            new_name='condition',
        ),
    ]
