# Generated by Django 3.2.15 on 2022-12-13 09:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0179_alter_form_period_type"),
        ("iaso", "0184_alter_storagedevice_status_updated_at"),
    ]

    operations = []
