# Generated by Django 3.2.15 on 2022-12-22 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iaso', '0185_merge_20221213_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='submission_to_be_validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='form_to_be_validated_by', to='iaso.orgunittype'),
        ),
    ]
