# Generated by Django 3.2.15 on 2023-01-12 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iaso", "0186_workflowversion_deleted_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workflowversion",
            name="reference_form",
        ),
    ]
