# Generated by Django 3.2.15 on 2022-12-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0187_reportversion_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportversion",
            name="file",
            field=models.FileField(upload_to="reports"),
        ),
    ]
