# Generated by Django 3.2.15 on 2023-01-09 17:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0186_workflowversion_deleted_at"),
        ("iaso", "0188_alter_reportversion_file"),
    ]

    operations = []
