# Generated by Django 3.2.15 on 2023-01-20 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iaso", "0187_remove_workflowversion_reference_form"),
        ("iaso", "0189_merge_20230109_1747"),
    ]

    operations = []
