# Generated by Django 3.2.15 on 2023-01-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0189_merge_20230109_1747"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="sourceversion",
            constraint=models.UniqueConstraint(
                fields=("data_source", "number"), name="unique_number_data_source_version"
            ),
        ),
    ]
