# Generated by Django 3.2.15 on 2023-01-31 09:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0190_sourceversion_unique_number_data_source_version"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="users",
        ),
    ]
