# Generated by Django 3.2.15 on 2023-01-25 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iaso", "0190_merge_20230120_1227"),
        ("iaso", "0190_sourceversion_unique_number_data_source_version"),
    ]

    operations = []
