# Generated by Django 3.2.15 on 2023-01-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iaso", "0190_sourceversion_unique_number_data_source_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="powerbi_language",
            field=models.CharField(
                blank=True,
                help_text="Language and locale for the PowerBI embedded report e.g en-us or fr-be",
                max_length=20,
                null=True,
            ),
        ),
    ]
