# Generated by Django 3.2.15 on 2023-02-02 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0191_merge_20230125_1559"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="planning",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="instances",
                to="iaso.planning",
            ),
        ),
    ]
