# Generated by Django 3.2.15 on 2023-02-28 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("iaso", "0192_merge_20230131_1036"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instance",
            name="form_version_id",
        ),
        migrations.AddField(
            model_name="instance",
            name="form_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="form_version",
                to="iaso.formversion",
            ),
        ),
    ]
