# Generated by Django 3.2.15 on 2023-02-21 09:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0192_merge_20230131_1306"),
        ("iaso", "0193_merge_0192_instance_planning_0192_merge_20230131_1353"),
    ]

    operations = []
