# Generated by Django 3.2.15 on 2023-04-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iaso", "0200_jsondatastore"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jsondatastore",
            name="content",
            field=models.JSONField(null=True),
        ),
    ]
