# Generated by Django 3.2.15 on 2023-04-19 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0201_alter_jsondatastore_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jsondatastore",
            name="account",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to="iaso.account"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="jsondatastore",
            name="content",
            field=models.JSONField(default={"test": "ok"}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="jsondatastore",
            name="slug",
            field=models.SlugField(),
        ),
    ]
