# Generated by Django 3.2.15 on 2023-04-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iaso", "0202_auto_20230419_1444"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="to_display",
            field=models.BooleanField(default=False),
        ),
    ]
