# Generated by Django 3.2.15 on 2023-04-28 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iaso", "0203_group_to_display"),
    ]

    operations = [
        migrations.RenameField(
            model_name="group",
            old_name="to_display",
            new_name="block_of_countries",
        ),
    ]
