# Generated by Django 3.2.15 on 2023-05-04 13:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0198_instance_form_version"),
        ("iaso", "0204_rename_to_display_group_block_of_countries"),
    ]

    operations = []
