# Generated by Django 3.2.15 on 2023-05-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0205_merge_20230504_1352"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planning",
            name="forms",
            field=models.ManyToManyField(related_name="plannings", to="iaso.Form"),
        ),
    ]
