# Generated by Django 3.2.15 on 2023-05-23 09:51

from django.db import migrations, models
import django.db.models.deletion
import iaso.models.forms


class Migration(migrations.Migration):

    dependencies = [
        ("iaso", "0206_add_feature_flag_LIMIT_OU_DOWNLOAD_TO_ROOTS"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormAttachment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField()),
                ("file", models.FileField(upload_to=iaso.models.forms.FormAttachment.form_folder)),
                ("md5", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="iaso.form"
                    ),
                ),
            ],
            options={
                "unique_together": {("form", "name")},
            },
        ),
    ]
