# Generated by Django 3.2.15 on 2023-05-08 08:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0205_merge_20230505_0828"),
        ("iaso", "0206_merge_20230508_0829"),
    ]

    operations = []
