# Generated by Django 3.2.15 on 2023-05-24 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iaso', '0207_formattachment'),
        ('iaso', '0207_merge_20230508_0849'),
    ]

    operations = [
    ]
