# Generated by Django 3.2.15 on 2023-05-31 09:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0207_formattachment"),
        ("iaso", "0207_merge_20230517_1226"),
    ]

    operations = []
