# Generated by Django 3.2.15 on 2023-06-05 13:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0208_merge_0207_formattachment_0207_merge_20230508_0849"),
        ("iaso", "0208_merge_0207_formattachment_0207_merge_20230517_1226"),
    ]

    operations = []
