# Generated by Django 3.2.15 on 2023-06-02 10:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0207_orgunittype_allow_creating_sub_unit_types"),
        ("iaso", "0208_merge_0207_formattachment_0207_merge_20230517_1226"),
    ]

    operations = []
