# Generated by Django 3.2.15 on 2023-06-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0208_merge_0207_formattachment_0207_merge_20230517_1226"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orgunit",
            name="validation_status",
            field=models.CharField(
                choices=[("NEW", "new"), ("VALID", "valid"), ("REJECTED", "rejected"), ("CLOSED", "closed")],
                default="NEW",
                max_length=25,
            ),
        ),
    ]
