# Generated by Django 3.2.15 on 2023-06-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaso', '0209_alter_orgunit_validation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgunit',
            name='validation_status',
            field=models.CharField(choices=[('NEW', 'new'), ('VALID', 'valid'), ('REJECTED', 'rejected')], default='NEW', max_length=25),
        ),
    ]
