# Generated by Django 3.2.15 on 2023-06-06 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iaso', '0210_auto_20230605_1314'),
    ]

    operations = [
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;",
                          "DROP EXTENSION IF EXISTS fuzzystrmatch;"),
    ]
