# Generated by Django 3.2.15 on 2023-06-08 13:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0209_merge_20230602_1002"),
        ("iaso", "0211_auto_20230606_1322"),
    ]

    operations = []
