# Generated by Django 3.2.15 on 2023-06-12 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0212_merge_20230608_1352"),
    ]

    operations = [
        migrations.RenameModel("EntityDuplicateAnalyze", "EntityDuplicateAnalyzis"),
        migrations.AlterField(
            model_name="entityduplicate",
            name="analyze",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="duplicates",
                to="iaso.entityduplicateanalyzis",
            ),
        ),
    ]
