# Generated by Django 3.2.15 on 2023-06-12 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0213_auto_20230612_0825"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entityduplicateanalyzis",
            name="task",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entity_duplicate_analyzis",
                to="iaso.task",
            ),
        ),
    ]
