# Generated by Django 3.2.15 on 2023-06-19 09:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0216_merge_20230614_0839"),
        ("iaso", "0216_profile_projects"),
    ]

    operations = []
