# Generated by Django 3.2.15 on 2023-06-27 12:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0217_fill_allow_creating_sub_unit_types"),
        ("iaso", "0217_profile_user_roles"),
    ]

    operations = []
