# Generated by Django 3.2.15 on 2023-06-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0218_merge_20230621_0850"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="projects",
            field=models.ManyToManyField(blank=True, related_name="iaso_profile", to="iaso.Project"),
        ),
    ]
