# Generated by Django 3.2.15 on 2023-06-28 10:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0218_merge_20230627_1233"),
        ("iaso", "0219_alter_profile_projects"),
    ]

    operations = []
