# Generated by Django 3.2.15 on 2023-07-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0220_merge_20230628_1038"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featureflag",
            name="code",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
