# Generated by Django 3.2.15 on 2023-06-30 07:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0217_fill_allow_creating_sub_unit_types"),
        ("iaso", "0220_add_feature_flag_MOBILE_FORCE_OU_UPDATE"),
    ]

    operations = []
