# Generated by Django 3.2.15 on 2023-07-18 13:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0221_alter_featureflag_code"),
        ("iaso", "0221_merge_20230630_0710"),
    ]

    operations = []
