# Generated by Django 3.2.15 on 2023-07-18 15:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0222_merge_20230718_1414"),
        ("iaso", "0222_merge_20230718_1500"),
    ]

    operations = []
