# Generated by Django 3.2.15 on 2023-07-19 12:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0222_merge_20230718_1321"),
        ("iaso", "0223_merge_20230718_1530"),
    ]

    operations = []
