# Generated by Django 3.2.15 on 2023-07-19 14:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0223_merge_20230718_1708"),
        ("iaso", "0224_merge_20230719_1238"),
    ]

    operations = []
