# Generated by Django 3.2.15 on 2023-07-24 12:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0223_merge_20230719_0755"),
        ("iaso", "0225_merge_20230719_1411"),
    ]

    operations = []
