# Generated by Django 3.2.15 on 2023-08-29 20:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0229_merge_20230829_1353"),
        ("iaso", "0229_merge_20230829_1408"),
    ]

    operations = []
