# Generated by Django 3.2.15 on 2023-09-04 21:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0229_remove_uuid_null_20230824_1448"),
        ("iaso", "0230_merge_20230829_2057"),
    ]

    operations = []
