# Generated by Django 3.2.15 on 2023-09-01 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("iaso", "0231_module"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModulePermission",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "module",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="iaso.module"
                    ),
                ),
                (
                    "permission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="iaso_module_permission",
                        to="auth.permission",
                    ),
                ),
            ],
        ),
    ]
