# Generated by Django 3.2.21 on 2023-09-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0231_merge_20230904_2154"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgunittype",
            name="reference_forms",
            field=models.ManyToManyField(related_name="org_unit_type_references", to="iaso.Form"),
        ),
    ]
