# Generated by Django 3.2.21 on 2023-09-21 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0231_merge_20230904_2154"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgunittype",
            name="reference_forms",
            field=models.ManyToManyField(blank=True, related_name="org_unit_type_references", to="iaso.Form"),
        ),
        migrations.CreateModel(
            name="OrgUnitReferenceInstance",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("form", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="iaso.form")),
                ("instance", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="iaso.instance")),
                ("org_unit", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="iaso.orgunit")),
            ],
            options={
                "unique_together": {("org_unit", "form")},
            },
        ),
        migrations.AddField(
            model_name="orgunit",
            name="reference_instances",
            field=models.ManyToManyField(
                blank=True,
                through="iaso.OrgUnitReferenceInstance",
                to="iaso.Instance",
            ),
        ),
    ]
