# Generated by Django 3.2.21 on 2023-09-19 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0231_merge_20230904_2154"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockItem",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=500)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="iaso.account"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.IntegerField()),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="iaso.account"
                    ),
                ),
                ("org_unit", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="iaso.orgunit")),
                ("stock_item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="iaso.stockitem")),
            ],
        ),
    ]
