# Generated by Django 3.2.15 on 2023-09-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0231_merge_20230904_2154"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="external",
            field=models.BooleanField(default=False),
        ),
    ]
