# Generated by Django 3.2.15 on 2023-09-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0232_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="modules",
            field=models.ManyToManyField(related_name="account_modules", to="iaso.Module"),
        ),
    ]
