# Generated by Django 3.2.21 on 2023-09-15 08:05
"""
We are replacing `OrgUnitType.reference_form` by `OrgUnitType.reference_forms`
to enable the possibility to have several "reference forms" per OrgUnitType.
Before deleting `OrgUnitType.reference_form`, we need to move its data to the
new field.
"""


from django.db import migrations


def migrate_data_forward(apps, schema_editor):
    OrgUnitType = apps.get_model("iaso", "OrgUnitType")
    for org_unit in OrgUnitType.objects.all():
        if org_unit.reference_form_id:
            org_unit.reference_forms.add(org_unit.reference_form)
            org_unit.save()


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0232_orgunittype_reference_forms"),
    ]

    operations = [migrations.RunPython(migrate_data_forward, migrations.RunPython.noop, elidable=True)]
