# Generated by Django 3.2.21 on 2023-09-25 12:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0232_check_no_duplicated_version_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="formversion",
            unique_together={("form", "version_id")},
        ),
    ]
