# Generated by Django 3.2.15 on 2023-09-01 09:40

from django.db import migrations
from django.contrib.auth.models import Permission
from iaso.models import ModulePermission


def create_module_permisssions(apps, schema_editor):
    for permission in Permission.objects.filter(codename__startswith="iaso_"):
        ModulePermission.objects.get_or_create(permission=permission)


def reverse_create_module_permisssions(apps, schema_editor):
    Permission.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0232_modulepermission"),
    ]

    operations = [
        migrations.RunPython(create_module_permisssions, reverse_create_module_permisssions),
    ]
