# Generated by Django 3.2.21 on 2023-09-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0234_remove_orgunittype_reference_form"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgunit",
            name="reference_instances",
            field=models.ManyToManyField(related_name="is_reference_for_org_units", to="iaso.Instance"),
        ),
    ]
