# Generated by Django 3.2.21 on 2023-10-12 06:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0232_task_external"),
        ("iaso", "0234_delete_reference_form_and_reference_instance"),
    ]

    operations = []
