# Generated by Django 3.2.15 on 2023-09-16 11:57

from django.db import migrations
from iaso.models import Module
from hat.menupermissions.constants import MODULES


def create_modules(apps, schema_editor):
    for module in MODULES:
        Module.objects.get_or_create(name=module["name"], codename=module["codename"])


def reverse_create_modules(apps, schema_editor):
    Module.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0235_create_iaso_permission_for_each_auth_permission"),
    ]

    operations = [
        migrations.RunPython(create_modules, reverse_create_modules),
    ]
