# Generated by Django 3.2.22 on 2023-10-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0236_auto_20231012_0955"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgunit",
            name="closed_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orgunit",
            name="opening_date",
            field=models.DateTimeField(null=True),
        ),
    ]
