# Generated by Django 3.2.15 on 2023-09-16 12:02

from django.db import migrations
from rest_framework.generics import get_object_or_404
from iaso.models import Module, Permission

MODULE_PERMISSIONS = {
    "DATA_COLLECTION_FORMS": [
        "iaso_forms",
        "iaso_update_submission",
        "iaso_submissions",
        "iaso_completeness",
        "iaso_completeness_stats",
    ],
    "DEFAULT": [
        "iaso_org_units",
        "iaso_org_unit_types",
        "iaso_sources",
        "iaso_links",
        "iaso_data_tasks",
        "iaso_reports",
        "iaso_projects",
        "iaso_users",
        "iaso_user_roles",
        "iaso_teams",
    ],
    "DHIS2_MAPPING": ["iaso_mappings"],
    "EMBEDDED_LINKS": ["iaso_pages"],
    "ENTITIES": ["iaso_entities", "iaso_workflows", "iaso_entity_duplicates_write", "iaso_entity_duplicates_read"],
    "EXTERNAL_STORAGE": ["iaso_storages"],
    "PLANNING": ["iaso_assignments"],
    "POLIO_PROJECT": ["iaso_polio_config", "iaso_polio", "iaso_polio_budget_admin", "iaso_polio_budget"],
    "REGISTRY": ["iaso_registry"],
}


def create_link_modules_and_permissions(apps, schema_editor):
    for key_module, permissions_value in MODULE_PERMISSIONS.items():
        module = get_object_or_404(Module, codename=key_module)
        permissions = Permission.objects.filter(permission__codename__in=permissions_value)
        if len(permissions) > 0:
            module.permission_set.set(permissions)
            module.save()


def reverse_create_link_modules_and_permissions(apps, schema_editor):
    for key_module in MODULE_PERMISSIONS.keys():
        module = get_object_or_404(Module, codename=key_module)
        module.permission_set.set([])
        module.save()


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0236_create_module"),
    ]

    operations = [
        migrations.RunPython(create_link_modules_and_permissions, reverse_create_link_modules_and_permissions),
    ]
