# Generated by Django 3.2.15 on 2023-09-11 12:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0231_merge_20230904_2154"),
        ("iaso", "0236_account_modules"),
    ]

    operations = []
