# Generated by Django 3.2.15 on 2023-09-16 12:02

from django.db import migrations
from rest_framework.generics import get_object_or_404
from iaso.models import Module, Permission
from hat.menupermissions.constants import MODULE_PERMISSIONS


def create_link_modules_and_permissions(apps, schema_editor):
    for key_module, permissions_value in MODULE_PERMISSIONS.items():
        module = get_object_or_404(Module, codename=key_module)
        permissions = Permission.objects.filter(permission__codename__in=permissions_value)
        if len(permissions) > 0:
            module.permission_set.set(permissions)
            module.save()


def reverse_create_link_modules_and_permissions(apps, schema_editor):
    for key_module in MODULE_PERMISSIONS.keys():
        module = get_object_or_404(Module, codename=key_module)
        module.permission_set.set([])
        module.save()


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0236_create_module"),
    ]

    operations = [
        migrations.RunPython(create_link_modules_and_permissions, reverse_create_link_modules_and_permissions),
    ]
