# Generated by Django 3.2.22 on 2023-10-24 07:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0237_add_account_feature_flag_SHOW_HOME_ONLINE"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orgunitchangerequest",
            old_name="new_accuracy",
            new_name="new_location_accuracy",
        ),
        migrations.AddField(
            model_name="orgunitchangerequest",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
