# Generated by Django 3.2.21 on 2023-10-17 12:47

from django.db import migrations, models
import iaso.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('iaso', '0237_add_modules_to_all_existing_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='modules',
            field=iaso.models.base.ChoiceArrayField(base_field=models.CharField(choices=[('DATA_COLLECTION_FORMS', 'Data collection - Forms'), ('DEFAULT', 'Default'), ('DHIS2_MAPPING', 'DHIS2 mapping'), ('EMBEDDED_LINKS', 'Embedded links'), ('ENTITIES', 'Entities'), ('EXTERNAL_STORAGE', 'External storage'), ('PLANNING', 'Planning'), ('POLIO_PROJECT', 'Polio project'), ('REGISTRY', 'Registry')], max_length=100), blank=True, default=list, null=True, size=None),
        ),
    ]
