# Generated by Django 3.2.15 on 2023-09-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0237_create_link_modules_and_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="codename",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
