# Generated by Django 3.2.22 on 2023-10-18 12:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0237_orgunitchangerequest_uuid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orgunitchangerequest",
            old_name="new_accuracy",
            new_name="new_location_accuracy",
        ),
    ]
