# Generated by Django 3.2.15 on 2023-10-06 13:12

from django.db import migrations
from iaso.models import Module, Account
from hat.menupermissions.constants import MODULES


def add_modules_to_accounts(apps, schema_editor):
    codenames = [module["codename"] for module in MODULES]
    modules = Module.objects.filter(codename__in=codenames)
    all_accounts = Account.objects.all()
    for account in all_accounts:
        account.modules.set(modules)
        account.save()


def reverse_add_modules_to_accounts(apps, schema_editor):
    all_accounts = Account.objects.all()
    for account in all_accounts:
        account.modules.set([])
        account.save()


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0239_merge_20231006_0832"),
    ]

    operations = [
        migrations.RunPython(add_modules_to_accounts, reverse_add_modules_to_accounts),
    ]
