# Generated by Django 3.2.22 on 2023-10-26 07:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0238_rename_new_accuracy_orgunitchangerequest_new_location_accuracy_uuid"),
        ("iaso", "0240_merge_20231020_1142"),
    ]

    operations = []
