# Generated by Django 3.2.22 on 2023-10-26 15:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0239_add_opening_and_closed_date_in_org_unit"),
        ("iaso", "0242_merge_20231026_0921"),
    ]

    operations = []
