# Generated by Django 3.2.21 on 2023-11-09 12:19

from django.db import migrations


def create_feature_flags(apps, schema_editor):
    FeatureFlag = apps.get_model("iaso", "FeatureFlag")
    FeatureFlag.objects.create(
        code="SHOW_DEV_FEATURES",
        name="Show in development features.",
    )


def destroy_feature_flags(apps, schema_editor):
    FeatureFlag = apps.get_model("iaso", "FeatureFlag")
    FeatureFlag.objects.filter(code="SHOW_DEV_FEATURES").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0242_merge_20231026_0921"),
    ]

    operations = [migrations.RunPython(create_feature_flags, destroy_feature_flags)]
