# Generated by Django 3.2.22 on 2023-10-31 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0242_merge_20231026_0921"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instance",
            name="planning",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instances",
                to="iaso.planning",
            ),
        ),
    ]
