# Generated by Django 3.2.22 on 2023-11-10 07:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0243_alter_instance_planning"),
        ("iaso", "0243_merge_20231026_1533"),
    ]

    operations = []
