# Generated by Django 3.2.22 on 2023-11-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0243_alter_instance_planning"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="formversion",
            constraint=models.UniqueConstraint(
                fields=("version_id", "form_id"), name="duplicate_version_id_for_same_form"
            ),
        ),
    ]
