# Generated by Django 3.2.22 on 2023-10-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0243_merge_20231026_1533"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgunitchangerequest",
            name="new_closed_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orgunitchangerequest",
            name="new_opening_date",
            field=models.DateField(null=True),
        ),
    ]
