# Generated by Django 3.2.21 on 2023-11-13 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iaso', '0243_alter_instance_planning'),
        ('iaso', '0244_alter_form_legend_threshold'),
    ]

    operations = [
    ]
