# Generated by Django 3.2.22 on 2023-11-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0244_add_opening_and_closed_date_in_org_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgunitchangerequest",
            name="new_closed_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orgunitchangerequest",
            name="new_opening_date",
            field=models.DateField(null=True),
        ),
    ]
