# Generated by Django 3.2.22 on 2023-11-20 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0245_auto_20231123_0912"),
    ]

    operations = [
        migrations.AddField(
            model_name="jsondatastore",
            name="org_unit",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="iaso.orgunit"),
        ),
        migrations.AlterUniqueTogether(
            name="jsondatastore",
            unique_together={("slug", "account", "org_unit")},
        ),
    ]
