# Generated by Django 3.2.22 on 2023-11-28 11:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0245_auto_20231123_0912"),
        ("iaso", "0245_merge_20231113_0947"),
    ]

    operations = []
