# Generated by Django 3.2.21 on 2023-11-29 13:00

from django.db import migrations


def create_feature_flags(apps, schema_editor):
    # Delete the model feature flag
    FeatureFlag = apps.get_model("iaso", "FeatureFlag")
    FeatureFlag.objects.filter(code="SHOW_DEV_FEATURES").delete()

    # Add the account feature flag
    AccountFeatureFlag = apps.get_model("iaso", "AccountFeatureFlag")
    AccountFeatureFlag.objects.get_or_create(
        code="SHOW_DEV_FEATURES", defaults={"name": "Display dev features in web."}
    )


def destroy_feature_flags(apps, schema_editor):
    # Recreate the model feature flag
    FeatureFlag = apps.get_model("iaso", "FeatureFlag")
    FeatureFlag.objects.create(
        code="SHOW_DEV_FEATURES",
        name="Show in development features.",
    )

    # Delete the account feature flag
    AccountFeatureFlag = apps.get_model("iaso", "AccountFeatureFlag")
    AccountFeatureFlag.objects.get(code="SHOW_DEV_FEATURES", name="Display dev features in web.").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0246_merge_20231124_1048"),
    ]

    operations = [migrations.RunPython(create_feature_flags, destroy_feature_flags)]
