# Generated by Django 3.2.22 on 2023-12-05 11:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0246_add_feature_flags"),
        ("iaso", "0247_merge_20231205_0938"),
    ]

    operations = []
