# Generated by Django 3.2.22 on 2023-12-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0249_merge_20231205_1120"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="analytics_script",
            field=models.TextField(blank=True, null=True),
        ),
    ]
