# Generated by Django 4.2.8 on 2023-12-29 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("iaso", "0251_merge_20231212_0857"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentiaso",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to={"model": "orgunit"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_type_set_for_%(class)s2",
                to="contenttypes.contenttype",
                verbose_name="content type",
            ),
        ),
        migrations.AlterField(
            model_name="commentiaso",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="feature_flags",
            field=models.ManyToManyField(blank=True, related_name="+", to="iaso.featureflag"),
        ),
    ]
