# Generated by Django 4.2.8 on 2023-12-29 13:15

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("iaso", "0252_case_insensitive_collation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentiaso",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to={"model": "orgunit"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_type_set_for_%(class)s2",
                to="contenttypes.contenttype",
                verbose_name="content type",
            ),
        ),
        migrations.AlterField(
            model_name="commentiaso",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="entitytype",
            name="fields_detail_info_view",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, db_collation="case_insensitive", max_length=255),
                blank=True,
                null=True,
                size=100,
            ),
        ),
        migrations.AlterField(
            model_name="entitytype",
            name="fields_duplicate_search",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, db_collation="case_insensitive", max_length=255),
                blank=True,
                null=True,
                size=100,
            ),
        ),
        migrations.AlterField(
            model_name="entitytype",
            name="fields_list_view",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, db_collation="case_insensitive", max_length=255),
                blank=True,
                null=True,
                size=100,
            ),
        ),
        migrations.AlterField(
            model_name="form",
            name="label_keys",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, db_collation="case_insensitive", max_length=255),
                blank=True,
                null=True,
                size=100,
            ),
        ),
        migrations.AlterField(
            model_name="orgunit",
            name="aliases",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, db_collation="case_insensitive", max_length=255),
                blank=True,
                null=True,
                size=100,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="feature_flags",
            field=models.ManyToManyField(blank=True, related_name="+", to="iaso.featureflag"),
        ),
    ]
