# Generated by Django 4.2.9 on 2024-01-16 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0258_orgunitchangerequest_old_closed_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orgunitchangerequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="orgunitchangerequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
