# Generated by Django 4.2.10 on 2024-02-21 12:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0262_alter_entity_name"),
        ("iaso", "0262_payment"),
    ]

    operations = []
