# Generated by Django 4.2.9 on 2024-03-08 09:37

from django.db import migrations
from django.db.models import Count


def migrate_data_forward(apps, schema_editor):
    """
    This data migration deletes `OrgUnitChangeRequest` duplicates sharing the same uuid.
    It's a prerequisite for adding a unique constraint on `OrgUnitChangeRequest.uuid`.
    """
    OrgUnitChangeRequest = apps.get_model("iaso", "OrgUnitChangeRequest")

    duplicated_uuids = (
        OrgUnitChangeRequest.objects.values_list("uuid", flat=True)
        .annotate(Count("uuid"))
        .order_by()
        .filter(uuid__count__gt=1)
    )

    for uuid in duplicated_uuids:
        # Retrieve change requests sharing the same UUID except for the oldest one.
        change_requests_to_delete = OrgUnitChangeRequest.objects.filter(uuid=uuid).order_by("created_at")[1:]
        for change_request in change_requests_to_delete:
            change_request.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0263_form_change_request_mode"),
    ]

    operations = [migrations.RunPython(migrate_data_forward, migrations.RunPython.noop, elidable=True)]
