# Generated by Django 4.2.10 on 2024-02-21 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("iaso", "0263_merge_0262_alter_entity_name_0262_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="change_requests",
            field=models.ManyToManyField(related_name="payment", to="iaso.orgunitchangerequest"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="payment", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="PotentialPayment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "change_requests",
                    models.ManyToManyField(related_name="potential_payment", to="iaso.orgunitchangerequest"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="potential_payment",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
