# Generated by Django 4.2.11 on 2024-03-11 16:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0265_merge_20240228_1725"),
        ("iaso", "0266_merge_20240311_1034"),
    ]

    operations = []
