# Generated by Django 4.2.10 on 2024-02-29 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0268_remove_payment_change_requests_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orgunitchangerequest",
            name="potential_payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="change_requests",
                to="iaso.potentialpayment",
            ),
        ),
    ]
