# Generated by Django 4.2.11 on 2024-03-14 13:26

from django.db import migrations

CODE = "MOBILE_ORG_UNIT_DEEP_SEARCH"


def create_feature_flags(apps, schema_editor):
    FeatureFlag = apps.get_model("iaso", "FeatureFlag")
    FeatureFlag.objects.create(
        code=CODE,
        name="Mobile: Search through children in OrgUnit tree.",
    )


def destroy_feature_flags(apps, schema_editor):
    FeatureFlag = apps.get_model("iaso", "FeatureFlag")
    FeatureFlag.objects.filter(code=CODE).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0268_remove_payment_change_requests_and_more"),
    ]

    operations = []
