# Generated by Django 4.2.10 on 2024-03-11 11:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0266_merge_20240311_1034"),
        ("iaso", "0269_alter_orgunitchangerequest_potential_payment"),
    ]

    operations = []
