# Generated by Django 4.2.11 on 2024-03-20 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0270_auto_20240314_1515"),
    ]

    operations = [
        migrations.AddField(
            model_name="potentialpayment",
            name="payment_lot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="potential_payments",
                to="iaso.paymentlot",
            ),
        ),
    ]
