# Generated by Django 4.2.11 on 2024-03-20 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0271_potentialpayment_payment_lot"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentlot",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_lots",
                to="iaso.task",
            ),
        ),
    ]
