# Generated by Django 4.2.11 on 2024-03-26 11:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0264_merge_20240301_1421"),
        ("iaso", "0271_upgrade_postgis_extensions_20240325_1139"),
    ]

    operations = []
