# Generated by Django 4.2.11 on 2024-03-26 11:39

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0271_upgrade_postgis_extensions_20240325_1139"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgunit",
            name="extra_fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddIndex(
            model_name="orgunit",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["extra_fields"], name="iaso_orguni_extra_f_a15e77_gin"
            ),
        ),
    ]
