# Generated by Django 4.2.11 on 2024-03-27 12:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0272_orgunit_extra_fields_and_more"),
        ("iaso", "0273_merge_20240327_0931"),
    ]

    operations = []
