# Generated by Django 4.2.11 on 2024-03-28 12:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0274_merge_20240327_1257"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgunitchangerequest",
            name="stored_requested_fields",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=30),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
