# Generated by Django 4.2.11 on 2024-03-28 13:21

from django.db import migrations


new_fields = [
    "new_parent",
    "new_name",
    "new_org_unit_type",
    "new_groups",
    "new_location",
    "new_location_accuracy",
    "new_opening_date",
    "new_closed_date",
    "new_reference_instances",
]


def migrate_data_forward(apps, schema_editor):
    """
    Make the `@requested_fields()` dynamic property a field of the model.
    """
    OrgUnitChangeRequest = apps.get_model("iaso", "OrgUnitChangeRequest")

    for change_request in OrgUnitChangeRequest.objects.all():
        requested = []
        for name in new_fields:
            field = getattr(change_request, name)
            is_m2m = field.__class__.__name__ == "ManyRelatedManager"
            is_requested = field.exists() if is_m2m else field
            if is_requested:
                requested.append(name)

        change_request.stored_requested_fields = requested
        change_request.save()


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0275_orgunitchangerequest_stored_requested_fields"),
    ]

    operations = [migrations.RunPython(migrate_data_forward, migrations.RunPython.noop, elidable=True)]
