# Generated by Django 4.2.11 on 2024-03-28 14:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0276_data_populate_requested_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orgunitchangerequest",
            old_name="stored_requested_fields",
            new_name="requested_fields",
        ),
        migrations.AlterField(
            model_name="orgunitchangerequest",
            name="requested_fields",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=30),
                blank=True,
                default=list,
                help_text="List of fields names for which a change is requested.",
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="orgunitchangerequest",
            name="approved_fields",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=30),
                blank=True,
                default=list,
                help_text="List of approved fields names (only a subset can be approved).",
                size=None,
            ),
        ),
    ]
