# Generated by Django 4.2.11 on 2024-04-10 11:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0272_merge_20240326_1125"),
        (
            "iaso",
            "0277_rename_stored_requested_fields_orgunitchangerequest_requested_fields",
        ),
    ]

    operations = []
