# Generated by Django 4.2.11 on 2024-04-10 09:39

from django.db import migrations, models
import iaso.models.base


class Migration(migrations.Migration):
    dependencies = [
        (
            "iaso",
            "0277_rename_stored_requested_fields_orgunitchangerequest_requested_fields",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="modules",
            field=iaso.models.base.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("DATA_COLLECTION_FORMS", "Data collection - Forms"),
                        ("DEFAULT", "Default"),
                        ("DHIS2_MAPPING", "DHIS2 mapping"),
                        ("EMBEDDED_LINKS", "Embedded links"),
                        ("ENTITIES", "Entities"),
                        ("EXTERNAL_STORAGE", "External storage"),
                        ("PLANNING", "Planning"),
                        ("POLIO_PROJECT", "Polio project"),
                        ("REGISTRY", "Registry"),
                        ("PAYMENTS", "Payments"),
                    ],
                    max_length=100,
                ),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
