# Generated by Django 4.2.11 on 2024-04-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "iaso",
            "0277_rename_stored_requested_fields_orgunitchangerequest_requested_fields",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="periods_after_allowed",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="form",
            name="periods_before_allowed",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
