# Generated by Django 4.2.11 on 2024-04-09 13:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0275_alter_form_periods_after_allowed_and_more"),
        (
            "iaso",
            "0277_rename_stored_requested_fields_orgunitchangerequest_requested_fields",
        ),
    ]

    operations = []
