# Generated by Django 4.2.11 on 2024-04-17 13:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0278_alter_account_modules"),
        ("iaso", "0278_alter_form_periods_after_allowed_and_more"),
    ]

    operations = []
