# Generated by Django 4.2.11 on 2024-05-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0279_merge_20240417_1319"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instance",
            name="file_name",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="instance",
            name="uuid",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
