# Generated by Django 4.2.11 on 2024-04-23 08:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0278_merge_20240410_1123"),
        ("iaso", "0279_merge_20240417_1319"),
    ]

    operations = []
