# Generated by Django 4.2.13 on 2024-05-14 14:23

import django.contrib.postgres.fields

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0279_merge_20240417_1319"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="tree_config_status_fields",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, choices=[], max_length=30),
                blank=True,
                default=list,
                help_text="List of statuses used for display configuration of the OrgUnit tree.",
                size=None,
            ),
        ),
    ]
