# Generated by Django 4.2.13 on 2024-05-31 13:35

from django.db import migrations, models

import iaso.models.base


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0280_datasource_tree_config_status_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="modules",
            field=iaso.models.base.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("DATA_COLLECTION_FORMS", "Data collection - Forms"),
                        ("DEFAULT", "Default"),
                        ("DHIS2_MAPPING", "DHIS2 mapping"),
                        ("EMBEDDED_LINKS", "Embedded links"),
                        ("ENTITIES", "Entities"),
                        ("EXTERNAL_STORAGE", "External storage"),
                        ("PLANNING", "Planning"),
                        ("POLIO_PROJECT", "Polio project"),
                        ("REGISTRY", "Registry"),
                        ("PAYMENTS", "Payments"),
                        ("COMPLETENESS_PER_PERIOD", "Completeness per Period"),
                    ],
                    max_length=100,
                ),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
