# Generated by Django 4.2.13 on 2024-06-03 09:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0281_alter_account_modules"),
        (
            "iaso",
            "0282_replace_planning_permission_by_read_and_write_to_users_permission",
        ),
    ]

    operations = []
