# Generated by Django 4.2.13 on 2024-06-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("iaso", "0283_merge_20240603_0930"),
    ]

    operations = [
        migrations.AddIndexConcurrently(
            model_name="assignment",
            index=models.Index(fields=["deleted_at"], name="iaso_assign_deleted_52634f_idx"),
        ),
        migrations.AddIndexConcurrently(
            model_name="entity",
            index=models.Index(fields=["deleted_at"], name="iaso_entity_deleted_9afec0_idx"),
        ),
        migrations.AddIndexConcurrently(
            model_name="form",
            index=models.Index(fields=["deleted_at"], name="iaso_form_deleted_294928_idx"),
        ),
        migrations.AddIndexConcurrently(
            model_name="instance",
            index=models.Index(fields=["updated_at"], name="iaso_instan_updated_1d2d65_idx"),
        ),
        migrations.AddIndexConcurrently(
            model_name="planning",
            index=models.Index(fields=["deleted_at"], name="iaso_planni_deleted_d0d6f3_idx"),
        ),
        migrations.AddIndexConcurrently(
            model_name="report",
            index=models.Index(fields=["deleted_at"], name="iaso_report_deleted_faca07_idx"),
        ),
        migrations.AddIndexConcurrently(
            model_name="reportversion",
            index=models.Index(fields=["deleted_at"], name="iaso_report_deleted_83ec05_idx"),
        ),
        migrations.AddIndexConcurrently(
            model_name="team",
            index=models.Index(fields=["deleted_at"], name="iaso_team_deleted_89ace1_idx"),
        ),
        migrations.AddIndexConcurrently(
            model_name="workflow",
            index=models.Index(fields=["deleted_at"], name="iaso_workfl_deleted_7096c6_idx"),
        ),
        migrations.AddIndexConcurrently(
            model_name="workflowversion",
            index=models.Index(fields=["deleted_at"], name="iaso_workfl_deleted_d18bc8_idx"),
        ),
    ]
