# Generated by Django 4.2.13 on 2024-06-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0285_replace_planning_permission_by_read_and_write_to_user_roles_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="entitytype",
            name="prevent_add_if_duplicate_found",
            field=models.BooleanField(default=False),
        ),
    ]
