# Generated by Django 4.2.13 on 2024-06-24 12:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0286_alter_account_modules"),
        ("iaso", "0286_entitytype_prevent_add_if_duplicate_found"),
    ]

    operations = []
