# Generated by Django 4.2.11 on 2024-07-05 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0286_entitytype_prevent_add_if_duplicate_found"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicRegistryConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("host", models.URLField(unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("whitelist", models.JSONField(default={"fields": []})),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="iaso.account")),
                (
                    "root_orgunit",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="iaso.orgunit"
                    ),
                ),
            ],
        ),
    ]
