# Generated by Django 4.2.11 on 2024-07-11 13:24

from django.db import migrations, models
import django.db.models.deletion
import iaso.models.registry


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0288_instance_iaso_instan_created_04174a_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="public",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="PublicRegistryConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("host", models.URLField(unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("whitelist", models.JSONField(default=iaso.models.registry.get_default_whitelist)),
                ("app_id", models.CharField(blank=True, max_length=255, null=True)),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="iaso.account")),
                (
                    "data_source",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="iaso.datasource"
                    ),
                ),
                (
                    "root_orgunit",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="iaso.orgunit"
                    ),
                ),
                (
                    "source_version",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="iaso.sourceversion"
                    ),
                ),
            ],
        ),
    ]
