# Generated by Django 4.2.11 on 2024-07-17 10:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0287_auto_20240703_1253"),
        ("iaso", "0291_instance_iaso_instan_created_04174a_idx_and_more"),
    ]

    operations = []
