# Generated by Django 4.2.14 on 2024-07-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0292_merge_20240717_1016"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgunitchangerequest",
            name="kind",
            field=models.CharField(
                choices=[
                    ("org_unit_creation", "Org Unit Creation"),
                    ("org_unit_change", "Org Unit Change"),
                ],
                default="org_unit_change",
                max_length=40,
            ),
        ),
    ]
