# Generated by Django 4.2.11 on 2024-07-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0292_merge_20240717_1016"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="public",
            field=models.BooleanField(default=False),
        ),
    ]
