# Generated by Django 4.2.13 on 2024-08-05 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0293_orgunitchangerequest_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instance",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="instances",
                to="iaso.device",
            ),
        ),
        migrations.AlterField(
            model_name="instance",
            name="org_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="instances",
                to="iaso.orgunit",
            ),
        ),
    ]
