# Generated by Django 4.2.14 on 2024-08-06 13:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0293_alter_account_modules"),
        ("iaso", "0293_orgunitchangerequest_kind"),
    ]

    operations = []
