# Generated by Django 4.2.13 on 2024-08-19 12:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0293_datasource_public"),
        ("iaso", "0294_project_redirection_url"),
    ]

    operations = []
