# Generated by Django 4.2.14 on 2024-08-19 07:54

import django.db.models.deletion

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("iaso", "0294_project_redirection_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenant_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "main_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenant_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["created_at"], name="iaso_tenant_created_003e12_idx"),
                    models.Index(fields=["updated_at"], name="iaso_tenant_updated_31049b_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="tenantuser",
            constraint=models.UniqueConstraint(fields=("main_user", "account_user"), name="main_user_user_constraint"),
        ),
    ]
