# Generated by Django 4.2.15 on 2024-09-11 09:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0296_alter_account_modules"),
        ("iaso", "0296_groupset_group_belonging"),
    ]

    operations = []
