# Generated by Django 4.2.11 on 2024-09-13 09:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0296_alter_account_modules"),
        ("iaso", "0296_groupset_group_belonging"),
        ("iaso", "0296_orgunit_default_image"),
    ]

    operations = []
