# Generated by Django 4.2.13 on 2024-09-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0297_merge_20240913_0900"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="organization",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
