# Generated by Django 4.2.13 on 2024-09-12 14:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0297_merge_20240911_0725"),
        ("iaso", "0297_merge_20240911_0935"),
    ]

    operations = []
