# Generated by Django 4.2.14 on 2024-09-16 13:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0297_entity_merged_to"),
        ("iaso", "0298_profile_organization"),
    ]

    operations = []
