# Generated by Django 4.2.14 on 2024-10-01 14:02

from django.db import migrations


def create_account_feature_flag(apps, schema_editor):
    AccountFeatureFlag = apps.get_model("iaso", "AccountFeatureFlag")
    AccountFeatureFlag.objects.get_or_create(
        code="ENTITY_DUPLICATES_SOFT_DELETE",
        defaults={"name": "Entity duplicates allow soft deletion instead of merging"},
    )


def destroy_account_feature_flag(apps, schema_editor):
    AccountFeatureFlag = apps.get_model("iaso", "AccountFeatureFlag")
    AccountFeatureFlag.objects.get(code="ENTITY_DUPLICATES_SOFT_DELETE").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0299_merge_0297_entity_merged_to_0298_profile_organization"),
    ]

    operations = [
        migrations.RunPython(create_account_feature_flag, destroy_account_feature_flag),
    ]
