# Generated by Django 4.2.15 on 2024-09-16 15:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0296_orgunitchangerequestconfiguration"),
        ("iaso", "0299_merge_0297_entity_merged_to_0298_profile_organization"),
    ]

    operations = []
