# Generated by Django 4.2.13 on 2024-10-01 11:47

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0300_merge_20240916_1512"),
    ]

    operations = [
        migrations.AddField(
            model_name="potentialpayment",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="potential_payments",
                to="iaso.task",
            ),
        ),
    ]
