# Generated by Django 4.2.13 on 2024-10-03 09:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0301_merge_20241002_0941"),
        ("iaso", "0301_merge_20241002_1206"),
    ]

    operations = []
