# Generated by Django 4.2.13 on 2024-10-03 12:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0301_potentialpayment_task"),
        ("iaso", "0302_merge_20241003_0911"),
    ]

    operations = []
