# Generated by Django 4.2.15 on 2024-09-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0303_merge_20241003_1256"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="editable_org_unit_types",
            field=models.ManyToManyField(blank=True, related_name="iaso_profile", to="iaso.orgunittype"),
        ),
        migrations.AddField(
            model_name="userrole",
            name="editable_org_unit_types",
            field=models.ManyToManyField(blank=True, related_name="user_roles", to="iaso.orgunittype"),
        ),
    ]
