# Generated by Django 4.2.14 on 2024-10-09 12:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0300_merge_20240916_1441"),
        ("iaso", "0303_merge_20241003_1256"),
    ]

    operations = []
