# Generated by Django 4.2.16 on 2024-10-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0303_merge_20241003_1256"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="org_unit_types",
            field=models.ManyToManyField(blank=True, related_name="iaso_profile", to="iaso.orgunittype"),
        ),
    ]
