# Generated by Django 4.2.16 on 2024-10-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0304_profile_org_unit_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrole",
            name="editable_org_unit_types",
            field=models.ManyToManyField(blank=True, related_name="editable_by_user_role_set", to="iaso.orgunittype"),
        ),
    ]
