# Generated by Django 4.2.16 on 2024-10-28 10:02

import django.db.models.deletion

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("iaso", "0304_profile_org_unit_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="potentialpayment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="potential_payment",
                to=settings.AUTH_USER_MODEL,
                unique=True,
            ),
        ),
    ]
