# Generated by Django 4.2.16 on 2024-10-25 12:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0304_merge_0300_alter_page_type_0303_merge_20241003_1256"),
        ("iaso", "0304_profile_org_unit_types"),
    ]

    operations = []
