# Generated by Django 4.2.14 on 2024-10-24 11:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0304_merge_20241009_1240"),
        ("iaso", "0306_merge_20241024_0902"),
    ]

    operations = []
