# Generated by Django 4.2.16 on 2024-10-28 11:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0305_alter_potentialpayment_user"),
        ("iaso", "0307_merge_20241024_1145"),
    ]

    operations = []
