# Generated by Django 4.2.15 on 2024-11-21 10:33

import django.db.models.deletion

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("iaso", "0308_merge_20241028_1145"),
    ]

    operations = [
        migrations.AlterField(
            model_name="potentialpayment",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="potential_payment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
