# Generated by Django 4.2.16 on 2024-12-05 10:25

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0309_alter_potentialpayment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orgunitchangerequestconfiguration",
            name="project",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="iaso.project"),
        ),
    ]
