# Generated by Django 4.2.16 on 2024-12-05 11:32

import django.db.models.deletion

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("iaso", "0310_alter_orgunitchangerequestconfiguration_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantuser",
            name="account_user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="tenant_user", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="tenantuser",
            name="main_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="tenant_users", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
