# Generated by Django 4.2.16 on 2024-12-06 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("iaso", "0311_alter_tenantuser_account_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSourceSynchronization",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Used in the UI e.g. to filter Change Requests by Data Source Synchronization operations.",
                        max_length=255,
                    ),
                ),
                (
                    "json_diff",
                    models.JSONField(blank=True, help_text="The diff used to create change requests.", null=True),
                ),
                (
                    "json_diff_config",
                    models.TextField(blank=True, help_text="A string representing the parameters used for the diff."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="iaso.account")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_data_source_synchronizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "left_source_version",
                    models.ForeignKey(
                        help_text="Left pyramid to sync.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_as_left_sync_sources",
                        to="iaso.sourceversion",
                    ),
                ),
                (
                    "right_source_version",
                    models.ForeignKey(
                        help_text="Right pyramid to sync.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_as_right_sync_sources",
                        to="iaso.sourceversion",
                    ),
                ),
                (
                    "sync_task",
                    models.OneToOneField(
                        blank=True,
                        help_text="The background task that used the diff to create change requests.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="iaso.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data source synchronization",
            },
        ),
    ]
