# Generated by Django 4.2.16 on 2025-01-13 10:51

from django.db import migrations
from datetime import datetime, timedelta


class Migration(migrations.Migration):
    """
    This migration adds a unique index on the UUID of all _new_ records (starting
    tomorrow) of the following models:
    - OrgUnit
    - Entity
    - Instance

    Since the queries to create these indexes can take a long time to run:
    - The migration has `atomic` set to `False` so we can create them `CONCURRENTLY`.
    - The indexes are created `IF NOT EXISTS`. This allows us to manually create
      them on certain servers, outside of the deploy procedure.
    """

    atomic = False
    dependencies = [
        ("iaso", "0313_page_superset_dashboard_id_and_more"),
    ]

    TOMORROW = (datetime.now() + timedelta(days=1)).strftime("%Y-%m-%d")

    operations = [
        migrations.RunSQL(
            sql=f"CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS iaso_orgunit_uuid_version_idx_unicity_newer ON iaso_orgunit (uuid, version_id) WHERE uuid IS NOT NULL AND version_id IS NOT NULL AND created_at >= '${TOMORROW}';",
            reverse_sql="DROP INDEX iaso_orgunit_uuid_version_idx_unicity_newer",
        ),
        migrations.RunSQL(
            sql=f"CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS iaso_entity_uuidx_unicity_newer ON iaso_entity (uuid) WHERE uuid IS NOT NULL AND created_at >= '${TOMORROW}';",
            reverse_sql="DROP INDEX iaso_entity_uuidx_unicity_newer",
        ),
        migrations.RunSQL(
            sql=f"CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS iaso_instance_uuidx_unicity_newer ON iaso_instance (uuid) WHERE uuid IS NOT NULL AND created_at >= '${TOMORROW}';",
            reverse_sql="DROP INDEX iaso_instance_uuidx_unicity_newer ",
        ),
    ]
