# Generated by Django 4.2.16 on 2024-12-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0313_page_superset_dashboard_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="period_type",
            field=models.TextField(
                blank=True,
                choices=[
                    ("DAY", "Day"),
                    ("MONTH", "Month"),
                    ("QUARTER", "Quarter"),
                    ("QUARTER_NOV", "Quarter Nov"),
                    ("SIX_MONTH", "Six-month"),
                    ("YEAR", "Year"),
                ],
                null=True,
            ),
        ),
    ]
