# Generated by Django 4.2.16 on 2025-01-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0314_alter_form_period_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="period_type",
            field=models.TextField(
                blank=True,
                choices=[
                    ("DAY", "Day"),
                    ("MONTH", "Month"),
                    ("QUARTER", "Quarter"),
                    ("QUARTER_NOV", "Quarter Nov"),
                    ("SIX_MONTH", "Six-month"),
                    ("YEAR", "Year"),
                    ("FINANCIAL_NOV", "Financial Nov"),
                ],
                null=True,
            ),
        ),
    ]
