# Generated by Django 4.2.16 on 2025-01-21 13:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0315_alter_form_period_type"),
        ("iaso", "0315_datasourceversionssynchronization_and_more"),
    ]

    operations = []
