# Generated by Django 4.2.18 on 2025-01-24 10:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0309_merge_20241113_1319"),
        ("iaso", "0316_merge_20250121_1321"),
    ]

    operations = []
