# Generated by Django 4.2.20 on 2025-03-17 07:16

from django.db import migrations


def add_data_validation_to_accounts(apps, schema_editor):
    accountModel = apps.get_model("iaso", "Account")
    accounts_with_register_module = accountModel.objects.filter(modules__contains=["REGISTRY"])
    for account in accounts_with_register_module:
        account.modules.append("DATA_VALIDATION")
        account.save()


def reverse_add_data_validation_to_accounts(apps, schema_editor):
    accountModel = apps.get_model("iaso", "Account")
    accounts_with_data_validation_module = accountModel.objects.filter(modules__contains=["DATA_VALIDATION"])
    for account in accounts_with_data_validation_module:
        account.modules.remove("DATA_VALIDATION")
        account.save()

class Migration(migrations.Migration):

    dependencies = [
        ('iaso', '0317_alter_account_modules'),
    ]

    operations = [
        migrations.RunPython(add_data_validation_to_accounts, reverse_add_data_validation_to_accounts),
    ]
