# Generated by Django 4.2.18 on 2025-02-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0317_metrictype_metricvalue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metricvalue",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
