# Generated by Django 4.2.19 on 2025-03-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0318_add_data_validation_module_to_accounts"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgunitchangerequestconfiguration",
            name="type",
            field=models.CharField(
                choices=[("creation", "Creation"), ("edition", "Edition")],
                default="edition",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.RemoveConstraint(
            model_name="orgunitchangerequestconfiguration",
            name="unique_project_org_unit_type_if_not_deleted",
        ),
        migrations.AddIndex(
            model_name="orgunitchangerequestconfiguration",
            index=models.Index(fields=["type"], name="iaso_orguni_type_c2bf6e_idx"),
        ),
        migrations.AddConstraint(
            model_name="orgunitchangerequestconfiguration",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("project", "org_unit_type", "type"),
                name="unique_project_org_unit_type_if_not_deleted",
            ),
        ),
    ]
