# Generated by Django 4.2.17 on 2025-03-21 16:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0317_formattachment_file_last_scan_and_more"),
        ("iaso", "0318_add_data_validation_module_to_accounts"),
    ]

    operations = []
