# Generated by Django 4.2.18 on 2025-02-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0319_metrictype_category_alter_metrictype_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="metrictype",
            name="legend_threshold",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
