# Generated by Django 4.2.20 on 2025-04-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0319_orgunitchangerequestconfiguration_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orgunit",
            name="extra_fields",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
