# Generated by Django 4.2.17 on 2025-04-08 15:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0319_merge_20250321_1644"),
        ("iaso", "0319_orgunitchangerequestconfiguration_type"),
    ]

    operations = []
