# Generated by Django 4.2.19 on 2025-02-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0320_metrictype_legend_threshold"),
    ]

    operations = [
        migrations.AddField(
            model_name="metrictype",
            name="unit_symbol",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
