# Generated by Django 4.2.17 on 2025-04-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0321_formattachment_file_last_scan_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="orgunit",
            index=models.Index(
                fields=["org_unit_type", "version"],
                name="iaso_orguni_org_uni_28a2c8_idx",
            ),
        ),
    ]
