# Generated by Django 4.2.19 on 2025-02-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0321_metrictype_unit_symbol"),
    ]

    operations = [
        migrations.AddField(
            model_name="metrictype",
            name="code",
            field=models.CharField(default="code", max_length=255),
            preserve_default=False,
        ),
    ]
