# Generated by Django 4.2.19 on 2025-03-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0322_metrictype_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="metrictype",
            options={},
        ),
        migrations.RenameField(
            model_name="metrictype",
            old_name="legend_threshold",
            new_name="legend_config",
        ),
        migrations.AddField(
            model_name="metrictype",
            name="legend_type",
            field=models.CharField(
                choices=[("threshold", "threshold"), ("linear", "linear"), ("ordinal", "ordinal")],
                default="threshold",
                max_length=40,
            ),
        ),
    ]
