# Generated by Django 4.2.17 on 2025-05-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0323_account_custom_translations"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="is_internal",
            field=models.BooleanField(default=False),
        ),
    ]
