# Generated by Django 4.2.20 on 2025-05-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaso', '0323_account_custom_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color',
            field=models.CharField(blank=True, default='#1976D2', max_length=7, null=True),
        ),
    ]
