# Generated by Django 4.2.20 on 2025-05-14 12:44

from django.db import migrations


def create_feature_flags(apps, schema_editor):
    FeatureFlag = apps.get_model("iaso", "FeatureFlag")
    FeatureFlag.objects.get_or_create(
        code="MOBILE_USE_ETHIOPIC_CALENDAR",
        name="Mobile: Use Ethiopic Calendar.",
    )
    FeatureFlag.objects.get_or_create(
        code="MOBILE_SELECT_CLOSEST_ORG_UNIT",
        name="Mobile: Propose to jump to closest OrgUnit.",
    )
    FeatureFlag.objects.get_or_create(
        code="MOBILE_CHANGE_REQUESTS_TAB",
        name="Mobile: Show change requests tab.",
    )


def destroy_feature_flags(apps, schema_editor):
    FeatureFlag = apps.get_model("iaso", "FeatureFlag")
    FeatureFlag.objects.filter(code="MOBILE_USE_ETHIOPIC_CALENDAR").delete()
    FeatureFlag.objects.filter(code="MOBILE_SELECT_CLOSEST_ORG_UNIT").delete()
    FeatureFlag.objects.filter(code="MOBILE_CHANGE_REQUESTS_TAB").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0323_account_custom_translations"),
    ]

    operations = [
        migrations.RunPython(create_feature_flags, destroy_feature_flags),
    ]
