# Generated by Django 4.2.20 on 2025-03-25 10:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0318_add_data_validation_module_to_accounts"),
        ("iaso", "0323_alter_metrictype_options_and_more"),
    ]

    operations = []
