# Generated by Django 4.2.21 on 2025-05-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0324_auto_20250514_1244"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="app_id",
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
