# Generated by Django 4.2.20 on 2025-05-19 07:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0324_auto_20250514_1244"),
        ("iaso", "0324_project_color"),
    ]

    operations = []
