# Generated by Django 4.2.21 on 2025-05-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0326_alter_project_app_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgunitchangerequest",
            name="deleted_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
