# Generated by Django 4.2.20 on 2025-06-17 07:56
import hashlib

from django.core.files import File
from django.db import migrations, models


def md5sum(file: File) -> str:
    md5 = hashlib.md5()
    for chunk in file.chunks():
        md5.update(chunk)
    return md5.hexdigest()


def data_migration(apps, schema_editor):
    FormVersion = apps.get_model("iaso", "FormVersion")
    versions = FormVersion.objects.filter(md5__isnull=True)
    for version in versions:
        version.md5 = md5sum(version.file)
        version.save()


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0327_orgunitchangerequest_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="formversion",
            name="md5",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.RunPython(data_migration, reverse),
        migrations.AlterField(
            model_name="formversion",
            name="md5",
            field=models.CharField(max_length=32, null=False),
        ),
    ]
