# Generated by Django 4.2.23 on 2025-06-24 13:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0328_auto_20250619_1436"),
        ("iaso", "0328_merge_20250613_1308"),
    ]

    operations = []
