# Generated by Django 4.2.17 on 2025-06-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0328_auto_20250619_1436"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgunit",
            name="code",
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AddConstraint(
            model_name="orgunit",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("code", ""), _negated=True),
                    models.Q(("validation_status", "VALID")),
                ),
                fields=("code", "version"),
                name="unique_code_per_source_version_if_not_blank_and_valid_status",
            ),
        ),
    ]
