# Generated by Django 4.2.20 on 2025-06-17 07:56

from django.db import migrations, models

from iaso.utils.encryption import calculate_md5


def migrate_data_forward(apps, schema_editor):
    FormVersion = apps.get_model("iaso", "FormVersion")
    versions = FormVersion.objects.filter(md5__isnull=True)
    for version in versions:
        version.md5 = calculate_md5(version.file)
        version.save()


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0328_auto_20250619_1436"),
    ]

    operations = [
        migrations.AddField(
            model_name="formversion",
            name="md5",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.RunPython(migrate_data_forward, migrations.RunPython.noop, elidable=True),
        migrations.AlterField(
            model_name="formversion",
            name="md5",
            field=models.CharField(max_length=32, null=False),
        ),
    ]
