# Generated by Django 4.2.20 on 2025-06-30 12:08

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0330_formversion_md5"),
    ]

    state_operations = [
        migrations.CreateModel(
            name="ProjectFeatureFlags",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("configuration", models.JSONField(null=True, default=None)),
                ("featureflag", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="iaso.featureflag")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="iaso.project")),
            ],
            options={
                "db_table": "iaso_project_feature_flags",
            },
        ),
        migrations.AlterField(
            model_name="project",
            name="feature_flags",
            field=models.ManyToManyField(
                blank=True,
                related_name="_iaso_project_feature_flags_+",
                through="iaso.ProjectFeatureFlags",
                to="iaso.FeatureFlag",
            ),
        ),
    ]
    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations),
        migrations.AddField(
            model_name="featureflag",
            name="configuration_schema",
            field=models.JSONField(null=True, default=None),
        ),
        migrations.AddField(
            model_name="ProjectFeatureFlags",
            name="configuration",
            field=models.JSONField(null=True, default=None),
        ),
        migrations.AlterField(
            model_name="project",
            name="feature_flags",
            field=models.ManyToManyField(
                blank=True, related_name="+", through="iaso.ProjectFeatureFlags", to="iaso.featureflag"
            ),
        ),
    ]
