# Generated by Django 4.2.20 on 2025-07-17 10:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0331_add_account_feature_flag_and_auto_assign"),
        ("iaso", "0331_remove_importgpkg_project"),
    ]

    operations = []
