# Generated by Django 4.2.23 on 2025-07-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0331_merge_20250627_1115"),
    ]

    operations = [
        migrations.AddField(
            model_name="metrictype",
            name="scale",
            field=models.JSONField(blank=True, default=""),
        ),
    ]
