# Generated by Django 4.2.23 on 2025-07-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0331_merge_20250627_1115"),
    ]

    operations = [
        migrations.AddField(
            model_name="metricvalue",
            name="string_value",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="metricvalue",
            name="value",
            field=models.FloatField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name="metrictype",
            unique_together={("account", "code")},
        ),
    ]
