# Generated by Django 4.2.23 on 2025-07-28 09:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0332_merge_20250717_1033"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={},
        ),
        migrations.AlterModelManagers(
            name="group",
            managers=[],
        ),
    ]
