# Generated by Django 4.2.17 on 2025-07-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False  # Prevent the migration from running in a transaction.

    dependencies = [
        ("iaso", "0332_merge_20250717_1033"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorePermissionSupport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("iaso_forms", "Formulaires"),
                    ("iaso_forms_stats", "Statistiques pour les formulaires"),
                    ("iaso_mappings", "Correspondances avec DHIS2"),
                    ("iaso_modules", "modules"),
                    ("iaso_completeness", "Complétude des données"),
                    ("iaso_org_units", "Unités d'organisations"),
                    ("iaso_org_units_history", "Historique des unités d'organisation"),
                    ("iaso_org_units_read", "Lire les unités d'organisations"),
                    ("iaso_registry_write", "Editer le Registre"),
                    ("iaso_registry_read", "Lire le Registre"),
                    ("iaso_links", "Correspondances sources"),
                    ("iaso_users", "Users"),
                    ("iaso_users_managed", "Users managed"),
                    ("iaso_pages", "Pages"),
                    ("iaso_projects", "Projets"),
                    ("iaso_sources", "Sources"),
                    (
                        "iaso_sources_can_change_default_version",
                        "Can change the default version of a data source",
                    ),
                    ("iaso_data_tasks", "Tâches"),
                    ("iaso_submissions", "Soumissions"),
                    ("iaso_update_submission", "Editer soumissions"),
                    ("iaso_planning_write", "Editer le planning"),
                    ("iaso_planning_read", "Lire le planning"),
                    ("iaso_reports", "Reports"),
                    ("iaso_teams", "Equipes"),
                    ("iaso_assignments", "Attributions"),
                    ("iaso_entities", "Entities"),
                    ("iaso_entity_type_write", "Write entity type"),
                    ("iaso_storages", "Storages"),
                    ("iaso_completeness_stats", "Completeness stats"),
                    ("iaso_workflows", "Workflows"),
                    ("iaso_entity_duplicates_read", "Read Entity duplicates"),
                    ("iaso_entity_duplicates_write", "Write Entity duplicates"),
                    ("iaso_user_roles", "Manage user roles"),
                    ("iaso_datastore_read", "Read data store"),
                    ("iaso_datastore_write", "Write data store"),
                    ("iaso_org_unit_types", "Org unit types"),
                    ("iaso_org_unit_groups", "Org unit groups"),
                    (
                        "iaso_org_unit_change_request_review",
                        "Org unit change request review",
                    ),
                    (
                        "iaso_org_unit_change_request_configurations",
                        "Org unit change request configurations",
                    ),
                    ("iaso_write_sources", "Write data source"),
                    ("iaso_page_write", "Write page"),
                    ("iaso_payments", "Payments page"),
                    ("iaso_mobile_app_offline_setup", "Mobile app offline setup"),
                ),
                "managed": False,
                "default_permissions": [],
            },
        ),
    ]
