# Generated by Django 4.2.23 on 2025-07-29 15:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0333_featureflag_category_featureflag_is_dangerous"),
    ]

    def set_feature_flag_category_and_is_dangerous(apps, schema_editor):
        """Set feature flag categories"""
        feature_flag_code_to_category = {
            "REQUIRE_AUTHENTICATION": "DCO",
            "FORMS_AUTO_UPLOAD": "DCO",
            "TAKE_GPS_ON_FORM": "DCO",
            "DATA_COLLECTION": "DCO",
            "MOBILE_FINALIZED_FORM_ARE_READ": "DCO",
            "MOBILE_SUBMISSION_INCOMPLETE_BY_DEFAULT": "DCO",
            "LIMIT_OU_DOWNLOAD_TO_ROOTS": "REO",
            "MOBILE_FORCE_OU_UPDATE": "REO",
            "MOBILE_FORCE_FORMS_UPDATE": "REO",
            "MOBILE_CHECK_OU_UPDATE": "REO",
            "MOBILE_CHECK_FORMS_UPDATE": "REO",
            "SHOW_DETAIL_MAP_ON_MOBILE": "GEO",
            "CHECK_POSITION_FOR_FORMS": "GEO",
            "MOBILE_SELECT_CLOSEST_ORG_UNIT": "GEO",
            "MOBILE_CHANGE_REQUESTS_TAB": "DAV",
            "MOBILE_ORG_UNIT_REGISTRY": "DAV",
            "SHOW_LINK_INSTANCE_REFERENCE": "DAV",
            "ENTITY": "ENT",
            "MOBILE_ENTITY_NO_CREATION": "ENT",
            "MOBILE_ENTITY_WARN_WHEN_FOUND": "ENT",
            "MOBILE_ENTITY_LIMITED_SEARCH": "ENT",
            "WRITE_ON_NFC_CARDS": "ENT",
            "PLANNING": "PLA",
            "TRANSPORT_TRACKING": "SPO",
            "GPS_TRACKING": "SPO",
            "MOBILE_HIDE_CLOSED_ORG_UNIT": "SPO",
            "MOBILE_USE_ETHIOPIC_CALENDAR": "SPO",
            "MOBILE_NO_ORG_UNIT": "SPO",
            "REPORTS": "SPO",
            "MOBILE_ORG_UNIT_DEEP_SEARCH": "NA",
        }

        FeatureFlag = apps.get_model("iaso", "FeatureFlag")
        all_feature_flags = FeatureFlag.objects.all()
        for flag in all_feature_flags:
            code = flag.code
            category = feature_flag_code_to_category.get(code)
            flag.category = category
            flag.is_dangerous = True if category == "SPO" else False
            flag.save()

    def reverse_set_feature_flag_category_and_is_dangerous(apps, schema_editor):
        # We can ignore this, not sure how to say that there is nothing to revert.
        pass

    operations = [
        migrations.RunPython(
            set_feature_flag_category_and_is_dangerous, reverse_set_feature_flag_category_and_is_dangerous
        )
    ]
