# Generated by Django 4.2.23 on 2025-07-28 08:19

from django.db import migrations


def remove_group_domain_value_if_exists(apps, schema_editor):
    Group = apps.get_model("iaso", "Group")
    groups_with_domain = Group.objects.filter(domain__isnull=False)
    for group in groups_with_domain:
        group.domain = None
        group.save()


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0333_alter_group_options_alter_group_managers"),
    ]

    operations = [
        migrations.RunPython(remove_group_domain_value_if_exists, migrations.RunPython.noop, elidable=True),
    ]
