# Generated by Django 4.2.17 on 2025-07-31 08:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0331_merge_20250715_1345"),
        ("iaso", "0334_split_core_permissions_from_hat"),
    ]

    operations = []
