# Generated by Django 4.2.23 on 2025-07-28 10:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0334_remove_group_domain_values"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="domain",
        ),
    ]
