# Generated by Django 4.2.23 on 2025-07-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0334_split_core_permissions_from_hat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entityduplicateanalyzis",
            name="algorithm",
            field=models.CharField(choices=[("levenshtein", "Levenshtein")], default="levenshtein", max_length=20),
        ),
    ]
