# Generated by Django 4.2.23 on 2025-08-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0335_alter_entityduplicateanalyzis_algorithm"),
    ]

    operations = [
        migrations.AddField(
            model_name="featureflag",
            name="category",
            field=models.TextField(
                choices=[
                    ("DCO", "Data collection options"),
                    ("REO", "Refresh options"),
                    ("GEO", "Geographic options"),
                    ("DAV", "Data Validation"),
                    ("ENT", "Entities"),
                    ("PLA", "Planning"),
                    ("SPO", "Specific options"),
                    ("NA", "Not specified"),
                ],
                default="NA",
            ),
        ),
        migrations.AddField(
            model_name="featureflag",
            name="is_dangerous",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="featureflag",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
