# Generated by Django 4.2.23 on 2025-08-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0335_alter_entityduplicateanalyzis_algorithm"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="entityduplicate",
            index=models.Index(fields=["entity1", "entity2"], name="idx_entityduplicate_pairs"),
        ),
    ]
