# Generated by Django 4.2.23 on 2025-07-31 09:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0335_alter_entityduplicateanalyzis_algorithm"),
        ("iaso", "0335_remove_group_domain"),
    ]

    operations = []
