# Generated by Django 4.2.23 on 2025-07-31 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iaso', '0335_alter_entityduplicateanalyzis_algorithm'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('units', models.CharField(blank=True, max_length=255)),
                ('unit_symbol', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('comments', models.TextField(blank=True)),
                ('legend_type', models.CharField(choices=[('threshold', 'threshold'), ('linear', 'linear'), ('ordinal', 'ordinal')], default='threshold', max_length=40)),
                ('legend_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iaso.account')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('account', 'code')},
            },
        ),
        migrations.CreateModel(
            name='MetricValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('value', models.FloatField(null=True)),
                ('string_value', models.TextField(null=True)),
                ('metric_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iaso.metrictype')),
                ('org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='iaso.orgunit')),
            ],
            options={
                'unique_together': {('metric_type', 'org_unit', 'year')},
            },
        ),
    ]
