# Generated by Django 4.2.17 on 2025-08-07 14:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0331_merge_20250715_1345"),
        ("iaso", "0339_add_deduplication_indexes"),
    ]

    operations = []
