# Generated by Django 4.2.17 on 2025-08-29 13:56

import django.db.models.deletion

from django.conf import settings
from django.db import migrations, models

import iaso.models.bulk_create_user_csv_file
import iaso.models.import_gpkg
import iaso.models.instances
import iaso.models.reports


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("iaso", "0341_merge_20250825_0807"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportversion",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="report_version_created_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reportversion",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="report_version_updated_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="bulkcreateusercsvfile",
            name="file",
            field=models.FileField(upload_to=iaso.models.bulk_create_user_csv_file.bulk_create_user_csv_file_upload_to),
        ),
        migrations.AlterField(
            model_name="importgpkg",
            name="file",
            field=models.FileField(upload_to=iaso.models.import_gpkg.import_gpkg_upload_to),
        ),
        migrations.AlterField(
            model_name="instance",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=iaso.models.instances.instance_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="instancefile",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=iaso.models.instances.instance_file_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="reportversion",
            name="file",
            field=models.FileField(upload_to=iaso.models.reports.report_version_upload_to),
        ),
    ]
