# Generated by Django 4.2.24 on 2025-09-22 12:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0331_merge_20250715_1345"),
        ("iaso", "0343_importgpkg_default_valid"),
    ]

    operations = []
