# Generated by Django 4.2.23 on 2025-09-16 09:05

import uuid

import django.db.models.deletion

from django.conf import settings
from django.db import migrations, models


def create_feature_flags(apps, schema_editor):
    FeatureFlag = apps.get_model("iaso", "FeatureFlag")
    FeatureFlag.objects.create(
        code="MOBILE_STOCK",
        name="Mobile: Enable Stock Management.",
    )


def destroy_feature_flags(apps, schema_editor):
    FeatureFlag = apps.get_model("iaso", "FeatureFlag")
    FeatureFlag.objects.filter(code="MOBILE_STOCK").delete()


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("iaso", "0344_alter_corepermissionsupport_options"),
    ]

    operations = [
        migrations.RunPython(create_feature_flags, destroy_feature_flags),
        migrations.CreateModel(
            name="StockItemRule",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question", models.CharField(max_length=255)),
                (
                    "impact",
                    models.CharField(
                        blank=True,
                        choices=[("ADD", "Add"), ("SUBTRACT", "Subtract"), ("RESET", "Reset")],
                        max_length=8,
                        null=True,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_item_rule_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="stock_item_rule_form", to="iaso.form"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockKeepingUnit",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("name", models.CharField(max_length=255)),
                ("short_name", models.CharField(max_length=255)),
                ("display_units", models.CharField(blank=True, max_length=25, null=True)),
                ("display_precision", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="iaso.account")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="corepermissionsupport",
            options={
                "default_permissions": [],
                "managed": False,
                "permissions": (
                    ("iaso_forms", "Formulaires"),
                    ("iaso_forms_stats", "Statistiques pour les formulaires"),
                    ("iaso_mappings", "Correspondances avec DHIS2"),
                    ("iaso_modules", "modules"),
                    ("iaso_completeness", "Complétude des données"),
                    ("iaso_org_units", "Unités d'organisations"),
                    ("iaso_org_units_history", "Historique des unités d'organisation"),
                    ("iaso_org_units_read", "Lire les unités d'organisations"),
                    ("iaso_registry_write", "Editer le Registre"),
                    ("iaso_registry_read", "Lire le Registre"),
                    ("iaso_links", "Correspondances sources"),
                    ("iaso_users", "Users"),
                    ("iaso_users_managed", "Users managed"),
                    ("iaso_pages", "Pages"),
                    ("iaso_projects", "Projets"),
                    ("iaso_sources", "Sources"),
                    ("iaso_sources_can_change_default_version", "Can change the default version of a data source"),
                    ("iaso_data_tasks", "Tâches"),
                    ("iaso_submissions", "Soumissions"),
                    ("iaso_update_submission", "Editer soumissions"),
                    ("iaso_planning_write", "Editer le planning"),
                    ("iaso_planning_read", "Lire le planning"),
                    ("iaso_reports", "Reports"),
                    ("iaso_teams", "Equipes"),
                    ("iaso_assignments", "Attributions"),
                    ("iaso_entities", "Entities"),
                    ("iaso_entity_type_write", "Write entity type"),
                    ("iaso_storages", "Storages"),
                    ("iaso_completeness_stats", "Completeness stats"),
                    ("iaso_workflows", "Workflows"),
                    ("iaso_entity_duplicates_read", "Read Entity duplicates"),
                    ("iaso_entity_duplicates_write", "Write Entity duplicates"),
                    ("iaso_user_roles", "Manage user roles"),
                    ("iaso_datastore_read", "Read data store"),
                    ("iaso_datastore_write", "Write data store"),
                    ("iaso_org_unit_types", "Org unit types"),
                    ("iaso_org_unit_groups", "Org unit groups"),
                    ("iaso_org_unit_change_request_review", "Org unit change request review"),
                    ("iaso_org_unit_change_request_configurations", "Org unit change request configurations"),
                    ("iaso_write_sources", "Write data source"),
                    ("iaso_page_write", "Write page"),
                    ("iaso_payments", "Payments page"),
                    ("iaso_mobile_app_offline_setup", "Mobile app offline setup"),
                    ("iaso_stock_management", "Stock Management"),
                ),
            },
        ),
        migrations.CreateModel(
            name="StockRulesVersion",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("name", models.CharField(default="No Name", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("UNPUBLISHED", "Unpublished"), ("PUBLISHED", "Published")],
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_rule_version_account",
                        to="iaso.account",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_rule_version_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_rule_version_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StockLedgerItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("question", models.CharField(blank=True, max_length=255, null=True)),
                ("value", models.IntegerField()),
                (
                    "impact",
                    models.CharField(
                        blank=True,
                        choices=[("ADD", "Add"), ("SUBTRACT", "Subtract"), ("RESET", "Reset")],
                        max_length=8,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_item_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "org_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_item_org_unit",
                        to="iaso.orgunit",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_item_rule",
                        to="iaso.stockitemrule",
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_item_sku",
                        to="iaso.stockkeepingunit",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_item_instance",
                        to="iaso.instance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockKeepingUnitChildren",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sku_children_child",
                        to="iaso.stockkeepingunit",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sku_children_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sku_children_parent",
                        to="iaso.stockkeepingunit",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sku_children_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="stockkeepingunit",
            name="children",
            field=models.ManyToManyField(
                blank=True, through="iaso.StockKeepingUnitChildren", to="iaso.stockkeepingunit"
            ),
        ),
        migrations.AddField(
            model_name="stockkeepingunit",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sku_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stockkeepingunit",
            name="forms",
            field=models.ManyToManyField(blank=True, related_name="sku_forms", to="iaso.form"),
        ),
        migrations.AddField(
            model_name="stockkeepingunit",
            name="org_unit_types",
            field=models.ManyToManyField(blank=True, related_name="sku_org_unit_types", to="iaso.orgunittype"),
        ),
        migrations.AddField(
            model_name="stockkeepingunit",
            name="projects",
            field=models.ManyToManyField(blank=True, related_name="sku_projects", to="iaso.project"),
        ),
        migrations.AddField(
            model_name="stockkeepingunit",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sku_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stockitemrule",
            name="sku",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_item_rule_sku",
                to="iaso.stockkeepingunit",
            ),
        ),
        migrations.AddField(
            model_name="stockitemrule",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_item_rule_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stockitemrule",
            name="version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="rules", to="iaso.stockrulesversion"
            ),
        ),
        migrations.CreateModel(
            name="StockItem",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "org_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_item_org_unit",
                        to="iaso.orgunit",
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_item_sku",
                        to="iaso.stockkeepingunit",
                    ),
                ),
            ],
        ),
    ]
