# Generated by Django 4.2.20 on 2025-09-30 15:07

import django.contrib.postgres.fields

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0344_alter_corepermissionsupport_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="planning",
            name="pipeline_uuids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=36),
                blank=True,
                default=list,
                help_text="List of OpenHexa pipeline UUIDs available for this planning",
                size=None,
            ),
        ),
    ]
