# Generated by Django 4.2.20 on 2025-10-08 13:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0347_alter_assignment_unique_together_and_more"),
        ("iaso", "0347_stockitemrule_stockkeepingunit_stockrulesversion_and_more"),
    ]

    operations = []
