# Generated by Django 4.2.17 on 2025-10-14 13:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0345_trypelim_instance_idx"),
        ("iaso", "0348_alter_assignment_unique_together_and_more"),
    ]

    operations = []
