# Generated by Django 4.2.25 on 2025-10-29 14:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0348_alter_assignment_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orgunit",
            name="validated",
        ),
    ]
