# Generated by Django 4.2.20 on 2025-11-03 14:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0349_remove_orgunit_validated"),
        ("iaso", "0350_alter_openhexaworkspace_slug"),
    ]

    operations = []
