# Generated by Django 4.2.20 on 2025-11-21 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iaso', '0353_team_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='target_org_unit_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='target_plannings', to='iaso.orgunittype'),
        ),
    ]
