# Generated by Django 4.2.20 on 2025-11-25 15:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0354_alter_account_modules"),
        ("iaso", "0354_planning_target_org_unit_type"),
    ]

    operations = []
