# Generated by Django 4.2.27 on 2025-12-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0355_merge_20251125_1555"),
    ]

    operations = [
        migrations.AddField(
            model_name="metrictype",
            name="is_utility",
            field=models.BooleanField(default=False),
        ),
    ]
