# Generated by Django 4.2.20 on 2025-12-05 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iaso', '0355_merge_20251125_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningSamplingResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_id', models.CharField(blank=True, help_text='OpenHexa pipeline UUID', max_length=36, null=True)),
                ('pipeline_version', models.CharField(blank=True, help_text='Pipeline version identifier', max_length=100, null=True)),
                ('parameters', models.JSONField(help_text='Sampling parameters used for this run')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, help_text='Created org unit group containing sampled units', null=True, on_delete=django.db.models.deletion.SET_NULL, to='iaso.group')),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sampling_results', to='iaso.planning')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sampling_results', to='iaso.task')),
            ],
            options={
                'verbose_name': 'Sampling Result',
                'verbose_name_plural': 'Sampling Results',
                'ordering': ['-created_at'],
            },
        ),
    ]
