# Generated by Django 4.2.27 on 2025-12-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0355_merge_20251125_1555"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name="instance",
                    index=models.Index(fields=["uuid"], name="iaso_instance_uuid_idx"),
                ),
            ],
            # The database operation is empty because the index must be created independently since it can take time
            database_operations=[],
        ),
    ]
