# Generated by Django 4.2.26 on 2025-12-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0356_metrictype_is_utility"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="forum_path",
            field=models.TextField(blank=True, null=True),
        ),
    ]
