# Generated by Django 4.2.26 on 2026-01-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0359_planning_selected_sampling_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="user_roles",
            field=models.ManyToManyField(blank=True, related_name="pages", to="iaso.userrole"),
        ),
    ]
