# Generated by Django 4.2.27 on 2026-01-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0359_planning_selected_sampling_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="metrictype",
            name="origin",
            field=models.CharField(
                choices=[("openhexa", "OpenHexa"), ("custom", "Custom"), ("other", "Other")],
                default="openhexa",
                max_length=50,
            ),
        ),
    ]
