# Generated by Django 4.2.27 on 2026-01-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0359_planning_selected_sampling_result"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="period_type",
            field=models.TextField(
                blank=True,
                choices=[
                    ("DAY", "Day"),
                    ("MONTH", "Month"),
                    ("QUARTER", "Quarter"),
                    ("QUARTER_NOV", "Quarter Nov"),
                    ("SIX_MONTH", "Six-month"),
                    ("YEAR", "Year"),
                    ("FINANCIAL_NOV", "Financial Nov"),
                    ("WEEK", "WEEK"),
                ],
                null=True,
            ),
        ),
    ]
