# Generated by Django 4.2.20 on 2026-01-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0360_page_user_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="color",
            field=models.CharField(blank=True, default="#1976D2", max_length=7),
        ),
    ]
