# Generated by Django 4.2.26 on 2026-02-03 13:47


from django.contrib.postgres.fields import ArrayField
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0363_merge_20260122_1147"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bulkcreateusercsvfile",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="bulkcreateusercsvfile",
            name="default_org_units",
            field=ArrayField(models.IntegerField(), blank=True, default=list),
        ),
        migrations.AddField(
            model_name="bulkcreateusercsvfile",
            name="default_organization",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="bulkcreateusercsvfile",
            name="default_permissions",
            field=ArrayField(models.CharField(max_length=50), blank=True, default=list),
        ),
        migrations.AddField(
            model_name="bulkcreateusercsvfile",
            name="default_profile_language",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="bulkcreateusercsvfile",
            name="default_projects",
            field=ArrayField(models.CharField(max_length=255), blank=True, default=list),
        ),
        migrations.AddField(
            model_name="bulkcreateusercsvfile",
            name="default_user_roles",
            field=ArrayField(models.CharField(max_length=100), blank=True, default=list),
        ),
        migrations.AddField(
            model_name="bulkcreateusercsvfile",
            name="default_teams",
            field=ArrayField(models.CharField(max_length=255), blank=True, default=list),
        ),
    ]
