# Generated by Django 4.2.28 on 2026-02-19 15:58

from django.db import migrations

import iaso.utils.models.color


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0365_alter_account_modules"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="color",
            field=iaso.utils.models.color.ColorField(blank=True, default="#1976D2", max_length=7),
        ),
        migrations.AlterField(
            model_name="project",
            name="color",
            field=iaso.utils.models.color.ColorField(blank=True, default="#1976D2", max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="color",
            field=iaso.utils.models.color.ColorField(default="#ef5350", max_length=7),
        ),
    ]
