# Generated by Django 4.2.26 on 2026-02-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("iaso", "0365_alter_account_modules"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bulkcreateusercsvfile",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="bulkcreateusercsvfile",
            name="default_org_units",
            field=models.ManyToManyField(
                blank=True,
                related_name="bulk_create_defaults_org_units",
                to="iaso.orgunit",
            ),
        ),
        migrations.AddField(
            model_name="bulkcreateusercsvfile",
            name="default_organization",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="bulkcreateusercsvfile",
            name="default_permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="bulk_create_defaults_permissions",
                to="auth.permission",
            ),
        ),
        migrations.AddField(
            model_name="bulkcreateusercsvfile",
            name="default_profile_language",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="bulkcreateusercsvfile",
            name="default_projects",
            field=models.ManyToManyField(
                blank=True,
                related_name="bulk_create_defaults_projects",
                to="iaso.project",
            ),
        ),
        migrations.AddField(
            model_name="bulkcreateusercsvfile",
            name="default_teams",
            field=models.ManyToManyField(blank=True, related_name="bulk_create_defaults_teams", to="iaso.team"),
        ),
        migrations.AddField(
            model_name="bulkcreateusercsvfile",
            name="default_user_roles",
            field=models.ManyToManyField(
                blank=True,
                related_name="bulk_create_defaults_user_roles",
                to="iaso.userrole",
            ),
        ),
    ]
