# Generated by Django 4.2.28 on 2026-03-09 16:52

import autoslug.fields
import django.db.models.deletion

from django.conf import settings
from django.db import migrations, models

import iaso.utils.models.color


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("iaso", "0367_add_bulkcreateusercsvfile_default_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValidationNode",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=256)),
                ("slug", autoslug.fields.AutoSlugField(editable=False, populate_from="name")),
                ("color", iaso.utils.models.color.ColorField(blank=True, max_length=7, null=True)),
                ("can_skip_previous_nodes", models.BooleanField(default=False)),
                ("next_nodes", models.ManyToManyField(related_name="previous_nodes", to="iaso.validationnode")),
                ("roles_required", models.ManyToManyField(blank=True, to="iaso.userrole")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="instance",
            name="parent_instance_for_validation",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="iaso.instance"),
        ),
        migrations.CreateModel(
            name="ValidationWorkflow",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=256)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        always_update=True, editable=False, populate_from="name", unique=True
                    ),
                ),
                ("description", models.TextField(blank=True, max_length=1024)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ValidationStatus",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("skipped", "Skipped"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("final", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("instance", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="iaso.instance")),
                ("node", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="iaso.validationnode")),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="validationnode",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="nodes", to="iaso.validationworkflow"
            ),
        ),
    ]
