# Generated by Django 4.2.28 on 2026-03-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0369_instance_parent_instance_for_validation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="validationstatus",
            name="previous_status",
        ),
        migrations.AddField(
            model_name="validationnode",
            name="can_skip_previous_nodes",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="validationstatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("skipped", "Skipped"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=20,
            ),
        ),
    ]
