# Generated by Django 4.2.29 on 2026-03-15 07:33

import django.db.models.deletion

from django.conf import settings
from django.db import migrations, models


def migrate_forms_to_missions(apps, schema_editor):
    """Convert each Planning-Form pair to a FORM_FILLING Mission with MissionForm."""
    Planning = apps.get_model("iaso", "Planning")
    Mission = apps.get_model("iaso", "Mission")
    MissionForm = apps.get_model("iaso", "MissionForm")

    for planning in Planning.objects.prefetch_related("forms").all():
        account = planning.project.account
        for form in planning.forms.all():
            mission = Mission.objects.create(
                name=form.name,
                account=account,
                mission_type="FORM_FILLING",
                created_by=planning.created_by,
            )
            MissionForm.objects.create(
                mission=mission,
                form=form,
                min_cardinality=1,
                max_cardinality=1,
            )
            planning.missions.add(mission)


def reverse_migrate_missions_to_forms(apps, schema_editor):
    """Reverse: convert FORM_FILLING missions back to Planning.forms."""
    Planning = apps.get_model("iaso", "Planning")
    MissionForm = apps.get_model("iaso", "MissionForm")

    for planning in Planning.objects.prefetch_related("missions").all():
        for mission in planning.missions.filter(mission_type="FORM_FILLING"):
            for mf in MissionForm.objects.filter(mission=mission):
                planning.forms.add(mf.form)


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("iaso", "0369_instance_parent_artefact_for_validation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mission",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "mission_type",
                    models.CharField(
                        choices=[
                            ("FORM_FILLING", "Form Filling"),
                            ("ORG_UNIT_AND_FORM", "Org Unit and Form"),
                            ("ENTITY_AND_FORM", "Entity and Form"),
                        ],
                        max_length=30,
                    ),
                ),
                ("org_unit_min_cardinality", models.PositiveIntegerField(blank=True, null=True)),
                ("org_unit_max_cardinality", models.PositiveIntegerField(blank=True, null=True)),
                ("entity_min_cardinality", models.PositiveIntegerField(blank=True, null=True)),
                ("entity_max_cardinality", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="missions", to="iaso.account"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "entity_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="missions",
                        to="iaso.entitytype",
                    ),
                ),
                (
                    "org_unit_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="missions",
                        to="iaso.orgunittype",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="MissionForm",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "min_cardinality",
                    models.PositiveIntegerField(
                        default=1, help_text="Minimum number of times this form should be filled"
                    ),
                ),
                (
                    "max_cardinality",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of times this form can be filled (null = unlimited)",
                        null=True,
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="mission_forms", to="iaso.form"
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="mission_forms", to="iaso.mission"
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
                "unique_together": {("mission", "form")},
            },
        ),
        migrations.AddField(
            model_name="mission",
            name="forms",
            field=models.ManyToManyField(
                blank=True, related_name="missions", through="iaso.MissionForm", to="iaso.form"
            ),
        ),
        migrations.AddField(
            model_name="planning",
            name="missions",
            field=models.ManyToManyField(blank=True, related_name="plannings", to="iaso.mission"),
        ),
        migrations.RunPython(migrate_forms_to_missions, reverse_migrate_missions_to_forms),
    ]
