# Generated by Django 4.2.28 on 2026-03-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0370_planning_target_org_unit_types_m2m"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="corepermissionsupport",
            options={
                "default_permissions": [],
                "managed": False,
                "permissions": [
                    ("iaso_assignments", "Attributions"),
                    ("iaso_completeness", "Complétude des données"),
                    ("iaso_completeness_stats", "Completeness stats"),
                    ("iaso_datastore_read", "Read data store"),
                    ("iaso_datastore_write", "Write data store"),
                    ("iaso_data_tasks", "Tâches"),
                    ("iaso_entities", "Entities"),
                    ("iaso_entity_type_write", "Write entity type"),
                    ("iaso_entity_duplicates_read", "Read Entity duplicates"),
                    ("iaso_entity_duplicates_write", "Write Entity duplicates"),
                    ("iaso_forms", "Formulaires"),
                    ("iaso_forms_stats", "Statistiques pour les formulaires"),
                    ("iaso_links", "Correspondances sources"),
                    ("iaso_mappings", "Correspondances avec DHIS2"),
                    ("iaso_mobile_app_offline_setup", "Mobile app offline setup"),
                    ("iaso_modules", "modules"),
                    ("iaso_metric_types", "Metric types"),
                    ("iaso_org_units", "Unités d'organisations"),
                    ("iaso_org_units_history", "Historique des unités d'organisation"),
                    ("iaso_org_units_read", "Lire les unités d'organisations"),
                    ("iaso_org_unit_types", "Org unit types"),
                    ("iaso_org_unit_groups", "Org unit groups"),
                    ("iaso_org_unit_change_request_review", "Org unit change request review"),
                    ("iaso_org_unit_change_request_configurations", "Org unit change request configurations"),
                    ("iaso_pages", "Pages"),
                    ("iaso_page_write", "Write page"),
                    ("iaso_payments", "Payments page"),
                    ("iaso_planning_write", "Editer le planning"),
                    ("iaso_planning_read", "Lire le planning"),
                    ("iaso_projects", "Projets"),
                    ("iaso_registry_write", "Editer le Registre"),
                    ("iaso_registry_read", "Lire le Registre"),
                    ("iaso_reports", "Reports"),
                    ("iaso_write_sources", "Write data source"),
                    ("iaso_sources", "Sources"),
                    ("iaso_sources_can_change_default_version", "Can change the default version of a data source"),
                    ("iaso_stock_management", "Stock management"),
                    ("iaso_storages", "Storages"),
                    ("iaso_submissions", "Soumissions"),
                    ("iaso_update_submission", "Editer soumissions"),
                    ("iaso_teams", "Equipes"),
                    ("iaso_users", "Users"),
                    ("iaso_users_managed", "Users managed"),
                    ("iaso_user_roles", "Manage user roles"),
                    ("iaso_workflows", "Workflows"),
                    ("iaso_validation_workflows", "Validation workflows"),
                ],
            },
        ),
        migrations.AlterUniqueTogether(
            name="validationnodetemplate",
            unique_together={("workflow", "name"), ("workflow", "slug")},
        ),
        migrations.AddField(
            model_name="validationnodetemplate",
            name="description",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterUniqueTogether(
            name="validationworkflow",
            unique_together={("account", "slug"), ("account", "name")},
        ),
    ]
