# Generated by Django 4.2.29 on 2026-03-15 07:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0370_create_mission_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planning",
            name="forms",
        ),
    ]
