# Generated by Django 4.2.28 on 2026-03-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0370_alter_corepermissionsupport_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="general_validation_status",
            field=models.CharField(
                blank=True,
                choices=[("APPROVED", "Approved"), ("REJECTED", "Rejected"), ("PENDING", "Pending")],
                default="",
                max_length=20,
            ),
        ),
    ]
