# Generated by Django 4.2.28 on 2026-03-20 11:23

from django.db import migrations

import iaso.models.common


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0370_alter_corepermissionsupport_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="validationnodetemplate",
            name="slug",
            field=iaso.models.common.BulkAutoSlugField(
                editable=False, populate_from="name", unique_with=("workflow_id",)
            ),
        ),
    ]
