# Generated by Django 4.2.28 on 2026-03-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0371_instance_general_validation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="validationnodetemplate",
            name="next_node_templates",
            field=models.ManyToManyField(
                blank=True, related_name="previous_node_templates", to="iaso.validationnodetemplate"
            ),
        ),
    ]
