# Generated by Django 4.2.29 on 2026-03-23 14:38

from django.db import migrations


def create_feature_flags(apps, schema_editor):
    FeatureFlag = apps.get_model("iaso", "FeatureFlag")
    if not FeatureFlag.objects.filter(code="MOBILE_VALIDATION_WORKFLOW").exists():
        FeatureFlag.objects.create(
            code="MOBILE_VALIDATION_WORKFLOW",
            name="Mobile: Enable validation workflow",
            requires_authentication=True,
            category="DAV",
        )


def destroy_feature_flags(apps, schema_editor):
    FeatureFlag = apps.get_model("iaso", "FeatureFlag")
    FeatureFlag.objects.filter(code="MOBILE_VALIDATION_WORKFLOW").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0371_alter_corepermissionsupport_options_and_more"),
    ]

    operations = [
        migrations.RunPython(create_feature_flags, destroy_feature_flags),
    ]
