# Generated by Django 4.2.28 on 2026-03-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0371_alter_corepermissionsupport_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="validationnode",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                    ("SKIPPED", "Skipped"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="UNKNOWN",
                max_length=20,
            ),
        ),
    ]
