# Generated by Django 4.2.29 on 2026-03-23 11:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0370_planning_target_org_unit_types_m2m"),
        ("iaso", "0371_alter_validationnodetemplate_slug"),
    ]

    operations = []
