# Generated by Django 4.2.29 on 2026-03-23 14:38

from django.db import migrations


def create_feature_flags(apps, schema_editor):
    FeatureFlag = apps.get_model("iaso", "FeatureFlag")
    if not FeatureFlag.objects.filter(code="MOBILE_SYNCHRONIZE_WITH_ZIP").exists():
        FeatureFlag.objects.create(
            code="MOBILE_SYNCHRONIZE_WITH_ZIP",
            name="Mobile: Synchronize via ZIP files",
            requires_authentication=True,
            category="DCO",
        )


def destroy_feature_flags(apps, schema_editor):
    FeatureFlag = apps.get_model("iaso", "FeatureFlag")
    FeatureFlag.objects.filter(code="MOBILE_SYNCHRONIZE_WITH_ZIP").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0372_auto_20260323_1438"),
    ]

    operations = [
        migrations.RunPython(create_feature_flags, destroy_feature_flags),
    ]
