# Generated by Django 4.2.29 on 2026-03-25 11:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0372_alter_validationnodetemplate_slug"),
        ("iaso", "0372_instance_general_validation_status_and_more"),
    ]

    operations = []
