# Generated by Django 4.2.29 on 2026-03-27 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iaso', '0373_instance_general_validation_status'),
        ('iaso', '0373_merge_20260325_1142'),
    ]

    operations = [
    ]
