# Generated by Django 4.2.29 on 2026-04-07 19:15

from django.db import migrations


def create_feature_flags(apps, schema_editor):
    AccountFeatureFlag = apps.get_model("iaso", "AccountFeatureFlag")
    if not AccountFeatureFlag.objects.filter(code="SUBMISSION_VALIDATION_WORKFLOW").exists():
        AccountFeatureFlag.objects.create(
            code="SUBMISSION_VALIDATION_WORKFLOW",
            name="Web: Enable validation workflow",
        )


def destroy_feature_flags(apps, schema_editor):
    AccountFeatureFlag = apps.get_model("iaso", "AccountFeatureFlag")
    AccountFeatureFlag.objects.filter(code="SUBMISSION_VALIDATION_WORKFLOW").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0373_mobile_send_zip_featureflag"),
    ]

    operations = [
        migrations.RunPython(create_feature_flags, destroy_feature_flags),
    ]
