# Generated by Django 4.2.28 on 2026-04-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0374_alter_validationworkflow_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instance",
            name="parent_artefact_for_validation",
        ),
        migrations.AlterField(
            model_name="validationnode",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                    ("SKIPPED", "Skipped"),
                    ("UNKNOWN", "Unknown"),
                    ("SUBMISSION", "Submission"),
                    ("NEW_VERSION", "New version"),
                ],
                default="UNKNOWN",
                max_length=20,
            ),
        ),
    ]
