# Generated by Django 4.2.28 on 2026-04-15 13:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0374_auto_20260407_1915"),
        ("iaso", "0375_remove_instance_parent_artefact_for_validation_and_more"),
    ]

    operations = []
