# Generated by Django 4.2.28 on 2026-04-15 15:58

import autoslug.fields

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0376_merge_20260415_1358"),
    ]

    operations = [
        migrations.AlterField(
            model_name="validationworkflow",
            name="slug",
            field=autoslug.fields.AutoSlugField(editable=False, populate_from="name", unique_with=("account_id",)),
        ),
    ]
