# Generated by Django 4.2.30 on 2026-04-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaso', '0379_alter_corepermissionsupport_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrictype',
            name='metric_kind',
            field=models.CharField(choices=[('population', 'Population'), ('any', 'Any')], default='any', max_length=50),
        ),
    ]
