# Generated by Django 4.2.29 on 2026-04-19 11:26

import uuid

import django.db.models.deletion

from django.conf import settings
from django.db import migrations, models

import iaso.models.form_ai


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("iaso", "0378_account_enforce_password_validation"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="anthropic_api_key",
            field=models.TextField(blank=True, help_text="Anthropic API key used by the Form AI", null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="modules",
            field=iaso.models.base.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("DATA_COLLECTION_FORMS", "Data collection - Forms"),
                        ("DEFAULT", "Default"),
                        ("DHIS2_MAPPING", "DHIS2 mapping"),
                        ("EMBEDDED_LINKS", "Embedded links"),
                        ("ENTITIES", "Entities"),
                        ("EXTERNAL_STORAGE", "External storage"),
                        ("PLANNING", "Planning"),
                        ("POLIO_PROJECT", "Polio project"),
                        ("REGISTRY", "Registry"),
                        ("PAYMENTS", "Payments"),
                        ("COMPLETENESS_PER_PERIOD", "Completeness per Period"),
                        ("TRYPELIM_PROJECT", "Trypelim project"),
                        ("DATA_VALIDATION", "Data validation"),
                        ("SAAS", "SaaS"),
                        ("STOCK_MANAGEMENT", "Stock management"),
                        ("SNT_MALARIA", "SNT Malaria"),
                        ("FORM_AI", "Form AI"),
                    ],
                    max_length=100,
                ),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.CreateModel(
            name="TemporaryForm",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("xls_file", models.FileField(upload_to=iaso.models.form_ai._xls_file_upload_to)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="temporary_forms", to="iaso.account"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temporary_forms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
