# Generated by Django 4.2.28 on 2026-04-28 14:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0379_rename_bulkcreateusercsvfile_bulkcreateuserfile"),
        ("iaso", "0380_metrictype_metric_kind"),
    ]

    operations = []
