# Generated by Django 4.2.30 on 2026-05-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0383_merge_form_ai_metrictype"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
