# Generated by Django 4.2.28 on 2026-05-04 16:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("iaso", "0383_merge_form_ai_metrictype"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BulkCreateUserCsvFile",
            new_name="BulkCreateUserFile",
        ),
    ]
