# Generated by Django 4.2.30 on 2026-05-08 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iaso', '0384_project_description'),
        ('iaso', '0384_rename_bulkcreateusercsvfile_bulkcreateuserfile'),
    ]

    operations = [
    ]
