# Generated by Django 4.2.30 on 2026-05-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0385_alter_corepermissionsupport_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
