# Generated by Django 4.2.30 on 2026-05-13 15:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0385_alter_corepermissionsupport_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="form",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="orgunittype",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="stockkeepingunitchildren",
            options={"ordering": ["id"]},
        ),
    ]
