# Generated by Django 4.2.28 on 2026-05-13 09:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0385_alter_corepermissionsupport_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="validationnodetemplate",
            name="color",
        ),
    ]
