# Generated by Django 4.2.30 on 2026-05-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaso', '0387_merge_20260518_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
