# Generated by Django 4.2.28 on 2026-05-21 06:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0388_alter_account_modules"),
        ("iaso", "0388_project_description"),
    ]

    operations = []
