# Generated by Django 4.2.28 on 2026-05-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0389_alter_account_modules"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="disabled_at",
            field=models.DateTimeField(null=True),
        ),
    ]
