# Generated by Django 4.2.30 on 2026-06-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0391_alter_formattachment_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="org_unit_groups",
            field=models.ManyToManyField(blank=True, related_name="forms", to="iaso.group"),
        ),
    ]
