# Generated by Django 4.2.30 on 2026-06-17 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iaso", "0371_merge_20260331_1612"),
        ("iaso", "0391_alter_formattachment_file"),
    ]

    operations = [
    ]
