# Generated by Django 4.2.30 on 2026-06-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0392_form_org_unit_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowversion",
            name="auto_first_step",
            field=models.BooleanField(default=False),
        ),
    ]
