# Generated by Django 4.2.30 on 2026-06-23 06:26

import django.contrib.gis.db.models.fields

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0394_remove_show_pages_feature_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgunitchangerequest",
            name="new_code",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="orgunitchangerequest",
            name="new_geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="orgunitchangerequest",
            name="old_code",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="orgunitchangerequest",
            name="old_geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
    ]
