# Generated by Django 4.2.30 on 2026-06-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0394_remove_show_pages_feature_flag"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="orgunit",
            index=models.Index(fields=["version"], name="iaso_orgunit_version_id_idx"),
        ),
    ]
