# Generated by Django 4.2.28 on 2026-06-18 09:43

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0394_remove_show_pages_feature_flag"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountUsage",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("DAY", "Day"),
                            ("WEEK", "Week"),
                            ("MONTH", "Month"),
                            ("YEAR", "Year"),
                            ("ALL_TIME", "All Time"),
                        ]
                    ),
                ),
                ("period_starts_at", models.DateTimeField(null=True)),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("SUBMISSION", "Submission"),
                            ("DISK_SPACE", "Disk Space"),
                            ("PROJECT", "Project"),
                            ("USER", "User"),
                        ]
                    ),
                ),
                ("usage", models.PositiveBigIntegerField(default=0)),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="iaso.account")),
            ],
            options={
                "unique_together": {("account", "metric", "period_type", "period_starts_at")},
            },
        ),
        migrations.CreateModel(
            name="DiskSpaceAccountUsage",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("iaso.accountusage",),
        ),
        migrations.CreateModel(
            name="ProjectAccountUsage",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("iaso.accountusage",),
        ),
        migrations.CreateModel(
            name="SubmissionAccountUsage",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("iaso.accountusage",),
        ),
        migrations.CreateModel(
            name="UserAccountUsage",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("iaso.accountusage",),
        ),
    ]
