# Generated by Django 4.2.28 on 2026-07-02 12:21

import django.db.models.deletion

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("iaso", "0394_remove_show_pages_feature_flag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mission",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.CharField(blank=True, max_length=500)),
                (
                    "mission_type",
                    models.CharField(
                        choices=[
                            ("FORM_FILLING", "Form Filling"),
                            ("ORG_UNIT_AND_FORM", "Org Unit and Form"),
                            ("ENTITY_AND_FORM", "Entity and Form"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="missions", to="iaso.account"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.RemoveField(
            model_name="planning",
            name="forms",
        ),
        migrations.CreateModel(
            name="MissionEntityType",
            fields=[
                (
                    "mission_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="iaso.mission",
                    ),
                ),
                (
                    "entity_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mission_entity_type",
                        to="iaso.entitytype",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
            bases=("iaso.mission",),
        ),
        migrations.CreateModel(
            name="MissionForm",
            fields=[
                (
                    "mission_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="iaso.mission",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
            bases=("iaso.mission",),
        ),
        migrations.CreateModel(
            name="MissionOrgUnitType",
            fields=[
                (
                    "mission_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="iaso.mission",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
            bases=("iaso.mission",),
        ),
        migrations.AddField(
            model_name="planning",
            name="missions",
            field=models.ManyToManyField(blank=True, related_name="plannings", to="iaso.mission"),
        ),
        migrations.CreateModel(
            name="MissionOrgUnitTypeThroughForm",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "min_cardinality",
                    models.PositiveIntegerField(
                        default=1, help_text="Minimum number of times this form should be filled"
                    ),
                ),
                (
                    "max_cardinality",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of times this form can be filled (null = unlimited)",
                        null=True,
                    ),
                ),
                ("form", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="iaso.form")),
                (
                    "mission_org_unit_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="iaso.missionorgunittype"),
                ),
            ],
            options={
                "unique_together": {("mission_org_unit_type", "form")},
            },
        ),
        migrations.AddField(
            model_name="missionorgunittype",
            name="forms",
            field=models.ManyToManyField(
                related_name="mission_org_unit_types", through="iaso.MissionOrgUnitTypeThroughForm", to="iaso.form"
            ),
        ),
        migrations.AddField(
            model_name="missionorgunittype",
            name="org_unit_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="mission_org_unit_type", to="iaso.orgunittype"
            ),
        ),
        migrations.CreateModel(
            name="MissionFormThroughForm",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "min_cardinality",
                    models.PositiveIntegerField(
                        default=1, help_text="Minimum number of times this form should be filled"
                    ),
                ),
                (
                    "max_cardinality",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of times this form can be filled (null = unlimited)",
                        null=True,
                    ),
                ),
                ("form", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="iaso.form")),
                ("mission_form", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="iaso.missionform")),
            ],
            options={
                "unique_together": {("mission_form", "form")},
            },
        ),
        migrations.AddField(
            model_name="missionform",
            name="forms",
            field=models.ManyToManyField(
                related_name="mission_forms", through="iaso.MissionFormThroughForm", to="iaso.form"
            ),
        ),
        migrations.CreateModel(
            name="MissionEntityTypeThroughForm",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "min_cardinality",
                    models.PositiveIntegerField(
                        default=1, help_text="Minimum number of times this form should be filled"
                    ),
                ),
                (
                    "max_cardinality",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of times this form can be filled (null = unlimited)",
                        null=True,
                    ),
                ),
                ("form", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="iaso.form")),
                (
                    "mission_entity_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="iaso.missionentitytype"),
                ),
            ],
            options={
                "unique_together": {("mission_entity_type", "form")},
            },
        ),
        migrations.AddField(
            model_name="missionentitytype",
            name="forms",
            field=models.ManyToManyField(
                related_name="mission_entities", through="iaso.MissionEntityTypeThroughForm", to="iaso.form"
            ),
        ),
    ]
