# Generated by Django 4.2.30 on 2026-07-27 14:49

import django.db.models.deletion

from django.conf import settings
from django.db import connection, migrations, models


def migrate_forms_to_missions(apps, schema_editor):
    """Convert each Planning-Form pair to a FORM_FILLING Mission with MissionForm."""
    ContentType = apps.get_model("contenttypes", "ContentType")
    Planning = apps.get_model("iaso", "Planning")
    Mission = apps.get_model("iaso", "Mission")
    MissionWithForms = apps.get_model("iaso", "MissionWithForms")
    MissionForm = apps.get_model("iaso", "MissionForm")
    MissionFormThroughForm = apps.get_model("iaso", "MissionFormThroughForm")
    PlanningFormThrough = apps.get_model("iaso", "Planning_forms")

    # get content_type for mission_form
    mission_form_ct = ContentType.objects.get_for_model(MissionForm)

    for planning in (
        Planning.objects.filter(project__account__isnull=False, project__isnull=False)
        .prefetch_related("forms")
        .select_related("project__account")
        .all()
    ):
        account = planning.project.account

        mission_objects = []
        mission_form_through_objects = []

        for form in planning.forms.all():
            mission_objects.append(
                Mission(
                    name=form.name,
                    account_id=account.id,
                    mission_type="FORM_FILLING",
                    polymorphic_ctype_id=mission_form_ct.id,
                    created_by_id=planning.created_by.id if planning.created_by else None,
                )
            )
            mission_form_through_objects.append({"form_id": form.id, "min_cardinality": 1, "max_cardinality": 1})

        mission_objs = Mission.objects.bulk_create(mission_objects)

        with connection.cursor() as cursor:
            sql = f"INSERT INTO {MissionWithForms._meta.db_table} (mission_ptr_id) VALUES (%s)"
            params = [[m.id] for m in mission_objs]
            cursor.executemany(sql, params)

        with connection.cursor() as cursor:
            sql = f"INSERT INTO {MissionForm._meta.db_table} (missionwithforms_ptr_id) VALUES (%s)"
            params = [[m.id] for m in mission_objs]
            cursor.executemany(sql, params)

        MissionFormThroughForm.objects.bulk_create(
            [
                MissionFormThroughForm(**through, mission_form_id=mf.id)
                for (through, mf) in zip(mission_form_through_objects, mission_objs)
            ]
        )

        planning.missions.set(mission_objs)

    PlanningFormThrough.objects.all().delete()


def reverse_migrate_missions_to_forms(apps, schema_editor):
    """Reverse: convert FORM_FILLING missions back to Planning.forms."""
    MissionForm = apps.get_model("iaso", "MissionForm")
    PlanningMissionsThrough = apps.get_model("iaso", "Planning_missions")

    for mission_form in MissionForm.objects.filter(plannings__isnull=False).prefetch_related("forms"):
        for planning in mission_form.plannings.all():
            for form in mission_form.forms.all():
                if form not in planning.forms.all():
                    planning.forms.add(form)

    PlanningMissionsThrough.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("iaso", "0394_remove_show_pages_feature_flag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mission",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.CharField(blank=True, max_length=500)),
                (
                    "mission_type",
                    models.CharField(
                        choices=[
                            ("FORM_FILLING", "Form Filling"),
                            ("ORG_UNIT_AND_FORM", "Org Unit and Form"),
                            ("ENTITY_AND_FORM", "Entity and Form"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="missions", to="iaso.account"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.AlterModelOptions(
            name="corepermissionsupport",
            options={
                "default_permissions": [],
                "managed": False,
                "permissions": [
                    ("iaso_assignments", "Attributions"),
                    ("iaso_completeness", "Complétude des données"),
                    ("iaso_completeness_stats", "Completeness stats"),
                    ("iaso_datastore_read", "Read data store"),
                    ("iaso_datastore_write", "Write data store"),
                    ("iaso_data_tasks", "Tâches"),
                    ("iaso_entities", "Entities"),
                    ("iaso_entity_type_write", "Write entity type"),
                    ("iaso_entity_duplicates_read", "Read Entity duplicates"),
                    ("iaso_entity_duplicates_write", "Write Entity duplicates"),
                    ("iaso_forms", "Formulaires"),
                    ("iaso_forms_stats", "Statistiques pour les formulaires"),
                    ("iaso_links", "Correspondances sources"),
                    ("iaso_mappings", "Correspondances avec DHIS2"),
                    ("iaso_mobile_app_offline_setup", "Mobile app offline setup"),
                    ("iaso_modules", "modules"),
                    ("iaso_metric_types", "Metric types"),
                    ("iaso_org_units", "Unités d'organisations"),
                    ("iaso_org_units_history", "Historique des unités d'organisation"),
                    ("iaso_org_units_read", "Lire les unités d'organisations"),
                    ("iaso_org_unit_types", "Org unit types"),
                    ("iaso_org_unit_groups", "Org unit groups"),
                    ("iaso_org_unit_change_request_review", "Org unit change request review"),
                    ("iaso_org_unit_change_request_configurations", "Org unit change request configurations"),
                    ("iaso_pages", "Pages"),
                    ("iaso_page_write", "Write page"),
                    ("iaso_payments", "Payments page"),
                    ("iaso_planning_write", "Editer le planning"),
                    ("iaso_planning_read", "Lire le planning"),
                    ("iaso_projects", "Projets"),
                    ("iaso_registry_write", "Editer le Registre"),
                    ("iaso_registry_read", "Lire le Registre"),
                    ("iaso_reports", "Reports"),
                    ("iaso_write_sources", "Write data source"),
                    ("iaso_sources", "Sources"),
                    ("iaso_sources_can_change_default_version", "Can change the default version of a data source"),
                    ("iaso_stock_management", "Stock management"),
                    ("iaso_storages", "Storages"),
                    ("iaso_submissions", "Soumissions"),
                    ("iaso_update_submission", "Editer soumissions"),
                    ("iaso_teams", "Equipes"),
                    ("iaso_users", "Users"),
                    ("iaso_users_managed", "Users managed"),
                    ("iaso_user_roles", "Manage user roles"),
                    ("iaso_workflows", "Workflows"),
                    ("iaso_validation_workflows", "Validation workflows"),
                    ("iaso_account_management", "Account management"),
                    ("iaso_pipeline_management", "Pipeline management"),
                    ("iaso_mission_write", "Edit mission"),
                    ("iaso_mission_read", "Read mission"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MissionWithForms",
            fields=[
                (
                    "mission_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="iaso.mission",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
                "verbose_name": "Mission with forms",
                "verbose_name_plural": "Missions with forms",
            },
            bases=("iaso.mission", models.Model),
        ),
        migrations.CreateModel(
            name="MissionFormThroughForm",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "min_cardinality",
                    models.PositiveIntegerField(
                        default=1, help_text="Minimum number of times this form should be filled"
                    ),
                ),
                (
                    "max_cardinality",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of times this form can be filled (null = unlimited)",
                        null=True,
                    ),
                ),
                ("form", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="iaso.form")),
            ],
        ),
        migrations.AddField(
            model_name="planning",
            name="missions",
            field=models.ManyToManyField(blank=True, related_name="plannings", to="iaso.mission"),
        ),
        migrations.CreateModel(
            name="MissionForm",
            fields=[
                (
                    "missionwithforms_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="iaso.missionwithforms",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
            bases=("iaso.missionwithforms",),
        ),
        migrations.AddField(
            model_name="missionwithforms",
            name="forms",
            field=models.ManyToManyField(
                related_name="mission_forms", through="iaso.MissionFormThroughForm", to="iaso.form"
            ),
        ),
        migrations.AddField(
            model_name="missionformthroughform",
            name="mission_form",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="iaso.missionwithforms"),
        ),
        migrations.CreateModel(
            name="MissionOrgUnitType",
            fields=[
                (
                    "missionwithforms_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="iaso.missionwithforms",
                    ),
                ),
                (
                    "min_cardinality",
                    models.PositiveIntegerField(
                        default=1, help_text="Minimum number of times this form should be filled"
                    ),
                ),
                (
                    "max_cardinality",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of times this form can be filled (null = unlimited)",
                        null=True,
                    ),
                ),
                (
                    "org_unit_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mission_org_unit_type",
                        to="iaso.orgunittype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("iaso.missionwithforms",),
        ),
        migrations.AlterUniqueTogether(
            name="missionformthroughform",
            unique_together={("mission_form", "form")},
        ),
        migrations.CreateModel(
            name="MissionEntityType",
            fields=[
                (
                    "missionwithforms_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="iaso.missionwithforms",
                    ),
                ),
                (
                    "min_cardinality",
                    models.PositiveIntegerField(
                        default=1, help_text="Minimum number of times this form should be filled"
                    ),
                ),
                (
                    "max_cardinality",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of times this form can be filled (null = unlimited)",
                        null=True,
                    ),
                ),
                (
                    "entity_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mission_entity_type",
                        to="iaso.entitytype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("iaso.missionwithforms",),
        ),
        migrations.RunPython(migrate_forms_to_missions, reverse_migrate_missions_to_forms),
        migrations.RemoveField(
            model_name="planning",
            name="forms",
        ),
    ]
