# Generated by Django 4.2.28 on 2026-07-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0395_mission_remove_planning_forms_missionentitytype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="missionorgunittype",
            name="max_cardinality",
            field=models.PositiveIntegerField(
                blank=True, help_text="Maximum number of times this form can be filled (null = unlimited)", null=True
            ),
        ),
        migrations.AddField(
            model_name="missionorgunittype",
            name="min_cardinality",
            field=models.PositiveIntegerField(
                default=1, help_text="Minimum number of times this form should be filled"
            ),
        ),
    ]
