# Generated by Django 4.2.30 on 2026-07-18 10:26

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0396_alter_planning_org_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="mission",
            field=models.ForeignKey(
                blank=True,
                help_text="The mission this submission fulfills, within Instance.planning",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instances",
                to="iaso.mission",
            ),
        ),
    ]
