# Generated by Django 4.2.30 on 2026-08-26 15:35

import django.contrib.postgres.fields

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0397_bulkcreateuserfile_file_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="embed_allowed_origins",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                help_text="Origins allowed to embed this page in an <iframe>, in addition to this site itself (e.g. https://afro-rrt-who.hub.arcgis.com). Used to build the Content-Security-Policy: frame-ancestors header.",
                size=None,
            ),
        ),
    ]
