# Generated by Django 4.2.30 on 2026-08-20 13:50

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_import", "0008_apiimport_file_size_alter_apiimport_file"),
        ("iaso", "0397_bulkcreateuserfile_file_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="api_import",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instances",
                to="api_import.apiimport",
            ),
        ),
    ]
