# Generated by Django 4.2.30 on 2026-08-26 18:45

import django.contrib.postgres.fields

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0398_page_embed_allowed_origins"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="embed_allowed_origins",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                help_text="Opt-in: origins allowed to embed this page in an <iframe>, in addition to this site itself (e.g. https://afro-rrt-who.hub.arcgis.com), used to build a Content-Security-Policy: frame-ancestors header. Leave empty to keep the page embeddable anywhere (the default, unrestricted behaviour).",
                size=None,
            ),
        ),
    ]
