# Generated by Django 4.2.30 on 2026-09-07 08:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0398_add_account_feature_flag_impact"),
        ("iaso", "0398_instance_api_import_instance_app_version"),
    ]

    operations = []
