# Generated by Django 4.2.30 on 2026-09-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0399_merge_20260907_0842"),
    ]

    operations = [
        migrations.AddField(
            model_name="metrictype",
            name="is_complete",
            field=models.BooleanField(default=True),
        ),
    ]
