# Generated by Django 4.2.30 on 2026-09-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0399_merge_20260907_0842"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="promptness_grace_period_days",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Number of days after the end of the period during which submissions are still considered on time",
                null=True,
            ),
        ),
    ]
