# Generated by Django 4.2.30 on 2026-10-01 11:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0400_metrictype_is_complete"),
        ("iaso", "0400_task_lease"),
    ]

    operations = []
