# Generated by Django 4.2.30 on 2026-10-01 14:30

from django.db import migrations

import iaso.models.instances
import iaso.utils.models.sized_file_field


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0402_page_language_and_additional_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instance",
            name="file",
            field=iaso.utils.models.sized_file_field.SizedFileField(
                blank=True, max_length=255, null=True, upload_to=iaso.models.instances.instance_upload_to
            ),
        ),
        migrations.AlterField(
            model_name="instancefile",
            name="file",
            field=iaso.utils.models.sized_file_field.SizedFileField(
                blank=True, max_length=255, null=True, upload_to=iaso.models.instances.instance_file_upload_to
            ),
        ),
    ]
