# Generated by Django 4.2.30 on 2026-10-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0402_page_language_and_additional_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="promptness_grace_period_days",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Number of days after the end of the period during which submissions are still considered on time",
                null=True,
            ),
        ),
    ]
