# Generated by Django 4.2.30 on 2026-10-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0403_form_promptness_grace_period_days"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="instance",
            index=models.Index(
                condition=models.Q(("deleted", False), ("file__isnull", False), models.Q(("file", ""), _negated=True)),
                fields=["form", "period", "org_unit", "created_at"],
                name="iaso_instance_promptness_idx",
            ),
        ),
    ]
