---
AWSTemplateFormatVersion: '2010-09-09'
Description: sense-hat environment

Parameters:
  ProjectName:
    Description: name of deployed project
    Type: String
    MinLength: 3

  Environment:
    Description: Application environment
    Type: String
    AllowedValues:
    - development
    - staging
    - prod
    ConstraintDescription: 'Allowed environment types: development/staging/prod'
    
  HostedZone:
    Description: Hosted zone name
    Type: String
    MinLength: 3
    
  SNSTopic:
    Description: ARN of SNS Topic for alarms
    Type: String
    AllowedPattern: arn:aws:sns:.*
    ConstraintDescription: Expected valid SNS ARN (starting with arn:aws:sns:).

  GetOrCreateRecordLambda:
    Description: ARN of Lambda responsible for storing records
    Type: String
    AllowedPattern: arn:aws:lambda:.*
    ConstraintDescription: Expected valid ARN (starting with arn:aws:lambda:)
    
  ConfigurationTemplate:
    Description: Reference to Beanstalk ConfigurationTemplate
    Type: String
    MinLength: 3
    
  Subnet:
    Description: Reference to VPC Subnet
    Type: String
    MinLength: 3
    
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the Elastic
      Beanstalk hosts
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
    
  ApplicationVersion:
    Description: Reference to Benastalk ApplicationVersion
    Type: String
    MinLength: 3
    
  Application:
    Description: Reference to Beanstalk Application
    Type: String
    MinLength: 3

  Subnets:
    Description: Reference to VPC Subnets list
    Type: CommaDelimitedList
    
  VPC:
    Description: Reference to VPC
    Type: String
    MinLength: 3

  KmsKey:
    Description: KMS key for DB encryption
    Type: String
    MinLength: 3

Mappings:
  InstanceType:
    development:
      InstanceType: t2.medium
    staging:
      InstanceType: t2.medium
    prod:
      InstanceType: t2.medium

  CouchDBInstance:
    development:
      AMI: ami-e2afff91
      InstanceType: t2.small
      Name: sense-hat-couchdb-development
    staging:
      AMI: ami-00aefe73
      InstanceType: t2.small
      Name: sense-hat-couchdb-staging
    prod:
      AMI: ami-9fafffec
      InstanceType: t2.small
      Name: sense-hat-couchdb-prod

  Variables:
    development:
      SpotPrice: ''
      CouchdbPassword: ''
      SecretKey: ''
      NewRelicLogLevel: 'info'
      CouchDBUser: 'admin'
      HatMobileKey: ''
      GoogleClientId: ''
      DbAllocatedStorage: 100
      DbInstanceType: db.t2.micro
      DbEncryption: false
      DbSnapshot: ''
      DbMultiAz: false

    staging:
      SpotPrice: ''
      CouchdbPassword: ''
      SecretKey: ''
      NewRelicLogLevel: 'info'
      CouchDBUser: 'admin'
      HatMobileKey: ''
      GoogleClientId: ''
      DbAllocatedStorage: 100
      DbInstanceType: db.t2.micro
      DbEncryption: false
      DbSnapshot: ''
      DbMultiAz: false

    prod:
      SpotPrice: ''
      CouchdbPassword: ''
      SecretKey: ''
      NewRelicLogLevel: 'info'
      CouchDBUser: 'admin'
      HatMobileKey: ''
      GoogleClientId: ''
      DbAllocatedStorage: 100
      DbInstanceType: db.t2.micro
      DbEncryption: false
      DbSnapshot: ''
      DbMultiAz: false

  DomainNameSuffix:
    development:
      DomainNameSuffix: "-dev"
    staging:
      DomainNameSuffix: "-staging"
    prod:
      DomainNameSuffix: ""

  Beanstalk2Route53HostedZoneId:
    us-east-1:
      HostedZoneId: Z117KPS5GTRQ2G
    us-west-1:
      HostedZoneId: Z1LQECGX5PH1X
    us-west-2:
      HostedZoneId: Z38NKT9BP95V3O
    eu-west-1:
      HostedZoneId: Z3NF1Z3NOM5OY2
    eu-central-1:
      HostedZoneId: Z1FRNW7UH4DEZJ
    ap-northeast-1:
      HostedZoneId: Z1R25G3KIG2GBW
    ap-northeast-2:
      HostedZoneId: Z3JE5OI70TWKCP
    ap-southeast-1:
      HostedZoneId: Z16FZ9L249IFLT
    ap-southeast-2:
      HostedZoneId: Z2PCDNR3VC2G1N
    sa-east-1:
      HostedZoneId: Z10X7K2B4QSOFV

Conditions:
  DbEncryptionBool: !Equals [!FindInMap [Variables, !Ref Environment, DbEncryption], true]
  DbFromSnapshot: !Not [!Equals [!FindInMap [Variables, !Ref Environment, DbSnapshot], '']]
  DbMultiAzBool: !Equals [!FindInMap [Variables, !Ref Environment, DbMultiAz], 'true']

Resources:
  GetOrCreateDbPassword:
    Type: Custom::GetOrCreateRecord
    Properties:
      ServiceToken: !Ref GetOrCreateRecordLambda
      RecordName: !Join ['-', [!Ref ProjectName, !Ref Environment, db_password]]

  GetOrCreateDbUser:
    Type: Custom::GetOrCreateRecord
    Properties:
      ServiceToken: !Ref GetOrCreateRecordLambda
      RecordName: !Join ['-', [!Ref ProjectName, !Ref Environment, db_user]]
      RecordValue: hat

  GetOrCreateDbName:
    Type: Custom::GetOrCreateRecord
    Properties:
      ServiceToken: !Ref GetOrCreateRecordLambda
      RecordName: !Join ['-', [!Ref ProjectName, !Ref Environment, db_name]]
      RecordValue: hat

  GetOrCreateDbPort:
    Type: Custom::GetOrCreateRecord
    Properties:
      ServiceToken: !Ref GetOrCreateRecordLambda
      RecordName: !Join ['-', [!Ref ProjectName, !Ref Environment, db_port]]
      RecordValue: 5432

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Group of VPC subnets for DB
      SubnetIds: !Ref Subnets

  DBInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    Properties:
      Engine: postgres
      DBName: !If [DbFromSnapshot, !Ref 'AWS::NoValue', !GetAtt [GetOrCreateDbName, RecordValue]]
      MasterUsername: !If [DbFromSnapshot, !Ref 'AWS::NoValue', !GetAtt [GetOrCreateDbUser, RecordValue]]
      MasterUserPassword: !If [DbFromSnapshot, !Ref 'AWS::NoValue', !GetAtt [GetOrCreateDbPassword, RecordValue]]
      Port: !If [DbFromSnapshot, !Ref 'AWS::NoValue', !GetAtt [GetOrCreateDbPort, RecordValue]]
      DBInstanceClass: !FindInMap [Variables, !Ref Environment, DbInstanceType]
      VPCSecurityGroups:
        - !GetAtt [DBSecurityGroup, GroupId]
      DBSubnetGroupName: !Ref DBSubnetGroup
      AllocatedStorage: !FindInMap [Variables, !Ref Environment, DbAllocatedStorage]
      StorageType: gp2
      PubliclyAccessible: false
      BackupRetentionPeriod: 35
      DBInstanceIdentifier: !Join ['-', [!Ref ProjectName, !Ref Environment]]
      StorageEncrypted: !If [DbEncryptionBool, true, !Ref 'AWS::NoValue']
      KmsKeyId: !If [DbEncryptionBool, !Ref KmsKey, !Ref 'AWS::NoValue']
      DBSnapshotIdentifier: !If [DbFromSnapshot, !FindInMap [Variables, !Ref Environment, DbSnapshot], !Ref 'AWS::NoValue']
      MultiAZ: !If [DbMultiAzBool, 'true', 'false']

  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    DependsOn: BeanstalkSecurityGroup
    Properties:
      GroupDescription: DB security group
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !GetAtt [GetOrCreateDbPort, RecordValue]
          ToPort: !GetAtt [GetOrCreateDbPort, RecordValue]
          SourceSecurityGroupId: !Ref BeanstalkSecurityGroup

  CouchDBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow access to CouchDB instances.
      VpcId: !Ref VPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '5984'
        ToPort: '5984'
        SourceSecurityGroupId: !Ref BeanstalkSecurityGroup
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: '0'
        ToPort: '65535'
        CidrIp: 0.0.0.0/0

  BeanstalkSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow access to Elastic Beanstalk instances.
      VpcId: !Ref VPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '443'
        ToPort: '443'
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: '0'
        ToPort: '65535'
        CidrIp: 0.0.0.0/0

  BeanstalkEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref Application
      EnvironmentName: !Join ['-', [!Ref ProjectName, !Ref Environment]]
      Description: Beanstalk environment
      VersionLabel: !Ref ApplicationVersion
      TemplateName: !Ref ConfigurationTemplate
      OptionSettings:
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: SecurityGroups
        Value: !Ref BeanstalkSecurityGroup
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: InstanceType
        Value: !FindInMap [InstanceType, !Ref Environment, InstanceType]
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: SPOT_PRICE
        Value: !FindInMap [Variables, !Ref Environment, SpotPrice]
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: RDS_PASSWORD
        Value: !GetAtt [GetOrCreateDbPassword, RecordValue]
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: RDS_USERNAME
        Value: !GetAtt [GetOrCreateDbUser, RecordValue]
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: RDS_DB_NAME
        Value: !GetAtt [GetOrCreateDbName, RecordValue]
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: RDS_PORT
        Value: !GetAtt [GetOrCreateDbPort, RecordValue]
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: RDS_HOSTNAME
        Value: !GetAtt [DBInstance, Endpoint.Address]
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: COUCHDB_PASSWORD 
        Value: !FindInMap [Variables, !Ref Environment, CouchdbPassword]
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: SECRET_KEY 
        Value: !FindInMap [Variables, !Ref Environment, SecretKey]
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: NEW_RELIC_LOG_LEVEL 
        Value: !FindInMap [Variables, !Ref Environment, NewRelicLogLevel]
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: COUCHDB_USER 
        Value: !FindInMap [Variables, !Ref Environment, CouchDBUser]
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: HAT_MOBILE_KEY
        Value: !FindInMap [Variables, !Ref Environment, HatMobileKey]
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: GOOGLE_CLIENT_ID
        Value: !FindInMap [Variables, !Ref Environment, GoogleClientId]
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: NEW_RELIC_APP_NAME
        Value: !Join ['', [!Ref ProjectName, !FindInMap [DomainNameSuffix, !Ref Environment, DomainNameSuffix]]]
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: COUCHDB_URL
        Value: !Join ['', ['http://', !Ref ProjectName, "-couchdb", !FindInMap [DomainNameSuffix, !Ref Environment, DomainNameSuffix], '.', !Ref HostedZone, ':5984']]

  CouchDBInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [CouchDBInstance, !Ref Environment, AMI]
      InstanceType: !FindInMap [CouchDBInstance, !Ref Environment, InstanceType]
      KeyName: !Ref KeyName
      InstanceInitiatedShutdownBehavior: stop
      NetworkInterfaces:
      - AssociatePublicIpAddress: 'true'
        DeviceIndex: '0'
        GroupSet:
        - !Ref CouchDBSecurityGroup
        SubnetId: !Ref Subnet
      Tags:
      - Key: Name
        Value: !FindInMap [CouchDBInstance, !Ref Environment, Name]

  CouchDBDNSRecord:
    Type: AWS::Route53::RecordSet
    DependsOn: CouchDBInstance
    Properties:
      HostedZoneName: !Join ['', [!Ref HostedZone, '.']]
      Comment: CouchDB DNS name
      Name: !Join ['', [!Ref ProjectName, "-couchdb", !FindInMap [DomainNameSuffix, !Ref Environment, DomainNameSuffix], '.', !Ref HostedZone, '.']]
      Type: A
      TTL: '60'
      ResourceRecords:
      - !GetAtt [CouchDBInstance, PrivateIp]

  DNSRecord:
    Type: AWS::Route53::RecordSet
    DependsOn: BeanstalkEnvironment
    Properties:
      HostedZoneName: !Join ['', [!Ref HostedZone, '.']]
      Comment: DNS name
      Name: !Join ['', [!Ref ProjectName, !FindInMap [DomainNameSuffix, !Ref Environment, DomainNameSuffix], '.', !Ref HostedZone, '.']]
      Type: A
      AliasTarget:
        HostedZoneId: !FindInMap [Beanstalk2Route53HostedZoneId, !Ref 'AWS::Region', HostedZoneId]
        DNSName: !GetAtt [BeanstalkEnvironment, EndpointURL]

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['', [!Ref ProjectName, '-', !Ref Environment]]
      RetentionInDays: 180

  BytesTransferredMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: !Ref LogGroup
      FilterPattern: "[]"
      MetricTransformations:
      - MetricValue: "$size"
        MetricNamespace: !Join ['', [!Ref ProjectName, '/']]
        MetricName: !Join ['', [!Ref Environment, '-', BytesTransferred]]

  BandwidthAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: The average volume of traffic is greater 3500 KB over 10 minutes
      MetricName: !Join ['', [!Ref Environment, '-', BytesTransferred]]
      Namespace: !Join ['', [!Ref ProjectName, '/']]
      Statistic: Average
      Period: '300'
      EvaluationPeriods: '2'
      Threshold: '3500'
      AlarmActions:
      - !Ref SNSTopic
      ComparisonOperator: GreaterThanThreshold

Outputs:
  DNSName:
    Description: DNS name
    Value: !Ref DNSRecord
  CouchDBDNSName:
    Description: CouchDB DNS name
    Value: !Ref CouchDBDNSRecord
