# Generated by Django 4.2.14 on 2024-12-04 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("iaso", "0309_alter_potentialpayment_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Import",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("org_unit_id", models.IntegerField()),
                ("month", models.CharField(max_length=255)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("source", models.CharField(max_length=255)),
                ("hash_key", models.TextField()),
                ("file_name", models.TextField(unique=True)),
                ("file_check", models.TextField()),
            ],
            options={
                "db_table": "import",
            },
        ),
        migrations.CreateModel(
            name="Validation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user_id", models.IntegerField()),
                ("user_name", models.CharField(max_length=255)),
                ("level", models.CharField(choices=[("region", "Région"), ("district", "District")], max_length=255)),
                ("comment", models.TextField()),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("waiting_for_validation", "Waiting For Validation"),
                            ("district_validated", "Validated by District"),
                            ("region_validated", "Validated by Region"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "source_import",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="active_list.import"),
                ),
            ],
            options={
                "db_table": "validation",
            },
        ),
        migrations.CreateModel(
            name="ActivePatientsList",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.IntegerField()),
                ("region", models.TextField()),
                ("district", models.TextField()),
                ("code_ets", models.CharField(max_length=255)),
                ("facility_name", models.TextField()),
                ("period", models.TextField(db_index=True)),
                ("sex", models.TextField(choices=[("Male", "Homme"), ("Female", "Femme")])),
                ("age", models.IntegerField()),
                ("weight", models.IntegerField(null=True)),
                ("new_inclusion", models.BooleanField()),
                ("transfer_in", models.BooleanField()),
                ("return_to_care", models.BooleanField()),
                ("tb_hiv", models.BooleanField()),
                (
                    "hiv_type",
                    models.TextField(choices=[("HIV1", "HIV 1"), ("HIV2", "HIV 2"), ("HIV 1&2", "HIV 1 & 2")]),
                ),
                ("treatment_line", models.TextField(choices=[("1stline", "1er Ligne"), ("2ndline", "2e Ligne")])),
                ("last_dispensation_date", models.DateField(null=True)),
                ("days_dispensed", models.IntegerField(null=True)),
                ("regimen", models.TextField(null=True)),
                ("stable", models.IntegerField(null=True)),
                ("arv_stock_days", models.IntegerField(null=True)),
                ("discontinuation_date", models.DateField(null=True)),
                ("transfer_out", models.BooleanField()),
                ("death", models.BooleanField()),
                ("art_stoppage", models.BooleanField()),
                ("served_elsewhere", models.BooleanField()),
                ("active", models.BooleanField()),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("waiting_for_validation", "Waiting For Validation"),
                            ("district_validated", "Validated by District"),
                            ("region_validated", "Validated by Region"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "import_source",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="active_list.import"),
                ),
                ("org_unit", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="iaso.orgunit")),
            ],
            options={
                "db_table": "active_list",
            },
        ),
    ]
