# Generated by Django 4.2.17 on 2025-04-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("active_list", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="record",
            name="disappeared",
        ),
        migrations.RemoveField(
            model_name="record",
            name="validation_status",
        ),
        migrations.AlterField(
            model_name="patient",
            name="identifier_code",
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name="Code identifiant"),
        ),
    ]
