# Generated by Django 4.2.17 on 2024-12-07 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0309_alter_potentialpayment_user"),
        ("active_list", "0002_activepatientslist_identifier_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="import",
            name="org_unit_id",
        ),
        migrations.AddField(
            model_name="import",
            name="org_unit",
            field=models.ForeignKey(default=2247732, on_delete=django.db.models.deletion.CASCADE, to="iaso.orgunit"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="activepatientslist",
            name="treatment_line",
            field=models.TextField(
                choices=[("1STLINE", "1er Ligne"), ("2NDLINE", "2e Ligne"), ("3RDLINE", "3e Ligne")]
            ),
        ),
    ]
