# Generated by Django 4.2.17 on 2024-12-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("active_list", "0003_remove_import_org_unit_id_import_org_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activepatientslist",
            name="disappeared",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="activepatientslist",
            name="received_arv",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="import",
            name="on_time",
            field=models.BooleanField(default=False),
        ),
    ]
