# Generated by Django 4.2.20 on 2025-05-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_list', '0003_patientinactiveevent_last_patient_record_at_time_of_loss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='file',
            field=models.FileField(null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
