# Generated by Django 4.2.17 on 2024-12-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("active_list", "0004_activepatientslist_disappeared_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Month",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="activepatientslist",
            name="hiv_type",
            field=models.TextField(
                choices=[("HIV1", "HIV 1"), ("HIV2", "HIV 2"), ("HIV 1&2", "HIV 1 & 2"), ("UNKNOWN", "")]
            ),
        ),
        migrations.AlterField(
            model_name="activepatientslist",
            name="validation_status",
            field=models.CharField(
                choices=[
                    ("WAITING_FOR_VALIDATION", "En attente de Validation"),
                    ("DISTRICT_VALIDATED", "Validé par District"),
                    ("REGION_VALIDATED", "Validé par la Région"),
                ],
                default="WAITING_FOR_VALIDATION",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="validation",
            name="validation_status",
            field=models.CharField(choices=[("OK", "Validé"), ("INVALID", "Invalide")], max_length=255, null=True),
        ),
    ]
