# Generated by Django 4.2.17 on 2024-12-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("active_list", "0005_month_alter_activepatientslist_hiv_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activepatientslist",
            name="next_dispensation_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="activepatientslist",
            name="hiv_type",
            field=models.TextField(
                choices=[("HIV1", "VIH 1"), ("HIV2", "VIH 2"), ("HIV 1&2", "VIH 1+ VIH 2"), ("UNKNOWN", "")]
            ),
        ),
        migrations.AlterField(
            model_name="activepatientslist",
            name="sex",
            field=models.TextField(choices=[("MALE", "H"), ("FEMALE", "F")]),
        ),
        migrations.AlterField(
            model_name="validation",
            name="comment",
            field=models.TextField(verbose_name="Commentaire"),
        ),
        migrations.AlterField(
            model_name="validation",
            name="level",
            field=models.CharField(
                choices=[("REGION", "Région"), ("DISTRICT", "District")],
                max_length=255,
                verbose_name="Niveau de Validation",
            ),
        ),
        migrations.AlterField(
            model_name="validation",
            name="validation_status",
            field=models.CharField(
                choices=[("OK", "Validé"), ("INVALID", "Invalide")], max_length=255, null=True, verbose_name="Statut"
            ),
        ),
    ]
