# Generated by Django 4.2.21 on 2025-06-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("active_list", "0006_patient_entity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="import",
            name="file_check",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="import",
            name="file_name",
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="import",
            name="hash_key",
            field=models.TextField(null=True),
        ),
    ]
