# Generated by Django 4.2.21 on 2025-06-02 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0325_merge_0324_auto_20250514_1244_0324_project_color"),
        ("active_list", "0007_alter_import_file_check_alter_import_file_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="instance",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instances",
                to="iaso.instance",
                verbose_name="Soumission",
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="treatment_line",
            field=models.TextField(
                choices=[
                    ("1STLINE", "1er Ligne"),
                    ("2NDLINE", "2e Ligne"),
                    ("3RDLINE", "3e Ligne"),
                    ("UNKNOWN", "Inconnu"),
                ],
                verbose_name="Ligne de traitement",
            ),
        ),
    ]
