# Generated by Django 4.2.21 on 2025-06-02 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0325_merge_0324_auto_20250514_1244_0324_project_color"),
        ("active_list", "0008_record_instance_alter_record_treatment_line"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="instance",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="iaso.instance",
                verbose_name="Soumission",
            ),
        ),
    ]
