# Generated by Django 4.2.21 on 2025-06-04 15:00

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("active_list", "0010_record_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="records", to="active_list.patient"
            ),
        ),
    ]
