# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-12 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_auto_20180106_0759'),
        ('users', '0004_auto_20180108_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordination',
            name='zss',
            field=models.ManyToManyField(to='geo.ZS'),
        ),
        migrations.AddField(
            model_name='team',
            name='ass',
            field=models.ManyToManyField(to='geo.AS'),
        ),
    ]
