# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-12 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180112_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordination',
            old_name='zss',
            new_name='ZS',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='ass',
            new_name='AS',
        ),
    ]
