# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-22 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_team_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='UM',
            field=models.BooleanField(default=True),
        ),
    ]
