# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-23 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_team_um'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='AS',
            field=models.ManyToManyField(blank=True, null=True, to='geo.AS'),
        ),
    ]
