# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-23 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180123_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='AS',
            field=models.ManyToManyField(blank=True, to='geo.AS'),
        ),
    ]
