# Generated by Django 2.0 on 2018-05-23 12:40

import django.contrib.postgres.fields
import django.contrib.postgres.fields.citext
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0010_remove_null_on_AS'),
    ]

    operations = [
        CITextExtension(),
        migrations.AddField(
            model_name='team',
            name='aliases',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.citext.CITextField(blank=True, max_length=255), blank=True,
                null=True, size=4),
        ),
    ]
