# Generated by Django 2.0 on 2018-08-13 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_increase_your_aliases_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='restrict_to_zs',
        ),
    ]
