# Generated by Django 2.0 on 2018-09-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_profile_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password_reset',
            field=models.BooleanField(default=False),
        ),
    ]
