# Generated by Django 2.0 on 2018-09-28 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_profile_password_reset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='AS',
        ),
    ]
