# Generated by Django 2.0 on 2018-10-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_team_as'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='AS_scope',
            field=models.ManyToManyField(blank=True, to='geo.AS'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ZS_scope',
            field=models.ManyToManyField(blank=True, to='geo.ZS'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='province_scope',
            field=models.ManyToManyField(blank=True, to='geo.Province'),
        ),
    ]
