# Generated by Django 2.0 on 2019-02-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_geom_polygon'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tester_type',
            field=models.TextField(blank=True, null=True, verbose_name=models.TextField(blank=True, choices=[('screener', 'Dépisteur'), ('confirmer', 'Confirmateur')], max_length=255)),
        ),
    ]
