# Generated by Django 2.0 on 2019-02-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_profile_tester_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tester_type',
            field=models.TextField(blank=True, choices=[('screener', 'Dépisteur'), ('confirmer', 'Confirmateur')], null=True, verbose_name='Type de tester'),
        ),
    ]
