# Generated by Django 2.0 on 2019-02-25 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20190222_1624'),
        ('users', '0021_auto_20190221_1811'),
        ('users', '0021_auto_20190212_1105'),
    ]

    operations = [
    ]
