# Generated by Django 2.0 on 2019-04-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20190320_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.IntegerField(blank=True, choices=[(10, 'Niveau 1'), (20, 'Niveau 2'), (30, 'Niveau 3'), (40, 'Niveau 4')], default=10, null=True),
        ),
    ]
