# Generated by Django 2.0 on 2019-05-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_other_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='screening_type',
            field=models.TextField(blank=True, choices=[('active', 'Dépistage actif'), ('passive', 'Dépistage passif')], default='active', null=True, verbose_name='Dépistage actif/passif'),
        ),
    ]
