# Generated by Django 2.0 on 2019-05-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20190520_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='UM',
            field=models.NullBooleanField(),
        ),
    ]
