# Generated by Django 2.0 on 2019-05-31 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_depistage_passif'),
        ('users', '0028_auto_20190520_1255'),
    ]

    operations = [
    ]
