# Generated by Django 2.0 on 2019-05-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_merge_20190523_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_type',
            field=models.TextField(choices=[('tester', 'Dépistage & confirmation'), ('vector', 'Vecteur contrôle')], default='tester', verbose_name="Type d'équipe"),
        ),
    ]
