# Generated by Django 2.0 on 2019-07-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20190530_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='is_erased',
            field=models.BooleanField(default=False),
        ),
    ]
