# Generated by Django 2.2.4 on 2019-11-13 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("users", "0031_usertype_is_erased")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="coordination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.Coordination",
            ),
        )
    ]
