import React, { FunctionComponent } from 'react';
import { Box, Grid } from '@mui/material';
import { makeStyles } from '@mui/styles';
import { useSafeIntl, commonStyles } from 'bluesquare-components';
import DownloadButtonsComponent from '../../components/DownloadButtonsComponent';
import TopBar from '../../components/nav/TopBarComponent';
import { baseUrls } from '../../constants/urls';
import { useQueryString } from '../../hooks/useApiParams';
import { useParamsObject } from '../../routing/hooks/useParamsObject';
import { Filters } from './components/Filters';
import { FormsTable } from './components/FormsTable';
import { tableDefaults, useGetForms } from './hooks/useGetForms';
import MESSAGES from './messages';
import { FormsParams } from './types/forms';

const useStyles = makeStyles(theme => ({ ...commonStyles(theme) }));

const dwnldBaseUrl = '/api/forms';

const Forms: FunctionComponent = () => {
    const baseUrl = baseUrls.forms;
    const params = useParamsObject(baseUrl) as unknown as FormsParams;
    const classes = useStyles();
    const { formatMessage } = useSafeIntl();

    // This doesn't duplicate API calls as long as
    // the querystring generated by useGetForms is the same as the one in the table
    const { data: forms, isLoading: isLoadingForms } = useGetForms(
        params,
        undefined,
        true,
    );
    const downloadQueryString = useQueryString(
        { ...params, all: 'true' },
        tableDefaults,
    );
    const csvUrl = `${dwnldBaseUrl}/?${downloadQueryString}&csv=true`;
    const xlsxUrl = `${dwnldBaseUrl}/?${downloadQueryString}&xlsx=true`;

    return (
        <>
            <TopBar title={formatMessage(MESSAGES.title)} />
            <Box className={classes.containerFullHeightNoTabPadded}>
                <Filters params={params} />
                <Box mt={4}>
                    <Grid container spacing={2} justifyContent="flex-end">
                        <DownloadButtonsComponent
                            variant="outlined"
                            xlsxUrl={xlsxUrl}
                            csvUrl={csvUrl}
                            disabled={isLoadingForms || !forms?.forms?.length}
                        />
                    </Grid>
                </Box>

                <FormsTable baseUrl={baseUrl} params={params} />
            </Box>
        </>
    );
};

export default Forms;
