# Generated by Django 4.2.24 on 2025-09-21 06:37


from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("menupermissions", "0001_squashed_0023_auto_20211028_1436"),
        ("menupermissions", "0024_auto_20211217_1119"),
        ("menupermissions", "0025_auto_20211221_1413"),
        ("menupermissions", "0026_auto_20220325_1437"),
        ("menupermissions", "0027_add_update_submissions_perm_to_existing_users"),
        ("menupermissions", "0028_auto_20220421_0921"),
        ("menupermissions", "0029_auto_20220510_1332"),
        ("menupermissions", "0028_alter_custompermissionsupport_options"),
        ("menupermissions", "0030_merge_20220518_1227"),
        ("menupermissions", "0031_alter_custompermissionsupport_options"),
        ("menupermissions", "0032_alter_custompermissionsupport_options"),
        ("menupermissions", "0033_alter_custompermissionsupport_options"),
        ("menupermissions", "0034_add-entities_perm_to-users_with_beneficairies_perm"),
        ("menupermissions", "0035_alter_custompermissionsupport_options"),
        ("menupermissions", "0036_alter_custompermissionsupport_options"),
        ("menupermissions", "0037_alter_custompermissionsupport_options"),
        ("menupermissions", "0038_alter_custompermissionsupport_options"),
        ("menupermissions", "0039_alter_custompermissionsupport_options"),
        ("menupermissions", "0040_delete_perm_beneficiary"),
        ("menupermissions", "0041_alter_custompermissionsupport_options"),
        ("menupermissions", "0042_alter_custompermissionsupport_options"),
        ("menupermissions", "0043_alter_custompermissionsupport_options"),
        ("menupermissions", "0044_alter_custompermissionsupport_options"),
        ("menupermissions", "0045_alter_custompermissionsupport_options"),
        ("menupermissions", "0046_alter_custompermissionsupport_options"),
        ("menupermissions", "0047_alter_custompermissionsupport_options"),
        ("menupermissions", "0048_alter_custompermissionsupport_options"),
        ("menupermissions", "0049_alter_custompermissionsupport_options"),
        ("menupermissions", "0050_alter_custompermissionsupport_options"),
        ("menupermissions", "0051_alter_custompermissionsupport_options"),
        ("menupermissions", "0052_alter_custompermissionsupport_options"),
        ("menupermissions", "0053_alter_custompermissionsupport_options"),
        ("menupermissions", "0054_alter_custompermissionsupport_options"),
        ("menupermissions", "0055_alter_custompermissionsupport_options"),
        ("menupermissions", "0056_alter_custompermissionsupport_options"),
        ("menupermissions", "0057_alter_custompermissionsupport_options"),
        ("menupermissions", "0058_alter_custompermissionsupport_options"),
        ("menupermissions", "0059_alter_custompermissionsupport_options"),
        ("menupermissions", "0060_alter_custompermissionsupport_options"),
        ("menupermissions", "0061_alter_custompermissionsupport_options"),
        ("menupermissions", "0062_alter_custompermissionsupport_options"),
        ("menupermissions", "0063_alter_custompermissionsupport_options"),
        ("menupermissions", "0064_alter_custompermissionsupport_options"),
        ("menupermissions", "0065_alter_custompermissionsupport_options"),
        ("menupermissions", "0066_alter_custompermissionsupport_options"),
        ("menupermissions", "0067_alter_custompermissionsupport_options"),
        ("menupermissions", "0068_alter_custompermissionsupport_options"),
        ("menupermissions", "0069_alter_custompermissionsupport_options"),
        ("menupermissions", "0070_alter_custompermissionsupport_options"),
        ("menupermissions", "0071_alter_custompermissionsupport_options"),
        ("menupermissions", "0072_alter_custompermissionsupport_options"),
        ("menupermissions", "0073_alter_custompermissionsupport_options"),
        ("menupermissions", "0074_alter_custompermissionsupport_options"),
        ("menupermissions", "0075_alter_custompermissionsupport_options"),
    ]

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        #   ('iaso', '0178_remove_beneficiary_user_perm'),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomPermissionSupport",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "permissions": (),
                "managed": False,
            },
        )
    ]
