# Generated by Django 2.0 on 2019-08-19 08:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("menupermissions", "0011_auto_20190627_1327"),
        ("menupermissions", "0012_auto_20190802_1444"),
    ]

    operations = []
