# Generated by Django 3.1.14 on 2022-03-25 14:37

from django.db import migrations


def add_user_permissions(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    permissions_p = Permission.objects.all()
    for p in permissions_p:
        print(p.codename)
    permissions = Permission.objects.get(codename="iaso_update_submission")

    User = apps.get_model("auth", "User")

    users = User.objects.filter(user_permissions=Permission.objects.get(codename="iaso_submissions"))

    for user in users:
        print(f"Adding perms {permissions} to {user}")
        user.user_permissions.add(permissions)


class Migration(migrations.Migration):

    dependencies = [
        ("menupermissions", "0026_auto_20220325_1437"),
    ]

    operations = [migrations.RunPython(add_user_permissions, migrations.RunPython.noop)]
