# Generated by Django 3.1.14 on 2022-03-25 14:37
from django.contrib.auth.management import create_permissions
from django.db import migrations


class Migration(migrations.Migration):
    def add_user_permissions(apps, schema_editor):
        # Ensure the permissions are created in the databse
        # cf https://stackoverflow.com/questions/38822273/how-to-add-a-permission-to-a-user-group-during-a-django-migration/41564061#41564061
        for app_config in apps.get_app_configs():
            app_config.models_module = True
            create_permissions(app_config, verbosity=0)
            app_config.models_module = None

        Permission = apps.get_model("auth", "Permission")
        try:
            permissions = Permission.objects.get(codename="iaso_update_submission")
        except Permission.DoesNotExist:  # The CustomPermissionSupport model is no longer used, so it can't be found and no permissions were created by create_permissions()
            return  # this migration is not needed on a fresh DB

        User = apps.get_model("auth", "User")

        users = User.objects.filter(user_permissions=Permission.objects.get(codename="iaso_submissions"))

        for user in users:
            print(f"Adding perms {permissions} to {user}")
            user.user_permissions.add(permissions)

    dependencies = [
        ("menupermissions", "0026_auto_20220325_1437"),
        ("contenttypes", "0002_remove_content_type_name"),  # Making sure to use the freshest version of ContentType
    ]

    operations = [
        migrations.RunPython(add_user_permissions, migrations.RunPython.noop),
    ]
