# Generated by Django 3.2.13 on 2022-05-18 12:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("menupermissions", "0028_alter_custompermissionsupport_options"),
        ("menupermissions", "0029_auto_20220510_1332"),
    ]

    operations = []
