# Generated by Django 4.2.17 on 2025-07-15 15:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("menupermissions", "0073_alter_custompermissionsupport_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="custompermissionsupport",
            options={
                "managed": False,
                "permissions": (
                    ("iaso_trypelim_anonymous", "Anonymisation des patients"),
                    ("iaso_trypelim_management_areas", "Areas"),
                    ("iaso_trypelim_management_edit_areas", "Edit areas"),
                    ("iaso_trypelim_management_edit_shape_areas", "Edit areas shapes"),
                    ("iaso_trypelim_case_cases", "Cases"),
                    ("iaso_trypelim_case_analysis", "Cases analysis"),
                    ("iaso_trypelim_management_coordinations", "Coordinations"),
                    ("iaso_trypelim_management_devices", "Devices"),
                    ("iaso_trypelim_datas_download", "Téléchargement de données"),
                    ("iaso_trypelim_duplicates", "Doublons"),
                    ("iaso_trypelim_datas_patient_edition", "Edition d'un patient"),
                    ("iaso_trypelim_management_health_structures", "Health facilities"),
                    ("iaso_trypelim_lab", "Labo"),
                    ("iaso_trypelim_labupload", "Labo import"),
                    ("iaso_trypelim_locator", "Locator"),
                    ("iaso_trypelim_plannings_macroplanning", "Macroplanning"),
                    ("iaso_trypelim_plannings_microplanning", "Microplanning"),
                    ("iaso_trypelim_modifications", "Modifications"),
                    ("iaso_trypelim_management_plannings", "Plannings"),
                    (
                        "iaso_trypelim_management_plannings_template",
                        "Plannings template",
                    ),
                    ("iaso_trypelim_qualitycontrol", "Quality control"),
                    ("iaso_trypelim_case_reconciliation", "Reconciliation"),
                    ("iaso_trypelim_plannings_routes", "Routes"),
                    ("iaso_trypelim_stats_graphs", "Graphs"),
                    ("iaso_trypelim_stats_reports", "Reports"),
                    ("iaso_trypelim_datasets_datauploads", "Upload of cases files"),
                    (
                        "iaso_trypelim_datasets_villageuploads",
                        "Upload of villages files",
                    ),
                    ("iaso_trypelim_management_teams", "Teams"),
                    ("iaso_trypelim_management_users", "Users"),
                    ("iaso_trypelim_vectorcontrol", "Vector control"),
                    ("iaso_trypelim_vectorcontrolupload", "Vector control import Gpx"),
                    ("iaso_trypelim_management_villages", "Villages"),
                    ("iaso_trypelim_management_workzones", "Work zones"),
                    ("iaso_trypelim_management_zones", "Zones"),
                    ("iaso_trypelim_management_edit_zones", "Edit zones"),
                    ("iaso_trypelim_management_edit_shape_zones", "Edit zones shapes"),
                ),
            },
        ),
    ]
