# Generated by Django 4.2.17 on 2025-07-31 10:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("menupermissions", "0074_alter_custompermissionsupport_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="custompermissionsupport",
            options={"managed": False, "permissions": ()},
        ),
    ]
