# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.TextField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mobileuser',
            name='couchdb_id',
        ),
        migrations.RemoveField(
            model_name='mobileuser',
            name='db_name',
        ),
    ]
