# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-10 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_imageupload_videoupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
