# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_auto_20170210_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceDBEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.TextField(db_index=True)),
                ('device_doc_id', models.TextField(db_index=True, null=True)),
                ('device_doc_rev', models.TextField(null=True)),
            ],
            options={
                'permissions': (('import_sync', 'Can import synced cases'),),
            },
        ),
        migrations.AddField(
            model_name='devicedb',
            name='last_synced_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='devicedb',
            name='last_synced_seq',
            field=models.TextField(null=True, default=0),
        ),
        migrations.AddField(
            model_name='devicedb',
            name='last_synced_docs',
            field=models.TextField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='devicedbentry',
            unique_together=set([('device_id', 'device_doc_id')]),
        ),
    ]
