# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-16 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0003_auto_20171010_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DeviceEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('comment', models.TextField(null=True)),
                ('event_type', models.IntegerField(choices=[(0, 'Status Change'), (1, 'Action'), (2, 'Comment')], default=0)),
                ('action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sync.DeviceAction')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sync.DeviceDB')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='deviceevent',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sync.DeviceStatus'),
        ),
    ]
