# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-16 11:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sync', '0004_auto_20171016_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceevent',
            name='reporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
