# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-13 17:15
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0006_auto_20171016_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouchDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.TextField()),
                ('doc_revision', models.TextField()),
                ('doc', django.contrib.postgres.fields.jsonb.JSONField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sync.DeviceDB')),
            ],
        ),
    ]
