# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-04 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0008_jsondocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='document_id',
        ),
        migrations.RemoveField(
            model_name='videoupload',
            name='document_id',
        ),
        migrations.AddField(
            model_name='imageupload',
            name='group_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoupload',
            name='group_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
