# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-05 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0009_auto_20171204_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='hat_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='participant_uuid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
