# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-22 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0011_auto_20171218_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='group_id',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='participant_uuid',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='videoupload',
            name='group_id',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='videoupload',
            name='participant_uuid',
            field=models.TextField(db_index=True),
        ),
    ]
