# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-22 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0012_auto_20171222_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='type',
            field=models.TextField(default='catt'),
        ),
        migrations.AddField(
            model_name='videoupload',
            name='type',
            field=models.TextField(default='pg'),
        ),
    ]
