# Generated by Django 2.0 on 2018-03-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0013_auto_20171222_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='type',
            field=models.TextField(choices=[('CATT', 'CATT'), ('PG', 'PG'), ('ctcwoo', 'ctcwoo'), ('maect', 'maect'), ('RDT', 'RDT')], default='catt'),
        ),
        migrations.AlterField(
            model_name='videoupload',
            name='type',
            field=models.TextField(choices=[('CATT', 'CATT'), ('PG', 'PG'), ('ctcwoo', 'ctcwoo'), ('maect', 'maect'), ('RDT', 'RDT')], default='pg'),
        ),
    ]
