# Generated by Django 2.0.4 on 2018-04-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0014_constraining_upload_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='type',
            field=models.TextField(choices=[('CATT', 'CATT'), ('PG', 'PG'), ('ctcwoo', 'ctcwoo'), ('maect', 'maect'), ('RDT', 'RDT')], default='CATT'),
        ),
    ]
