# Generated by Django 2.0 on 2018-04-09 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sync', '0015_zsasimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedb',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='devicedb_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devicedb',
            name='last_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='devicedb_last_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
