# Generated by Django 2.0 on 2018-05-08 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0021_jsondocument_reverse'),
        ('sync', '0016_devicedb_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsondocument',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.Case'),
        ),
    ]
