# Generated by Django 2.0 on 2018-05-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0017_jsondocument_reverse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='type',
            field=models.TextField(choices=[('CATT', 'CATT'), ('PG', 'PG'), ('CTCWOO', 'CTCWOO'), ('MAECT', 'MAECT'), ('RDT', 'RDT')], default='CATT'),
        ),
        migrations.AlterField(
            model_name='videoupload',
            name='type',
            field=models.TextField(choices=[('CATT', 'CATT'), ('PG', 'PG'), ('CTCWOO', 'CTCWOO'), ('MAECT', 'MAECT'), ('RDT', 'RDT')], default='PG'),
        ),
    ]
