# Generated by Django 2.0 on 2018-05-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0018_resync_migrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='type',
            field=models.TextField(choices=[('CATT', 'CATT'), ('PG', 'PG'), ('PL', 'PL'), ('CTCWOO', 'CTCWOO'), ('MAECT', 'MAECT'), ('RDT', 'RDT')], default='CATT'),
        ),
        migrations.AlterField(
            model_name='videoupload',
            name='type',
            field=models.TextField(choices=[('CATT', 'CATT'), ('PG', 'PG'), ('PL', 'PL'), ('CTCWOO', 'CTCWOO'), ('MAECT', 'MAECT'), ('RDT', 'RDT')], default='PG'),
        ),
        migrations.AlterField(
            model_name='videoupload',
            name='video',
            field=models.FileField(upload_to='images/'),
        ),
    ]
