# Generated by Django 2.0 on 2018-06-14 10:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    """
    This migration needs the following cleanup to be performed:
    create temporary table sync_jsondocument_dupes as
    select doc_id, doc_revision, max(id) as max_id
      from sync_jsondocument
      group by doc_id, doc_revision
      having count(*)>1;
    delete from sync_jsondocument sj using sync_jsondocument_dupes sjd where sj.doc_id=sjd.doc_id and sj.doc_revision=sjd.doc_revision and sj.id<>sjd.max_id;

    """

    dependencies = [
        ('sync', '0019_video_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsondocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jsondocument',
            name='processed',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jsondocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='videoupload',
            name='video',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
