# Generated by Django 2.0 on 2018-06-14 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0020_json_doc_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceImportEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.IntegerField(choices=[(0, 'Data fetched from CouchDB'), (1, 'Data actually imported into the DB'), (2, 'Any error')], default=0)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('total_records', models.IntegerField(null=True)),
                ('created_records', models.IntegerField(null=True)),
                ('updated_records', models.IntegerField(null=True)),
                ('deleted_records', models.IntegerField(null=True)),
                ('errors', models.IntegerField(null=True)),
                ('last_synced_seq', models.IntegerField(null=True)),
                ('details', models.TextField(null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sync.DeviceDB')),
            ],
        ),
    ]
