# Generated by Django 2.0 on 2019-02-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0023_ptr'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedb',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
    ]
