# Generated by Django 2.0 on 2019-04-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0024_devicedb_is_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='type',
            field=models.TextField(choices=[('CATT', 'CATT'), ('PG', 'PG'), ('PL', 'PL'), ('CTCWOO', 'CTCWOO'), ('MAECT', 'MAECT'), ('RDT', 'RDT'), ('SF', 'Sang Frais'), ('SP', 'Ponction Sternale'), ('IFAT', 'ImmunoFluorescence Antibody Test'), ('LCR', 'Liquide CéphaloRachidien'), ('DIL', 'Dil = ou > + à 1/16 en zone hyperendémique'), ('GE', 'Goutte Épaisse'), ('CLINICAL_SICKNESS', 'Malade clinique'), ('LNP', 'Lymph Node Puncture'), ('PARASIT', 'Confirmation parasytologique')], default='CATT'),
        ),
        migrations.AlterField(
            model_name='videoupload',
            name='type',
            field=models.TextField(choices=[('CATT', 'CATT'), ('PG', 'PG'), ('PL', 'PL'), ('CTCWOO', 'CTCWOO'), ('MAECT', 'MAECT'), ('RDT', 'RDT'), ('SF', 'Sang Frais'), ('SP', 'Ponction Sternale'), ('IFAT', 'ImmunoFluorescence Antibody Test'), ('LCR', 'Liquide CéphaloRachidien'), ('DIL', 'Dil = ou > + à 1/16 en zone hyperendémique'), ('GE', 'Goutte Épaisse'), ('CLINICAL_SICKNESS', 'Malade clinique'), ('LNP', 'Lymph Node Puncture'), ('PARASIT', 'Confirmation parasytologique')], default='PG'),
        ),
    ]
