# Generated by Django 2.1.11 on 2020-01-07 10:24

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0026_delete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jsondocument",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sync.DeviceDB",
            ),
        ),
        migrations.AlterField(
            model_name="jsondocument",
            name="doc",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
        migrations.AlterField(
            model_name="jsondocument",
            name="type",
            field=models.TextField(
                choices=[
                    ("participant", "Participant information, including tests"),
                    ("ptr", "Population data provided by tablets"),
                    ("historic", "Historic"),
                    ("pv", "Pharmacovigilance"),
                    ("backup", "Backup"),
                ],
                default="participant",
            ),
        ),
    ]
