# Generated by Django 2.1.11 on 2020-04-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0027_json_documents_for_historic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imageupload",
            name="type",
            field=models.TextField(
                choices=[
                    ("CATT", "CATT"),
                    ("PG", "PG"),
                    ("PL", "PL"),
                    ("CTCWOO", "CTCWOO"),
                    ("MAECT", "MAECT"),
                    ("RDT", "RDT"),
                    ("SF", "Sang Frais"),
                    ("SP", "Ponction Sternale"),
                    ("IFAT", "ImmunoFluorescence Antibody Test"),
                    ("LCR", "Liquide CéphaloRachidien"),
                    ("DIL", "Dil = ou > + à 1/16 en zone hyperendémique"),
                    ("GE", "Goutte Épaisse"),
                    ("CLINICAL_SICKNESS", "Malade clinique"),
                    ("LNP", "Lymph Node Puncture"),
                    ("PARASIT", "Confirmation parasytologique"),
                    ("RESEARCH_PL", "PL de recherche"),
                ],
                default="CATT",
            ),
        ),
        migrations.AlterField(
            model_name="videoupload",
            name="type",
            field=models.TextField(
                choices=[
                    ("CATT", "CATT"),
                    ("PG", "PG"),
                    ("PL", "PL"),
                    ("CTCWOO", "CTCWOO"),
                    ("MAECT", "MAECT"),
                    ("RDT", "RDT"),
                    ("SF", "Sang Frais"),
                    ("SP", "Ponction Sternale"),
                    ("IFAT", "ImmunoFluorescence Antibody Test"),
                    ("LCR", "Liquide CéphaloRachidien"),
                    ("DIL", "Dil = ou > + à 1/16 en zone hyperendémique"),
                    ("GE", "Goutte Épaisse"),
                    ("CLINICAL_SICKNESS", "Malade clinique"),
                    ("LNP", "Lymph Node Puncture"),
                    ("PARASIT", "Confirmation parasytologique"),
                    ("RESEARCH_PL", "PL de recherche"),
                ],
                default="PG",
            ),
        ),
    ]
