# Generated by Django 2.1.11 on 2020-04-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0028_test_remove_note_add_research_pl"),
    ]

    operations = [
        migrations.AddField(
            model_name="deviceimportevent",
            name="ptr_records",
            field=models.IntegerField(null=True),
        ),
    ]
