# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-08 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180108_0912'),
        ('geo', '0003_auto_20180106_0759'),
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignation',
            unique_together=set([('planning', 'village', 'team')]),
        ),
    ]
