# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-12 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_auto_20180108_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planning',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
