# Generated by Django 2.0 on 2018-07-18 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_increase_your_aliases_size'),
        ('geo', '0014_geo_sources'),
        ('planning', '0007_auto_20180424_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('AS', models.ManyToManyField(blank=True, to='geo.AS')),
                ('coordination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Coordination')),
            ],
        ),
        migrations.AlterField(
            model_name='planning',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workzone',
            name='planning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.Planning'),
        ),
        migrations.AddField(
            model_name='workzone',
            name='teams',
            field=models.ManyToManyField(to='users.Team'),
        ),
    ]
