# Generated by Django 2.0 on 2018-09-27 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0015_track_village_creator_device'),
        ('users', '0017_profile_password_reset'),
        ('planning', '0010_auto_20180912_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamActionZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.AS')),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.Planning')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Team')),
            ],
        ),
    ]
