# Generated by Django 2.0 on 2018-10-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0011_teamactionzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
    ]
