# Generated by Django 2.1.11 on 2020-03-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0023_auto_20190627_0847'),
        ('planning', '0012_planning_is_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignation',
            name='population_splitted',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='assignation',
            unique_together={('planning', 'village', 'month')},
        ),
    ]
