# Generated by Django 2.1.11 on 2020-04-08 09:58

import django.contrib.postgres.fields
import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0013_auto_20200330_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='years_coverage',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.citext.CITextField(blank=True, max_length=255), blank=True, null=True, size=100),
        ),
    ]
