# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HatCase',
            new_name='Case',
        ),
        migrations.AlterModelOptions(
            name='case',
            options={'permissions': (('import', 'Can import data'), ('export', 'Can export data'), ('export_full', 'Can export the full dataset as csv'), ('view', 'Can view data'))},
        ),
    ]
