# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-13 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_caseimports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseimports',
            name='case',
        ),
        migrations.DeleteModel(
            name='CaseImports',
        ),
    ]
