# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20160902_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='test_catt_total_blood',
        ),
        migrations.RemoveField(
            model_name='case',
            name='test_lcr_fr',
        ),
        migrations.RemoveField(
            model_name='case',
            name='test_lcr_scm',
        ),
        migrations.RemoveField(
            model_name='case',
            name='test_maec',
        ),
        migrations.RemoveField(
            model_name='case',
            name='test_maect_bc',
        ),
        migrations.RemoveField(
            model_name='case',
            name='test_woo',
        ),
        migrations.AlterField(
            model_name='case',
            name='treatment_result',
            field=models.TextField(null=True),
        ),
    ]
