# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-22 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_testgroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testgroup',
            old_name='case_id',
            new_name='group_id',
        ),
    ]
