# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_auto_20161005_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ZS', models.TextField(db_index=True, null=True)),
                ('AS', models.TextField(db_index=True, null=True)),
                ('AS_alt', models.TextField(db_index=True, null=True)),
                ('village', models.TextField(db_index=True, null=True)),
                ('village_alt', models.TextField(db_index=True, null=True)),
                ('village_type', models.TextField(null=True)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, null=True)),
                ('population', models.PositiveIntegerField(null=True)),
            ],
            options={
                'permissions': (('import_locations', 'Can import location data'),),
            },
        ),
    ]
