# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-05 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_auto_20171222_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='case',
            name='document_date',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='Date document'),
        ),
        migrations.AlterField(
            model_name='case',
            name='entry_date',
            field=models.DateTimeField(null=True, verbose_name='Date de collection'),
        ),
        migrations.AlterField(
            model_name='case',
            name='entry_name',
            field=models.TextField(null=True, verbose_name="Nom d'entrée"),
        ),
        migrations.AlterField(
            model_name='case',
            name='followup_done',
            field=models.NullBooleanField(verbose_name='Suivi effectué'),
        ),
        migrations.AlterField(
            model_name='case',
            name='form_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mois du formulaire'),
        ),
        migrations.AlterField(
            model_name='case',
            name='form_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Numéro de formulaire'),
        ),
        migrations.AlterField(
            model_name='case',
            name='form_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Année du formulaire'),
        ),
        migrations.AlterField(
            model_name='case',
            name='lastname',
            field=models.TextField(null=True, verbose_name='Nom de famille'),
        ),
        migrations.AlterField(
            model_name='case',
            name='mothers_surname',
            field=models.TextField(null=True, verbose_name='Nom de la mère'),
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.TextField(null=True, verbose_name='Postnom'),
        ),
        migrations.AlterField(
            model_name='case',
            name='prename',
            field=models.TextField(null=True, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='case',
            name='sex',
            field=models.TextField(choices=[('female', 'Femme'), ('male', 'Homme')], null=True, verbose_name='Sexe'),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_catt',
            field=models.IntegerField(blank=True, null=True, verbose_name='Test CATT'),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_catt_dilution',
            field=models.TextField(blank=True, null=True, verbose_name='Dilution CATT'),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_clinical_sickness',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maladie clinique'),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_ctcwoo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_dil',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_followup_decision',
            field=models.TextField(blank=True, null=True, verbose_name='Suivi décision'),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_followup_ge',
            field=models.TextField(blank=True, null=True, verbose_name='Suivi GE'),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_followup_maect',
            field=models.TextField(blank=True, null=True, verbose_name='Suivi MAECT'),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_followup_pg',
            field=models.TextField(blank=True, null=True, verbose_name='Suivi PG'),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_followup_pl',
            field=models.TextField(blank=True, null=True, verbose_name='Suivi PL'),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_followup_pl_gb',
            field=models.TextField(blank=True, null=True, verbose_name='Suivi PL GB'),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_followup_pl_trypanosome',
            field=models.TextField(blank=True, null=True, verbose_name='Suivi PL trypanosome'),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_followup_sf',
            field=models.TextField(blank=True, null=True, verbose_name='Suivi SF'),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_followup_woo',
            field=models.TextField(blank=True, null=True, verbose_name='Suivi WOO'),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_followup_woo_maect',
            field=models.TextField(blank=True, null=True, verbose_name='Suivi WOO MAECT'),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_ge',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_ifat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_lcr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_lymph_node_puncture',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ponction Ganglions'),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_maect',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_other',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_parasit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_pg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_pl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_pl_albumine',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_pl_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire Ponction Lombaire'),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_pl_gb_mm3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_pl_lcr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_pl_liquid',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_pl_result',
            field=models.TextField(blank=True, choices=[('stage1', 'Stage1'), ('stage2', 'Stage2'), ('unknown', 'Inconnu')], null=True, verbose_name='Résultat de test PL'),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_pl_trypanosome',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_rdt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_sf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_sternal_puncture',
            field=models.IntegerField(blank=True, null=True, verbose_name='Test Ponction Sternale'),
        ),
        migrations.AlterField(
            model_name='case',
            name='treatment_center',
            field=models.TextField(blank=True, null=True, verbose_name='Centre de traitement'),
        ),
        migrations.AlterField(
            model_name='case',
            name='treatment_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin de traitement'),
        ),
        migrations.AlterField(
            model_name='case',
            name='treatment_prescribed',
            field=models.TextField(blank=True, null=True, verbose_name='Prescription'),
        ),
        migrations.AlterField(
            model_name='case',
            name='treatment_result',
            field=models.TextField(blank=True, null=True, verbose_name='Résultat'),
        ),
        migrations.AlterField(
            model_name='case',
            name='treatment_secondary_effects',
            field=models.NullBooleanField(verbose_name='Effets Secondaires'),
        ),
        migrations.AlterField(
            model_name='case',
            name='treatment_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Début de traitement'),
        ),
        migrations.AlterField(
            model_name='case',
            name='year_of_birth',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Année de naissance'),
        ),
    ]
