# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-29 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_auto_20161121_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='classification',
            field=models.TextField(null=True),
        ),
    ]
