# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-09 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_case_normalized_village'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='confirmed_case',
            field=models.BooleanField(default=False, verbose_name='Cas confirmé'),
        ),
        migrations.AlterField(
            model_name='case',
            name='form_month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Aout'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], null=True, verbose_name='Mois du formulaire'),
        ),
        migrations.AlterField(
            model_name='case',
            name='form_year',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999)], null=True, verbose_name='Année du formulaire'),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_catt',
            field=models.IntegerField(blank=True, choices=[(2, 'Positif'), (1, 'Négatif'), (0, 'Absent'), (-1, 'Manquant')], null=True, verbose_name='Test CATT'),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_catt_dilution',
            field=models.TextField(blank=True, choices=[(2, 'Positif'), (1, 'Négatif'), (0, 'Absent'), (-1, 'Manquant')], null=True, verbose_name='Dilution CATT'),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_clinical_sickness',
            field=models.IntegerField(blank=True, choices=[(2, 'Positif'), (1, 'Négatif'), (0, 'Absent'), (-1, 'Manquant')], null=True, verbose_name='Maladie clinique'),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_ctcwoo',
            field=models.IntegerField(blank=True, choices=[(2, 'Positif'), (1, 'Négatif'), (0, 'Absent'), (-1, 'Manquant')], null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_dil',
            field=models.IntegerField(blank=True, choices=[(2, 'Positif'), (1, 'Négatif'), (0, 'Absent'), (-1, 'Manquant')], null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_ge',
            field=models.IntegerField(blank=True, choices=[(2, 'Positif'), (1, 'Négatif'), (0, 'Absent'), (-1, 'Manquant')], null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_ifat',
            field=models.IntegerField(blank=True, choices=[(2, 'Positif'), (1, 'Négatif'), (0, 'Absent'), (-1, 'Manquant')], null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_lcr',
            field=models.IntegerField(blank=True, choices=[(2, 'Positif'), (1, 'Négatif'), (0, 'Absent'), (-1, 'Manquant')], null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_lymph_node_puncture',
            field=models.IntegerField(blank=True, choices=[(2, 'Positif'), (1, 'Négatif'), (0, 'Absent'), (-1, 'Manquant')], null=True, verbose_name='Ponction Ganglions'),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_maect',
            field=models.IntegerField(blank=True, choices=[(2, 'Positif'), (1, 'Négatif'), (0, 'Absent'), (-1, 'Manquant')], null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_other',
            field=models.IntegerField(blank=True, choices=[(2, 'Positif'), (1, 'Négatif'), (0, 'Absent'), (-1, 'Manquant')], null=True, verbose_name='Autre test'),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_parasit',
            field=models.IntegerField(blank=True, choices=[(2, 'Positif'), (1, 'Négatif'), (0, 'Absent'), (-1, 'Manquant')], null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_pg',
            field=models.IntegerField(blank=True, choices=[(2, 'Positif'), (1, 'Négatif'), (0, 'Absent'), (-1, 'Manquant')], null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_pl',
            field=models.IntegerField(blank=True, choices=[(2, 'Positif'), (1, 'Négatif'), (0, 'Absent'), (-1, 'Manquant')], null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_rdt',
            field=models.IntegerField(blank=True, choices=[(2, 'Positif'), (1, 'Négatif'), (0, 'Absent'), (-1, 'Manquant')], null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_sf',
            field=models.IntegerField(blank=True, choices=[(2, 'Positif'), (1, 'Négatif'), (0, 'Absent'), (-1, 'Manquant')], null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_sternal_puncture',
            field=models.IntegerField(blank=True, choices=[(2, 'Positif'), (1, 'Négatif'), (0, 'Absent'), (-1, 'Manquant')], null=True, verbose_name='Test Ponction Sternale'),
        ),
    ]
