# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-12 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_auto_20180109_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['-id'], 'permissions': (('import', 'Can import data'), ('import_reconciled', 'Can import reconciliation data'), ('export', 'Can export anonymized cases data'), ('export_full', 'Can export non anonymized cases data'), ('view', 'Can view anonymized cases data'), ('view_full', 'Can view non anonymized cases data'))},
        ),
    ]
