# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_caseview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='source',
            field=models.TextField(choices=[('historic', 'Historic'), ('mobile_backup', 'Mobile backup'), ('pv', 'Pharmacovigilance')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='caseview',
            name='source',
            field=models.TextField(choices=[('historic', 'Historic'), ('mobile_backup', 'Mobile backup'), ('pv', 'Pharmacovigilance')], null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='village_official',
            field=models.TextField(choices=[('YES', 'Villages from Z.S.'), ('NO', 'Villages not from Z.S.'), ('OTHER', 'Locations in which people work/study...'), ('NA', 'Villages from satellite (unknown)')], null=True),
        ),
    ]
