# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_auto_20170124_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='AZ',
            new_name='AS',
        ),
        migrations.AddField(
            model_name='case',
            name='deleted',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='device_id',
            field=models.TextField(null=True),
        ),

        migrations.RenameField(
            model_name='caseview',
            old_name='AZ',
            new_name='AS',
        ),
    ]
