# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-29 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_auto_20180116_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='confirmed_case',
            field=models.NullBooleanField(default=False, verbose_name='Cas confirmé'),
        ),
    ]
