# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-05 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_auto_20180129_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='normalized_village_not_found',
            field=models.BooleanField(default=False),
        ),
    ]
