# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_auto_20170124_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicatesPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('reconcile_duplicates', 'Can reconcile duplicates'),),
            },
        ),
        migrations.AlterField(
            model_name='case',
            name='AS',
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='village',
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='duplicatespair',
            name='case1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cases.Case'),
        ),
        migrations.AddField(
            model_name='duplicatespair',
            name='case2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cases.Case'),
        ),
        migrations.AlterUniqueTogether(
            name='duplicatespair',
            unique_together=set([('case1', 'case2')]),
        ),
        migrations.RunSQL(
            sql = '''
            -- Load the postgres trigrams extension
            CREATE EXTENSION pg_trgm;
            -- Create trigram indexes for names
            CREATE INDEX cases_case_names_trgm_idx
            ON cases_case
            USING gin (
                name gin_trgm_ops,
                prename gin_trgm_ops,
                lastname gin_trgm_ops,
                mothers_surname gin_trgm_ops
            )''',
            reverse_sql = '''
            -- Disable extension
            DROP EXTENSION pg_trgm;
            -- Remove trigram indexes for names
            DROP INDEX cases_case_names_trgm_idx
            '''
        ),
    ]
