# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-07 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_case_normalized_village_not_found'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='normalized_village_not_found',
            field=models.NullBooleanField(default=False),
        ),
    ]
