# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_auto_20170125_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='duplicatespair',
            name='AS',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='duplicatespair',
            name='ZS',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='duplicatespair',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='duplicatespair',
            name='village',
            field=models.TextField(null=True),
        ),
    ]
