# Generated by Django 2.0 on 2018-03-07 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_location_already_put_in_normalized_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='normalized_village',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geo.Village'),
        ),
        migrations.AlterField(
            model_name='duplicatespair',
            name='case1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cases.Case'),
        ),
        migrations.AlterField(
            model_name='duplicatespair',
            name='case2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cases.Case'),
        ),
    ]
