# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0015_locations_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoredPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id1', models.TextField(db_index=True)),
                ('document_id2', models.TextField(db_index=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='duplicatespair',
            name='AS',
        ),
        migrations.RemoveField(
            model_name='duplicatespair',
            name='ZS',
        ),
        migrations.RemoveField(
            model_name='duplicatespair',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='duplicatespair',
            name='village',
        ),
        migrations.AddField(
            model_name='duplicatespair',
            name='document_id1',
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='duplicatespair',
            name='document_id2',
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='ignoredpair',
            unique_together=set([('document_id1', 'document_id2')]),
        ),
    ]
