# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-28 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_qctest_index'),
        ('cases', '0016_constraing_result_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='normalized_patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.Patient'),
        ),
    ]
