# Generated by Django 2.0 on 2018-04-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0017_normalized_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='test_catt_index',
            field=models.IntegerField(blank=True, null=True, verbose_name='CATT Card Index'),
        ),
        migrations.AddField(
            model_name='case',
            name='test_catt_picture_filename',
            field=models.TextField(blank=True, null=True, verbose_name='CATT picture filename'),
        ),
        migrations.AddField(
            model_name='case',
            name='test_catt_session_type',
            field=models.TextField(blank=True, choices=[('doorToDoor', 'Door to door'), ('onSite', 'On site')], null=True, verbose_name='CATT session type door to door or on site'),
        ),
        migrations.AddField(
            model_name='case',
            name='test_rdt_picture_filename',
            field=models.TextField(blank=True, null=True, verbose_name='RDT picture filename'),
        ),
        migrations.AddField(
            model_name='case',
            name='test_rdt_session_type',
            field=models.TextField(blank=True, choices=[('doorToDoor', 'Door to door'), ('onSite', 'On site')], null=True, verbose_name='RDT session type door to door or on site'),
        ),
    ]
