# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0017_auto_20170131_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='document_id',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='caseview',
            name='document_id',
            field=models.TextField(unique=True),
        ),
    ]
