# Generated by Django 2.0 on 2018-04-18 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0016_devicedb_user'),
        ('cases', '0018_test_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='json_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sync.JSONDocument'),
        ),
    ]
