# Generated by Django 2.0 on 2018-05-08 11:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('sync', '0016_devicedb_user'),
        ('cases', '0020_normalized_as'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='json_document',
        ),
    ]
