# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 18:30
from __future__ import unicode_literals

from django.db import migrations
from hat.queries import migration2 as migration


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0021_event_log'),
    ]

    operations = [
        migrations.RunSQL(migration.run()),
    ]
