# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0022_cases_file_event_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caseview',
            options={'managed': False, 'ordering': ['-document_date'], 'permissions': (('import', 'Can import data'), ('import_reconciled', 'Can import reconciliation data'), ('export', 'Can export anonymized cases data'), ('export_full', 'Can export non anonymized cases data'), ('view', 'Can view anonymized cases data'), ('view_full', 'Can view non anonymized cases data'))},
        ),
        migrations.AlterField(
            model_name='case',
            name='source',
            field=models.TextField(choices=[('historic', 'Historic'), ('mobile_backup', 'Mobile backup'), ('mobile_sync', 'Mobile synced'), ('pv', 'Pharmacovigilance')], null=True),
        ),
    ]
