# Generated by Django 2.0 on 2018-05-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0022_remove_corrected_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='test_ctcwoo_video_filename',
            field=models.TextField(blank=True, null=True, verbose_name='filename of CTCWOO test video'),
        ),
        migrations.AddField(
            model_name='case',
            name='test_maect_video_filename',
            field=models.TextField(blank=True, null=True, verbose_name='filename of mAECT test video'),
        ),
        migrations.AddField(
            model_name='case',
            name='test_pg_video_filename',
            field=models.TextField(blank=True, null=True, verbose_name='filename of PG test video'),
        ),
        migrations.AddField(
            model_name='case',
            name='test_pl_video_filename',
            field=models.TextField(blank=True, null=True, verbose_name='filename of PL test video'),
        ),
        migrations.AddField(
            model_name='case',
            name='test_pl_white_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
