# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0022_cases_file_event_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caseview',
            options={'managed': False, 'ordering': ['-document_date'], 'permissions': (('import', 'Can import data'), ('import_reconciled', 'Can import reconciliation data'), ('export', 'Can export anonymized cases data'), ('export_full', 'Can export non anonymized cases data'), ('view', 'Can view anonymized cases data'), ('view_full', 'Can view non anonymized cases data'))},
        ),
        migrations.AlterField(
            model_name='case',
            name='source',
            field=models.TextField(choices=[('historic', 'Historic'), ('mobile_backup', 'Mobile backup'), ('mobile_sync', 'Mobile synced'), ('pv', 'Pharmacovigilance')], null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_catt',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_clinical_sickness',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_ctcwoo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_dil',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_ge',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_ifat',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_lcr',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_lymph_node_puncture',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_maect',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_other',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_parasit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_pg',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_pl',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_rdt',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_sf',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_sternal_puncture',
            field=models.IntegerField(null=True),
        ),
    ]
