# Generated by Django 2.0 on 2018-05-30 15:07

from django.db import migrations, models
import django.db.models.deletion

# This field can be updated with this SQL query:
#
# UPDATE cases_case cc
# SET normalized_team_id=t.id
# FROM users_team t
# WHERE cc.mobile_unit ILIKE t.name
# OR cc.mobile_unit=ANY (t.aliases)
# AND cc.normalized_team_id is null;
#
# This query is not run here to avoid failing the production beanstalk deployment.

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_increase_your_aliases_size'),
        ('cases', '0023_video_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='normalized_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Team'),
        ),
    ]
