# Generated by Django 2.0 on 2018-06-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0024_normalized_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='circumstances_da',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='case',
            name='circumstances_da_um',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='circumstances_dp',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='case',
            name='circumstances_dp_cs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='circumstances_dp_hgr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='circumstances_dp_um',
            field=models.TextField(blank=True, null=True),
        ),
    ]
