# Generated by Django 2.0 on 2018-09-23 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0027_caseview_age_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caseview',
            options={'managed': False, 'permissions': (('import', 'Can import data'), ('import_reconciled', 'Can import reconciliation data'), ('export', 'Can export anonymized cases data'), ('export_full', 'Can export non anonymized cases data'), ('view', 'Can view anonymized cases data'), ('view_full', 'Can view non anonymized cases data'))},
        ),
    ]
