# Generated by Django 2.0 on 2018-10-11 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0028_caseview_location'),
    ]

    operations = [
        migrations.RunSQL(sql="update cases_case set test_pl_gb_mm3 = test_pl_white_count "
                              "where test_pl_gb_mm3 is null and test_pl_white_count is not null", reverse_sql=""),
        migrations.RemoveField(
            model_name='case',
            name='test_pl_white_count',
        ),
    ]
