# Generated by Django 2.0 on 2018-11-07 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0029_merge_white_cells_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='duplicatespair',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='duplicatespair',
            name='case1',
        ),
        migrations.RemoveField(
            model_name='duplicatespair',
            name='case2',
        ),
        migrations.DeleteModel(
            name='IgnoredPair',
        ),
        migrations.DeleteModel(
            name='DuplicatesPair',
        ),
    ]
