# Generated by Django 2.0 on 2019-01-08 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0031_auto_20190103_1648'),
    ]

    operations = [
        migrations.RunSQL(sql="""
            update cases_case
            set entry_date=document_date,
                document_date=entry_date
            where source in ('mobile_sync', 'mobile_backup')
            and document_date::date > entry_date::date;
        """, reverse_sql="")
    ]
