# Generated by Django 2.0 on 2019-03-24 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0032_fix_mobile_dates'),
    ]

    operations = [
        migrations.RunSQL(sql="update cases_case set year_of_birth=NULL where year_of_birth<1901", reverse_sql="")
    ]
