# Generated by Django 2.0 on 2019-04-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0033_birth_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='test_catt_level',
            field=models.IntegerField(blank=True, null=True, verbose_name='CATT positivity level'),
        ),
    ]
