# Generated by Django 2.0 on 2019-05-03 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0035_other_tests'),
    ]

    operations = [
        migrations.RunSQL(sql="""
            update cases_case cc
            set "normalized_AS_id"=v."AS_id"
            from geo_village v
            where v.id=cc.normalized_village_id
              and normalized_village_id is not null
              and "normalized_AS_id" is null;
        """, reverse_sql=""),
        migrations.RunSQL(sql="""
            update patient_patient pt
            set origin_area_id=cc."normalized_AS_id"
            from cases_case cc
            where cc."normalized_AS_id" is not null
            and pt.origin_area_id is null
            and pt.id=cc.normalized_patient_id;
        """, reverse_sql=""),
        migrations.RunSQL(sql="""
            update patient_patient pt
            set origin_village_id=cc."normalized_village_id"
            from cases_case cc
            where cc."normalized_village_id" is not null
            and pt.origin_village_id is null
            and pt.id=cc.normalized_patient_id
        """, reverse_sql=""),
    ]
