# Generated by Django 2.0 on 2019-05-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0036_update_as_from_village'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='circumstances_da',
        ),
        migrations.RemoveField(
            model_name='case',
            name='circumstances_dp',
        ),
        migrations.AddField(
            model_name='case',
            name='circumstances_dp_cdtc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='screening_type',
            field=models.TextField(blank=True, choices=[('active', 'Dépistage actif'), ('passive', 'Dépistage passif')],
                                   db_index=True, null=True),
        ),
    ]
