# Generated by Django 2.0 on 2019-07-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0037_depistage_passif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='test_catt',
            field=models.IntegerField(blank=True, choices=[(4, 'Positif +++'), (3, 'Positif ++'), (2, 'Positif'), (1, 'Négatif'), (0, 'Absent'), (-1, 'Manquant'), (-2, 'Illisible'), (-3, 'Invalide'), (-4, 'Pas certain')], null=True, verbose_name='Test CATT'),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_catt_dilution',
            field=models.TextField(blank=True, choices=[(4, 'Positif +++'), (3, 'Positif ++'), (2, 'Positif'), (1, 'Négatif'), (0, 'Absent'), (-1, 'Manquant'), (-2, 'Illisible'), (-3, 'Invalide'), (-4, 'Pas certain')], null=True, verbose_name='Dilution CATT'),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_clinical_sickness',
            field=models.IntegerField(blank=True, choices=[(4, 'Positif +++'), (3, 'Positif ++'), (2, 'Positif'), (1, 'Négatif'), (0, 'Absent'), (-1, 'Manquant'), (-2, 'Illisible'), (-3, 'Invalide'), (-4, 'Pas certain')], null=True, verbose_name='Maladie clinique'),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_ctcwoo',
            field=models.IntegerField(blank=True, choices=[(4, 'Positif +++'), (3, 'Positif ++'), (2, 'Positif'), (1, 'Négatif'), (0, 'Absent'), (-1, 'Manquant'), (-2, 'Illisible'), (-3, 'Invalide'), (-4, 'Pas certain')], null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_dil',
            field=models.IntegerField(blank=True, choices=[(4, 'Positif +++'), (3, 'Positif ++'), (2, 'Positif'), (1, 'Négatif'), (0, 'Absent'), (-1, 'Manquant'), (-2, 'Illisible'), (-3, 'Invalide'), (-4, 'Pas certain')], null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_ge',
            field=models.IntegerField(blank=True, choices=[(4, 'Positif +++'), (3, 'Positif ++'), (2, 'Positif'), (1, 'Négatif'), (0, 'Absent'), (-1, 'Manquant'), (-2, 'Illisible'), (-3, 'Invalide'), (-4, 'Pas certain')], null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_ifat',
            field=models.IntegerField(blank=True, choices=[(4, 'Positif +++'), (3, 'Positif ++'), (2, 'Positif'), (1, 'Négatif'), (0, 'Absent'), (-1, 'Manquant'), (-2, 'Illisible'), (-3, 'Invalide'), (-4, 'Pas certain')], null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_lcr',
            field=models.IntegerField(blank=True, choices=[(4, 'Positif +++'), (3, 'Positif ++'), (2, 'Positif'), (1, 'Négatif'), (0, 'Absent'), (-1, 'Manquant'), (-2, 'Illisible'), (-3, 'Invalide'), (-4, 'Pas certain')], null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_lymph_node_puncture',
            field=models.IntegerField(blank=True, choices=[(4, 'Positif +++'), (3, 'Positif ++'), (2, 'Positif'), (1, 'Négatif'), (0, 'Absent'), (-1, 'Manquant'), (-2, 'Illisible'), (-3, 'Invalide'), (-4, 'Pas certain')], null=True, verbose_name='Ponction Ganglions'),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_maect',
            field=models.IntegerField(blank=True, choices=[(4, 'Positif +++'), (3, 'Positif ++'), (2, 'Positif'), (1, 'Négatif'), (0, 'Absent'), (-1, 'Manquant'), (-2, 'Illisible'), (-3, 'Invalide'), (-4, 'Pas certain')], null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_other',
            field=models.IntegerField(blank=True, choices=[(4, 'Positif +++'), (3, 'Positif ++'), (2, 'Positif'), (1, 'Négatif'), (0, 'Absent'), (-1, 'Manquant'), (-2, 'Illisible'), (-3, 'Invalide'), (-4, 'Pas certain')], null=True, verbose_name='Autre test'),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_parasit',
            field=models.IntegerField(blank=True, choices=[(4, 'Positif +++'), (3, 'Positif ++'), (2, 'Positif'), (1, 'Négatif'), (0, 'Absent'), (-1, 'Manquant'), (-2, 'Illisible'), (-3, 'Invalide'), (-4, 'Pas certain')], null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_pg',
            field=models.IntegerField(blank=True, choices=[(4, 'Positif +++'), (3, 'Positif ++'), (2, 'Positif'), (1, 'Négatif'), (0, 'Absent'), (-1, 'Manquant'), (-2, 'Illisible'), (-3, 'Invalide'), (-4, 'Pas certain')], null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_pl',
            field=models.IntegerField(blank=True, choices=[(4, 'Positif +++'), (3, 'Positif ++'), (2, 'Positif'), (1, 'Négatif'), (0, 'Absent'), (-1, 'Manquant'), (-2, 'Illisible'), (-3, 'Invalide'), (-4, 'Pas certain')], null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_rdt',
            field=models.IntegerField(blank=True, choices=[(4, 'Positif +++'), (3, 'Positif ++'), (2, 'Positif'), (1, 'Négatif'), (0, 'Absent'), (-1, 'Manquant'), (-2, 'Illisible'), (-3, 'Invalide'), (-4, 'Pas certain')], null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_sf',
            field=models.IntegerField(blank=True, choices=[(4, 'Positif +++'), (3, 'Positif ++'), (2, 'Positif'), (1, 'Négatif'), (0, 'Absent'), (-1, 'Manquant'), (-2, 'Illisible'), (-3, 'Invalide'), (-4, 'Pas certain')], null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_sternal_puncture',
            field=models.IntegerField(blank=True, choices=[(4, 'Positif +++'), (3, 'Positif ++'), (2, 'Positif'), (1, 'Négatif'), (0, 'Absent'), (-1, 'Manquant'), (-2, 'Illisible'), (-3, 'Invalide'), (-4, 'Pas certain')], null=True, verbose_name='Test Ponction Sternale'),
        ),
    ]
