# Generated by Django 2.1.11 on 2019-10-17 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0023_auto_20190627_0847'),
        ('cases', '0038_unused_rename_invalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='infection_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infection_cases', to='geo.Village'),
        ),
        migrations.AddField(
            model_name='case',
            name='infection_location_type',
            field=models.TextField(blank=True, choices=[('ambiguous', "Lieu ambigu dans l'app mobile version 2.0.45"), ('residence', 'Lieu de résidence'), ('test', 'Lieu du test'), ('other', 'Autre')], null=True, verbose_name="Type d'endroit où l'infection a été rapportée"),
        ),
    ]
