# Generated by Django 2.1.11 on 2019-10-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0039_infection_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='latest_test_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunSQL(
            sql="update cases_case cc set latest_test_date=(select max(pt.date) from patient_test pt "
                "where pt.form_id=cc.id) where latest_test_date is null",
            reverse_sql=""
        ),
    ]
