# Generated by Django 2.1.11 on 2019-10-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cases", "0040_latest_test_date")]

    operations = [
        migrations.AddField(
            model_name="case",
            name="mark_for_deletion",
            field=models.BooleanField(
                default=False, verbose_name="Item is marked for deletion"
            ),
        )
    ]
