# Generated by Django 2.1.11 on 2019-11-18 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0041_delete'),
    ]

    operations = [
        migrations.RunSQL(sql="""
            update cases_case cc
            set test_pl_result='stage1'
            where test_pl_result is null and source in ('mobile_sync', 'mobile_backup')
            and test_pl_gb_mm3 is not null and test_pl_gb_mm3::float <= 5
                and (test_pl is null or test_pl < 2);
        """, reverse_sql=""),
        migrations.RunSQL(sql="""
            update cases_case cc
            set test_pl_result='stage2'
            where test_pl_result is null and source in ('mobile_sync', 'mobile_backup')
            and (
                    (test_pl_gb_mm3 is not null and test_pl_gb_mm3::float > 5)
                    or (test_pl >= 2)
                );
        """, reverse_sql=""),
    ]
