# Generated by Django 2.1.11 on 2020-01-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cases", "0042_pl_stage_step1")]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="form_year",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (2020, 2020),
                    (2019, 2019),
                    (2018, 2018),
                    (2017, 2017),
                    (2016, 2016),
                    (2015, 2015),
                    (2014, 2014),
                    (2013, 2013),
                    (2012, 2012),
                    (2011, 2011),
                    (2010, 2010),
                    (2009, 2009),
                    (2008, 2008),
                    (2007, 2007),
                    (2006, 2006),
                    (2005, 2005),
                    (2004, 2004),
                    (2003, 2003),
                    (2002, 2002),
                    (2001, 2001),
                ],
                null=True,
                verbose_name="Année du formulaire",
            ),
        )
    ]
