# Generated by Django 2.1.11 on 2020-04-21 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0044_allow_dupes_document_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="case", old_name="name", new_name="postname",
        ),
        migrations.RunSQL(
            sql="update cases_case set postname=lastname, lastname=postname where source in ('pv', 'historic')",
            reverse_sql="",  # We could run the same query to reverse it but if some new data arrived after the mig...
        ),
        migrations.RunSQL(
            sql="update patient_patient pp set post_name=cc.postname, last_name=cc.lastname "
            "from cases_case cc where cc.source in ('pv', 'historic') and cc.postname=pp.last_name "
            "and cc.lastname=pp.post_name and cc.normalized_patient_id=pp.id",
            reverse_sql="",  # We could run the same query to reverse it but if some new data arrived after the mig...
        ),
    ]
