# Generated by Django 2.1.11 on 2020-05-05 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0024_villages_merge"),
        ("cases", "0045_postname_mixup"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="infection_location_as",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="infection_cases",
                to="geo.AS",
            ),
        ),
        # These queries are really heavy and will be applied manually.
        # Christophe can add a "and confirmed_case=true" to the conditions to avoid overloading his docker DB :)
        # migrations.RunSQL(sql="""
        #     update cases_case cc
        #     set infection_location_as_id="normalized_AS_id"
        #     where infection_location_as_id is null and infection_location_type is null;
        #     update cases_case cc
        #     set infection_location_id="normalized_village_id"
        #     where infection_location_id is null and infection_location_type is null and normalized_village_id is not null;
        #     """, reverse_sql=""),
    ]
