# Generated by Django 2.1.11 on 2020-06-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0046_infection_location_as'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='user_type',
            field=models.TextField(blank=True, choices=[('UM', 'Unité mobile'), ('MUM', 'Mini unité mobile'), ('MUM_CONF', 'Mini unité mobile de confirmation'), ('CDTC', 'CDTC'), ('fixed_structure', 'Structure fixe')], null=True, verbose_name="Type d'utilisateur"),
        ),
    ]
