# Generated by Django 2.1.11 on 2020-06-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cases", "0047_case_user_type")]

    operations = [
        migrations.AddField(
            model_name="case",
            name="test_research_pl",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (4, "Positif +++"),
                    (3, "Positif ++"),
                    (2, "Positif"),
                    (1, "Négatif"),
                    (0, "Absent"),
                    (-1, "Manquant"),
                    (-2, "Illisible"),
                    (-3, "Invalide"),
                    (-4, "Pas certain"),
                ],
                null=True,
            ),
        ),
        # First update the negative results, then the positive so the positive take precedence
        migrations.RunSQL(
            sql="update cases_case cc set test_research_pl=1 from patient_test pt "
            "where pt.type='RESEARCH_PL' and pt.result=1 and pt.form_id=cc.id",
            reverse_sql="",
        ),
        migrations.RunSQL(
            sql="update cases_case cc set test_research_pl=2 from patient_test pt "
            "where pt.type='RESEARCH_PL' and pt.result=2 and pt.form_id=cc.id",
            reverse_sql="",
        ),
        # Update the confirmed_case flag
        migrations.RunSQL(
            sql="update cases_case cc set confirmed_case=true "
            "where test_pl=2 or test_research_pl=2 and confirmed_case=false",
            reverse_sql="",
        ),
    ]
