# Generated by Django 3.0.3 on 2020-06-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cases", "0048_research_pl_case")]

    operations = [
        migrations.AddField(
            model_name="case",
            name="test_ielisa",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (4, "Positif +++"),
                    (3, "Positif ++"),
                    (2, "Positif"),
                    (1, "Négatif"),
                    (0, "Absent"),
                    (-1, "Manquant"),
                    (-2, "Illisible"),
                    (-3, "Invalide"),
                    (-4, "Pas certain"),
                ],
                null=True,
            ),
        )
    ]
