/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Iaso
 * Iaso Swagger
 * OpenAPI spec version: v1
 */
import { z as zod } from 'zod';

export const MobilePlanning = zod
    .strictObject({
        id: zod.int(),
        name: zod.string(),
        description: zod.string(),
        created_at: zod.number(),
        started_at: zod.string(),
        ended_at: zod.string(),
        assignments: zod.string(),
    })
    .describe(
        'Serialize plannings for mobile and transforms missions into forms to stay backward compatible with older versions',
    );

export type MobilePlanning = zod.input<typeof MobilePlanning>;
export type MobilePlanningOutput = zod.output<typeof MobilePlanning>;
