/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Iaso
 * Iaso Swagger
 * OpenAPI spec version: v1
 */
import { z as zod } from 'zod';

export const PaginatedMobilePlanningList = zod.strictObject({
    count: zod.int().optional(),
    has_next: zod.boolean().optional(),
    has_previous: zod.boolean().optional(),
    limit: zod.int().optional(),
    page: zod.int().optional().describe('The current page number'),
    pages: zod.int().optional().describe('The total number of pages'),
    results: zod
        .array(
            zod
                .strictObject({
                    id: zod.int(),
                    name: zod.string(),
                    description: zod.string(),
                    created_at: zod.number(),
                    started_at: zod.string(),
                    ended_at: zod.string(),
                    assignments: zod.string(),
                })
                .describe(
                    'Serialize plannings for mobile and transforms missions into forms to stay backward compatible with older versions',
                ),
        )
        .optional(),
});

export type PaginatedMobilePlanningList = zod.input<
    typeof PaginatedMobilePlanningList
>;
export type PaginatedMobilePlanningListOutput = zod.output<
    typeof PaginatedMobilePlanningList
>;
