/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Iaso
 * Iaso Swagger
 * OpenAPI spec version: v1
 */
import { z as zod } from 'zod';

export const planningOrgUnitTableAssignmentOneTeamOneNameMax = 100;

export const planningOrgUnitTableAssignmentOneTeamOneColorMax = 7;

export const planningOrgUnitTableAssignmentOneTeamOneColorRegExp = new RegExp(
    '#[0-9A-Fa-f]{6}',
);
export const planningOrgUnitTableAssignmentOneUserOneUsernameMax = 150;

export const planningOrgUnitTableAssignmentOneUserOneUsernameRegExp =
    new RegExp('[\\w.@+-]+');
export const planningOrgUnitTableAssignmentOneUserOneFirstNameMax = 150;

export const planningOrgUnitTableAssignmentOneUserOneLastNameMax = 150;

export const PlanningOrgUnitTable = zod
    .strictObject({
        id: zod.int(),
        name: zod.string(),
        org_unit_type: zod.strictObject({
            id: zod.int(),
            name: zod.string(),
        }),
        assignment: zod.strictObject({
            id: zod.int(),
            team: zod
                .strictObject({
                    id: zod.int(),
                    name: zod
                        .string()
                        .max(planningOrgUnitTableAssignmentOneTeamOneNameMax),
                    color: zod
                        .string()
                        .max(planningOrgUnitTableAssignmentOneTeamOneColorMax)
                        .regex(
                            planningOrgUnitTableAssignmentOneTeamOneColorRegExp,
                        )
                        .optional(),
                })
                .nullable(),
            user: zod
                .strictObject({
                    id: zod.int(),
                    username: zod
                        .string()
                        .max(
                            planningOrgUnitTableAssignmentOneUserOneUsernameMax,
                        )
                        .regex(
                            planningOrgUnitTableAssignmentOneUserOneUsernameRegExp,
                        )
                        .describe(
                            'Required. 150 characters or fewer. Letters, digits and @\/.\/+\/-\/_ only.',
                        ),
                    first_name: zod
                        .string()
                        .max(
                            planningOrgUnitTableAssignmentOneUserOneFirstNameMax,
                        )
                        .optional(),
                    last_name: zod
                        .string()
                        .max(
                            planningOrgUnitTableAssignmentOneUserOneLastNameMax,
                        )
                        .optional(),
                    color: zod.string(),
                })
                .nullable(),
            assignment_type: zod
                .union([
                    zod
                        .enum(['team', 'user'])
                        .describe('\* `team` - team\n\* `user` - user'),
                    zod.literal(null),
                ])
                .nullable(),
        }),
    })
    .describe(
        'Paginated planning org units for tables (minimal columns + assignment for this planning).',
    );

export type PlanningOrgUnitTable = zod.input<typeof PlanningOrgUnitTable>;
export type PlanningOrgUnitTableOutput = zod.output<
    typeof PlanningOrgUnitTable
>;
