/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Iaso
 * Iaso Swagger
 * OpenAPI spec version: v1
 */
import { z as zod } from 'zod';

export const planningWriteRequestNameMax = 100;

export const PlanningWriteRequest = zod.strictObject({
    selected_sampling_result: zod.int().nullish(),
    pipeline_uuids: zod.array(zod.uuid()).optional(),
    name: zod.string().min(1).max(planningWriteRequestNameMax),
    description: zod.string().optional(),
    started_at: zod.iso.date().nullish(),
    ended_at: zod.iso.date().nullish(),
    published_at: zod.iso.datetime({ offset: true }).nullish(),
    project: zod.int(),
    team: zod.int(),
    org_unit: zod
        .int()
        .describe(
            'The root org unit of the planning used to scope the assignments org units',
        ),
    created_by: zod.int().nullish(),
    missions: zod.array(zod.int()).optional(),
    target_org_unit_types: zod
        .array(zod.int())
        .optional()
        .describe(
            'Org unit types that can receive assignments in this planning',
        ),
});

export type PlanningWriteRequest = zod.input<typeof PlanningWriteRequest>;
export type PlanningWriteRequestOutput = zod.output<
    typeof PlanningWriteRequest
>;
