/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Iaso
 * Iaso Swagger
 * OpenAPI spec version: v1
 */
import { z as zod } from 'zod';

export const PlanningMissionPolymorphicList = zod.union([
    zod.strictObject({
        mission_type: zod.enum(['FORM_FILLING']),
        id: zod.int(),
        name: zod.string(),
        forms_count: zod.int(),
        created_at: zod.iso.datetime({ offset: true }),
    }),
    zod.strictObject({
        mission_type: zod.enum(['ORG_UNIT_AND_FORM']),
        id: zod.int(),
        name: zod.string(),
        org_unit_type: zod.strictObject({
            id: zod.int(),
            name: zod.string(),
        }),
        forms_count: zod.int(),
        created_at: zod.iso.datetime({ offset: true }),
    }),
    zod.strictObject({
        mission_type: zod.enum(['ENTITY_AND_FORM']),
        id: zod.int(),
        name: zod.string(),
        entity_type: zod.strictObject({
            id: zod.int(),
            name: zod.string(),
        }),
        forms_count: zod.int(),
        created_at: zod.iso.datetime({ offset: true }),
    }),
]);

export type PlanningMissionPolymorphicList = zod.input<
    typeof PlanningMissionPolymorphicList
>;
export type PlanningMissionPolymorphicListOutput = zod.output<
    typeof PlanningMissionPolymorphicList
>;
