/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Iaso
 * Iaso Swagger
 * OpenAPI spec version: v1
 */
import { z as zod } from 'zod';

export const planningOrgUnitTableAssignmentTeamNameMax = 100;

export const planningOrgUnitTableAssignmentTeamColorMax = 7;

export const planningOrgUnitTableAssignmentTeamColorRegExp = new RegExp(
    '#[0-9A-Fa-f]{6}',
);

export const PlanningOrgUnitTableAssignmentTeam = zod.strictObject({
    id: zod.int(),
    name: zod.string().max(planningOrgUnitTableAssignmentTeamNameMax),
    color: zod
        .string()
        .max(planningOrgUnitTableAssignmentTeamColorMax)
        .regex(planningOrgUnitTableAssignmentTeamColorRegExp)
        .optional(),
});

export type PlanningOrgUnitTableAssignmentTeam = zod.input<
    typeof PlanningOrgUnitTableAssignmentTeam
>;
export type PlanningOrgUnitTableAssignmentTeamOutput = zod.output<
    typeof PlanningOrgUnitTableAssignmentTeam
>;
