# Generated by Django 2.0 on 2018-12-18 14:38

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vector_control", "0008_auto_20181218_1426"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIImport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RenameField(model_name="catch", old_name="location", new_name="endLocation"),
        migrations.RemoveField(model_name="catch", name="distance_to_targets"),
        migrations.RemoveField(model_name="catch", name="elev_change"),
        migrations.RemoveField(model_name="catch", name="elev_diff"),
        migrations.RemoveField(model_name="catch", name="in_out"),
        migrations.RemoveField(model_name="catch", name="near_intervention"),
        migrations.RemoveField(model_name="catch", name="operation"),
        migrations.RemoveField(model_name="catch", name="target_elev"),
        migrations.RemoveField(model_name="catch", name="trap_elev"),
        migrations.AddField(
            model_name="catch",
            name="endAccuracy",
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name="catch",
            name="endAltitude",
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name="catch",
            name="startAccuracy",
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name="catch",
            name="startAltitude",
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name="catch",
            name="startLocation",
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
