# Generated by Django 2.0 on 2018-12-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vector_control', '0013_auto_20181227_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
    ]
