# Generated by Django 2.0 on 2019-01-04 12:31

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("vector_control", "0014_auto_20190104_1112")]

    operations = [
        migrations.AlterField(
            model_name="catch",
            name="end_location",
            field=django.contrib.gis.db.models.fields.PointField(dim=3, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name="catch",
            name="start_location",
            field=django.contrib.gis.db.models.fields.PointField(dim=3, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name="site",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(dim=3, null=True, srid=4326),
        ),
    ]
