# Generated by Django 2.0 on 2019-02-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("vector_control", "0016_auto_20190109_1622")]

    operations = [
        migrations.AddField(
            model_name="catch",
            name="problem",
            field=models.TextField(blank=True, null=True),
        )
    ]
