# Generated by Django 2.0 on 2019-02-25 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("vector_control", "0018_auto_20190221_1811")]

    operations = [
        migrations.AlterField(
            model_name="apiimport",
            name="import_type",
            field=models.TextField(
                blank=True,
                choices=[("site", "Site"), ("catch", "Catch"), ("target", "Target")],
                max_length=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="target",
            name="api_import",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vector_control.APIImport",
            ),
        ),
        migrations.AlterField(
            model_name="target",
            name="deployment",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="target",
            name="external_index",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="target",
            name="full_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="target",
            name="gps",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="target",
            name="gps_import",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vector_control.GpsImport",
            ),
        ),
        migrations.AlterField(
            model_name="target",
            name="name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="target",
            name="river",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="target",
            name="uuid",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="target",
            name="village",
            field=models.TextField(blank=True, null=True),
        ),
    ]
