# Generated by Django 3.1.12 on 2021-06-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vector_control", "0031_auto_20200721_1125"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiimport",
            name="headers",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="apiimport",
            name="json_body",
            field=models.JSONField(),
        ),
    ]
