# Generated by Django 2.0 on 2018-03-16 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.TextField(null=True)),
                ('setup_date', models.DateTimeField(null=True)),
                ('collect_date', models.DateTimeField(null=True)),
                ('in_out', models.TextField(null=True)),
                ('male_count', models.IntegerField(default=0)),
                ('female_count', models.IntegerField(default=0)),
                ('unknown_count', models.IntegerField(default=0)),
                ('remarks', models.TextField(default=0)),
                ('distance_to_targets', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('near_intervention', models.CharField(max_length=100)),
                ('elev_change', models.IntegerField(null=True)),
                ('trap_elev', models.IntegerField(null=True)),
                ('elev_diff', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('zone', models.TextField(null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('habitat', models.CharField(max_length=255, null=True)),
                ('first_survey', models.CharField(max_length=255, null=True)),
                ('first_survey_date', models.DateTimeField(null=True)),
                ('count', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('deployment', models.IntegerField(null=True)),
                ('full_name', models.TextField(null=True)),
                ('gps', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('altitude', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('date_time', models.DateTimeField(null=True)),
                ('river', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='catch',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vector.Site'),
        ),
    ]
