# Generated by Django 2.0 on 2018-03-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vector', '0002_catch_target_elev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catch',
            name='female_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='catch',
            name='male_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='catch',
            name='remarks',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='catch',
            name='unknown_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
