# Generated by Django 2.0 on 2018-03-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vector', '0003_auto_20180316_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='gps',
            field=models.CharField(max_length=100),
        ),
    ]
