# Generated by Django 2.0 on 2018-11-20 16:11

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.citext
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vector', '0004_auto_20180319_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='GpsImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField()),
                ('file_date_time', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GpsWaypoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('elevation', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.citext.CITextField(blank=True, max_length=255), blank=True, null=True, size=20)),
                ('ignore', models.BooleanField(default=False)),
                ('gps_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vector.GpsImport')),
            ],
        ),
    ]
