from iaso.models import FeatureFlag


DEFAULT_PROJECT_FEATURE_FLAGS = [
    FeatureFlag.REQUIRE_AUTHENTICATION,
    FeatureFlag.MOBILE_SYNCHRONIZE_WITH_ZIP,
    FeatureFlag.TAKE_GPS_ON_FORM,
]

DEFAULT_ACCOUNT_FEATURE_FLAGS = [
    "SHOW_BENEFICIARY_TYPES_IN_LIST_MENU",
    "SHOW_LINK_INSTANCE_REFERENCE",
    "SHOW_HOME_ONLINE",
]
