/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Iaso
 * Iaso Swagger
 * OpenAPI spec version: v1
 */
import { z as zod } from 'zod';

export const apiMicroplanningMissionsUpdateBodyOneTwoNameMax = 200;

export const apiMicroplanningMissionsUpdateBodyOneTwoDescriptionMax = 500;

export const apiMicroplanningMissionsUpdateBodyOneTwoFormsItemMinCardinalityMin = 0;
export const apiMicroplanningMissionsUpdateBodyOneTwoFormsItemMinCardinalityMax = 2147483647;

export const apiMicroplanningMissionsUpdateBodyOneTwoFormsItemMaxCardinalityMin = 0;
export const apiMicroplanningMissionsUpdateBodyOneTwoFormsItemMaxCardinalityMax = 2147483647;

export const ApiMicroplanningMissionsUpdateBody = zod.strictObject({
    mission_type: zod.enum(['FORM_FILLING']),
    name: zod
        .string()
        .min(1)
        .max(apiMicroplanningMissionsUpdateBodyOneTwoNameMax),
    description: zod
        .string()
        .max(apiMicroplanningMissionsUpdateBodyOneTwoDescriptionMax)
        .optional(),
    forms: zod.array(
        zod.strictObject({
            form: zod.number(),
            min_cardinality: zod
                .number()
                .min(
                    apiMicroplanningMissionsUpdateBodyOneTwoFormsItemMinCardinalityMin,
                )
                .max(
                    apiMicroplanningMissionsUpdateBodyOneTwoFormsItemMinCardinalityMax,
                )
                .optional()
                .describe('Minimum number of times this form should be filled'),
            max_cardinality: zod
                .number()
                .min(
                    apiMicroplanningMissionsUpdateBodyOneTwoFormsItemMaxCardinalityMin,
                )
                .max(
                    apiMicroplanningMissionsUpdateBodyOneTwoFormsItemMaxCardinalityMax,
                )
                .nullish()
                .describe(
                    'Maximum number of times this form can be filled (null = unlimited)',
                ),
        }),
    ),
});

export type ApiMicroplanningMissionsUpdateBody = zod.input<
    typeof ApiMicroplanningMissionsUpdateBody
>;
export type ApiMicroplanningMissionsUpdateBodyOutput = zod.output<
    typeof ApiMicroplanningMissionsUpdateBody
>;
