/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Iaso
 * Iaso Swagger
 * OpenAPI spec version: v1
 */
import { z as zod } from 'zod';

export const missionEntityTypeUpdateTypedTwoNameMax = 200;

export const missionEntityTypeUpdateTypedTwoDescriptionMax = 500;

export const MissionEntityTypeUpdateTyped = zod.strictObject({
    mission_type: zod.enum(['ENTITY_AND_FORM']),
    name: zod.string().max(missionEntityTypeUpdateTypedTwoNameMax),
    description: zod
        .string()
        .max(missionEntityTypeUpdateTypedTwoDescriptionMax)
        .optional(),
});

export type MissionEntityTypeUpdateTyped = zod.input<
    typeof MissionEntityTypeUpdateTyped
>;
export type MissionEntityTypeUpdateTypedOutput = zod.output<
    typeof MissionEntityTypeUpdateTyped
>;
