/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Iaso
 * Iaso Swagger
 * OpenAPI spec version: v1
 */
import { z as zod } from 'zod';

export const missionFormCreateRequestNameMax = 200;

export const missionFormCreateRequestDescriptionMax = 500;

export const missionFormCreateRequestFormsItemMinCardinalityDefault = 0;
export const missionFormCreateRequestFormsItemMinCardinalityMin = 0;
export const missionFormCreateRequestFormsItemMinCardinalityMax = 2147483647;

export const missionFormCreateRequestFormsItemMaxCardinalityMin = 0;
export const missionFormCreateRequestFormsItemMaxCardinalityMax = 2147483647;

export const MissionFormCreateRequest = zod.strictObject({
    name: zod.string().min(1).max(missionFormCreateRequestNameMax),
    description: zod
        .string()
        .max(missionFormCreateRequestDescriptionMax)
        .optional(),
    forms: zod.array(
        zod.strictObject({
            form: zod.number(),
            min_cardinality: zod
                .number()
                .min(missionFormCreateRequestFormsItemMinCardinalityMin)
                .max(missionFormCreateRequestFormsItemMinCardinalityMax)
                .default(missionFormCreateRequestFormsItemMinCardinalityDefault)
                .describe('Minimum number of times this form should be filled'),
            max_cardinality: zod
                .number()
                .min(missionFormCreateRequestFormsItemMaxCardinalityMin)
                .max(missionFormCreateRequestFormsItemMaxCardinalityMax)
                .nullish()
                .describe(
                    'Maximum number of times this form can be filled (null = unlimited)',
                ),
        }),
    ),
    mission_type: zod
        .enum(['FORM_FILLING', 'ORG_UNIT_AND_FORM', 'ENTITY_AND_FORM'])
        .describe(
            '\* `FORM_FILLING` - Form Filling\n\* `ORG_UNIT_AND_FORM` - Org Unit and Form\n\* `ENTITY_AND_FORM` - Entity and Form',
        ),
});

export type MissionFormCreateRequest = zod.input<
    typeof MissionFormCreateRequest
>;
export type MissionFormCreateRequestOutput = zod.output<
    typeof MissionFormCreateRequest
>;
