/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Iaso
 * Iaso Swagger
 * OpenAPI spec version: v1
 */
import { z as zod } from 'zod';

export const MissionOrgUnitTypeCreateMissionTypeEnum = zod
    .enum(['ORG_UNIT_AND_FORM'])
    .describe('\* `ORG_UNIT_AND_FORM` - ORG_UNIT_AND_FORM');

export type MissionOrgUnitTypeCreateMissionTypeEnum = zod.input<
    typeof MissionOrgUnitTypeCreateMissionTypeEnum
>;
export type MissionOrgUnitTypeCreateMissionTypeEnumOutput = zod.output<
    typeof MissionOrgUnitTypeCreateMissionTypeEnum
>;
