/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Iaso
 * Iaso Swagger
 * OpenAPI spec version: v1
 */
import { z as zod } from 'zod';

export const missionEntityTypeCreateTypedTwoNameMax = 200;

export const missionEntityTypeCreateTypedTwoDescriptionMax = 500;

export const MissionEntityTypeCreateTyped = zod.strictObject({
    mission_type: zod.enum(['ENTITY_AND_FORM']),
    id: zod.number(),
    name: zod.string().max(missionEntityTypeCreateTypedTwoNameMax),
    description: zod
        .string()
        .max(missionEntityTypeCreateTypedTwoDescriptionMax)
        .optional(),
});

export type MissionEntityTypeCreateTyped = zod.input<
    typeof MissionEntityTypeCreateTyped
>;
export type MissionEntityTypeCreateTypedOutput = zod.output<
    typeof MissionEntityTypeCreateTyped
>;
