/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Iaso
 * Iaso Swagger
 * OpenAPI spec version: v1
 */
import { z as zod } from 'zod';

export const missionEntityTypeCreateTypedRequestTwoNameMax = 200;

export const missionEntityTypeCreateTypedRequestTwoDescriptionMax = 500;

export const missionEntityTypeCreateTypedRequestTwoFormsItemMinCardinalityMin = 0;
export const missionEntityTypeCreateTypedRequestTwoFormsItemMinCardinalityMax = 2147483647;

export const missionEntityTypeCreateTypedRequestTwoFormsItemMaxCardinalityMin = 0;
export const missionEntityTypeCreateTypedRequestTwoFormsItemMaxCardinalityMax = 2147483647;

export const missionEntityTypeCreateTypedRequestTwoMinCardinalityMin = 0;
export const missionEntityTypeCreateTypedRequestTwoMinCardinalityMax = 2147483647;

export const missionEntityTypeCreateTypedRequestTwoMaxCardinalityMin = 0;
export const missionEntityTypeCreateTypedRequestTwoMaxCardinalityMax = 2147483647;

export const MissionEntityTypeCreateTypedRequest = zod.strictObject({
    mission_type: zod.enum(['ENTITY_AND_FORM']),
    name: zod
        .string()
        .min(1)
        .max(missionEntityTypeCreateTypedRequestTwoNameMax),
    description: zod
        .string()
        .max(missionEntityTypeCreateTypedRequestTwoDescriptionMax)
        .optional(),
    entity_type: zod.number(),
    forms: zod
        .array(
            zod.strictObject({
                form: zod.number(),
                min_cardinality: zod
                    .number()
                    .min(
                        missionEntityTypeCreateTypedRequestTwoFormsItemMinCardinalityMin,
                    )
                    .max(
                        missionEntityTypeCreateTypedRequestTwoFormsItemMinCardinalityMax,
                    )
                    .describe(
                        'Minimum number of times this form should be filled',
                    ),
                max_cardinality: zod
                    .number()
                    .min(
                        missionEntityTypeCreateTypedRequestTwoFormsItemMaxCardinalityMin,
                    )
                    .max(
                        missionEntityTypeCreateTypedRequestTwoFormsItemMaxCardinalityMax,
                    )
                    .nullish()
                    .describe(
                        'Maximum number of times this form can be filled (null = unlimited)',
                    ),
            }),
        )
        .min(1),
    min_cardinality: zod
        .number()
        .min(missionEntityTypeCreateTypedRequestTwoMinCardinalityMin)
        .max(missionEntityTypeCreateTypedRequestTwoMinCardinalityMax)
        .describe('Minimum number of times this form should be filled'),
    max_cardinality: zod
        .number()
        .min(missionEntityTypeCreateTypedRequestTwoMaxCardinalityMin)
        .max(missionEntityTypeCreateTypedRequestTwoMaxCardinalityMax)
        .nullish()
        .describe(
            'Maximum number of times this form can be filled (null = unlimited)',
        ),
});

export type MissionEntityTypeCreateTypedRequest = zod.input<
    typeof MissionEntityTypeCreateTypedRequest
>;
export type MissionEntityTypeCreateTypedRequestOutput = zod.output<
    typeof MissionEntityTypeCreateTypedRequest
>;
