/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Iaso
 * Iaso Swagger
 * OpenAPI spec version: v1
 */
import { z as zod } from 'zod';

export const missionOrgUnitTypeCreateTypedRequestTwoNameMax = 200;

export const missionOrgUnitTypeCreateTypedRequestTwoDescriptionMax = 500;

export const missionOrgUnitTypeCreateTypedRequestTwoFormsItemMinCardinalityMin = 0;
export const missionOrgUnitTypeCreateTypedRequestTwoFormsItemMinCardinalityMax = 2147483647;

export const missionOrgUnitTypeCreateTypedRequestTwoFormsItemMaxCardinalityMin = 0;
export const missionOrgUnitTypeCreateTypedRequestTwoFormsItemMaxCardinalityMax = 2147483647;

export const missionOrgUnitTypeCreateTypedRequestTwoMinCardinalityMin = 0;
export const missionOrgUnitTypeCreateTypedRequestTwoMinCardinalityMax = 2147483647;

export const missionOrgUnitTypeCreateTypedRequestTwoMaxCardinalityMin = 0;
export const missionOrgUnitTypeCreateTypedRequestTwoMaxCardinalityMax = 2147483647;

export const MissionOrgUnitTypeCreateTypedRequest = zod.strictObject({
    mission_type: zod.enum(['ORG_UNIT_AND_FORM']),
    name: zod
        .string()
        .min(1)
        .max(missionOrgUnitTypeCreateTypedRequestTwoNameMax),
    description: zod
        .string()
        .max(missionOrgUnitTypeCreateTypedRequestTwoDescriptionMax)
        .optional(),
    org_unit_type: zod.number(),
    forms: zod
        .array(
            zod.strictObject({
                form: zod.number(),
                min_cardinality: zod
                    .number()
                    .min(
                        missionOrgUnitTypeCreateTypedRequestTwoFormsItemMinCardinalityMin,
                    )
                    .max(
                        missionOrgUnitTypeCreateTypedRequestTwoFormsItemMinCardinalityMax,
                    )
                    .describe(
                        'Minimum number of times this form should be filled',
                    ),
                max_cardinality: zod
                    .number()
                    .min(
                        missionOrgUnitTypeCreateTypedRequestTwoFormsItemMaxCardinalityMin,
                    )
                    .max(
                        missionOrgUnitTypeCreateTypedRequestTwoFormsItemMaxCardinalityMax,
                    )
                    .nullish()
                    .describe(
                        'Maximum number of times this form can be filled (null = unlimited)',
                    ),
            }),
        )
        .min(1),
    min_cardinality: zod
        .number()
        .min(missionOrgUnitTypeCreateTypedRequestTwoMinCardinalityMin)
        .max(missionOrgUnitTypeCreateTypedRequestTwoMinCardinalityMax)
        .describe('Minimum number of times this form should be filled'),
    max_cardinality: zod
        .number()
        .min(missionOrgUnitTypeCreateTypedRequestTwoMaxCardinalityMin)
        .max(missionOrgUnitTypeCreateTypedRequestTwoMaxCardinalityMax)
        .nullish()
        .describe(
            'Maximum number of times this form can be filled (null = unlimited)',
        ),
});

export type MissionOrgUnitTypeCreateTypedRequest = zod.input<
    typeof MissionOrgUnitTypeCreateTypedRequest
>;
export type MissionOrgUnitTypeCreateTypedRequestOutput = zod.output<
    typeof MissionOrgUnitTypeCreateTypedRequest
>;
