/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Iaso
 * Iaso Swagger
 * OpenAPI spec version: v1
 */
import { z as zod } from 'zod';

export const MissionOrgUnitTypeUpdateTyped = zod.strictObject({
    mission_type: zod.enum(['ORG_UNIT_AND_FORM']),
});

export type MissionOrgUnitTypeUpdateTyped = zod.input<
    typeof MissionOrgUnitTypeUpdateTyped
>;
export type MissionOrgUnitTypeUpdateTypedOutput = zod.output<
    typeof MissionOrgUnitTypeUpdateTyped
>;
