/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Iaso
 * Iaso Swagger
 * OpenAPI spec version: v1
 */
import { z as zod } from 'zod';

export const MissionDropdown = zod.strictObject({
    label: zod.string(),
    value: zod.number(),
});

export type MissionDropdown = zod.input<typeof MissionDropdown>;
export type MissionDropdownOutput = zod.output<typeof MissionDropdown>;
