/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Iaso
 * Iaso Swagger
 * OpenAPI spec version: v1
 */
import { z as zod } from 'zod';

export const MissionPolymorphicCreate = zod.union([
    zod.strictObject({
        mission_type: zod.enum(['FORM_FILLING']),
        id: zod.int(),
    }),
    zod.strictObject({
        mission_type: zod.enum(['ORG_UNIT_AND_FORM']),
        id: zod.int(),
    }),
    zod.strictObject({
        mission_type: zod.enum(['ENTITY_AND_FORM']),
        id: zod.int(),
    }),
]);

export type MissionPolymorphicCreate = zod.input<
    typeof MissionPolymorphicCreate
>;
export type MissionPolymorphicCreateOutput = zod.output<
    typeof MissionPolymorphicCreate
>;
