/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Iaso
 * Iaso Swagger
 * OpenAPI spec version: v1
 */
import { z as zod } from 'zod';

export const MissionOrgUnitTypeRetrieveTyped = zod.strictObject({
    mission_type: zod.enum(['ORG_UNIT_AND_FORM']),
    id: zod.number(),
    name: zod.string(),
    description: zod.string(),
    created_at: zod.iso.datetime({ offset: true }),
    org_unit_type: zod.strictObject({
        id: zod.number(),
        name: zod.string(),
    }),
    forms: zod.array(
        zod.strictObject({
            form: zod.number(),
            form_name: zod.string(),
            min_cardinality: zod
                .number()
                .describe('Minimum number of times this form should be filled'),
            max_cardinality: zod
                .number()
                .nullable()
                .describe(
                    'Maximum number of times this form can be filled (null = unlimited)',
                ),
        }),
    ),
    min_cardinality: zod
        .number()
        .describe('Minimum number of times this form should be filled'),
    max_cardinality: zod
        .number()
        .nullable()
        .describe(
            'Maximum number of times this form can be filled (null = unlimited)',
        ),
});

export type MissionOrgUnitTypeRetrieveTyped = zod.input<
    typeof MissionOrgUnitTypeRetrieveTyped
>;
export type MissionOrgUnitTypeRetrieveTypedOutput = zod.output<
    typeof MissionOrgUnitTypeRetrieveTyped
>;
