/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Iaso
 * Iaso Swagger
 * OpenAPI spec version: v1
 */
import { z as zod } from 'zod';

export const MissionType = zod.strictObject({
    value: zod
        .enum(['FORM_FILLING', 'ORG_UNIT_AND_FORM', 'ENTITY_AND_FORM'])
        .describe(
            '\* `FORM_FILLING` - FORM_FILLING\n\* `ORG_UNIT_AND_FORM` - ORG_UNIT_AND_FORM\n\* `ENTITY_AND_FORM` - ENTITY_AND_FORM',
        ),
    label: zod.string(),
});

export type MissionType = zod.input<typeof MissionType>;
export type MissionTypeOutput = zod.output<typeof MissionType>;
