/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Iaso
 * Iaso Swagger
 * OpenAPI spec version: v1
 */
import { z as zod } from 'zod';

export const missionFormCreateTypedRequestTwoNameMax = 200;

export const missionFormCreateTypedRequestTwoDescriptionMax = 500;

export const missionFormCreateTypedRequestTwoFormsItemMinCardinalityMin = 0;
export const missionFormCreateTypedRequestTwoFormsItemMinCardinalityMax = 2147483647;

export const missionFormCreateTypedRequestTwoFormsItemMaxCardinalityMin = 0;
export const missionFormCreateTypedRequestTwoFormsItemMaxCardinalityMax = 2147483647;

export const MissionFormCreateTypedRequest = zod.strictObject({
    mission_type: zod.enum(['FORM_FILLING']),
    name: zod.string().min(1).max(missionFormCreateTypedRequestTwoNameMax),
    description: zod
        .string()
        .max(missionFormCreateTypedRequestTwoDescriptionMax)
        .optional(),
    forms: zod
        .array(
            zod.strictObject({
                form: zod.number(),
                min_cardinality: zod
                    .number()
                    .min(
                        missionFormCreateTypedRequestTwoFormsItemMinCardinalityMin,
                    )
                    .max(
                        missionFormCreateTypedRequestTwoFormsItemMinCardinalityMax,
                    )
                    .describe(
                        'Minimum number of times this form should be filled',
                    ),
                max_cardinality: zod
                    .number()
                    .min(
                        missionFormCreateTypedRequestTwoFormsItemMaxCardinalityMin,
                    )
                    .max(
                        missionFormCreateTypedRequestTwoFormsItemMaxCardinalityMax,
                    )
                    .nullish()
                    .describe(
                        'Maximum number of times this form can be filled (null = unlimited)',
                    ),
            }),
        )
        .min(1),
});

export type MissionFormCreateTypedRequest = zod.input<
    typeof MissionFormCreateTypedRequest
>;
export type MissionFormCreateTypedRequestOutput = zod.output<
    typeof MissionFormCreateTypedRequest
>;
