/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Iaso
 * Iaso Swagger
 * OpenAPI spec version: v1
 */
import { z as zod } from 'zod';

export const patchedMissionEntityTypeUpdateTypedRequestTwoNameMax = 200;

export const patchedMissionEntityTypeUpdateTypedRequestTwoDescriptionMax = 500;

export const patchedMissionEntityTypeUpdateTypedRequestTwoFormsItemMinCardinalityMin = 0;
export const patchedMissionEntityTypeUpdateTypedRequestTwoFormsItemMinCardinalityMax = 2147483647;

export const patchedMissionEntityTypeUpdateTypedRequestTwoFormsItemMaxCardinalityMin = 0;
export const patchedMissionEntityTypeUpdateTypedRequestTwoFormsItemMaxCardinalityMax = 2147483647;

export const patchedMissionEntityTypeUpdateTypedRequestTwoMinCardinalityMin = 0;
export const patchedMissionEntityTypeUpdateTypedRequestTwoMinCardinalityMax = 2147483647;

export const patchedMissionEntityTypeUpdateTypedRequestTwoMaxCardinalityMin = 0;
export const patchedMissionEntityTypeUpdateTypedRequestTwoMaxCardinalityMax = 2147483647;

export const PatchedMissionEntityTypeUpdateTypedRequest = zod.strictObject({
    mission_type: zod.enum(['ENTITY_AND_FORM']),
    name: zod
        .string()
        .min(1)
        .max(patchedMissionEntityTypeUpdateTypedRequestTwoNameMax)
        .optional(),
    description: zod
        .string()
        .max(patchedMissionEntityTypeUpdateTypedRequestTwoDescriptionMax)
        .optional(),
    entity_type: zod.int().optional(),
    forms: zod
        .array(
            zod.strictObject({
                form: zod.int(),
                min_cardinality: zod
                    .int()
                    .min(
                        patchedMissionEntityTypeUpdateTypedRequestTwoFormsItemMinCardinalityMin,
                    )
                    .max(
                        patchedMissionEntityTypeUpdateTypedRequestTwoFormsItemMinCardinalityMax,
                    )
                    .describe(
                        'Minimum number of times this form should be filled',
                    ),
                max_cardinality: zod
                    .int()
                    .min(
                        patchedMissionEntityTypeUpdateTypedRequestTwoFormsItemMaxCardinalityMin,
                    )
                    .max(
                        patchedMissionEntityTypeUpdateTypedRequestTwoFormsItemMaxCardinalityMax,
                    )
                    .nullish()
                    .describe(
                        'Maximum number of times this form can be filled (null = unlimited)',
                    ),
            }),
        )
        .min(1)
        .optional(),
    min_cardinality: zod
        .int()
        .min(patchedMissionEntityTypeUpdateTypedRequestTwoMinCardinalityMin)
        .max(patchedMissionEntityTypeUpdateTypedRequestTwoMinCardinalityMax)
        .optional()
        .describe('Minimum number of times this form should be filled'),
    max_cardinality: zod
        .int()
        .min(patchedMissionEntityTypeUpdateTypedRequestTwoMaxCardinalityMin)
        .max(patchedMissionEntityTypeUpdateTypedRequestTwoMaxCardinalityMax)
        .nullish()
        .describe(
            'Maximum number of times this form can be filled (null = unlimited)',
        ),
});

export type PatchedMissionEntityTypeUpdateTypedRequest = zod.input<
    typeof PatchedMissionEntityTypeUpdateTypedRequest
>;
export type PatchedMissionEntityTypeUpdateTypedRequestOutput = zod.output<
    typeof PatchedMissionEntityTypeUpdateTypedRequest
>;
