/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Iaso
 * Iaso Swagger
 * OpenAPI spec version: v1
 */
import { z as zod } from 'zod';

export const patchedMissionOrgUnitTypeUpdateRequestNameMax = 200;

export const patchedMissionOrgUnitTypeUpdateRequestDescriptionMax = 500;

export const patchedMissionOrgUnitTypeUpdateRequestFormsItemMinCardinalityMin = 0;
export const patchedMissionOrgUnitTypeUpdateRequestFormsItemMinCardinalityMax = 2147483647;

export const patchedMissionOrgUnitTypeUpdateRequestFormsItemMaxCardinalityMin = 0;
export const patchedMissionOrgUnitTypeUpdateRequestFormsItemMaxCardinalityMax = 2147483647;

export const patchedMissionOrgUnitTypeUpdateRequestMinCardinalityMin = 0;
export const patchedMissionOrgUnitTypeUpdateRequestMinCardinalityMax = 2147483647;

export const patchedMissionOrgUnitTypeUpdateRequestMaxCardinalityMin = 0;
export const patchedMissionOrgUnitTypeUpdateRequestMaxCardinalityMax = 2147483647;

export const PatchedMissionOrgUnitTypeUpdateRequest = zod.strictObject({
    name: zod
        .string()
        .min(1)
        .max(patchedMissionOrgUnitTypeUpdateRequestNameMax)
        .optional(),
    description: zod
        .string()
        .max(patchedMissionOrgUnitTypeUpdateRequestDescriptionMax)
        .optional(),
    org_unit_type: zod.number().optional(),
    forms: zod
        .array(
            zod.strictObject({
                form: zod.number(),
                min_cardinality: zod
                    .number()
                    .min(
                        patchedMissionOrgUnitTypeUpdateRequestFormsItemMinCardinalityMin,
                    )
                    .max(
                        patchedMissionOrgUnitTypeUpdateRequestFormsItemMinCardinalityMax,
                    )
                    .describe(
                        'Minimum number of times this form should be filled',
                    ),
                max_cardinality: zod
                    .number()
                    .min(
                        patchedMissionOrgUnitTypeUpdateRequestFormsItemMaxCardinalityMin,
                    )
                    .max(
                        patchedMissionOrgUnitTypeUpdateRequestFormsItemMaxCardinalityMax,
                    )
                    .nullish()
                    .describe(
                        'Maximum number of times this form can be filled (null = unlimited)',
                    ),
            }),
        )
        .min(1)
        .optional(),
    min_cardinality: zod
        .number()
        .min(patchedMissionOrgUnitTypeUpdateRequestMinCardinalityMin)
        .max(patchedMissionOrgUnitTypeUpdateRequestMinCardinalityMax)
        .optional()
        .describe('Minimum number of times this form should be filled'),
    max_cardinality: zod
        .number()
        .min(patchedMissionOrgUnitTypeUpdateRequestMaxCardinalityMin)
        .max(patchedMissionOrgUnitTypeUpdateRequestMaxCardinalityMax)
        .nullish()
        .describe(
            'Maximum number of times this form can be filled (null = unlimited)',
        ),
});

export type PatchedMissionOrgUnitTypeUpdateRequest = zod.input<
    typeof PatchedMissionOrgUnitTypeUpdateRequest
>;
export type PatchedMissionOrgUnitTypeUpdateRequestOutput = zod.output<
    typeof PatchedMissionOrgUnitTypeUpdateRequest
>;
