/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Iaso
 * Iaso Swagger
 * OpenAPI spec version: v1
 */
import { z as zod } from 'zod';

export const patchedMissionPolymorphicUpdateRequestOneTwoNameMax = 200;

export const patchedMissionPolymorphicUpdateRequestOneTwoDescriptionMax = 500;

export const patchedMissionPolymorphicUpdateRequestOneTwoFormsItemMinCardinalityMin = 0;
export const patchedMissionPolymorphicUpdateRequestOneTwoFormsItemMinCardinalityMax = 2147483647;

export const patchedMissionPolymorphicUpdateRequestOneTwoFormsItemMaxCardinalityMin = 0;
export const patchedMissionPolymorphicUpdateRequestOneTwoFormsItemMaxCardinalityMax = 2147483647;

export const patchedMissionPolymorphicUpdateRequestTwoTwoNameMax = 200;

export const patchedMissionPolymorphicUpdateRequestTwoTwoDescriptionMax = 500;

export const patchedMissionPolymorphicUpdateRequestTwoTwoFormsItemMinCardinalityMin = 0;
export const patchedMissionPolymorphicUpdateRequestTwoTwoFormsItemMinCardinalityMax = 2147483647;

export const patchedMissionPolymorphicUpdateRequestTwoTwoFormsItemMaxCardinalityMin = 0;
export const patchedMissionPolymorphicUpdateRequestTwoTwoFormsItemMaxCardinalityMax = 2147483647;

export const patchedMissionPolymorphicUpdateRequestTwoTwoMinCardinalityMin = 0;
export const patchedMissionPolymorphicUpdateRequestTwoTwoMinCardinalityMax = 2147483647;

export const patchedMissionPolymorphicUpdateRequestTwoTwoMaxCardinalityMin = 0;
export const patchedMissionPolymorphicUpdateRequestTwoTwoMaxCardinalityMax = 2147483647;

export const patchedMissionPolymorphicUpdateRequestThreeTwoNameMax = 200;

export const patchedMissionPolymorphicUpdateRequestThreeTwoDescriptionMax = 500;

export const patchedMissionPolymorphicUpdateRequestThreeTwoFormsItemMinCardinalityMin = 0;
export const patchedMissionPolymorphicUpdateRequestThreeTwoFormsItemMinCardinalityMax = 2147483647;

export const patchedMissionPolymorphicUpdateRequestThreeTwoFormsItemMaxCardinalityMin = 0;
export const patchedMissionPolymorphicUpdateRequestThreeTwoFormsItemMaxCardinalityMax = 2147483647;

export const patchedMissionPolymorphicUpdateRequestThreeTwoMinCardinalityMin = 0;
export const patchedMissionPolymorphicUpdateRequestThreeTwoMinCardinalityMax = 2147483647;

export const patchedMissionPolymorphicUpdateRequestThreeTwoMaxCardinalityMin = 0;
export const patchedMissionPolymorphicUpdateRequestThreeTwoMaxCardinalityMax = 2147483647;

export const PatchedMissionPolymorphicUpdateRequest = zod.union([
    zod.strictObject({
        mission_type: zod.enum(['FORM_FILLING']),
        name: zod
            .string()
            .min(1)
            .max(patchedMissionPolymorphicUpdateRequestOneTwoNameMax)
            .optional(),
        description: zod
            .string()
            .max(patchedMissionPolymorphicUpdateRequestOneTwoDescriptionMax)
            .optional(),
        forms: zod
            .array(
                zod.strictObject({
                    form: zod.number(),
                    min_cardinality: zod
                        .number()
                        .min(
                            patchedMissionPolymorphicUpdateRequestOneTwoFormsItemMinCardinalityMin,
                        )
                        .max(
                            patchedMissionPolymorphicUpdateRequestOneTwoFormsItemMinCardinalityMax,
                        )
                        .describe(
                            'Minimum number of times this form should be filled',
                        ),
                    max_cardinality: zod
                        .number()
                        .min(
                            patchedMissionPolymorphicUpdateRequestOneTwoFormsItemMaxCardinalityMin,
                        )
                        .max(
                            patchedMissionPolymorphicUpdateRequestOneTwoFormsItemMaxCardinalityMax,
                        )
                        .nullish()
                        .describe(
                            'Maximum number of times this form can be filled (null = unlimited)',
                        ),
                }),
            )
            .min(1)
            .optional(),
    }),
    zod.strictObject({
        mission_type: zod.enum(['ORG_UNIT_AND_FORM']),
        name: zod
            .string()
            .min(1)
            .max(patchedMissionPolymorphicUpdateRequestTwoTwoNameMax)
            .optional(),
        description: zod
            .string()
            .max(patchedMissionPolymorphicUpdateRequestTwoTwoDescriptionMax)
            .optional(),
        org_unit_type: zod.number().optional(),
        forms: zod
            .array(
                zod.strictObject({
                    form: zod.number(),
                    min_cardinality: zod
                        .number()
                        .min(
                            patchedMissionPolymorphicUpdateRequestTwoTwoFormsItemMinCardinalityMin,
                        )
                        .max(
                            patchedMissionPolymorphicUpdateRequestTwoTwoFormsItemMinCardinalityMax,
                        )
                        .describe(
                            'Minimum number of times this form should be filled',
                        ),
                    max_cardinality: zod
                        .number()
                        .min(
                            patchedMissionPolymorphicUpdateRequestTwoTwoFormsItemMaxCardinalityMin,
                        )
                        .max(
                            patchedMissionPolymorphicUpdateRequestTwoTwoFormsItemMaxCardinalityMax,
                        )
                        .nullish()
                        .describe(
                            'Maximum number of times this form can be filled (null = unlimited)',
                        ),
                }),
            )
            .min(1)
            .optional(),
        min_cardinality: zod
            .number()
            .min(patchedMissionPolymorphicUpdateRequestTwoTwoMinCardinalityMin)
            .max(patchedMissionPolymorphicUpdateRequestTwoTwoMinCardinalityMax)
            .optional()
            .describe('Minimum number of times this form should be filled'),
        max_cardinality: zod
            .number()
            .min(patchedMissionPolymorphicUpdateRequestTwoTwoMaxCardinalityMin)
            .max(patchedMissionPolymorphicUpdateRequestTwoTwoMaxCardinalityMax)
            .nullish()
            .describe(
                'Maximum number of times this form can be filled (null = unlimited)',
            ),
    }),
    zod.strictObject({
        mission_type: zod.enum(['ENTITY_AND_FORM']),
        name: zod
            .string()
            .min(1)
            .max(patchedMissionPolymorphicUpdateRequestThreeTwoNameMax)
            .optional(),
        description: zod
            .string()
            .max(patchedMissionPolymorphicUpdateRequestThreeTwoDescriptionMax)
            .optional(),
        entity_type: zod.number().optional(),
        forms: zod
            .array(
                zod.strictObject({
                    form: zod.number(),
                    min_cardinality: zod
                        .number()
                        .min(
                            patchedMissionPolymorphicUpdateRequestThreeTwoFormsItemMinCardinalityMin,
                        )
                        .max(
                            patchedMissionPolymorphicUpdateRequestThreeTwoFormsItemMinCardinalityMax,
                        )
                        .describe(
                            'Minimum number of times this form should be filled',
                        ),
                    max_cardinality: zod
                        .number()
                        .min(
                            patchedMissionPolymorphicUpdateRequestThreeTwoFormsItemMaxCardinalityMin,
                        )
                        .max(
                            patchedMissionPolymorphicUpdateRequestThreeTwoFormsItemMaxCardinalityMax,
                        )
                        .nullish()
                        .describe(
                            'Maximum number of times this form can be filled (null = unlimited)',
                        ),
                }),
            )
            .min(1)
            .optional(),
        min_cardinality: zod
            .number()
            .min(
                patchedMissionPolymorphicUpdateRequestThreeTwoMinCardinalityMin,
            )
            .max(
                patchedMissionPolymorphicUpdateRequestThreeTwoMinCardinalityMax,
            )
            .optional()
            .describe('Minimum number of times this form should be filled'),
        max_cardinality: zod
            .number()
            .min(
                patchedMissionPolymorphicUpdateRequestThreeTwoMaxCardinalityMin,
            )
            .max(
                patchedMissionPolymorphicUpdateRequestThreeTwoMaxCardinalityMax,
            )
            .nullish()
            .describe(
                'Maximum number of times this form can be filled (null = unlimited)',
            ),
    }),
]);

export type PatchedMissionPolymorphicUpdateRequest = zod.input<
    typeof PatchedMissionPolymorphicUpdateRequest
>;
export type PatchedMissionPolymorphicUpdateRequestOutput = zod.output<
    typeof PatchedMissionPolymorphicUpdateRequest
>;
