# Generated by Django 4.2.24 on 2025-09-22 13:25

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("wfp", "0001_initial"),
        ("wfp", "0002_auto_20230918_0905"),
        ("wfp", "0003_auto_20230928_1350"),
        ("wfp", "0004_auto_20231119_1721"),
        ("wfp", "0005_auto_20231123_1502"),
        ("wfp", "0006_alter_journey_exit_type"),
        ("wfp", "0007_auto_20231207_0839"),
        ("wfp", "0008_alter_journey_exit_type"),
        ("wfp", "0009_alter_journey_admission_type"),
        ("wfp", "0010_alter_journey_beneficiary_alter_step_visit_and_more"),
        ("wfp", "0011_journey_weight_difference_journey_weight_loss"),
        ("wfp", "0012_rename_weight_difference_journey_initial_weight_and_more"),
        ("wfp", "0013_yearlystatistics_monthlystatistics"),
        ("wfp", "0013_beneficiary_account"),
        ("wfp", "0014_merge_20241120_0748"),
        ("wfp", "0015_monthlystatistics_year"),
        ("wfp", "0016_monthlystatistics_account"),
        ("wfp", "0017_delete_yearlystatistics"),
        ("wfp", "0018_monthlystatistics_given_ration_cbt_step_ration_size"),
        ("wfp", "0019_alter_monthlystatistics_given_ration_cbt"),
    ]

    initial = True

    dependencies = [
        ("iaso", "0307_merge_20241024_1145"),
        ("iaso", "0231_merge_20230904_2154"),
        ("iaso", "0308_merge_20241028_1145"),
        ("iaso", "0293_orgunitchangerequest_kind"),
        ("iaso", "0225_merge_20230719_1411"),
    ]

    operations = [
        migrations.CreateModel(
            name="Beneficiary",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("birth_date", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        blank=True, choices=[("Male", "Male"), ("Female", "Female")], max_length=8, null=True
                    ),
                ),
                ("entity_id", models.IntegerField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="iaso.account"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Journey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "admission_criteria",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("muac", "MUAC"),
                            ("whz", "WHZ"),
                            ("oedema", "OEDEMA"),
                            ("child_wasted", "By wasted child"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "admission_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("new_case", "New case"),
                            ("readmission_as_non_respondent", "Readmission as non-respondent"),
                            ("referred_from_otp_sam", "Referred from OTP (SAM)"),
                            ("referred_from_sc", "Referred from SC"),
                            ("referred_from_tsfp_mam", "Referred from TSFP (MAM)"),
                            ("relapse", "Relapse"),
                            ("returned_defaulter", "Returned defaulter"),
                            ("returned_referral", "Returned referral"),
                            ("transfer_from_other_tsfp", "Transfer from other TSFP"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "nutrition_programme",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TSFP", "TSFP"),
                            ("OTP", "OTP"),
                            ("breastfeeding", "Breastfeeding"),
                            ("pregnant", "Pregnant"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "programme_type",
                    models.CharField(blank=True, choices=[("PLW", "PLW"), ("U5", "U5")], max_length=255, null=True),
                ),
                ("weight_gain", models.FloatField(default=0)),
                (
                    "exit_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("death", "Death"),
                            ("cured", "Cured"),
                            ("dismissed_due_to_cheating", "Dismissal"),
                            ("voluntary_withdrawal", "Voluntary Withdrawal"),
                            ("transfer_to_otp", "Transfer To OTP"),
                            ("transfer_to_tsfp", "Transfer To TSFP"),
                            ("non_respondent", "Non respondent"),
                            ("transferred_out", "Transferred out"),
                            ("defaulter", "Defaulter"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "beneficiary",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="wfp.beneficiary"
                    ),
                ),
                ("instance_id", models.IntegerField(blank=True, null=True)),
                ("initial_weight", models.FloatField(default=0)),
                ("weight_loss", models.FloatField(default=0)),
                ("discharge_weight", models.FloatField(blank=True, null=True)),
                ("duration", models.FloatField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateTimeField(blank=True, null=True)),
                ("number", models.IntegerField(default=1)),
                (
                    "journey",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="wfp.journey"
                    ),
                ),
                (
                    "org_unit",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="iaso.orgunit"
                    ),
                ),
                ("instance_id", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Step",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("assistance_type", models.CharField(max_length=255)),
                ("quantity_given", models.FloatField()),
                ("instance_id", models.IntegerField(blank=True, null=True)),
                (
                    "visit",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="wfp.visit"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrgUnit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("uuid", models.TextField(blank=True, db_index=True, null=True)),
                ("custom", models.BooleanField(default=False)),
                ("validated", models.BooleanField(db_index=True, default=True)),
                (
                    "validation_status",
                    models.CharField(
                        choices=[("NEW", "new"), ("VALID", "valid"), ("REJECTED", "rejected")],
                        default="NEW",
                        max_length=25,
                    ),
                ),
                ("sub_source", models.TextField(blank=True, null=True)),
                ("source_ref", models.TextField(blank=True, db_index=True, null=True)),
                ("geom_ref", models.IntegerField(blank=True, null=True)),
                ("gps_source", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "iaso_orgunit",
                "managed": False,
            },
        ),
        migrations.AlterField(
            model_name="visit",
            name="org_unit",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="wfp.orgunit"
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="org_unit",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="iaso.orgunit"
            ),
        ),
        migrations.DeleteModel(
            name="OrgUnit",
        ),
        migrations.AlterField(
            model_name="step",
            name="visit",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="wfp.visit"),
        ),
        migrations.AlterField(
            model_name="visit",
            name="journey",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="wfp.journey"
            ),
        ),
        migrations.AddField(
            model_name="step",
            name="ration_size",
            field=models.CharField(
                blank=True,
                choices=[("full", "Full"), ("partial", "Partial"), ("none", "None"), ("More", "More")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="MonthlyStatistics",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("month", models.CharField(blank=True, max_length=8, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True, choices=[("Male", "Male"), ("Female", "Female")], max_length=8, null=True
                    ),
                ),
                (
                    "admission_criteria",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("muac", "MUAC"),
                            ("whz", "WHZ"),
                            ("oedema", "OEDEMA"),
                            ("child_wasted", "By wasted child"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "admission_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("new_case", "New case"),
                            ("readmission_as_non_respondent", "Readmission as non-respondent"),
                            ("referred_from_otp_sam", "Referred from OTP (SAM)"),
                            ("referred_from_sc", "Referred from SC"),
                            ("referred_from_tsfp_mam", "Referred from TSFP (MAM)"),
                            ("relapse", "Relapse"),
                            ("returned_defaulter", "Returned defaulter"),
                            ("returned_referral", "Returned referral"),
                            ("transfer_from_other_tsfp", "Transfer from other TSFP"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "exit_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("death", "Death"),
                            ("cured", "Cured"),
                            ("dismissed_due_to_cheating", "Dismissal"),
                            ("voluntary_withdrawal", "Voluntary Withdrawal"),
                            ("transfer_to_otp", "Transfer To OTP"),
                            ("transfer_to_tsfp", "Transfer To TSFP"),
                            ("non_respondent", "Non respondent"),
                            ("transferred_out", "Transferred out"),
                            ("defaulter", "Defaulter"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "nutrition_programme",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TSFP", "TSFP"),
                            ("OTP", "OTP"),
                            ("breastfeeding", "Breastfeeding"),
                            ("pregnant", "Pregnant"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "programme_type",
                    models.CharField(blank=True, choices=[("PLW", "PLW"), ("U5", "U5")], max_length=255, null=True),
                ),
                ("number_visits", models.IntegerField(default=0)),
                ("given_sachet_rusf", models.FloatField(blank=True, null=True)),
                ("given_sachet_rutf", models.FloatField(blank=True, null=True)),
                ("given_quantity_csb", models.FloatField(blank=True, null=True)),
                (
                    "org_unit",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="iaso.orgunit"
                    ),
                ),
                ("year", models.CharField(blank=True, max_length=6, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="iaso.account"
                    ),
                ),
                (
                    "given_ration_cbt",
                    models.CharField(
                        blank=True,
                        choices=[("full", "Full"), ("partial", "Partial"), ("none", "None"), ("More", "More")],
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
