# Generated by Django 3.2.22 on 2023-11-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wfp", "0004_auto_20231119_1721"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journey",
            name="admission_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("new_case", "new case"),
                    ("readmission_as_non_respondent", "New respondant"),
                    ("referred_from_otp_sam", "Referred from OTP (SAM)"),
                    ("referred_from_sc", "Referred from SC"),
                    ("referred_from_tsfp_mam", "Referred from TSFP (MAM)"),
                    ("relapse", "Relapse"),
                    ("returned_defaulter", "Returned defaulter"),
                    ("returned_referral", "Returned referral"),
                    ("transfer_if_from_other_tsfp", "Transfer if from other TSFP"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="journey",
            name="exit_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("death", "Death"),
                    ("cured", "Cured"),
                    ("dismissed_due_to_cheating", "Dismissal"),
                    ("voluntary_with_drawal", "Voluntary Withdrawal"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
