# Generated by Django 3.2.22 on 2023-11-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wfp", "0005_auto_20231123_1502"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journey",
            name="exit_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("death", "Death"),
                    ("cured", "Cured"),
                    ("dismissed_due_to_cheating", "Dismissal"),
                    ("voluntary_withdrawal", "Voluntary Withdrawal"),
                    ("transfer_to_otp", "Transfer To OTP"),
                    ("transfer_to_tsfp", "Transfer To TSFP"),
                    ("non_respondent", "Non respondent"),
                    ("transferredout", "Transferred out"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
