# Generated by Django 3.2.22 on 2023-12-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wfp", "0006_alter_journey_exit_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journey",
            name="admission_criteria",
            field=models.CharField(
                blank=True,
                choices=[("muac", "MUAC"), ("whz", "WHZ"), ("oedema", "OEDEMA"), ("child_wasted", "By wasted child")],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="journey",
            name="admission_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("new_case", "new case"),
                    ("readmission_as_non_respondent", "Readmission as non-respondent"),
                    ("referred_from_otp_sam", "Referred from OTP (SAM)"),
                    ("referred_from_sc", "Referred from SC"),
                    ("referred_from_tsfp_mam", "Referred from TSFP (MAM)"),
                    ("relapse", "Relapse"),
                    ("returned_defaulter", "Returned defaulter"),
                    ("returned_referral", "Returned referral"),
                    ("transfer_from_other_tsfp", "Transfer from other TSFP"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="journey",
            name="exit_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("death", "Death"),
                    ("cured", "Cured"),
                    ("dismissed_due_to_cheating", "Dismissal"),
                    ("voluntary_withdrawal", "Voluntary Withdrawal"),
                    ("transfer_to_otp", "Transfer To OTP"),
                    ("transfer_to_tsfp", "Transfer To TSFP"),
                    ("non_respondent", "Non respondent"),
                    ("transferredout", "Transferred out"),
                    ("other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="journey",
            name="nutrition_programme",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TSFP", "TSFP"),
                    ("OTP", "OTP"),
                    ("breastfeeding", "Breastfeeding"),
                    ("pregnant", "Pregnant"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
