# Generated by Django 3.2.22 on 2023-12-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wfp", "0008_alter_journey_exit_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journey",
            name="admission_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("new_case", "New case"),
                    ("readmission_as_non_respondent", "Readmission as non-respondent"),
                    ("referred_from_otp_sam", "Referred from OTP (SAM)"),
                    ("referred_from_sc", "Referred from SC"),
                    ("referred_from_tsfp_mam", "Referred from TSFP (MAM)"),
                    ("relapse", "Relapse"),
                    ("returned_defaulter", "Returned defaulter"),
                    ("returned_referral", "Returned referral"),
                    ("transfer_from_other_tsfp", "Transfer from other TSFP"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
