# Generated by Django 4.2.9 on 2024-02-09 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wfp", "0009_alter_journey_admission_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journey",
            name="beneficiary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wfp.beneficiary",
            ),
        ),
        migrations.AlterField(
            model_name="step",
            name="visit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wfp.visit",
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="journey",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wfp.journey",
            ),
        ),
    ]
