# Generated by Django 4.2.11 on 2024-03-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wfp", "0010_alter_journey_beneficiary_alter_step_visit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="journey",
            name="weight_difference",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="journey",
            name="weight_loss",
            field=models.FloatField(default=0),
        ),
    ]
