# Generated by Django 4.2.11 on 2024-04-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wfp", "0011_journey_weight_difference_journey_weight_loss"),
    ]

    operations = [
        migrations.RenameField(
            model_name="journey",
            old_name="weight_difference",
            new_name="initial_weight",
        ),
        migrations.AddField(
            model_name="journey",
            name="discharge_weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journey",
            name="duration",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journey",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journey",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="journey",
            name="exit_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("death", "Death"),
                    ("cured", "Cured"),
                    ("dismissed_due_to_cheating", "Dismissal"),
                    ("voluntary_withdrawal", "Voluntary Withdrawal"),
                    ("transfer_to_otp", "Transfer To OTP"),
                    ("transfer_to_tsfp", "Transfer To TSFP"),
                    ("non_respondent", "Non respondent"),
                    ("transferred_out", "Transferred out"),
                    ("defaulter", "Defaulter"),
                    ("other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
