# Generated by Django 4.2.16 on 2024-11-20 07:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wfp", "0013_beneficiary_account"),
        ("wfp", "0013_yearlystatistics_monthlystatistics"),
    ]

    operations = []
