# Generated by Django 4.2.16 on 2024-11-25 16:20

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0308_merge_20241028_1145"),
        ("wfp", "0015_monthlystatistics_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlystatistics",
            name="account",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="iaso.account"
            ),
        ),
    ]
