# Generated by Django 4.2.23 on 2025-09-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wfp", "0019_alter_monthlystatistics_given_ration_cbt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beneficiary",
            name="entity_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="beneficiary",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female")],
                db_index=True,
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="journey",
            name="admission_criteria",
            field=models.CharField(
                blank=True,
                choices=[
                    ("muac", "MUAC"),
                    ("whz", "WHZ"),
                    ("oedema", "OEDEMA"),
                    ("child_wasted", "By wasted child"),
                ],
                db_index=True,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="journey",
            name="admission_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("new_case", "New case"),
                    ("readmission_as_non_respondent", "Readmission as non-respondent"),
                    ("referred_from_otp_sam", "Referred from OTP (SAM)"),
                    ("referred_from_sc", "Referred from SC"),
                    ("referred_from_tsfp_mam", "Referred from TSFP (MAM)"),
                    ("relapse", "Relapse"),
                    ("returned_defaulter", "Returned defaulter"),
                    ("returned_referral", "Returned referral"),
                    ("transfer_from_other_tsfp", "Transfer from other TSFP"),
                ],
                db_index=True,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="journey",
            name="end_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="journey",
            name="exit_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("death", "Death"),
                    ("cured", "Cured"),
                    ("dismissed_due_to_cheating", "Dismissal"),
                    ("voluntary_withdrawal", "Voluntary Withdrawal"),
                    ("transfer_to_otp", "Transfer To OTP"),
                    ("transfer_to_tsfp", "Transfer To TSFP"),
                    ("non_respondent", "Non respondent"),
                    ("transferred_out", "Transferred out"),
                    ("defaulter", "Defaulter"),
                    ("other", "Other"),
                ],
                db_index=True,
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="journey",
            name="nutrition_programme",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TSFP", "TSFP"),
                    ("OTP", "OTP"),
                    ("breastfeeding", "Breastfeeding"),
                    ("pregnant", "Pregnant"),
                ],
                db_index=True,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="journey",
            name="programme_type",
            field=models.CharField(
                blank=True,
                choices=[("PLW", "PLW"), ("U5", "U5")],
                db_index=True,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="journey",
            name="start_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="step",
            name="assistance_type",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="step",
            name="instance_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="visit",
            name="date",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="visit",
            name="instance_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
