# Generated by Django 4.2.24 on 2025-09-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wfp", "0020_alter_beneficiary_entity_id_alter_beneficiary_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="beneficiary",
            name="guidelines",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
