# Generated by Django 4.2.25 on 2025-10-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wfp", "0021_beneficiary_guidelines"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journey",
            name="nutrition_programme",
            field=models.CharField(blank=True, choices=[("TSFP", "TSFP"), ("OTP", "OTP"), ("OTP - Under 6", "OTP - Under 6"), ("breastfeeding", "Breastfeeding"), ("pregnant", "Pregnant")], db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="monthlystatistics",
            name="nutrition_programme",
            field=models.CharField(blank=True, choices=[("TSFP", "TSFP"), ("OTP", "OTP"), ("OTP - Under 6", "OTP - Under 6"), ("breastfeeding", "Breastfeeding"), ("pregnant", "Pregnant")], max_length=255, null=True),
        ),
    ]
