# Generated by Django 4.2.25 on 2025-11-01 10:28

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0348_alter_assignment_unique_together_and_more"),
        ("wfp", "0022_alter_journey_nutrition_programme_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="journey",
            name="muac_size",
            field=models.CharField(db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="journey",
            name="whz_score",
            field=models.CharField(db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="monthlystatistics",
            name="beneficiary_with_admission_type",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="monthlystatistics",
            name="beneficiary_with_exit_type",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="monthlystatistics",
            name="beneficiary_with_nutrition_programme",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="monthlystatistics",
            name="dhis2_id",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="monthlystatistics",
            name="muac_11_5_12_4",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="monthlystatistics",
            name="muac_above_12_5",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="monthlystatistics",
            name="muac_above_23",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="monthlystatistics",
            name="muac_under_11_5",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="monthlystatistics",
            name="muac_under_23",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="monthlystatistics",
            name="oedema",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="monthlystatistics",
            name="period",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="monthlystatistics",
            name="whz_score_2",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="monthlystatistics",
            name="whz_score_3",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="monthlystatistics",
            name="whz_score_3_2",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="entry_point",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="muac_size",
            field=models.CharField(db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="oedema",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="whz_color",
            field=models.CharField(db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="journey",
            name="exit_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("death", "Death"),
                    ("cured", "Cured"),
                    ("dismissed_due_to_cheating", "Dismissal"),
                    ("voluntary_withdrawal", "Voluntary Withdrawal"),
                    ("transfer_to_otp", "Transfer To OTP"),
                    ("transfer_from_other_otp", "Transfer in from other OTP"),
                    ("transfer_to_tsfp", "Transfer To TSFP"),
                    ("transfer_from_other_tsfp", "Transfer in from other TSFP"),
                    ("non_respondent", "Non respondent"),
                    ("transferred_out", "Transferred out"),
                    ("defaulter", "Defaulter"),
                    ("other", "Other"),
                ],
                db_index=True,
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="monthlystatistics",
            name="exit_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("death", "Death"),
                    ("cured", "Cured"),
                    ("dismissed_due_to_cheating", "Dismissal"),
                    ("voluntary_withdrawal", "Voluntary Withdrawal"),
                    ("transfer_to_otp", "Transfer To OTP"),
                    ("transfer_from_other_otp", "Transfer in from other OTP"),
                    ("transfer_to_tsfp", "Transfer To TSFP"),
                    ("transfer_from_other_tsfp", "Transfer in from other TSFP"),
                    ("non_respondent", "Non respondent"),
                    ("transferred_out", "Transferred out"),
                    ("defaulter", "Defaulter"),
                    ("other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Dhis2SyncResults",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("org_unit_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("org_unit_dhis2_id", models.TextField(null=True)),
                ("data_set_id", models.TextField(null=True)),
                (
                    "programme_type",
                    models.CharField(blank=True, choices=[("PLW", "PLW"), ("U5", "U5")], max_length=255, null=True),
                ),
                ("status", models.TextField(null=True)),
                ("period", models.CharField(blank=True, max_length=8, null=True)),
                ("month", models.CharField(blank=True, max_length=8, null=True)),
                ("year", models.CharField(blank=True, max_length=6, null=True)),
                ("response", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="iaso.account"
                    ),
                ),
            ],
        ),
    ]
