# Generated by Django 4.2.24 on 2025-09-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wfp", "0022_journey_muac_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="journey",
            name="whz_score",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="muac_size",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="whz_score",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
