# Generated by Django 4.2.26 on 2025-12-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wfp", "0023_journey_muac_size_journey_whz_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journey",
            name="nutrition_programme",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TSFP", "TSFP"),
                    ("OTP", "OTP"),
                    ("OTP - Under 6", "OTP - Under 6"),
                    ("BSFP", "BSFP"),
                    ("breastfeeding", "Breastfeeding"),
                    ("pregnant", "Pregnant"),
                ],
                db_index=True,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="monthlystatistics",
            name="nutrition_programme",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TSFP", "TSFP"),
                    ("OTP", "OTP"),
                    ("OTP - Under 6", "OTP - Under 6"),
                    ("BSFP", "BSFP"),
                    ("breastfeeding", "Breastfeeding"),
                    ("pregnant", "Pregnant"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
