# Generated by Django 4.2.26 on 2025-12-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wfp", "0023_journey_muac_size_journey_whz_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journey",
            name="admission_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("new_case", "New case"),
                    ("readmission_as_non_respondent", "Readmission as non-respondent"),
                    ("referred_from_otp_sam", "Referred from OTP (SAM)"),
                    ("referred_from_sc", "Referred from SC"),
                    ("referred_from_tsfp_mam", "Referred from TSFP (MAM)"),
                    ("referred_from_BSFP", "Referred from BSFP"),
                    ("relapse", "Relapse"),
                    ("returned_defaulter", "Returned defaulter"),
                    ("returned_referral", "Returned referral"),
                    ("transfer_from_other_tsfp", "Transfer from other TSFP"),
                ],
                db_index=True,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="journey",
            name="nutrition_programme",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TSFP", "TSFP"),
                    ("OTP", "OTP"),
                    ("OTP - Under 6", "OTP - Under 6"),
                    ("BSFP", "BSFP"),
                    ("breastfeeding", "Breastfeeding"),
                    ("pregnant", "Pregnant"),
                ],
                db_index=True,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="monthlystatistics",
            name="admission_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("new_case", "New case"),
                    ("readmission_as_non_respondent", "Readmission as non-respondent"),
                    ("referred_from_otp_sam", "Referred from OTP (SAM)"),
                    ("referred_from_sc", "Referred from SC"),
                    ("referred_from_tsfp_mam", "Referred from TSFP (MAM)"),
                    ("referred_from_BSFP", "Referred from BSFP"),
                    ("relapse", "Relapse"),
                    ("returned_defaulter", "Returned defaulter"),
                    ("returned_referral", "Returned referral"),
                    ("transfer_from_other_tsfp", "Transfer from other TSFP"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="monthlystatistics",
            name="nutrition_programme",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TSFP", "TSFP"),
                    ("OTP", "OTP"),
                    ("OTP - Under 6", "OTP - Under 6"),
                    ("BSFP", "BSFP"),
                    ("breastfeeding", "Breastfeeding"),
                    ("pregnant", "Pregnant"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
