# Generated by Django 4.2.24 on 2025-09-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wfp", "0023_journey_whz_score_visit_muac_size_visit_whz_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlystatistics",
            name="muac_11_5_12_4",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="monthlystatistics",
            name="muac_above_12_5",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="monthlystatistics",
            name="muac_under_11_5",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="journey",
            name="muac_size",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="journey",
            name="whz_score",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="visit",
            name="muac_size",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="visit",
            name="whz_score",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
