# Generated by Django 4.2.26 on 2026-02-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wfp", "0024_alter_journey_admission_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journey",
            name="initial_weight",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
