# Generated by Django 4.2.24 on 2025-09-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wfp", "0024_monthlystatistics_muac_11_5_12_4_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlystatistics",
            name="beneficiary_with_exit_type",
            field=models.FloatField(null=True),
        ),
    ]
