# Generated by Django 4.2.26 on 2026-01-22 10:14

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0362_metrictype_origin"),
        ("wfp", "0024_alter_journey_admission_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="beneficiary",
            name="entity_id",
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="entity",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="iaso.entity"
            ),
        ),
    ]
