# Generated by Django 4.2.26 on 2026-02-03 14:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wfp", "0025_alter_journey_initial_weight"),
        ("wfp", "0025_remove_beneficiary_entity_id_beneficiary_entity"),
    ]

    operations = []
