# Generated by Django 4.2.26 on 2026-02-03 15:47

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0363_merge_20260122_1147"),
        ("wfp", "0025_remove_beneficiary_entity_id_beneficiary_entity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journey",
            name="initial_weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ScreeningData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("month", models.CharField(blank=True, max_length=8, null=True)),
                ("year", models.CharField(blank=True, max_length=6, null=True)),
                ("period", models.CharField(blank=True, max_length=8, null=True)),
                ("u5_male_green", models.FloatField(null=True)),
                ("u5_female_green", models.FloatField(null=True)),
                ("u5_male_yellow", models.FloatField(null=True)),
                ("u5_female_yellow", models.FloatField(null=True)),
                ("u5_male_red", models.FloatField(null=True)),
                ("u5_female_red", models.FloatField(null=True)),
                ("pregnant_w_muac_gt_23", models.FloatField(null=True)),
                ("pregnant_w_muac_lte_23", models.FloatField(null=True)),
                ("lactating_w_muac_gt_23", models.FloatField(null=True)),
                ("lactating_w_muac_lte_23", models.FloatField(null=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="iaso.account"
                    ),
                ),
                (
                    "org_unit",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="iaso.orgunit"
                    ),
                ),
            ],
        ),
    ]
