# Generated by Django 4.2.26 on 2026-02-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wfp", "0025_remove_beneficiary_entity_id_beneficiary_entity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journey",
            name="initial_weight",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
