# Generated by Django 4.2.24 on 2025-09-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wfp", "0025_monthlystatistics_beneficiary_with_exit_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="visit",
            old_name="whz_score",
            new_name="whz_color",
        ),
        migrations.AddField(
            model_name="monthlystatistics",
            name="beneficiary_with_admission_type",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="monthlystatistics",
            name="beneficiary_with_nutrition_programme",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="monthlystatistics",
            name="whz_score_2",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="monthlystatistics",
            name="whz_score_3",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="monthlystatistics",
            name="whz_score_3_2",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
