# Generated by Django 4.2.24 on 2025-09-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wfp", "0026_rename_whz_score_visit_whz_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlystatistics",
            name="dhis2_id",
            field=models.TextField(null=True),
        ),
    ]
