# Generated by Django 4.2.24 on 2025-09-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wfp", "0027_monthlystatistics_dhis2_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlystatistics",
            name="period",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
