# Generated by Django 4.2.28 on 2026-03-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wfp", "0027_dhis2syncresults_json_screeningdata_u5_female_oedema_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="journey",
            name="physiology_status",
            field=models.CharField(
                blank=True,
                choices=[("breastfeeding", "Breastfeeding"), ("pregnant", "Pregnant")],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="monthlystatistics",
            name="physiology_status",
            field=models.CharField(
                blank=True,
                choices=[("breastfeeding", "Breastfeeding"), ("pregnant", "Pregnant")],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="journey",
            name="nutrition_programme",
            field=models.CharField(
                blank=True,
                choices=[("TSFP", "TSFP"), ("OTP", "OTP"), ("OTP - Under 6", "OTP - Under 6"), ("BSFP", "BSFP")],
                db_index=True,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="monthlystatistics",
            name="nutrition_programme",
            field=models.CharField(
                blank=True,
                choices=[("TSFP", "TSFP"), ("OTP", "OTP"), ("OTP - Under 6", "OTP - Under 6"), ("BSFP", "BSFP")],
                max_length=255,
                null=True,
            ),
        ),
    ]
