# Generated by Django 4.2.28 on 2026-03-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wfp", "0028_journey_physiology_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monthlystatistics",
            name="beneficiary_with_admission_type",
        ),
        migrations.RemoveField(
            model_name="monthlystatistics",
            name="beneficiary_with_exit_type",
        ),
        migrations.RemoveField(
            model_name="monthlystatistics",
            name="beneficiary_with_nutrition_programme",
        ),
        migrations.RemoveField(
            model_name="monthlystatistics",
            name="exit_type",
        ),
        migrations.RemoveField(
            model_name="monthlystatistics",
            name="given_quantity_csb",
        ),
        migrations.RemoveField(
            model_name="monthlystatistics",
            name="given_ration_cbt",
        ),
        migrations.RemoveField(
            model_name="monthlystatistics",
            name="given_sachet_rusf",
        ),
        migrations.RemoveField(
            model_name="monthlystatistics",
            name="given_sachet_rutf",
        ),
        migrations.AddField(
            model_name="monthlystatistics",
            name="admission_type_admission_sc_itp_otp",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="monthlystatistics",
            name="admission_type_new_case",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="monthlystatistics",
            name="admission_type_relapse",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="monthlystatistics",
            name="admission_type_returned_defaulter",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="monthlystatistics",
            name="admission_type_returned_referral",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="monthlystatistics",
            name="admission_type_transfer_from_other_tsfp",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="monthlystatistics",
            name="admission_type_transfer_sc_itp_otp",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="monthlystatistics",
            name="breastfeeding",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="monthlystatistics",
            name="exit_type_cured",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="monthlystatistics",
            name="exit_type_death",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="monthlystatistics",
            name="exit_type_defaulter",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="monthlystatistics",
            name="exit_type_non_respondent",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="monthlystatistics",
            name="exit_type_transfer_in_from_other_tsfp",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="monthlystatistics",
            name="pregnant",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="journey",
            name="nutrition_programme",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TSFP", "TSFP"),
                    ("OTP", "OTP"),
                    ("OTP - Under 6", "OTP - Under 6"),
                    ("BSFP", "BSFP"),
                    ("Not Eligible", "Not Eligible"),
                ],
                db_index=True,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="monthlystatistics",
            name="muac_11_5_12_4",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="monthlystatistics",
            name="muac_above_12_5",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="monthlystatistics",
            name="muac_above_23",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="monthlystatistics",
            name="muac_under_11_5",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="monthlystatistics",
            name="muac_under_23",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="monthlystatistics",
            name="number_visits",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="monthlystatistics",
            name="nutrition_programme",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TSFP", "TSFP"),
                    ("OTP", "OTP"),
                    ("OTP - Under 6", "OTP - Under 6"),
                    ("BSFP", "BSFP"),
                    ("Not Eligible", "Not Eligible"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="monthlystatistics",
            name="oedema",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="monthlystatistics",
            name="whz_score_2",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="monthlystatistics",
            name="whz_score_3",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="monthlystatistics",
            name="whz_score_3_2",
            field=models.IntegerField(null=True),
        ),
        migrations.AddIndex(
            model_name="beneficiary",
            index=models.Index(fields=["account", "id"], name="wfp_benefic_account_b32174_idx"),
        ),
        migrations.AddIndex(
            model_name="journey",
            index=models.Index(
                fields=["programme_type", "beneficiary", "nutrition_programme"], name="wfp_journey_program_48c13a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journey",
            index=models.Index(fields=["physiology_status"], name="wfp_journey_physiol_a08448_idx"),
        ),
        migrations.AddIndex(
            model_name="visit",
            index=models.Index(fields=["org_unit", "date", "journey"], name="wfp_visit_org_uni_765b0f_idx"),
        ),
        migrations.AddIndex(
            model_name="visit",
            index=models.Index(fields=["muac_size", "whz_color"], name="wfp_visit_muac_si_ce15a3_idx"),
        ),
    ]
