# Generated by Django 4.2.24 on 2025-10-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wfp", "0029_monthlystatistics_oedema"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="oedema",
            field=models.FloatField(null=True),
        ),
    ]
