# Generated by Django 4.2.28 on 2026-03-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wfp", "0029_restructure_and_map_monthly_statistics_to_data_to_push_to_dhis2"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="beneficiary",
            index=models.Index(fields=["account", "id"], name="wfp_benefic_account_b32174_idx"),
        ),
        migrations.AddIndex(
            model_name="journey",
            index=models.Index(
                fields=["programme_type", "beneficiary", "nutrition_programme"], name="wfp_journey_program_48c13a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journey",
            index=models.Index(fields=["physiology_status"], name="wfp_journey_physiol_a08448_idx"),
        ),
        migrations.AddIndex(
            model_name="visit",
            index=models.Index(fields=["org_unit", "date", "journey"], name="wfp_visit_org_uni_765b0f_idx"),
        ),
        migrations.AddIndex(
            model_name="visit",
            index=models.Index(fields=["muac_size", "whz_color"], name="wfp_visit_muac_si_ce15a3_idx"),
        ),
    ]
