# Generated by Django 4.2.30 on 2026-04-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "wfp",
            "0029_additional_index_on_analytics_and_restructure_and_map_monthly_statistics_to_data_to_push_to_dhis2",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="journey",
            name="weight_gain",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="journey",
            name="weight_loss",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
