# Generated by Django 4.2.25 on 2025-10-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wfp", "0030_visit_oedema"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="entry_point",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="journey",
            name="exit_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("death", "Death"),
                    ("cured", "Cured"),
                    ("dismissed_due_to_cheating", "Dismissal"),
                    ("voluntary_withdrawal", "Voluntary Withdrawal"),
                    ("transfer_to_otp", "Transfer To OTP"),
                    ("transfer_from_other_otp", "Transfer in from other OTP"),
                    ("transfer_to_tsfp", "Transfer To TSFP"),
                    ("transfer_from_other_tsfp", "Transfer in from other TSFP"),
                    ("non_respondent", "Non respondent"),
                    ("transferred_out", "Transferred out"),
                    ("defaulter", "Defaulter"),
                    ("other", "Other"),
                ],
                db_index=True,
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="monthlystatistics",
            name="exit_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("death", "Death"),
                    ("cured", "Cured"),
                    ("dismissed_due_to_cheating", "Dismissal"),
                    ("voluntary_withdrawal", "Voluntary Withdrawal"),
                    ("transfer_to_otp", "Transfer To OTP"),
                    ("transfer_from_other_otp", "Transfer in from other OTP"),
                    ("transfer_to_tsfp", "Transfer To TSFP"),
                    ("transfer_from_other_tsfp", "Transfer in from other TSFP"),
                    ("non_respondent", "Non respondent"),
                    ("transferred_out", "Transferred out"),
                    ("defaulter", "Defaulter"),
                    ("other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
