# Generated by Django 4.2.30 on 2026-09-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wfp", "0030_alter_journey_weight_gain_alter_journey_weight_loss"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journey",
            name="admission_criteria",
            field=models.CharField(
                blank=True,
                choices=[
                    ("muac", "MUAC"),
                    ("whz", "WHZ"),
                    ("muac_whz", "Both MUAC & WHZ"),
                    ("oedema", "OEDEMA"),
                    ("child_wasted", "By wasted child"),
                ],
                db_index=True,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="journey",
            name="admission_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("new_case", "New case"),
                    ("new_case_MUAC", "New admission (MUAC <11.5 cm)"),
                    ("new_case_WHZ", "New admission (WHZ scores <-3SD)"),
                    ("new_case_MUAC_WHZ", "New admission (Both WHZ and MUAC)"),
                    ("new_case_OEDEMA", "New admission (Oedema + or ++)"),
                    ("readmission_as_non_respondent", "Readmission as non-respondent"),
                    ("referred_from_otp_sam", "Referred from OTP (SAM)"),
                    ("referred_from_sc", "Referred from SC"),
                    ("referred_from_tsfp_mam", "Referred from TSFP (MAM)"),
                    ("referred_from_BSFP", "Referred from BSFP"),
                    ("relapse", "Relapse"),
                    ("returned_defaulter", "Returned defaulter"),
                    ("returned_referral", "Returned referral"),
                    ("transfer_from_other_tsfp", "Transfer from other TSFP"),
                ],
                db_index=True,
                max_length=255,
                null=True,
            ),
        ),
    ]
