# Generated by Django 4.2.25 on 2025-10-28 08:16

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0348_alter_assignment_unique_together_and_more"),
        ("wfp", "0032_merge_20251025_0930"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dhis2SyncResults",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("org_unit_dhis2_id", models.TextField(null=True)),
                (
                    "nutrition_programme",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TSFP", "TSFP"),
                            ("OTP", "OTP"),
                            ("OTP - Under 6", "OTP - Under 6"),
                            ("breastfeeding", "Breastfeeding"),
                            ("pregnant", "Pregnant"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "programme_type",
                    models.CharField(blank=True, choices=[("PLW", "PLW"), ("U5", "U5")], max_length=255, null=True),
                ),
                ("status", models.TextField(null=True)),
                ("period", models.CharField(blank=True, max_length=8, null=True)),
                ("response", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="iaso.account"
                    ),
                ),
                (
                    "org_unit",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="iaso.orgunit"
                    ),
                ),
            ],
        ),
    ]
