# Generated by Django 4.2.25 on 2025-10-28 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wfp', '0033_dhis2syncresults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dhis2syncresults',
            name='nutrition_programme',
        ),
    ]
