# Generated by Django 4.2.25 on 2025-10-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wfp", "0036_dhis2syncresults_data_set_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlystatistics",
            name="muac_above_23",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="monthlystatistics",
            name="muac_under_23",
            field=models.FloatField(null=True),
        ),
    ]
