# Generated by Django 4.2.25 on 2025-10-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wfp", "0038_alter_journey_muac_size_alter_journey_whz_score_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dhis2syncresults",
            name="org_unit",
        ),
        migrations.AddField(
            model_name="dhis2syncresults",
            name="org_unit_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
