import json

from base64 import b64encode
from collections import OrderedDict
from urllib import parse

from django.db.models import Q
from rest_framework import pagination
from rest_framework.pagination import CursorPagination, _reverse_ordering
from rest_framework.response import Response


class EntityLocationPaginator(pagination.PageNumberPagination):
    """Paginator for entities `asLocation`.

    Note: this might be unnecessary but maintained for strict
    legacy API compatibility.
    """

    page_size_query_param = "limit"

    def get_paginated_response(self, data):
        return Response(
            {
                "result": data,
                "limit": self.page.paginator.per_page,
            }
        )


class EntityListPaginator(pagination.PageNumberPagination):
    """Paginator for the entities list.

    Similar to a default paginator but adds the "columns" attribute from the view's context.
    """

    page_size_query_param = "limit"
    # large default page_size for legacy API compatibility
    # not specifying a limit used to return everything
    page_size = 10000
    _view = None

    def paginate_queryset(self, queryset, request, view=None):
        """Store a reference to the view to access later."""

        self._view = view
        return super().paginate_queryset(queryset, request, view)

    def get_paginated_response(self, data):
        columns = getattr(self._view, "entity_type_columns", [])
        return Response(
            {
                "count": self.page.paginator.count,
                "result": data,
                "has_next": self.page.has_next(),
                "has_previous": self.page.has_previous(),
                "page": self.page.number,
                "pages": self.page.paginator.num_pages,
                "limit": self.page.paginator.per_page,
                "columns": columns,
            }
        )


class EntityCursorPagination(CursorPagination):
    """Cursor pagination for the Entities list."""

    ordering = "-created_at"
    page_size = 20
    page_size_query_param = "limit"
    nullable_fields = ["attributes__org_unit__name", "attributes__json__"]
    _view = None

    def decode_cursor(self, request):
        """Accept a 'null' cursor as a starting cursor."""
        cursor = request.query_params.get(self.cursor_query_param)
        if cursor == "null":
            return None
        return super().decode_cursor(request)

    def encode_cursor(self, cursor):
        """
        Override default behavior to return the cursor instead
        of the full URL to the next/previous pages.
        """
        tokens = {}
        if cursor.offset != 0:
            tokens["o"] = str(cursor.offset)
        if cursor.reverse:
            tokens["r"] = "1"
        if cursor.position is not None:
            tokens["p"] = cursor.position

        querystring = parse.urlencode(tokens, doseq=True)
        encoded = b64encode(querystring.encode("ascii")).decode("ascii")
        return encoded

    def get_paginated_response(self, data):
        """
        Use 'result' instead of 'results' for consistency with the existing API
        and inject our custom columns in the response.
        """
        columns = getattr(self._view, "entity_type_columns", [])
        return Response(
            OrderedDict(
                [
                    ("next", self.get_next_link()),
                    ("previous", self.get_previous_link()),
                    ("result", data),
                    ("columns", columns),
                ]
            )
        )

    def get_ordering(self, request, queryset, view):
        """Always ensure a unique tie-breaker pk is present in the ordering."""
        ordering = super().get_ordering(request, queryset, view)
        if isinstance(ordering, str):
            ordering = (ordering,)

        if not any(f.lstrip("-") in ("id", "pk") for f in ordering):
            ordering = ordering + ("id",)

        return tuple(ordering)

    def _get_position_from_instance(self, instance, ordering):
        """
        Extract the values of the ordering fields from an instance to build the cursor.

        Extended from the base class to support multi-field ordering and traversing
        relations with __.

        Note: there is a possible edge case where a json value could be explicitly
        `null` (vs. missing key). To my knowledge, we never encode values like this,
        but jsonb attributes with an explicit null are ordered differently than other
        NULL values by postgres.
        Cursors generated by this method might be invalid for those fields unless the
        the nulls are casted into NULL (with KeyTextTransform for instance).
        """
        fields = []
        for o in ordering:
            field_name = o.lstrip("-")
            attr = instance

            if isinstance(attr, dict):
                attr = attr.get(field_name)
            else:
                # Handle 'entity_type__name' -> instance.entity_type.name
                for part in field_name.split("__"):
                    if attr is None:
                        break

                    if isinstance(attr, dict):
                        attr = attr.get(part)
                    else:
                        attr = getattr(attr, part, None)

            fields.append(str(attr) if attr is not None else None)

        return json.dumps(fields)

    def paginate_queryset(self, queryset, request, view=None):
        """
        Adjust paginate_queryset to include the primary key in the ordering,
        in order to make cursor pagination more reliable with non-unique or nullable fields.

        The implementation below is mostly vanilla DRF + ideas from the patch listed in this discussion:
        - https://github.com/encode/django-rest-framework/discussions/7888
        - https://github.com/encode/django-rest-framework/commit/9408b4311cb49519b820b0464d13cc982cbdead4
        """
        self._view = view

        # Mostly standard DRF logic from the parent class

        self.page_size = self.get_page_size(request)
        if not self.page_size:
            return None

        self.base_url = request.build_absolute_uri()
        self.ordering = self.get_ordering(request, queryset, view)

        self.cursor = self.decode_cursor(request)
        if self.cursor is None:
            (offset, reverse, current_position) = (0, False, None)
        else:
            (offset, reverse, current_position) = self.cursor

        if reverse:
            queryset = queryset.order_by(*_reverse_ordering(self.ordering))
        else:
            queryset = queryset.order_by(*self.ordering)

        if current_position is not None:
            # Custom behaviour to support mulitple field ordering and null field handling
            queryset = self._apply_cursor_filter(queryset, current_position, reverse)

        results = list(queryset[offset : offset + self.page_size + 1])
        self.page = list(results[: self.page_size])

        has_following_position = len(results) > len(self.page)
        following_position = (
            self._get_position_from_instance(results[-1], self.ordering) if has_following_position else None
        )

        if reverse:
            self.page.reverse()
            self.has_next = (current_position is not None) or (offset > 0)
            self.has_previous = has_following_position
            if self.has_next:
                self.next_position = current_position
            if self.has_previous:
                self.previous_position = following_position
        else:
            self.has_next = has_following_position
            self.has_previous = (current_position is not None) or (offset > 0)
            if self.has_next:
                self.next_position = following_position
            if self.has_previous:
                self.previous_position = current_position

        if self.has_next:
            self.next_offset = (offset + self.page_size) if reverse else 0
        if self.has_previous:
            self.previous_offset = 0 if reverse else (offset + self.page_size)

        return self.page

    def _apply_cursor_filter(self, queryset, cursor, direction_reverse):
        """
        Filter the queryset based on the cursor's position.

        Build a "cascading" OR condition.
        For example, if ordering by (field_A, field_B, field_id) with cursor
        values (a, b, id), we must fetch records where:
            (field_A > a) OR
            (field_A == a AND field_B > b) OR
            (field_A == a AND field_B == b AND field_id > id)

        More commonly, with one field A and the id as the tie-breaker, we'll have:
        (A > a) OR (A == a AND id > 123)

        The logic is different for NULL values, as postgres treats them as
        the highest value possible. The result will be something like:
        (A > a OR A IS NULL) OR (A == a AND id > 123)
        """
        current_position_list = json.loads(cursor)

        filter_q = Q()
        accumulated_equals = Q()

        for order, position in zip(self.ordering, current_position_list):
            order_reversed = order.startswith("-")
            order_attr = order.lstrip("-")

            is_nullable = any(order_attr.startswith(field) for field in self.nullable_fields)

            # When moving forward in DESC order, or backward in ASC order.
            is_less_than = direction_reverse != order_reversed

            if position is None:
                # The cursor landed on a null value.
                q_equals = Q(**{f"{order_attr}__isnull": True})

                if is_less_than:
                    # Transitioning out of nulls.
                    q_compare = Q(**{f"{order_attr}__isnull": False})
                else:
                    # Transitioning in/beyond nulls.
                    # Nothing is greater than null so return nothing for this comparison,
                    # this evaluates to false and leaves the next field as the tie-breaker.
                    q_compare = Q(pk__in=[])
            else:
                # The cursor landed on a non-null value.
                q_equals = Q(**{order_attr: position})

                compare_op = "lt" if is_less_than else "gt"
                q_compare = Q(**{f"{order_attr}__{compare_op}": position})

                if is_nullable and not is_less_than:
                    # Transitioning into nulls.
                    q_compare |= Q(**{f"{order_attr}__isnull": True})

            filter_q |= accumulated_equals & q_compare
            accumulated_equals &= q_equals

        return queryset.filter(filter_q)
