FROM enketo/enketo-express:4.1.1-4

EXPOSE 8005

#ADD config.json /srv/src/enketo_express/config/config.json
ADD ./docker/enketo/create_config.py /srv/src/enketo_express/setup/docker/create_config.py
