/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Iaso
 * Iaso Swagger
 * OpenAPI spec version: v1
 */
import { z as zod } from 'zod';

export const ApiProfilesUpdatePasswordUpdateBody = zod.strictObject({
    password: zod.string().min(1),
    confirm_password: zod.string().min(1),
});

export type ApiProfilesUpdatePasswordUpdateBody = zod.input<
    typeof ApiProfilesUpdatePasswordUpdateBody
>;
export type ApiProfilesUpdatePasswordUpdateBodyOutput = zod.output<
    typeof ApiProfilesUpdatePasswordUpdateBody
>;
