/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Iaso
 * Iaso Swagger
 * OpenAPI spec version: v1
 */
import { z as zod } from 'zod';

export const ApiProfilesDropdownRetrieveParams = zod.strictObject({
    format: zod.enum(['csv', 'json']).optional(),
});

export type ApiProfilesDropdownRetrieveParams = zod.input<
    typeof ApiProfilesDropdownRetrieveParams
>;
export type ApiProfilesDropdownRetrieveParamsOutput = zod.output<
    typeof ApiProfilesDropdownRetrieveParams
>;
