/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Iaso
 * Iaso Swagger
 * OpenAPI spec version: v1
 */
import { z as zod } from 'zod';

export const apiProfilesPartialUpdateBodyLanguageMax = 512;

export const apiProfilesPartialUpdateBodyHomePageMax = 512;

export const apiProfilesPartialUpdateBodyOrganizationMax = 512;

export const apiProfilesPartialUpdateBodyColorMax = 7;

export const apiProfilesPartialUpdateBodyColorRegExp = new RegExp(
    '#[0-9A-Fa-f]{6}',
);
export const apiProfilesPartialUpdateBodyDhis2IdMax = 128;

export const ApiProfilesPartialUpdateBody = zod.strictObject({
    language: zod
        .string()
        .max(apiProfilesPartialUpdateBodyLanguageMax)
        .nullish(),
    home_page: zod
        .string()
        .max(apiProfilesPartialUpdateBodyHomePageMax)
        .nullish(),
    first_name: zod.string().optional(),
    organization: zod
        .string()
        .max(apiProfilesPartialUpdateBodyOrganizationMax)
        .nullish(),
    last_name: zod.string().optional(),
    user_name: zod.string().min(1).optional(),
    email: zod.email().optional(),
    color: zod
        .string()
        .max(apiProfilesPartialUpdateBodyColorMax)
        .regex(apiProfilesPartialUpdateBodyColorRegExp)
        .optional(),
    phone_number: zod.string().optional(),
    country_code: zod.string().nullish(),
    dhis2_id: zod
        .string()
        .max(apiProfilesPartialUpdateBodyDhis2IdMax)
        .nullish()
        .describe('Dhis2 user ID for SSO Auth'),
    user_permissions: zod.array(zod.string().min(1)).optional(),
    org_units: zod.array(zod.number()).optional(),
    editable_org_unit_type_ids: zod.array(zod.number()).optional(),
    projects: zod.array(zod.number()).optional(),
    user_roles: zod.array(zod.number()).optional(),
});

export type ApiProfilesPartialUpdateBody = zod.input<
    typeof ApiProfilesPartialUpdateBody
>;
export type ApiProfilesPartialUpdateBodyOutput = zod.output<
    typeof ApiProfilesPartialUpdateBody
>;
