/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Iaso
 * Iaso Swagger
 * OpenAPI spec version: v1
 */
import { z as zod } from 'zod';

export const nestedEditableOrgUnitTypeNameMax = 255;

export const NestedEditableOrgUnitType = zod.strictObject({
    id: zod.number(),
    name: zod.string().max(nestedEditableOrgUnitTypeNameMax),
});

export type NestedEditableOrgUnitType = zod.input<
    typeof NestedEditableOrgUnitType
>;
export type NestedEditableOrgUnitTypeOutput = zod.output<
    typeof NestedEditableOrgUnitType
>;
