/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Iaso
 * Iaso Swagger
 * OpenAPI spec version: v1
 */
import { z as zod } from 'zod';

export const profileUpdateLanguageMax = 512;

export const profileUpdateHomePageMax = 512;

export const profileUpdateOrganizationMax = 512;

export const profileUpdateColorMax = 7;

export const profileUpdateColorRegExp = new RegExp('#[0-9A-Fa-f]{6}');
export const profileUpdateDhis2IdMax = 128;

export const ProfileUpdate = zod.strictObject({
    language: zod.string().max(profileUpdateLanguageMax).nullish(),
    home_page: zod.string().max(profileUpdateHomePageMax).nullish(),
    organization: zod.string().max(profileUpdateOrganizationMax).nullish(),
    color: zod
        .string()
        .max(profileUpdateColorMax)
        .regex(profileUpdateColorRegExp)
        .optional(),
    phone_number: zod.string().optional(),
    dhis2_id: zod
        .string()
        .max(profileUpdateDhis2IdMax)
        .nullish()
        .describe('Dhis2 user ID for SSO Auth'),
    user_permissions: zod.array(zod.string()).optional(),
    org_units: zod.array(zod.number()).optional(),
    editable_org_unit_type_ids: zod.array(zod.number()).optional(),
    projects: zod.array(zod.number()).optional(),
    user_roles: zod.array(zod.number()).optional(),
});

export type ProfileUpdate = zod.input<typeof ProfileUpdate>;
export type ProfileUpdateOutput = zod.output<typeof ProfileUpdate>;
