import logging
from django.db import models
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from .couchdb_helpers import create_db, delete_user, generate_db_name

logger = logging.getLogger(__name__)


class DeviceDB(models.Model):
    '''
    Keeps the device and its last successful sync import.

    :ivar text     device_id: **unique** -- Device id generated by Sense-HAT-mobile App.
    :ivar datetime last_synced_date: Timestamp of the last successful sync import.
    :ivar text     last_synced_seq: CouchDB ``last_seq`` value of the last successful sync import.
    :ivar text     last_synced_log_message: Contains information about how many
        records were created/updated during the last successful sync import.

    '''
    device_id = models.TextField(unique=True)

    # used to log the sync execution
    last_synced_date = models.DateTimeField(null=True)
    last_synced_seq = models.TextField(null=True, default=0)
    last_synced_log_message = models.TextField(null=True)

    @property
    def db_name(self) -> str:
        ''' Returns the device CouchDB database name. '''
        return generate_db_name(self.device_id)


@receiver(post_save, sender=DeviceDB)
def device_db_post_save(sender, instance, *args, **kwargs):  # type: ignore
    # Create the accompaning couchdb db for the device db record
    create_db(instance.device_id)


class DeviceDBView(models.Model):
    '''
    References a postgresql view that retrieves data about devices and their
    last successful sync import. Sometimes the device data come only via
    encrypted backup files and not via sync.

    :ivar text     device_id: **unique** -- Device id generated by Sense-HAT-mobile App.
    :ivar datetime last_synced_date: Timestamp of the last successful sync import.
    :ivar text     last_synced_seq: CouchDB ``last_seq`` value of the last successful sync import.
    :ivar text     last_synced_stats: Contains information about how many
        records were created/updated during the last successful sync import.

    :ivar boolean  is_synced:    Indicates if the device activated sync.
    :ivar datetime date_first:   First document date for this device.
    :ivar datetime date_last:    Last document date for this device.
    :ivar integer  locations:    Number of visited villages with this device.
    :ivar integer  participants: Number of screened people with this device.

    '''

    device_id = models.TextField(primary_key=True)

    # used to log the sync execution
    last_synced_date = models.DateTimeField(null=True)
    last_synced_seq = models.TextField(null=True)
    last_synced_stats = models.TextField(null=True)

    is_synced = models.NullBooleanField()
    date_first = models.DateTimeField(null=True)
    date_last = models.DateTimeField(null=True)
    locations = models.PositiveIntegerField(null=True)
    participants = models.PositiveIntegerField(null=True)

    class Meta:
        managed = False
        db_table = 'sync_devicedb_view'


class MobileUser(models.Model):
    '''
    List of granted google user accounts.
    If the device user account is not in this table, the device is not allowed to sync.

    :ivar text email: **unique** --  Validated google user email.

    '''
    email = models.EmailField(unique=True)


@receiver(post_delete, sender=MobileUser)
def mobile_user_post_delete(sender, instance, *args, **kwargs):  # type: ignore
    # When a Mobile User is deleted, delete the CouchDB user to revoke sync access
    delete_user(instance.email)
