import logging

from django.contrib.auth.models import User
from django.contrib.postgres.fields import JSONField
from django.db import models
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.forms import ModelForm
from django.utils import timezone

from hat.constants import TEST_TYPE_CHOICES
from hat.geo.models import PopulationData
from .couchdb_helpers import create_db, delete_user, generate_db_name

logger = logging.getLogger(__name__)


class DeviceDB(models.Model):
    """
    Keeps the device and its last successful sync import.

    :ivar text     device_id: **unique** -- Device id generated by Sense-HAT-mobile App.
    :ivar datetime last_synced_date: Timestamp of the last successful sync import.
    :ivar text     last_synced_seq: CouchDB ``last_seq`` value of the last successful sync import.
    :ivar text     last_synced_log_message: Contains information about how many
        records were created/updated during the last successful sync import.

    """
    device_id = models.TextField(unique=True)
    creator = models.ForeignKey(User, related_name='devicedb_creator', on_delete=models.DO_NOTHING, null=True,
                                blank=True)
    last_user = models.ForeignKey(User, related_name='devicedb_last_user', on_delete=models.DO_NOTHING, null=True,
                                  blank=True)

    # used to log the sync execution
    last_synced_date = models.DateTimeField(null=True)
    last_synced_seq = models.TextField(null=True, default=0)
    last_synced_log_message = models.TextField(null=True)
    is_test = models.BooleanField(default=False)

    def get_team(self):
        """Returns the team of the last user of this device"""
        if self.last_user is None \
                or self.last_user.profile is None \
                or self.last_user.profile.team is None:
            return None
        else:
            return self.last_user.profile.team

    @property
    def db_name(self) -> str:
        """ Returns the device CouchDB database name. """
        return generate_db_name(self.device_id)

    def days_since_sync(self):
        if not self.last_synced_date:
            return -1
        days_since = (timezone.now() - self.last_synced_date).days
        return days_since if days_since >= 0 else 0

    def __str__(self):
        return self.device_id

    def as_dict(self, full=True):
        result = {
            'id': self.id,
            'device_id': self.device_id,
        }
        if full:
            last_user = ""
            last_team = ""
            if self.last_user and self.last_user.profile:
                last_user = self.last_user.profile.full_name()
                if self.last_user.profile.team:
                    last_team = self.last_user.profile.team.name
            result['last_user'] = last_user
            result['last_team'] = last_team
            result['is_test'] = self.is_test

        return result


@receiver(post_save, sender=DeviceDB)
def device_db_post_save(sender, instance, *args, **kwargs):  # type: ignore
    # Create the accompanying couchdb db for the device db record
    create_db(instance.device_id)


class DeviceImportEvent(models.Model):
    """
    Keeps the details about the various imports from devices
    """

    FETCH_COUCHDB = 0
    IMPORTED = 1
    ERROR = 2

    IMPORT_EVENT_TYPES = (
        (FETCH_COUCHDB, 'Data fetched from CouchDB'),
        (IMPORTED, 'Data actually imported into the DB'),
        (ERROR, 'Any error')
    )
    event_type = models.IntegerField(choices=IMPORT_EVENT_TYPES, default=FETCH_COUCHDB)
    device = models.ForeignKey(DeviceDB, on_delete=models.CASCADE)
    date = models.DateTimeField(null=True, auto_now_add=True)
    total_records = models.IntegerField(null=True)
    created_records = models.IntegerField(null=True)
    updated_records = models.IntegerField(null=True)
    deleted_records = models.IntegerField(null=True)
    errors = models.IntegerField(null=True)
    last_synced_seq = models.IntegerField(null=True)
    details = models.TextField(null=True)


class DeviceDBView(models.Model):
    '''
    References a postgresql view that retrieves data about devices and their
    last successful sync import. Sometimes the device data come only via
    encrypted backup files and not via sync.

    :ivar text     device_id: **unique** -- Device id generated by Sense-HAT-mobile App.
    :ivar datetime last_synced_date: Timestamp of the last successful sync import.
    :ivar text     last_synced_seq: CouchDB ``last_seq`` value of the last successful sync import.
    :ivar text     last_synced_stats: Contains information about how many
        records were created/updated during the last successful sync import.

    :ivar boolean  is_synced:    Indicates if the device activated sync.
    :ivar datetime date_first:   First document date for this device.
    :ivar datetime date_last:    Last document date for this device.
    :ivar integer  locations:    Number of visited villages with this device.
    :ivar integer  participants: Number of screened people with this device.

    '''

    device_id = models.TextField(primary_key=True)

    # used to log the sync execution
    last_synced_date = models.DateTimeField(null=True)
    last_synced_seq = models.TextField(null=True)
    last_synced_stats = models.TextField(null=True)

    is_synced = models.NullBooleanField()
    date_first = models.DateTimeField(null=True)
    date_last = models.DateTimeField(null=True)
    locations = models.PositiveIntegerField(null=True)
    participants = models.PositiveIntegerField(null=True)

    class Meta:
        managed = False
        db_table = 'sync_devicedb_view'


class DeviceStatus(models.Model):
    label = models.TextField()

    def __str__(self):
        return self.label


class DeviceAction(models.Model):
    label = models.TextField()

    def __str__(self):
        return self.label


class DeviceEvent(models.Model):
    STATUS_CHANGE = 0
    ACTION = 1
    COMMENT = 2

    EVENT_TYPES = (
        (STATUS_CHANGE, 'Status Change'),
        (ACTION, 'Action'),
        (COMMENT, 'Comment')
    )

    device = models.ForeignKey(DeviceDB, on_delete=models.CASCADE)
    date = models.DateTimeField(null=True, auto_now_add=True)
    status = models.ForeignKey(DeviceStatus, null=True, blank=True, on_delete=models.CASCADE)
    action = models.ForeignKey(DeviceAction, null=True, blank=True, on_delete=models.CASCADE)
    comment = models.TextField(null=True, blank=True)
    event_type = models.IntegerField(choices=EVENT_TYPES, default=STATUS_CHANGE)
    reporter = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return ("event %s - device %s - status %s - action %s - comment %s" % (self.event_type,
                                                                               self.device_id,
                                                                               self.status,
                                                                               self.action,
                                                                               self.comment
                                                                               ))


class DeviceEventForm(ModelForm):
    class Meta:
        model = DeviceEvent
        fields = ('status', 'action', 'comment', 'event_type')


class MobileUser(models.Model):
    '''
    List of granted google user accounts.
    If the device user account is not in this table, the device is not allowed to sync.

    :ivar text email: **unique** --  Validated google user email.

    '''
    email = models.EmailField(unique=True)


@receiver(post_delete, sender=MobileUser)
def mobile_user_post_delete(sender, instance, *args, **kwargs):  # type: ignore
    # When a Mobile User is deleted, delete the CouchDB user to revoke sync access
    delete_user(instance.email)


class ImageUpload(models.Model):
    UPLOADED_TO = 'images/'
    participant_uuid = models.TextField(null=True, blank=True, db_index=True)
    hat_id = models.TextField(null=True, blank=True)
    group_id = models.TextField(null=True, blank=True, db_index=True)
    type = models.TextField(default='CATT', choices=TEST_TYPE_CHOICES)
    image = models.FileField(upload_to=UPLOADED_TO)
    upload_date = models.DateTimeField(auto_now_add=True)

    def semantic_id(self):
        if self.participant_uuid:
            return self.participant_uuid
        else:
            return self.group_id

    def __str__(self):
        return "%s - %s" % (str(self.upload_date), self.semantic_id())


class VideoUpload(models.Model):
    UPLOADED_TO = 'videos/'
    participant_uuid = models.TextField(db_index=True)
    hat_id = models.TextField()
    group_id = models.TextField(null=True, blank=True, db_index=True)
    type = models.TextField(default='PG', choices=TEST_TYPE_CHOICES)
    video = models.FileField(upload_to=UPLOADED_TO)
    upload_date = models.DateTimeField(auto_now_add=True)

    def semantic_id(self):
        if self.participant_uuid:
            return self.participant_uuid
        else:
            return self.group_id

    def __str__(self):
        return "%s - %s" % (str(self.upload_date), self.semantic_id())


class ImageUploadForm(ModelForm):
    class Meta:
        model = ImageUpload
        fields = ('image', 'participant_uuid', 'hat_id', 'group_id', 'type')


class VideoUploadForm(ModelForm):
    class Meta:
        model = VideoUpload
        fields = ('video', 'participant_uuid', 'hat_id', 'group_id', 'type')


JSONDOCUMENT_TYPE_CHOICES = (
    ('participant', 'participant information, including tests'),
    ('ptr', 'Population data provided by tablets'),
)


class JSONDocument(models.Model):
    doc_id = models.TextField()
    doc_revision = models.TextField()
    device = models.ForeignKey(DeviceDB, on_delete=models.CASCADE)
    case = models.ForeignKey(to="cases.Case", on_delete=models.SET_NULL, null=True, blank=True)
    population = models.ForeignKey(to=PopulationData, on_delete=models.SET_NULL, null=True, blank=True)
    type = models.TextField(choices=JSONDOCUMENT_TYPE_CHOICES, default='participant')
    doc = JSONField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    processed = models.NullBooleanField(default=False)

    # To be activated when duplicates have been removed
    class Meta:
        unique_together = ('doc_id', 'doc_revision')

    def __str__(self):
        return "id %s - revision %s - device %s" % (self.doc_id, self.doc_revision, self.device)
