# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-06 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_auto_20180105_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='as',
            options={'verbose_name_plural': 'AS'},
        ),
        migrations.AlterModelOptions(
            name='zs',
            options={'verbose_name_plural': 'ZS'},
        ),
    ]
