# Generated by Django 2.0 on 2018-03-22 10:02
from django.contrib.postgres.operations import CreateExtension, TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_adding_aliases'),
    ]

    operations = [
        CreateExtension("postgis"),
        TrigramExtension(),
    ]
