# Generated by Django 2.0 on 2018-03-22 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_adding_aliases'),
    ]

    operations = [
        migrations.RunSQL(sql='CREATE EXTENSION IF NOT EXISTS postgis;',
                          reverse_sql='DROP EXTENSION IF EXISTS postgis RESTRICT;')
    ]
