# Generated by Django 2.0 on 2018-03-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0006_citext'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='village_source',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
