# Generated by Django 2.0.4 on 2018-04-05 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0008_revert_aliases_to_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZSASMappingImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ZSASMappingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.IntegerField()),
                ('case_province', models.TextField(blank=True, null=True)),
                ('case_zs', models.TextField(blank=True, null=True)),
                ('case_as', models.TextField(blank=True, null=True)),
                ('match_province', models.TextField(blank=True, null=True)),
                ('match_zs', models.TextField(blank=True, null=True)),
                ('match_as', models.TextField(blank=True, null=True)),
                ('match_yesno', models.CharField(blank=True, max_length=20, null=True)),
                ('match_comment', models.TextField(blank=True, null=True)),
                ('added_zone_alias', models.BooleanField(default=False)),
                ('added_area_alias', models.BooleanField(default=False)),
                ('zsas_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.ZSASMappingImport')),
            ],
        ),
    ]
