# Generated by Django 2.0 on 2018-04-11 16:35

import django.contrib.postgres.fields
import django.contrib.postgres.fields.citext
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0009_zsasimport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='as',
            name='aliases',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.citext.CITextField(blank=True, max_length=255), blank=True, null=True, size=4),
        ),
        migrations.AlterField(
            model_name='province',
            name='aliases',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.citext.CITextField(blank=True, max_length=255), blank=True, null=True, size=4),
        ),
        migrations.AlterField(
            model_name='village',
            name='aliases',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.citext.CITextField(blank=True, max_length=255), blank=True, null=True, size=4),
        ),
        migrations.AlterField(
            model_name='zs',
            name='aliases',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.citext.CITextField(blank=True, max_length=255), blank=True, null=True, size=4),
        ),
    ]
