# Generated by Django 2.0 on 2018-05-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0010_citext_again'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zsasmappingimport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
