# Generated by Django 2.0 on 2018-05-23 15:32

import django.contrib.postgres.fields
import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0011_resync_migrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='as',
            name='aliases',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.citext.CITextField(blank=True, max_length=255), blank=True, null=True, size=10),
        ),
        migrations.AlterField(
            model_name='province',
            name='aliases',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.citext.CITextField(blank=True, max_length=255), blank=True, null=True, size=10),
        ),
        migrations.AlterField(
            model_name='village',
            name='aliases',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.citext.CITextField(blank=True, max_length=255), blank=True, null=True, size=10),
        ),
        migrations.AlterField(
            model_name='zs',
            name='aliases',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.citext.CITextField(blank=True, max_length=255), blank=True, null=True, size=10),
        ),
    ]
