# Generated by Django 2.0 on 2018-06-25 09:07

import django.contrib.gis.db.models.fields
from django.db import migrations

# When importing the data from the shape files of UCLA, one can use this kind of query:
# update geo_as a set geom=st_setsrid(u.geom, 4326)
# from ucla_ha u, geo_zs z
# where (u.as_ ilike a.name or u.as_ = any(a.aliases))
# and (u.zs ilike z.name or u.zs = any(z.aliases))
# and a."ZS_id"=z.id


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0012_increase_your_aliases_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='as',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='village',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.RunSQL(
            sql='update geo_village set location=ST_SetSRID(ST_MakePoint(longitude, latitude),4326) '
                'where location is null and latitude is not null and longitude is not null',
        ),  # no need for reverse SQL since this column would just be deleted
    ]
