# Generated by Django 2.0 on 2018-09-11 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0022_jsondocuments_unique'),
        ('geo', '0014_geo_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='creator_device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sync.DeviceDB'),
        ),
    ]
