# Generated by Django 2.0 on 2018-10-22 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0022_jsondocuments_unique'),
        ('geo', '0017_village_sources_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopulationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population', models.IntegerField()),
                ('type', models.TextField(choices=[('PTR', 'Population Totale Recensée'), ('PTE', 'Population Totale Estimée')], default='PTR')),
                ('source', models.TextField(default='device')),
                ('population_year', models.IntegerField()),
                ('report_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sync.DeviceDB')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geo.Village')),
            ],
        ),
        migrations.RunSQL(sql="insert into geo_populationdata (population, type, source, population_year, report_date, "
                              "created_at, village_id) select population, 'PTR', coalesce(population_source, 'ucla'), "
                              "population_year, ('01-01-' || population_year)::timestamp, now(), v.id "
                              "from geo_village v where population is not null and population_year is not null;",
                          reverse_sql=""),
    ]
