# Generated by Django 2.0 on 2018-10-25 14:10

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0018_ptr'),
    ]

    operations = [
        migrations.RunSQL(sql="create table old_geo_as as select * from geo_as",
                          reverse_sql=""),
        migrations.RunSQL(sql="update geo_as set geom=null",
                          reverse_sql=""),
        migrations.RunSQL(sql="create table old_geo_zs as select * from geo_zs",
                          reverse_sql=""),
        migrations.RunSQL(sql="update geo_zs set geom=null",
                          reverse_sql=""),
        migrations.RunSQL(sql="create table old_geo_province as select * from geo_province",
                          reverse_sql=""),
        migrations.RunSQL(sql="update geo_province set geom=null", reverse_sql=""),
        migrations.RunSQL(sql="drop view if exists snapshot.areas", reverse_sql=""),
        migrations.AddField(
            model_name='as',
            name='simplified_geom',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='province',
            name='simplified_geom',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='zs',
            name='simplified_geom',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='as',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='province',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='zs',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
        # A little word on this weird query:
        # We were using multipolygon while only half a dozen of the AS did actually have more than one polygon
        # Those multiple polygons were incorrect. Most being just tiny lines. So after careful verification,
        # we decided to remove the smallest polygons.
        # Now, to split a multipolygon into several polygon objects, one has to use ST_Dump() (opposite of ST_Collect())
        # But that function returns a *set* of objects that cannot be manipulated directly. You can't length(ST_Dump())
        # not count(ST_Dump()). The only way is to make an intermediate table. To avoid adding another table to the mix,
        # we're using the `using foo as (select....) select * from foo` notation
        # And from there, we exclude the surfaces smaller than 0.0000005. This number is slightly larger than the
        # biggest junk shape and much smaller than the smallest useful shape.
        # migrations.RunSQL(
        #     sql="with split_as as (select id, name, (st_dump(geom)).path as path, (st_dump(geom)).geom as geom, "
        #         "st_area((st_dump(geom)).geom) as area from old_geo_as) "
        #         "update geo_as a set geom=old.geom::geometry(Polygon, 4326),"
        #         "simplified_geom=st_simplifypreservetopology("
        #         "(st_dump(old.geom)).geom::geometry(Polygon, 4326), 0.0001) "
        #         "from split_as old where a.id=old.id and area>0.0000005",
        #     reverse_sql=""),
        # migrations.RunSQL(
        #     sql="update geo_zs z set geom=za.geom, simplified_geom=za.simplified_geom, geom_source='ucla' "
        #         "from (select a.\"ZS_id\" as zs_id, st_makepolygon(st_exteriorring(st_union(a.geom))) as geom, "
        #         "st_makepolygon(st_exteriorring(st_union(a.simplified_geom))) as simplified_geom "
        #         " from geo_as a "
        #         "where a.geom_source='ucla' "
        #         "group by a.\"ZS_id\") za "
        #         "where za.zs_id=z.id",
        #     reverse_sql=""),
        # migrations.RunSQL(sql="update geo_province p set geom=(st_dump(old.geom)).geom::geometry(Polygon, 4326),"
        #                       "simplified_geom=st_simplifypreservetopology("
        #                       "(st_dump(old.geom)).geom::geometry(Polygon, 4326), 0.0001) "
        #                       "from old_geo_province old where p.id=old.id",
        #                   reverse_sql=""),

    ]
