# Generated by Django 2.0 on 2018-11-08 12:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0019_geom_polygon'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('source', models.TextField(choices=[('snis', 'SNIS'), ('ucla', 'UCLA'), ('pnltha', 'PNL THA'), ('derivated', 'Derivated from actual data')], null=True)),
                ('source_ref', models.TextField(null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('AS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.AS')),
            ],
        ),
    ]
