# Generated by Django 2.0 on 2018-12-12 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0020_healthstructure'),
    ]

    operations = [
        migrations.RunSQL(sql="update geo_healthstructure set location=st_flipcoordinates(location) "
                              "where location is not null",
                          reverse_sql="update geo_healthstructure "
                              "set location=st_flipcoordinates(location) where location is not null")
    ]
