# Generated by Django 2.0 on 2019-02-14 08:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0021_invert_health_struct_coords'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeopodeSettlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_code', models.TextField(blank=True, null=True)),
                ('province_name', models.TextField(blank=True, null=True)),
                ('zone_code', models.TextField(blank=True, null=True)),
                ('zone_name', models.TextField(blank=True, null=True)),
                ('area_code', models.TextField(blank=True, null=True)),
                ('area_name', models.TextField(blank=True, null=True)),
                ('guid', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('lat', models.TextField(blank=True, null=True)),
                ('long', models.TextField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('pop_female', models.IntegerField(blank=True, null=True)),
                ('pop_male', models.IntegerField(blank=True, null=True)),
                ('pop_total', models.IntegerField(blank=True, null=True)),
                ('normalized_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geo.AS')),
                ('normalized_village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geo.Village')),
                ('normalized_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geo.ZS')),
            ],
        ),
    ]
