# Generated by Django 2.0 on 2019-06-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0022_import_geopode'),
    ]

    operations = [
        migrations.AddField(
            model_name='as',
            name='is_erased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zs',
            name='is_erased',
            field=models.BooleanField(default=False),
        ),
    ]
