# Generated by Django 4.2.13 on 2024-09-06 08:42

import django.db.models.deletion

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("audit", "0004_alter_modification_object_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modification",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunSQL(
            sql="update audit_modification set user_id = null where user_id not in (select id from auth_user)",
            reverse_sql="",
        ),
    ]
