# Generated by Django 4.2.20 on 2025-04-01 13:01

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0236_auto_20231012_0955"),
        ("audit", "0005_alter_modification_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="modification",
            name="org_unit_change_request",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="iaso.orgunitchangerequest"
            ),
        ),
    ]
