/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Iaso
 * Iaso Swagger
 * OpenAPI spec version: v1
 */
import { z as zod } from 'zod';

export const apiV2OrgunittypesCreateBodyNameMax = 255;

export const apiV2OrgunittypesCreateBodyShortNameMax = 255;

export const apiV2OrgunittypesCreateBodyDepthMin = 0;
export const apiV2OrgunittypesCreateBodyDepthMax = 32767;

export const ApiV2OrgunittypesCreateBody = zod.strictObject({
    name: zod.string().min(1).max(apiV2OrgunittypesCreateBodyNameMax),
    short_name: zod
        .string()
        .min(1)
        .max(apiV2OrgunittypesCreateBodyShortNameMax),
    depth: zod
        .number()
        .min(apiV2OrgunittypesCreateBodyDepthMin)
        .max(apiV2OrgunittypesCreateBodyDepthMax)
        .nullish(),
    project_ids: zod.array(zod.number()),
    sub_unit_type_ids: zod.array(zod.number()),
    allow_creating_sub_unit_type_ids: zod.array(zod.number()),
    reference_forms_ids: zod.array(zod.number()).optional(),
});

export type ApiV2OrgunittypesCreateBody = zod.input<
    typeof ApiV2OrgunittypesCreateBody
>;
export type ApiV2OrgunittypesCreateBodyOutput = zod.output<
    typeof ApiV2OrgunittypesCreateBody
>;
