/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Iaso
 * Iaso Swagger
 * OpenAPI spec version: v1
 */
import { z as zod } from 'zod';

export const ApiV2OrgunittypesUpdateParams = zod.strictObject({
    format: zod.enum(['csv', 'json']).optional(),
});

export type ApiV2OrgunittypesUpdateParams = zod.input<
    typeof ApiV2OrgunittypesUpdateParams
>;
export type ApiV2OrgunittypesUpdateParamsOutput = zod.output<
    typeof ApiV2OrgunittypesUpdateParams
>;
