/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Iaso
 * Iaso Swagger
 * OpenAPI spec version: v1
 */
import { z as zod } from 'zod';

export const apiV2OrgunittypesPartialUpdateBodyNameMax = 255;

export const apiV2OrgunittypesPartialUpdateBodyShortNameMax = 255;

export const apiV2OrgunittypesPartialUpdateBodyDepthMin = 0;
export const apiV2OrgunittypesPartialUpdateBodyDepthMax = 32767;

export const ApiV2OrgunittypesPartialUpdateBody = zod.strictObject({
    name: zod
        .string()
        .min(1)
        .max(apiV2OrgunittypesPartialUpdateBodyNameMax)
        .optional(),
    short_name: zod
        .string()
        .min(1)
        .max(apiV2OrgunittypesPartialUpdateBodyShortNameMax)
        .optional(),
    depth: zod
        .number()
        .min(apiV2OrgunittypesPartialUpdateBodyDepthMin)
        .max(apiV2OrgunittypesPartialUpdateBodyDepthMax)
        .nullish(),
    project_ids: zod.array(zod.number()).optional(),
    sub_unit_type_ids: zod.array(zod.number()).optional(),
    allow_creating_sub_unit_type_ids: zod.array(zod.number()).optional(),
    reference_forms_ids: zod.array(zod.number()).optional(),
});

export type ApiV2OrgunittypesPartialUpdateBody = zod.input<
    typeof ApiV2OrgunittypesPartialUpdateBody
>;
export type ApiV2OrgunittypesPartialUpdateBodyOutput = zod.output<
    typeof ApiV2OrgunittypesPartialUpdateBody
>;
