/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Iaso
 * Iaso Swagger
 * OpenAPI spec version: v1
 */
import { z as zod } from 'zod';

export const nestedFormProjectsItemColorMax = 7;

export const nestedFormProjectsItemColorRegExp = new RegExp('#[0-9A-Fa-f]{6}');

export const NestedForm = zod.strictObject({
    id: zod.number(),
    form_id: zod.string().nullish(),
    created_at: zod.iso.datetime({ offset: true }),
    updated_at: zod.iso.datetime({ offset: true }),
    projects: zod.array(
        zod
            .strictObject({
                id: zod.number(),
                name: zod.string(),
                app_id: zod.string().nullish(),
                color: zod
                    .string()
                    .max(nestedFormProjectsItemColorMax)
                    .regex(nestedFormProjectsItemColorRegExp)
                    .nullish(),
            })
            .describe('Mimics project as_dict method'),
    ),
});

export type NestedForm = zod.input<typeof NestedForm>;
export type NestedFormOutput = zod.output<typeof NestedForm>;
