/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Iaso
 * Iaso Swagger
 * OpenAPI spec version: v1
 */
import { z as zod } from 'zod';

export const OrgUnitTypeHierarchyCategoryEnum = zod
    .enum(['COUNTRY', 'REGION', 'DISTRICT', 'HF'])
    .describe(
        '\* `COUNTRY` - Country\n\* `REGION` - Region\n\* `DISTRICT` - District\n\* `HF` - Health Facility',
    );

export type OrgUnitTypeHierarchyCategoryEnum = zod.input<
    typeof OrgUnitTypeHierarchyCategoryEnum
>;
export type OrgUnitTypeHierarchyCategoryEnumOutput = zod.output<
    typeof OrgUnitTypeHierarchyCategoryEnum
>;
