# Generated by Django 3.0.14 on 2021-05-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0004_auto_20210505_1813"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="budget_submitted_at",
            field=models.DateField(blank=True, null=True, verbose_name="Budget Submission"),
        ),
        migrations.AddField(
            model_name="campaign",
            name="district_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
