# Generated by Django 3.0.14 on 2021-06-01 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polio", "0005_campaign_group"),
        ("polio", "0005_auto_20210528_1640"),
        ("polio", "0005_auto_20210525_1849"),
    ]

    operations = []
