# Generated by Django 3.0.14 on 2021-06-02 16:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0006_merge_20210602_1150"),
        ("polio", "0006_merge_20210602_0635"),
    ]

    operations = []
