# Generated by Django 3.0.14 on 2021-06-01 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polio", "0006_merge_20210601_1717"),
        ("polio", "0006_merge_20210601_1619"),
        ("polio", "0006_merge_20210601_1708"),
    ]

    operations = []
