# Generated by Django 3.0.14 on 2021-06-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0008_auto_20210603_1656"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="unicef_disbursed_to_co_at",
            field=models.DateField(blank=True, null=True, verbose_name="Disbursed to CO (UNICEF)"),
        ),
        migrations.AddField(
            model_name="campaign",
            name="unicef_disbursed_to_moh_at",
            field=models.DateField(blank=True, null=True, verbose_name="Disbursed to MOH (UNICEF)"),
        ),
        migrations.AddField(
            model_name="campaign",
            name="who_disbursed_to_co_at",
            field=models.DateField(blank=True, null=True, verbose_name="Disbursed to CO (WHO)"),
        ),
        migrations.AddField(
            model_name="campaign",
            name="who_disbursed_to_moh_at",
            field=models.DateField(blank=True, null=True, verbose_name="Disbursed to MOH (WHO)"),
        ),
    ]
