# Generated by Django 3.0.14 on 2021-06-08 08:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0009_auto_20210604_1027"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="country_name_in_surge_spreadsheet",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="surge_spreadsheet_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Surge",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("spreadsheet_url", models.URLField()),
                (
                    "who_recruitment",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Recruitment WHO"),
                ),
                (
                    "who_completed_recruitment",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Completed for WHO"),
                ),
                (
                    "unicef_recruitment",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Recruitment UNICEF"),
                ),
                (
                    "unicef_completed_recruitment",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Completed for UNICEF"),
                ),
                ("payload", django.contrib.postgres.fields.jsonb.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("campaign", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="polio.Campaign")),
            ],
        ),
    ]
