# Generated by Django 3.0.14 on 2021-06-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0010_auto_20210608_0838"),
    ]

    operations = [
        migrations.AddField(
            model_name="surge",
            name="surge_country_name",
            field=models.CharField(default=True, max_length=250, null=True),
        ),
    ]
