# Generated by Django 3.1.12 on 2021-06-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0011_surge_surge_country_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preparedness",
            name="payload",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="surge",
            name="payload",
            field=models.JSONField(),
        ),
    ]
