# Generated by Django 3.1.12 on 2021-06-30 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0099_orgunittype_category"),
        ("polio", "0014_merge_20210630_1106"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="budget_status",
            field=models.CharField(
                blank=True,
                choices=[("PENDING", "Pending"), ("ONGOING", "Ongoing"), ("FINISHED", "Finished")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="detection_status",
            field=models.CharField(
                choices=[("PENDING", "Pending"), ("ONGOING", "Ongoing"), ("FINISHED", "Finished")],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="group",
            field=models.ForeignKey(
                blank=True,
                default=None,
                limit_choices_to={"domain": "POLIO"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaigns",
                to="iaso.group",
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="preperadness_sync_status",
            field=models.CharField(
                choices=[("QUEUED", "Queued"), ("ONGOING", "Ongoing"), ("FAILURE", "Failed"), ("FINISHED", "Finished")],
                default="FINISHED",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="risk_assessment_status",
            field=models.CharField(
                blank=True,
                choices=[("PENDING", "Pending"), ("ONGOING", "Ongoing"), ("FINISHED", "Finished")],
                max_length=10,
                null=True,
            ),
        ),
    ]
