# Generated by Django 3.1.12 on 2021-07-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0018_campaign_vials_requested"),
    ]

    operations = [
        migrations.AddField(
            model_name="round",
            name="im_percentage_children_missed_in_plus_out_household",
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="budget_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("APPROVED", "Approved"),
                    ("TO_SUBMIT", "To Submit"),
                    ("SUBMITTED", "Submitted"),
                    ("REVIEWED", "Reviewed by RRT"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="risk_assessment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("APPROVED", "Approved"),
                    ("TO_SUBMIT", "To Submit"),
                    ("SUBMITTED", "Submitted"),
                    ("REVIEWED", "Reviewed by RRT"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
