# Generated by Django 3.1.12 on 2021-08-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polio", "0021_auto_20210805_1750"),
    ]

    operations = [
        migrations.CreateModel(
            name="LineListImport",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to="uploads/linelist/% Y/% m/% d/")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
