# Generated by Django 3.1.12 on 2021-08-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0023_countryusersgroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="countryusersgroup",
            name="language",
            field=models.CharField(choices=[("FR", "Français"), ("EN", "English")], default="FR", max_length=32),
        ),
    ]
