# Generated by Django 3.1.12 on 2021-09-01 12:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0024_countryusersgroup_language"),
        ("polio", "0023_linelistimport"),
    ]

    operations = []
