# Generated by Django 3.1.12 on 2021-09-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0025_merge_20210901_1222"),
    ]

    operations = [
        migrations.AlterField(
            model_name="countryusersgroup",
            name="language",
            field=models.CharField(choices=[("FR", "Français"), ("EN", "English")], default="EN", max_length=32),
        ),
    ]
