# Generated by Django 3.1.12 on 2021-09-30 09:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0028_remove_campaign_budget_first_draft_submitted_at"),
        ("polio", "0027_urlcache"),
    ]

    operations = []
