# Generated by Django 3.1.13 on 2021-10-04 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0107_auto_20211001_1845"),
        ("polio", "0028_remove_campaign_budget_first_draft_submitted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="country",
            field=models.ForeignKey(
                blank=True,
                help_text="Country for campaign, set automatically from initial_org_unit",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaigns_country",
                to="iaso.orgunit",
            ),
        ),
    ]
