# Generated by Django 3.1.13 on 2021-10-28 12:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0032_campaign_is_preventive"),
        ("polio", "0032_auto_20211024_2118"),
    ]

    operations = []
