# Generated by Django 3.1.13 on 2021-12-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0035_spreadsheetimport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spreadsheetimport",
            name="spread_id",
            field=models.CharField(db_index=True, max_length=60),
        ),
    ]
