# Generated by Django 3.1.13 on 2021-12-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0036_auto_20211203_1025"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="enable_send_weekly_email",
            field=models.BooleanField(default=False, help_text="Activate the sending of a remainder email every week."),
        ),
    ]
