# Generated by Django 3.1.14 on 2022-01-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0039_round_preparedness_spreadsheet_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="round",
            name="preparedness_sync_status",
            field=models.CharField(
                choices=[("QUEUED", "Queued"), ("ONGOING", "Ongoing"), ("FAILURE", "Failed"), ("FINISHED", "Finished")],
                default="FINISHED",
                max_length=10,
            ),
        ),
    ]
