# Generated by Django 3.1.14 on 2022-02-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0042_auto_20220121_1434"),
    ]

    operations = [
        migrations.AlterField(
            model_name="round",
            name="awareness_of_campaign_planning",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="round",
            name="im_percentage_children_missed_in_household",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="round",
            name="im_percentage_children_missed_in_plus_out_household",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="round",
            name="im_percentage_children_missed_out_household",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
