# Generated by Django 3.1.14 on 2022-02-24 11:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0043_auto_20220210_1045"),
        ("polio", "0043_imstatscache_lqasimcache"),
    ]

    operations = []
