# Generated by Django 3.1.14 on 2022-04-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0045_auto_20220308_1410"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignGroup",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("campaigns", models.ManyToManyField(related_name="groups", to="polio.Campaign")),
            ],
        ),
    ]
