# Generated by Django 3.1.14 on 2022-04-08 09:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0046_auto_20220323_1055"),
        ("polio", "0046_campaigngroup"),
    ]

    operations = []
