# Generated by Django 3.1 on 2022-04-12 09:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0047_campaign_is_test"),
        ("polio", "0047_merge_20220408_0926"),
    ]

    operations = []
