# Generated by Django 3.1.14 on 2022-04-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polio', '0047_campaigngroup_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigngroup',
            name='campaigns',
            field=models.ManyToManyField(related_name='grouped_campaigns', to='polio.Campaign'),
        ),
    ]
