# Generated by Django 3.2.13 on 2022-04-12 11:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0047_campaigngroup_deleted_at"),
        ("polio", "0048_merge_20220412_0946"),
    ]

    operations = []
