# Generated by Django 3.1.14 on 2022-04-12 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polio", "0050_imstatscache_lqasimcache"),
        ("polio", "0047_campaign_is_test"),
    ]

    operations = []
