# Generated by Django 3.2.13 on 2022-04-20 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0052_polio_migrate_multi_round"),
    ]

    operations = [
        migrations.AlterField(
            model_name="round",
            name="campaign",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="rounds", to="polio.campaign"
            ),
        ),
    ]
