# Generated by Django 3.2.13 on 2022-06-03 12:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0055_budgetevent_budgetfiles"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="budgetfiles",
            name="event",
        ),
        migrations.DeleteModel(
            name="BudgetEvent",
        ),
        migrations.DeleteModel(
            name="BudgetFiles",
        ),
    ]
