# Generated by Django 3.2.13 on 2022-06-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0059_alter_budgetfiles_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="budgetfiles",
            name="cc_emails",
        ),
        migrations.AddField(
            model_name="budgetevent",
            name="cc_emails",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="budgetevent",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
