# Generated by Django 3.2.13 on 2022-06-09 14:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0055_alter_campaign_options"),
        ("polio", "0060_auto_20220607_1350"),
    ]

    operations = []
