# Generated by Django 3.2.13 on 2022-06-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0065_auto_20220616_1603"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetevent",
            name="internal",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="budgetevent",
            name="status",
            field=models.CharField(
                choices=[("validation_ongoing", "Validation Ongoing"), ("validated", "Validated")],
                default="validation_ongoing",
                max_length=200,
                null=True,
            ),
        ),
    ]
