# Generated by Django 3.2.13 on 2022-07-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0066_auto_20220620_0902"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="enable_send_weekly_email",
            field=models.BooleanField(default=False, help_text="Activate the sending of a reminder email every week."),
        ),
    ]
