# Generated by Django 3.2.13 on 2022-07-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0067_alter_campaign_enable_send_weekly_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="cvdpv2_notified_at",
            field=models.DateField(blank=True, null=True, verbose_name="cVDPV2 Notification"),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="cvdpv_notified_at",
            field=models.DateField(blank=True, null=True, verbose_name="cVDPV Notification"),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="pv2_notified_at",
            field=models.DateField(blank=True, null=True, verbose_name="PV2 Notification"),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="pv_notified_at",
            field=models.DateField(blank=True, null=True, verbose_name="PV Notification"),
        ),
    ]
