# Generated by Django 3.2.13 on 2022-07-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0069_budgetevent_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("submission", "Budget Submission"),
                    ("comments", "Comments"),
                    ("validation", "Approval"),
                    ("request", "Request"),
                    ("feedback", "Feedback"),
                    ("review", "Review"),
                    ("transmission", "Transmission"),
                ],
                max_length=200,
            ),
        ),
    ]
