# Generated by Django 3.2.15 on 2022-08-26 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0070_alter_budgetevent_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetfiles",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="event_files", to="polio.budgetevent"
            ),
        ),
    ]
