# Generated by Django 3.2.14 on 2022-08-10 09:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0070_alter_budgetevent_type"),
        ("polio", "0071_multi_scope"),
    ]

    operations = []
