# Generated by Django 3.2.15 on 2022-09-02 08:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0071_alter_budgetfiles_event"),
        ("polio", "0072_merge_0070_alter_budgetevent_type_0071_multi_scope"),
    ]

    operations = []
