# Generated by Django 3.2.15 on 2022-09-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0073_merge_20220902_0833"),
    ]

    operations = [
        migrations.AddField(
            model_name="round",
            name="doses_requested",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
