# Generated by Django 3.2.14 on 2022-09-09 13:43

from django.db import migrations, models
import plugins.polio.models


class Migration(migrations.Migration):

    dependencies = [
        ("polio", "0073_merge_20220902_0833"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="form_template",
            field=models.FileField(
                blank=True, null=True, upload_to=plugins.polio.models._campaign_template_form_upload_to
            ),
        ),
    ]
