# Generated by Django 3.2.15 on 2022-09-05 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0162_merge_20220901_1052"),
        ("polio", "0073_merge_20220902_0833"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaigns",
                to="iaso.account",
            ),
        ),
    ]
