# Generated by Django 3.2.15 on 2022-09-22 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polio', '0074_campaign_form_template'),
        ('polio', '0075_migrate_doses_requested'),
    ]

    operations = [
    ]
