# Generated by Django 3.2.15 on 2022-09-05 10:38

# Since we've assigned all campaigns to an account in a previous migration, we can now tighten the system by making the
# account field non-nullable
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0162_merge_20220901_1052"),
        ("polio", "0075_assign_existing_campaigns_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="campaigns", to="iaso.account"
            ),
        ),
    ]
