# Generated by Django 3.2.15 on 2022-09-23 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polio", "0075_migrate_doses_requested"),
        ("polio", "0076_alter_campaign_account"),
    ]

    operations = []
