# Generated by Django 3.2.15 on 2022-09-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0078_auto_20220920_1212"),
    ]

    operations = [
        migrations.RenameField(
            model_name="roundvaccine",
            old_name="wastage_ratio",
            new_name="wastage_ratio_forecast",
        ),
        migrations.RemoveField(
            model_name="roundvaccine",
            name="date_destruction",
        ),
        migrations.RemoveField(
            model_name="roundvaccine",
            name="date_signed_vrf_received",
        ),
        migrations.RemoveField(
            model_name="roundvaccine",
            name="forma_missing_vials",
        ),
        migrations.RemoveField(
            model_name="roundvaccine",
            name="forma_reception",
        ),
        migrations.RemoveField(
            model_name="roundvaccine",
            name="forma_unusable_vials",
        ),
        migrations.RemoveField(
            model_name="roundvaccine",
            name="forma_usable_vials",
        ),
        migrations.RemoveField(
            model_name="roundvaccine",
            name="reporting_delays_district_to_region",
        ),
        migrations.RemoveField(
            model_name="roundvaccine",
            name="reporting_delays_hc_to_district",
        ),
        migrations.RemoveField(
            model_name="roundvaccine",
            name="reporting_delays_region_to_national",
        ),
        migrations.RemoveField(
            model_name="roundvaccine",
            name="vials_destroyed",
        ),
        migrations.AddField(
            model_name="round",
            name="date_destruction",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="round",
            name="date_signed_vrf_received",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="round",
            name="forma_missing_vials",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="round",
            name="forma_reception",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="round",
            name="forma_unusable_vials",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="round",
            name="forma_usable_vials",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="round",
            name="reporting_delays_district_to_region",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="round",
            name="reporting_delays_hc_to_district",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="round",
            name="reporting_delays_region_to_national",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="round",
            name="vials_destroyed",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
