# Generated by Django 3.2.15 on 2022-09-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0080_auto_20220921_0943"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roundvaccine",
            name="wastage_ratio_forecast",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
