# Generated by Django 3.2.15 on 2022-09-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0081_alter_roundvaccine_wastage_ratio_forecast"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roundvaccine",
            name="wastage_ratio_forecast",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
