# Generated by Django 3.2.15 on 2022-09-26 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polio", "0077_auto_20220926_0731"),
        ("polio", "0082_alter_roundvaccine_wastage_ratio_forecast"),
    ]

    operations = []
