# Generated by Django 3.2.15 on 2022-10-21 11:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0076_alter_campaign_account"),
        ("polio", "0082_alter_roundvaccine_wastage_ratio_forecast"),
    ]

    operations = []
