# Generated by Django 3.2.15 on 2022-10-03 12:52

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.citext
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("iaso", "0167_merge_20220909_1207"),
        ("polio", "0082_alter_roundvaccine_wastage_ratio_forecast"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetStep",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("transition_key", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("comment", models.TextField()),
                (
                    "links",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.citext.CITextField(blank=True, max_length=255),
                        blank=True,
                        null=True,
                        size=100,
                    ),
                ),
                ("amount", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("is_email_sent", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="campaign",
            name="budget_current_state_key",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="budget_current_state_label",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="BudgetStepFiles",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="files", to="polio.budgetstep"
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget Step File",
                "verbose_name_plural": "Budget Step Files",
            },
        ),
        migrations.AddField(
            model_name="budgetstep",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="budget_steps", to="polio.campaign"
            ),
        ),
        migrations.AddField(
            model_name="budgetstep",
            name="created_by",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="budgetstep",
            name="created_by_team",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="iaso.team"),
        ),
    ]
