# Generated by Django 3.2.15 on 2022-10-05 11:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0085_auto_20221003_1629"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BudgetStepFiles",
            new_name="BudgetStepFile",
        ),
    ]
