# Generated by Django 3.2.15 on 2022-10-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0087_budgetstepfile_filename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetstep",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
