# Generated by Django 3.2.15 on 2022-10-05 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0089_remove_budgetstep_links"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetStepLink",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.CharField(max_length=500)),
                ("alias", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="links", to="polio.budgetstep"
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget Step Link",
                "verbose_name_plural": "Budget Step Link",
            },
        ),
    ]
