# Generated by Django 3.2.15 on 2022-10-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0091_budgetsteplink_deleted_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailTemplate",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(unique=True)),
                ("template", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
