# Generated by Django 3.2.15 on 2022-10-10 12:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0095_budgetstep_deleted_at"),
    ]

    operations = [
        migrations.RenameField("MailTemplate", "template", "html_template"),
    ]
