# Generated by Django 3.2.15 on 2022-10-10 12:17

from django.db import migrations, models
import plugins.polio.budget.models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0097_alter_mailtemplate_html_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailtemplate",
            name="text_template",
            field=models.TextField(
                default=" ",
                help_text="Plain text Template for the Email body, use the Django Template language, see https://docs.djangoproject.com/en/4.1/ref/templates/language/ for reference",
                validators=[plugins.polio.budget.models.validator_template],
            ),
            preserve_default=False,
        ),
    ]
