# Generated by Django 3.2.15 on 2022-10-12 08:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0096_alter_budgetstep_options"),
        ("polio", "0100_alter_mailtemplate_subject_template"),
    ]

    operations = []
