# Generated by Django 3.2.15 on 2022-10-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0103_workflowmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetstep",
            name="transition_key",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="budget_current_state_key",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
