# Generated by Django 3.2.15 on 2022-10-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polio", "0104_auto_20221014_1401"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="budget_current_state_key",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
    ]
