# Generated by Django 3.2.15 on 2022-11-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0173_storagedevice_org_unit"),
        ("polio", "0105_merge_20221021_1308"),
    ]

    operations = [
        migrations.AddField(
            model_name="countryusersgroup",
            name="teams",
            field=models.ManyToManyField(help_text="Teams used by the country", to="iaso.Team"),
        ),
    ]
