# Generated by Django 3.2.15 on 2022-11-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0176_storagedevice_status_updated_at"),
        ("polio", "0106_countryusersgroup_teams"),
    ]

    operations = [
        migrations.AlterField(
            model_name="countryusersgroup",
            name="teams",
            field=models.ManyToManyField(blank=True, help_text="Teams used by the country", to="iaso.Team"),
        ),
    ]
