# Generated by Django 3.2.15 on 2022-11-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0107_rename_doses_received_shipment_vials_received"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
