# Generated by Django 3.2.15 on 2022-11-04 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0109_destruction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destruction",
            name="round",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="destructions", to="polio.round"
            ),
        ),
    ]
