# Generated by Django 3.2.15 on 2022-11-10 10:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0107_alter_countryusersgroup_teams"),
        ("polio", "0110_alter_destruction_round"),
    ]

    operations = []
