# Generated by Django 3.2.15 on 2022-11-22 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polio", "0111_merge_20221110_0941"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CampaignFormTemplate",
        ),
    ]
