# Generated by Django 3.2.15 on 2022-11-23 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polio', '0112_delete_campaignformtemplate'),
        ('polio', '0113_merge_20221115_1540'),
    ]

    operations = [
    ]
