# Generated by Django 3.2.15 on 2022-12-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0114_alter_mailtemplate_subject_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetstep",
            name="node_key_from",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="budgetstep",
            name="node_key_to",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
