# Generated by Django 3.2.15 on 2022-12-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0114_alter_mailtemplate_subject_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="approved_at_WFEDITABLE",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="approved_by_unicef_at_WFEDITABLE",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="approved_by_who_at_WFEDITABLE",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="budget_requested_at_WFEDITABLE",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="feedback_sent_to_gpei_at_WFEDITABLE",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="feedback_sent_to_orpg_operations_unicef_at_WFEDITABLE",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="feedback_sent_to_orpg_operations_who_at_WFEDITABLE",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="feedback_sent_to_rrt1_at_WFEDITABLE",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="feedback_sent_to_rrt2_at_WFEDITABLE",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="feedback_sent_to_rrt3_at_WFEDITABLE",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="gpei_consolidation_at_WFEDITABLE",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="re_submission_to_orpg_operations_2_at_WFEDITABLE",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="re_submitted_to_orpg_at_WFEDITABLE",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="re_submitted_to_rrt_at_WFEDITABLE",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="submission_to_orpg_operations_1_at_WFEDITABLE",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="submission_to_orpg_operations_2_at_WFEDITABLE",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="submitted_for_approval_at_WFEDITABLE",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="submitted_to_orpg_at_WFEDITABLE",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="submitted_to_rrt_at_WFEDITABLE",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="unicef_sent_budget_at_WFEDITABLE",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="who_sent_budget_at_WFEDITABLE",
            field=models.DateField(blank=True, null=True),
        ),
    ]
