# Generated by Django 3.2.15 on 2023-01-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0117_merge_20221223_1012"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="budget_status",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
