# Generated by Django 3.2.15 on 2023-01-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polio", "0117_merge_20221223_1012"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="geojson",
            field=models.JSONField(
                blank=True, editable=False, help_text="Geo json representing the shape of the campaign", null=True
            ),
        ),
    ]
