# Generated by Django 3.2.15 on 2023-01-06 15:17

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polio", "0118_campaign_geojson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="geojson",
            field=models.JSONField(
                blank=True,
                editable=False,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="GeoJson representing the scope of the campaign",
                null=True,
            ),
        ),
    ]
