# Generated by Django 3.2.15 on 2023-01-12 10:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0119_alter_campaign_budget_status"),
        ("polio", "0120_campaign_fill_geojson"),
    ]

    operations = []
