# Generated by Django 3.2.15 on 2023-02-20 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polio", "0121_merge_20230112_1017"),
    ]

    operations = [
        migrations.RenameField(
            model_name="campaign",
            old_name="gpei_consolidation_at_WFEDITABLE",
            new_name="gpei_consolidated_budgets_at_WFEDITABLE",
        ),
        migrations.RenameField(
            model_name="campaign",
            old_name="re_submission_to_orpg_operations_2_at_WFEDITABLE",
            new_name="re_submitted_to_orpg_operations_2_at_WFEDITABLE",
        ),
        migrations.RenameField(
            model_name="campaign",
            old_name="submission_to_orpg_operations_1_at_WFEDITABLE",
            new_name="submitted_to_orpg_operations1_at_WFEDITABLE",
        ),
        migrations.RenameField(
            model_name="campaign",
            old_name="submission_to_orpg_operations_2_at_WFEDITABLE",
            new_name="submitted_to_orpg_operations2_at_WFEDITABLE",
        ),
        migrations.RenameField(
            model_name="campaign",
            old_name="re_submitted_to_orpg_at_WFEDITABLE",
            new_name="submitted_to_orpg_wider_at_WFEDITABLE",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="budget_requested_at_WFEDITABLE",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="feedback_sent_to_rrt3_at_WFEDITABLE",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="submitted_to_orpg_at_WFEDITABLE",
        ),
    ]
