# Generated by Django 3.2.15 on 2023-03-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polio", "0121_merge_20230112_1017"),
    ]

    operations = [
        migrations.AlterField(
            model_name="countryusersgroup",
            name="language",
            field=models.CharField(
                choices=[("FR", "Français"), ("EN", "English"), ("PT", "Português")], default="EN", max_length=32
            ),
        ),
    ]
