# Generated by Django 3.2.15 on 2023-03-16 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polio", "0122_auto_20230316_1033"),
    ]

    operations = [
        migrations.RenameField(
            model_name="campaign",
            old_name="budget_requested_at_WFEDITABLE",
            new_name="budget_requested_at_WFEDITABLE_old",
        ),
        migrations.RenameField(
            model_name="campaign",
            old_name="feedback_sent_to_rrt3_at_WFEDITABLE",
            new_name="feedback_sent_to_rrt3_at_WFEDITABLE_old",
        ),
        migrations.RenameField(
            model_name="campaign",
            old_name="re_submitted_to_orpg_at_WFEDITABLE",
            new_name="re_submitted_to_orpg_at_WFEDITABLE_old",
        ),
    ]
