# Generated by Django 3.2.15 on 2023-04-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0126_round_percentage_covered_target_population"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="three_level_call_at",
        ),
        migrations.AddField(
            model_name="campaign",
            name="outbreak_declaration_date",
            field=models.DateField(blank=True, null=True, verbose_name="Outbreak declaration date"),
        ),
    ]
