# Generated by Django 3.2.15 on 2023-04-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polio", "0128_config_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="ra_completed_at_WFEDITABLE",
            field=models.DateField(blank=True, null=True),
        ),
    ]
