# Generated by Django 3.2.15 on 2023-04-17 16:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0128_remove_campaign_surge_spreadsheet_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="country_name_in_surge_spreadsheet",
        ),
    ]
