# Generated by Django 3.2.15 on 2023-05-02 12:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0129_campaign_ra_completed_at_wfeditable"),
        ("polio", "0130_delete_surge"),
    ]

    operations = []
