# Generated by Django 3.2.15 on 2023-06-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0130_rounddatehistoryentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rounddatehistoryentry",
            name="ended_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rounddatehistoryentry",
            name="previous_ended_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rounddatehistoryentry",
            name="previous_started_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rounddatehistoryentry",
            name="started_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
