# Generated by Django 3.2.15 on 2023-08-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0139_merge_20230724_1542"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rounddatehistoryentry",
            name="reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INITIAL_DATA", "initial_data"),
                    ("ENCODING_ERROR", "encoding_error"),
                    ("PUBLIC_HOLIDAY", "public_holday"),
                    ("OTHER_ACTIVITIES", "other_activities"),
                    ("MOH_DECISION", "moh_decision"),
                    ("CAMPAIGN_SYNCHRONIZATION", "campaign_synchronization"),
                    ("PREPAREDNESS_LEVEL_NOT_REACHED", "preparedness_level_not_reached"),
                    ("FUNDS_NOT_RECEIVED_OPS_LEVEL", "funds_not_received_ops_level"),
                    ("FUNDS_NOT_ARRIVED_IN_COUNTRY", "funds_not_arrived_in_country"),
                    ("VACCINES_NOT_DELIVERED_OPS_LEVEL", "vaccines_not_delivered_ops_level"),
                    ("VACCINES_NOT_ARRIVED_IN_COUNTRY", "vaccines_not_arrived_in_country"),
                    ("SECURITY_CONTEXT", "security_context"),
                    ("CAMPAIGN_MOVED_FORWARD_BY_MOH", "campaign_moved_forward_by_moh"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
