# Generated by Django 3.2.15 on 2023-08-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polio", "0140_vaccineauthorization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vaccineauthorization",
            name="expiration_date",
            field=models.DateField(),
        ),
    ]
