# Generated by Django 3.2.15 on 2023-08-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polio", "0141_alter_vaccineauthorization_expiration_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vaccineauthorization",
            name="expiration_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
