# Generated by Django 3.2.15 on 2023-08-23 15:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0140_alter_rounddatehistoryentry_reason"),
        ("polio", "0142_alter_vaccineauthorization_expiration_date"),
    ]

    operations = []
