# Generated by Django 3.2.15 on 2023-09-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0143_merge_20230823_1508"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vaccineauthorization",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ONGOING", "Ongoing"),
                    ("VALIDATED", "Validated"),
                    ("SIGNATURE", "Sent for signature"),
                    ("EXPIRED", "Expired"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
