# Generated by Django 3.2.21 on 2023-10-03 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0147_alter_rounddatehistoryentry_reason"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReasonForDelay",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name_fr", models.CharField(max_length=200, verbose_name="name")),
                ("name_en", models.CharField(max_length=200, verbose_name="name")),
                (
                    "key_name",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("INITIAL_DATA", "initial_data"),
                            ("ENCODING_ERROR", "encoding_error"),
                            ("PUBLIC_HOLIDAY", "public_holday"),
                            ("OTHER_ACTIVITIES", "other_activities"),
                            ("MOH_DECISION", "moh_decision"),
                            ("CAMPAIGN_SYNCHRONIZATION", "campaign_synchronization"),
                            ("PREPAREDNESS_LEVEL_NOT_REACHED", "preparedness_level_not_reached"),
                            ("FUNDS_NOT_RECEIVED_OPS_LEVEL", "funds_not_received_ops_level"),
                            ("FUNDS_NOT_ARRIVED_IN_COUNTRY", "funds_not_arrived_in_country"),
                            ("VACCINES_NOT_DELIVERED_OPS_LEVEL", "vaccines_not_delivered_ops_level"),
                            ("VACCINES_NOT_ARRIVED_IN_COUNTRY", "vaccines_not_arrived_in_country"),
                            ("SECURITY_CONTEXT", "security_context"),
                            ("CAMPAIGN_MOVED_FORWARD_BY_MOH", "campaign_moved_forward_by_moh"),
                            ("VRF_NOT_SIGNED", "vrf_not_signed"),
                            ("FOUR_WEEKS_GAP_BETWEEN_ROUNDS", "four_weeks_gap_betwenn_rounds"),
                            ("OTHER_VACCINATION_CAMPAIGNS", "other_vaccination_campaigns"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="rounddatehistoryentry",
            name="reason_for_delay",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reason",
                to="polio.reasonfordelay",
            ),
        ),
    ]
