# Generated by Django 3.2.15 on 2023-10-02 16:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0146_vaccineauthorization_start_date"),
        ("polio", "0147_alter_rounddatehistoryentry_reason"),
    ]

    operations = []
