# Generated by Django 3.2.15 on 2023-10-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0234_delete_reference_form_and_reference_instance"),
        ("polio", "0149_merge_20231005_1130"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetprocess",
            name="teams",
            field=models.ManyToManyField(blank=True, related_name="budget_process_teams", to="iaso.Team"),
        ),
    ]
