# Generated by Django 3.2.21 on 2023-10-13 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iaso', '0235_merge_20231006_0940'),
        ('polio', '0149_auto_20231012_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineRequestForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_type', models.CharField(choices=[('mOPV2', 'mOPV2'), ('nOPV2', 'nOPV2'), ('bOPV', 'bOPV')], max_length=5)),
                ('date_vrf_signature', models.DateField()),
                ('date_vrf_reception', models.DateField()),
                ('date_dg_approval', models.DateField()),
                ('quantities_ordered_in_doses', models.PositiveIntegerField()),
                ('wastage_rate_used_on_vrf', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date_vrf_submission_to_orpg', models.DateField(blank=True, null=True)),
                ('quantities_approved_by_orpg_in_doses', models.PositiveIntegerField(blank=True, null=True)),
                ('date_rrt_orpg_approval', models.DateField(blank=True, null=True)),
                ('date_vrf_submitted_to_dg', models.DateField(blank=True, null=True)),
                ('quantities_approved_by_dg_in_doses', models.PositiveIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polio.campaign')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iaso.orgunit')),
                ('rounds', models.ManyToManyField(to='polio.Round')),
            ],
        ),
        migrations.CreateModel(
            name='VaccinePreAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pre_alert_reception', models.DateField()),
                ('po_number', models.CharField(max_length=200)),
                ('estimated_arrival_time', models.DateTimeField()),
                ('lot_number', models.CharField(max_length=200)),
                ('expiration_date', models.DateField()),
                ('doses_shipped', models.PositiveIntegerField()),
                ('doses_received', models.PositiveIntegerField()),
                ('request_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polio.vaccinerequestform')),
            ],
        ),
        migrations.CreateModel(
            name='VaccineArrivalReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_report_date', models.DateField()),
                ('doses_received', models.PositiveIntegerField()),
                ('request_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polio.vaccinerequestform')),
            ],
        ),
    ]
