# Generated by Django 3.2.21 on 2023-10-19 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0150_auto_20231016_1449"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetstep",
            name="budget_process",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="budget_process",
                to="polio.budgetprocess",
            ),
        ),
    ]
