# Generated by Django 3.2.21 on 2023-10-11 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polio', '0146_budgetprocess'),
        ('polio', '0150_alter_budgetprocess_teams'),
    ]

    operations = [
    ]
