# Generated by Django 3.2.21 on 2023-10-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0150_add_reason_for_delay_to_existing_datelogs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reasonfordelay",
            name="key_name",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
