# Generated by Django 3.2.21 on 2023-10-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0151_alter_reasonfordelay_key_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="reasonfordelay",
            name="deleted_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
