# Generated by Django 3.2.22 on 2023-10-24 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0151_budgetstep_budget_process"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetprocess",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="budget_process_campaign",
                to="polio.campaign",
            ),
        ),
    ]
