# Generated by Django 3.2.21 on 2023-10-05 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0231_merge_20230904_2154"),
        ("polio", "0152_reasonfordelay_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="reasonfordelay",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reasons_for_delay",
                to="iaso.account",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reasonfordelay",
            unique_together={("key_name", "account")},
        ),
    ]
