# Generated by Django 3.2.21 on 2023-11-06 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polio', '0151_alter_rounddatehistoryentry_reason'),
        ('polio', '0152_auto_20231020_1135'),
    ]

    operations = [
    ]
