# Generated by Django 3.2.21 on 2023-11-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0154_auto_20231109_1053"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaccinearrivalreport",
            name="deleted_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="vaccineprealert",
            name="deleted_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="vaccinerequestform",
            name="deleted_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="vaccineprealert",
            name="estimated_arrival_time",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
