# Generated by Django 3.2.22 on 2023-11-24 10:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0152_notification_notificationimport"),
        ("polio", "0154_auto_20231109_1053"),
    ]

    operations = []
