# Generated by Django 3.2.21 on 2023-11-17 11:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0155_auto_20231113_1010"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vaccineprealert",
            name="doses_received",
        ),
        migrations.RemoveField(
            model_name="vaccineprealert",
            name="lot_number",
        ),
        migrations.AddField(
            model_name="vaccineprealert",
            name="lot_numbers",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=200), default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name="vaccineprealert",
            name="po_number",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
