# Generated by Django 3.2.21 on 2023-12-05 09:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0153_alter_notification_vdpv_nucleotide_diff_sabin2"),
        ("polio", "0155_merge_20231124_1047"),
    ]

    operations = []
