# Generated by Django 3.2.21 on 2023-10-05 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0155_alter_reasonfordelay_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rounddatehistoryentry",
            name="reason_for_delay",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="round_history_entries",
                to="polio.reasonfordelay",
            ),
        ),
    ]
