# Generated by Django 3.2.22 on 2023-11-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0156_auto_20231117_1150"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaccineprealert",
            name="doses_per_vial",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
