# Generated by Django 3.2.21 on 2023-10-06 12:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0148_merge_20231002_1610"),
        ("polio", "0156_alter_rounddatehistoryentry_reason_for_delay"),
    ]

    operations = []
