# Generated by Django 3.2.22 on 2023-11-23 14:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0157_vaccineprealert_doses_per_vial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaccinearrivalreport",
            name="doses_per_vial",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="vaccinearrivalreport",
            name="doses_shipped",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="vaccinearrivalreport",
            name="expiration_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="vaccinearrivalreport",
            name="lot_numbers",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=200), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="vaccinearrivalreport",
            name="po_number",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
