# Generated by Django 3.2.21 on 2023-10-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0157_merge_20231006_1208"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reasonfordelay",
            name="name_fr",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="name"),
        ),
    ]
