# Generated by Django 3.2.22 on 2023-11-24 11:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0155_merge_20231124_1047"),
        ("polio", "0158_auto_20231123_1449"),
    ]

    operations = []
