# Generated by Django 3.2.21 on 2023-12-05 10:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0156_merge_20231205_0938"),
        ("polio", "0159_merge_20231124_1105"),
    ]

    operations = []
