# Generated by Django 3.2.22 on 2023-12-15 11:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0161_delete_linelistimport"),
        ("polio", "0161_destructionreport_incidentreport_outgoingstockmovement_vaccinestock"),
    ]

    operations = []
