# Generated by Django 3.2.22 on 2024-01-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0162_merge_20231215_1118"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaccinearrivalreport",
            name="vials_received",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="vaccinearrivalreport",
            name="vials_shipped",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="vaccineprealert",
            name="vials_shipped",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
