# Generated by Django 4.2.9 on 2024-02-01 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0260_auto_20240118_0948"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("polio", "0163_auto_20240123_1435"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetstep",
            name="campaign",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="budget_steps",
                to="polio.campaign",
            ),
        ),
        migrations.CreateModel(
            name="BudgetProcess",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(blank=True, max_length=100, null=True)),
                ("current_state_key", models.CharField(default="-", max_length=100)),
                (
                    "current_state_label",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ra_completed_at_WFEDITABLE", models.DateField(blank=True, null=True)),
                (
                    "who_sent_budget_at_WFEDITABLE",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "unicef_sent_budget_at_WFEDITABLE",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "gpei_consolidated_budgets_at_WFEDITABLE",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "submitted_to_rrt_at_WFEDITABLE",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "feedback_sent_to_gpei_at_WFEDITABLE",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "re_submitted_to_rrt_at_WFEDITABLE",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "submitted_to_orpg_operations1_at_WFEDITABLE",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "feedback_sent_to_rrt1_at_WFEDITABLE",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "re_submitted_to_orpg_operations1_at_WFEDITABLE",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "submitted_to_orpg_wider_at_WFEDITABLE",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "submitted_to_orpg_operations2_at_WFEDITABLE",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "feedback_sent_to_rrt2_at_WFEDITABLE",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "re_submitted_to_orpg_operations2_at_WFEDITABLE",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "submitted_for_approval_at_WFEDITABLE",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "feedback_sent_to_orpg_operations_unicef_at_WFEDITABLE",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "feedback_sent_to_orpg_operations_who_at_WFEDITABLE",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "approved_by_who_at_WFEDITABLE",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "approved_by_unicef_at_WFEDITABLE",
                    models.DateField(blank=True, null=True),
                ),
                ("approved_at_WFEDITABLE", models.DateField(blank=True, null=True)),
                (
                    "approval_confirmed_at_WFEDITABLE",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DIRECT", "Direct"),
                            ("DFC", "DFC"),
                            ("MOBILE_PAYMENT", "Mobile Payment"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("district_count", models.IntegerField(blank=True, null=True)),
                (
                    "who_disbursed_to_co_at",
                    models.DateField(blank=True, null=True, verbose_name="Disbursed to CO (WHO)"),
                ),
                (
                    "who_disbursed_to_moh_at",
                    models.DateField(blank=True, null=True, verbose_name="Disbursed to MOH (WHO)"),
                ),
                (
                    "unicef_disbursed_to_co_at",
                    models.DateField(blank=True, null=True, verbose_name="Disbursed to CO (UNICEF)"),
                ),
                (
                    "unicef_disbursed_to_moh_at",
                    models.DateField(blank=True, null=True, verbose_name="Disbursed to MOH (UNICEF)"),
                ),
                (
                    "no_regret_fund_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="iaso.team",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="budgetstep",
            name="budget_process",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="budgets",
                to="polio.budgetprocess",
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="budget_process",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rounds",
                to="polio.budgetprocess",
            ),
        ),
    ]
