# Generated by Django 4.2.9 on 2024-02-06 12:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0164_auto_20240201_1207"),
        ("polio", "0164_delete_config"),
    ]

    operations = []
