# Generated by Django 3.2.22 on 2024-02-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0166_vaccinerequestform_target_population"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vaccinerequestform",
            name="date_dg_approval",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vaccinerequestform",
            name="date_vrf_reception",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vaccinerequestform",
            name="date_vrf_signature",
            field=models.DateField(blank=True, null=True),
        ),
    ]
