# Generated by Django 3.2.22 on 2024-03-06 13:06

from django.db import migrations, models
import django.db.models.deletion
import plugins.polio.models


class Migration(migrations.Migration):

    dependencies = [
        ('polio', '0167_auto_20240226_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_type',
            field=models.ForeignKey(blank=True, default=plugins.polio.models.get_default_campaign_type, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polio.campaigntype'),
        ),
    ]
