# Generated by Django 3.2.22 on 2024-03-06 13:08

from django.db import migrations, models


def add_default_campaign_types(apps, schema_editor):
    models.CampaignType.objects.get_or_create(name="Polio")
    models.CampaignType.objects.get_or_create(name="Measles")
    models.CampaignType.objects.get_or_create(name="PIRI")
    models.CampaignType.objects.get_or_create(name="Yellow fever")
    models.CampaignType.objects.get_or_create(name="Vitamin A")
    models.CampaignType.objects.get_or_create(name="Rubella")
    models.CampaignType.objects.get_or_create(name="Deworming")


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0168_auto_20240306_1306"),
    ]

    operations = [migrations.RunPython(add_default_campaign_types)]
