# Generated by Django 4.2.11 on 2024-03-21 15:55

from django.db import migrations, models
from iaso.utils import slugify_underscore


def set_slugs(apps, schema_editor):
    campaigntypes = apps.get_model("polio", "CampaignType").objects.all()
    for ct in campaigntypes:
        ct.slug = slugify_underscore(ct.name)
        ct.save()


def unset_slugs(apps, schema_editor):
    campaigntypes = apps.get_model("polio", "CampaignType").objects.all()
    for ct in campaigntypes:
        ct.slug = ""
        ct.save()


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0169_auto_20240306_1327"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaigntype",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=False),
        ),
        migrations.RunPython(set_slugs, unset_slugs),
    ]
