# Generated by Django 4.2.11 on 2024-03-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0170_campaigntype_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaigntype",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
