# Generated by Django 4.2.11 on 2024-03-25 12:07

from django.db import migrations
from django.db.models import Count


def set_default_campaign_type_to_existing_campaigns(apps, schema_editor):
    Campaign = apps.get_model("polio", "Campaign")
    CType = apps.get_model("polio", "CampaignType")
    from plugins.polio.models import CampaignType as CTypeOrig

    polio_type, _ = CType.objects.get_or_create(name=CTypeOrig.POLIO)

    annotated_campaigns = Campaign.objects.all().annotate(campaign_type_count=Count("campaign_types"))
    campaigns_with_no_types = annotated_campaigns.filter(campaign_type_count=0)

    for campaign in campaigns_with_no_types:
        campaign.campaign_types.add(polio_type)


def unset_fake(apps, schema_editor):
    pass  # lets do nothing here


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0171_alter_campaigntype_slug"),
    ]

    operations = [migrations.RunPython(set_default_campaign_type_to_existing_campaigns, unset_fake)]
