# Generated by Django 4.2.11 on 2024-04-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0173_alter_outgoingstockmovement_usable_vials_used"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignscope",
            name="vaccine",
            field=models.CharField(
                blank=True, choices=[("mOPV2", "mOPV2"), ("nOPV2", "nOPV2"), ("bOPV", "bOPV")], max_length=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="roundscope",
            name="vaccine",
            field=models.CharField(
                blank=True, choices=[("mOPV2", "mOPV2"), ("nOPV2", "nOPV2"), ("bOPV", "bOPV")], max_length=5, null=True
            ),
        ),
    ]
