# Generated by Django 4.2.11 on 2024-04-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0174_alter_campaignscope_vaccine_alter_roundscope_vaccine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignscope",
            name="vaccine",
            field=models.CharField(
                blank=True, choices=[("mOPV2", "mOPV2"), ("nOPV2", "nOPV2"), ("bOPV", "bOPV")], max_length=5
            ),
        ),
        migrations.AlterField(
            model_name="roundscope",
            name="vaccine",
            field=models.CharField(
                blank=True, choices=[("mOPV2", "mOPV2"), ("nOPV2", "nOPV2"), ("bOPV", "bOPV")], max_length=5
            ),
        ),
    ]
