# Generated by Django 4.2.11 on 2024-06-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0178_subactivity_subactivityscope"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outgoingstockmovement",
            name="unusable_vials",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="outgoingstockmovement",
            name="usable_vials_used",
            field=models.PositiveIntegerField(),
        ),
    ]
