# Generated by Django 4.2.13 on 2024-06-25 09:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0179_round_age_max_round_age_min_round_age_type"),
        ("polio", "0180_rename_unusable_vials_outgoingstockmovement_usable_vials_used"),
    ]

    operations = []
