# Generated by Django 4.2.13 on 2024-07-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0182_alter_incidentreport_stock_correction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="virus",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PV1", "PV1"),
                    ("PV2", "PV2"),
                    ("PV3", "PV3"),
                    ("cVDPV2", "cVDPV2"),
                    ("WPV1", "WPV1"),
                    ("PV1 & cVDPV2", "PV1 & cVDPV2"),
                ],
                max_length=12,
                null=True,
            ),
        ),
    ]
