# Generated by Django 4.2.13 on 2024-07-16 08:50

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0184_chronogram_chronogramtemplatetask_chronogramtask"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chronogram",
            name="round",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chronograms",
                to="polio.round",
            ),
        ),
    ]
