# Generated by Django 4.2.13 on 2024-07-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0185_alter_chronogram_round"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chronogramtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Not started"),
                    ("IN_PROGRESS", "In progress"),
                    ("DONE", "Done"),
                    ("N/A", "N/A"),
                ],
                default="PENDING",
                max_length=15,
            ),
        ),
    ]
