# Generated by Django 4.2.14 on 2024-08-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0186_alter_chronogramtask_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chronogramtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Not started"),
                    ("IN_PROGRESS", "In progress"),
                    ("DONE", "Done"),
                    ("NON_APPLICABLE", "N/A"),
                ],
                default="PENDING",
                max_length=15,
            ),
        ),
    ]
