# Generated by Django 4.2.14 on 2024-08-01 13:04

from django.db import migrations


def migrate_data_forward(apps, schema_editor):
    ChronogramTask = apps.get_model("polio", "ChronogramTask")
    ChronogramTask.objects.filter(status="N/A").update(status="NON_APPLICABLE")


def migrate_data_backward(apps, schema_editor):
    ChronogramTask = apps.get_model("polio", "ChronogramTask")
    ChronogramTask.objects.filter(status="NON_APPLICABLE").update(status="N/A")


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0187_alter_chronogramtask_status"),
    ]

    operations = [migrations.RunPython(migrate_data_forward, migrate_data_backward, elidable=True)]
