# Generated by Django 4.2.14 on 2024-08-07 08:29

from django.db import migrations
from django.db.models import F


def migrate_data_forward(apps, schema_editor):
    ChronogramTask = apps.get_model("polio", "ChronogramTask")
    ChronogramTask.objects.all().update(description_new_en=F("description"))
    ChronogramTemplateTask = apps.get_model("polio", "ChronogramTemplateTask")
    ChronogramTemplateTask.objects.all().update(description_new_en=F("description"))


def migrate_data_backward(apps, schema_editor):
    ChronogramTask = apps.get_model("polio", "ChronogramTask")
    ChronogramTask.objects.all().update(description=F("description_new_en"))
    ChronogramTemplateTask = apps.get_model("polio", "ChronogramTemplateTask")
    ChronogramTemplateTask.objects.all().update(description=F("description_new_en"))


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0189_chronogramtask_description_new_en_and_more"),
    ]

    operations = [migrations.RunPython(migrate_data_forward, migrate_data_backward, elidable=True)]
