# Generated by Django 4.2.14 on 2024-08-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0193_alter_incidentreport_stock_correction"),
    ]

    operations = [
        migrations.AddField(
            model_name="chronogramtask",
            name="user_in_charge_new",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
