# Generated by Django 4.2.14 on 2024-08-27 14:49

from django.db import migrations


def migrate_data_forward(apps, schema_editor):
    ChronogramTask = apps.get_model("polio", "ChronogramTask")
    tasks = ChronogramTask.objects.filter(user_in_charge__isnull=False).select_related("user_in_charge")
    objs = []
    for task in tasks:
        user = task.user_in_charge
        user_str = ""
        if user.first_name and user.last_name:
            user_str = f"{user.first_name} {user.last_name}"
        elif user.first_name or user.last_name:
            user_str = user.first_name or user.last_name
        elif user.username:
            user_str = user.username
        if user_str:
            task.user_in_charge_new = user_str
            objs.append(task)
    ChronogramTask.objects.bulk_update(objs, ["user_in_charge_new"])


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0194_chronogramtask_user_in_charge_new"),
    ]

    operations = [migrations.RunPython(migrate_data_forward, migrations.RunPython.noop, elidable=True)]
