# Generated by Django 4.2.11 on 2024-09-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0196_remove_chronogramtask_user_in_charge_new_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaccinerequestform",
            name="vrf_type",
            field=models.CharField(
                choices=[("Normal", "Normal"), ("Missing", "Missing"), ("Not Required", "Not Required")],
                default="Normal",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="vaccinerequestform",
            name="quantities_ordered_in_doses",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
