# Generated by Django 4.2.13 on 2024-10-04 13:18

from django.db import migrations


def remove_prefix_from_objects(objects):
    for object in objects:
        if object.po_number and object.po_number.startswith("PO"):
            object.po_number = object.po_number[2:]
            object.save()


def remove_po_prefix(apps, schema_editor):
    VaccinePreAlert = apps.get_model("polio", "VaccinePreAlert")
    VaccineArrivalReport = apps.get_model("polio", "VaccineArrivalReport")
    PreAlerts = VaccinePreAlert.objects.all()
    ArrivalReport = VaccineArrivalReport.objects.all()
    remove_prefix_from_objects(PreAlerts)
    remove_prefix_from_objects(ArrivalReport)


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0197_vaccinerequestform_vrf_type_and_more"),
    ]

    operations = [migrations.RunPython(remove_po_prefix)]
