# Generated by Django 4.2.11 on 2024-10-22 14:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0198_destructionreport_document_incidentreport_document_and_more"),
        ("polio", "0198_remove_po_prefix"),
    ]

    operations = []
