# Generated by Django 4.2.16 on 2024-11-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0201_vaccinestockhistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vaccinestockhistory",
            name="unusable_doses_in",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="vaccinestockhistory",
            name="unusable_doses_out",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="vaccinestockhistory",
            name="unusable_vials_in",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="vaccinestockhistory",
            name="unusable_vials_out",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="vaccinestockhistory",
            name="usable_doses_in",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="vaccinestockhistory",
            name="usable_doses_out",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="vaccinestockhistory",
            name="usable_vials_in",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="vaccinestockhistory",
            name="usable_vials_out",
            field=models.IntegerField(null=True),
        ),
    ]
