# Generated by Django 4.2.11 on 2024-11-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0203_auto_20241119_1153"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vaccinearrivalreport",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="vaccineprealert",
            name="deleted_at",
        ),
        migrations.AlterField(
            model_name="vaccinearrivalreport",
            name="po_number",
            field=models.CharField(blank=True, default=None, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="vaccineprealert",
            name="po_number",
            field=models.CharField(blank=True, default=None, max_length=200, null=True, unique=True),
        ),
    ]
