# Generated by Django 4.2.16 on 2024-11-20 10:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0204_remove_vaccinearrivalreport_deleted_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="budget_requested_at_WFEDITABLE_old",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="budget_responsible",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="budget_rrt_oprtt_approval_at",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="budget_submitted_at",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="cvdpv_notified_at",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="detection_rrt_oprtt_approval_at",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="doses_requested",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="eomg",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="feedback_sent_to_rrt3_at_WFEDITABLE_old",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="last_budget_event",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="preperadness_spreadsheet_url",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="preperadness_sync_status",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="re_submitted_to_orpg_at_WFEDITABLE_old",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="round_one",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="round_two",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="vacine",
        ),
    ]
