# Generated by Django 4.2.16 on 2024-11-29 09:51

from django.db import migrations


def delete_unused_scopes(apps, schema_editor):
    Round = apps.get_model("polio", "Round")

    rounds = Round.objects.all().select_related("campaign").prefetch_related("campaign__scopes", "scopes")

    for rnd in rounds:
        # These rounds should be deleted in another migration once we confirmed that it is safe to do so
        if not rnd.campaign:
            continue
        if rnd.campaign.separate_scopes_per_round:
            rnd.campaign.scopes.set([])
        else:
            rnd.scopes.set([])


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0205_remove_campaign_budget_requested_at_wfeditable_old_and_more"),
    ]

    operations = [migrations.RunPython(delete_unused_scopes, migrations.RunPython.noop)]
