# Generated by Django 4.2.16 on 2024-12-04 14:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0203_merge_20241114_1711"),
        ("polio", "0206_delete_unused_scopes"),
    ]

    operations = []
