# Generated by Django 4.2.17 on 2024-12-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0207_merge_20241204_1433"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vaccinerequestform",
            name="rounds",
            field=models.ManyToManyField(db_index=True, to="polio.round"),
        ),
        migrations.AddIndex(
            model_name="destructionreport",
            index=models.Index(
                fields=["vaccine_stock", "destruction_report_date"], name="polio_destr_vaccine_e5b90d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="destructionreport",
            index=models.Index(fields=["rrt_destruction_report_reception_date"], name="polio_destr_rrt_des_449e4f_idx"),
        ),
        migrations.AddIndex(
            model_name="incidentreport",
            index=models.Index(
                fields=["vaccine_stock", "date_of_incident_report"], name="polio_incid_vaccine_b012dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incidentreport",
            index=models.Index(fields=["incident_report_received_by_rrt"], name="polio_incid_inciden_067b16_idx"),
        ),
        migrations.AddIndex(
            model_name="outgoingstockmovement",
            index=models.Index(fields=["vaccine_stock", "campaign"], name="polio_outgo_vaccine_fa2e84_idx"),
        ),
        migrations.AddIndex(
            model_name="outgoingstockmovement",
            index=models.Index(fields=["form_a_reception_date"], name="polio_outgo_form_a__b64b56_idx"),
        ),
        migrations.AddIndex(
            model_name="outgoingstockmovement",
            index=models.Index(fields=["report_date"], name="polio_outgo_report__44ffe2_idx"),
        ),
        migrations.AddIndex(
            model_name="vaccinearrivalreport",
            index=models.Index(fields=["request_form", "arrival_report_date"], name="polio_vacci_request_48e891_idx"),
        ),
        migrations.AddIndex(
            model_name="vaccinearrivalreport",
            index=models.Index(fields=["po_number"], name="polio_vacci_po_numb_bd6c9f_idx"),
        ),
        migrations.AddIndex(
            model_name="vaccinearrivalreport",
            index=models.Index(fields=["doses_received"], name="polio_vacci_doses_r_d2cd9d_idx"),
        ),
        migrations.AddIndex(
            model_name="vaccineprealert",
            index=models.Index(
                fields=["request_form", "estimated_arrival_time"], name="polio_vacci_request_4c2b0b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vaccineprealert",
            index=models.Index(fields=["po_number"], name="polio_vacci_po_numb_511963_idx"),
        ),
        migrations.AddIndex(
            model_name="vaccineprealert",
            index=models.Index(fields=["date_pre_alert_reception"], name="polio_vacci_date_pr_b7d59e_idx"),
        ),
        migrations.AddIndex(
            model_name="vaccinerequestform",
            index=models.Index(fields=["campaign", "vaccine_type"], name="polio_vacci_campaig_f43af8_idx"),
        ),
        migrations.AddIndex(
            model_name="vaccinerequestform",
            index=models.Index(fields=["vrf_type"], name="polio_vacci_vrf_typ_2acd7d_idx"),
        ),
        migrations.AddIndex(
            model_name="vaccinerequestform",
            index=models.Index(fields=["created_at"], name="polio_vacci_created_8563f0_idx"),
        ),
        migrations.AddIndex(
            model_name="vaccinerequestform",
            index=models.Index(fields=["updated_at"], name="polio_vacci_updated_fd171a_idx"),
        ),
        migrations.AddIndex(
            model_name="vaccinestock",
            index=models.Index(fields=["country", "vaccine"], name="polio_vacci_country_91274d_idx"),
        ),
        migrations.AddIndex(
            model_name="vaccinestock",
            index=models.Index(fields=["account"], name="polio_vacci_account_f1f77e_idx"),
        ),
    ]
