# Generated by Django 4.2.16 on 2024-12-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0208_migrate_vrf_orpg_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="virus",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PV1", "PV1"),
                    ("PV2", "PV2"),
                    ("PV3", "PV3"),
                    ("cVDPV2", "cVDPV2"),
                    ("WPV1", "WPV1"),
                    ("PV1 & cVDPV2", "PV1 & cVDPV2"),
                    ("cVDPV1 & cVDPV2", "cVDPV1 & cVDPV2"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="campaignscope",
            name="vaccine",
            field=models.CharField(
                blank=True,
                choices=[("mOPV2", "mOPV2"), ("nOPV2", "nOPV2"), ("bOPV", "bOPV"), ("nOPV & bOPV", "nOPV & bOPV")],
                max_length=11,
            ),
        ),
        migrations.AlterField(
            model_name="roundscope",
            name="vaccine",
            field=models.CharField(
                blank=True,
                choices=[("mOPV2", "mOPV2"), ("nOPV2", "nOPV2"), ("bOPV", "bOPV"), ("nOPV & bOPV", "nOPV & bOPV")],
                max_length=11,
            ),
        ),
        migrations.AlterField(
            model_name="subactivityscope",
            name="vaccine",
            field=models.CharField(
                blank=True,
                choices=[("mOPV2", "mOPV2"), ("nOPV2", "nOPV2"), ("bOPV", "bOPV"), ("nOPV & bOPV", "nOPV & bOPV")],
                max_length=11,
            ),
        ),
        migrations.AlterField(
            model_name="vaccinerequestform",
            name="vaccine_type",
            field=models.CharField(
                choices=[("mOPV2", "mOPV2"), ("nOPV2", "nOPV2"), ("bOPV", "bOPV"), ("nOPV & bOPV", "nOPV & bOPV")],
                max_length=11,
            ),
        ),
        migrations.AlterField(
            model_name="vaccinestock",
            name="vaccine",
            field=models.CharField(
                choices=[("mOPV2", "mOPV2"), ("nOPV2", "nOPV2"), ("bOPV", "bOPV"), ("nOPV & bOPV", "nOPV & bOPV")],
                max_length=11,
            ),
        ),
    ]
