# Generated by Django 4.2.17 on 2024-12-16 11:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0208_alter_vaccinerequestform_rounds_and_more"),
        ("polio", "0208_migrate_vrf_orpg_fields"),
    ]

    operations = []
