# Generated by Django 4.2.17 on 2024-12-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0208_migrate_vrf_orpg_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="subactivity",
            name="im_ended_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subactivity",
            name="im_started_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subactivity",
            name="lqas_ended_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subactivity",
            name="lqas_started_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
