# Generated by Django 4.2.17 on 2024-12-18 10:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0209_merge_20241216_1100"),
        ("polio", "0210_alter_campaignscope_vaccine_alter_roundscope_vaccine_and_more"),
    ]

    operations = []
