# Generated by Django 4.2.17 on 2024-12-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0211_merge_20241218_1038"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vaccinerequestform",
            name="vaccine_type",
            field=models.CharField(
                choices=[("mOPV2", "mOPV2"), ("nOPV2", "nOPV2"), ("bOPV", "bOPV"), ("nOPV2 & bOPV", "nOPV2 & bOPV")],
                max_length=30,
            ),
        ),
    ]
