# Generated by Django 4.2.17 on 2025-01-07 10:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0209_subactivity_im_ended_at_subactivity_im_started_at_and_more"),
        ("polio", "0214_remove_rounddatehistoryentry_reason"),
    ]

    operations = []
