# Generated by Django 4.2.17 on 2025-01-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0216_delete_rounds_without_campaign"),
    ]

    operations = [
        migrations.AddField(
            model_name="round",
            name="is_test",
            field=models.BooleanField(default=False),
        ),
    ]
