# Generated by Django 4.2.17 on 2025-02-11 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0217_round_is_test"),
    ]

    operations = [
        migrations.CreateModel(
            name="EarmarkedStock",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "earmarked_stock_type",
                    models.CharField(
                        choices=[("created", "Created"), ("used", "Used"), ("returned", "Returned")],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("vials_earmarked", models.PositiveIntegerField()),
                ("doses_earmarked", models.PositiveIntegerField()),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("campaign", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="polio.campaign")),
                (
                    "form_a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earmarked_stocks",
                        to="polio.outgoingstockmovement",
                    ),
                ),
                ("round", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="polio.round")),
                (
                    "vaccine_stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earmarked_stocks",
                        to="polio.vaccinestock",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["vaccine_stock", "campaign"], name="polio_earma_vaccine_0a002f_idx"),
                    models.Index(fields=["created_at"], name="polio_earma_created_54ada5_idx"),
                    models.Index(fields=["round"], name="polio_earma_round_i_a163e4_idx"),
                ],
            },
        ),
    ]
