# Generated by Django 4.2.17 on 2025-02-11 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0218_earmarkedstock"),
        ("polio", "0220_alter_incidentreport_stock_correction"),
    ]

    operations = []
