# Generated by Django 4.2.17 on 2025-02-20 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0222_data_migration_auto_create_chronograms"),
    ]

    operations = [
        migrations.AddField(
            model_name="destructionreport",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="destructionreport",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="outgoingstockmovement",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="outgoingstockmovement",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
