# Generated by Django 4.2.17 on 2025-03-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0224_earmarkedstock_temporary_campaign_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="destructionreport",
            name="document_last_scan",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="destructionreport",
            name="document_scan_status",
            field=models.CharField(
                choices=[
                    ("CLEAN", "Clean"),
                    ("PENDING", "Pending"),
                    ("INFECTED", "Infected"),
                    ("ERROR", "Error"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="document_last_scan",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="document_scan_status",
            field=models.CharField(
                choices=[
                    ("CLEAN", "Clean"),
                    ("PENDING", "Pending"),
                    ("INFECTED", "Infected"),
                    ("ERROR", "Error"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="notificationimport",
            name="file_last_scan",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationimport",
            name="file_scan_status",
            field=models.CharField(
                choices=[
                    ("CLEAN", "Clean"),
                    ("PENDING", "Pending"),
                    ("INFECTED", "Infected"),
                    ("ERROR", "Error"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="outgoingstockmovement",
            name="document_last_scan",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="outgoingstockmovement",
            name="document_scan_status",
            field=models.CharField(
                choices=[
                    ("CLEAN", "Clean"),
                    ("PENDING", "Pending"),
                    ("INFECTED", "Infected"),
                    ("ERROR", "Error"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="vaccineprealert",
            name="document_last_scan",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vaccineprealert",
            name="document_scan_status",
            field=models.CharField(
                choices=[
                    ("CLEAN", "Clean"),
                    ("PENDING", "Pending"),
                    ("INFECTED", "Infected"),
                    ("ERROR", "Error"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="vaccinerequestform",
            name="document_last_scan",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vaccinerequestform",
            name="document_scan_status",
            field=models.CharField(
                choices=[
                    ("CLEAN", "Clean"),
                    ("PENDING", "Pending"),
                    ("INFECTED", "Infected"),
                    ("ERROR", "Error"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
