# Generated by Django 4.2.17 on 2025-03-31 14:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0225_campaign_on_hold"),
        ("polio", "0225_destructionreport_document_last_scan_and_more"),
    ]

    operations = []
