# Generated by Django 4.2.20 on 2025-04-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polio", "0226_remove_outgoingstockmovement_missing_vials"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incidentreport",
            name="stock_correction",
            field=models.CharField(choices=[("vvm_reached_discard_point", "VVM reached the discard point"), ("vaccine_expired", "Vaccine expired"), ("missing", "Missing"), ("return", "Return"), ("stealing", "Stealing"), ("physical_inventory_add", "Add to Physical Inventory"), ("physical_inventory_remove", "remove from Physical Inventory"), ("broken", "Broken"), ("unreadable_label", "Unreadable label")], default="vvm_reached_discard_point", max_length=50),
        ),
    ]
