# Generated by Django 4.2.20 on 2025-04-11 13:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0226_destructionreport_document_last_scan_and_more"),
        ("polio", "0229_replace_losses_by_missing_in_incident_report"),
    ]

    operations = []
