# Generated by Django 4.2.20 on 2025-04-22 09:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0230_merge_20250411_1345"),
    ]

    operations = [
        migrations.RenameField(
            model_name="round",
            old_name="is_test",
            new_name="on_hold",
        ),
    ]
