# Generated by Django 4.2.21 on 2025-06-02 15:49

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0231_rename_is_test_round_on_hold"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outgoingstockmovement",
            name="campaign",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="polio.campaign"
            ),
        ),
    ]
