# Generated by Django 4.2.21 on 2025-06-11 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polio', '0231_rename_is_test_round_on_hold'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingstockmovement',
            name='non_obr_name',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='outgoingstockmovement',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polio.campaign'),
        ),
        migrations.AddConstraint(
            model_name='outgoingstockmovement',
            constraint=models.CheckConstraint(check=models.Q(('campaign__isnull', False), models.Q(('non_obr_name', ''), _negated=True), _connector='OR'), name='campaign_or_pseudo_campaign_not_null'),
        ),
        migrations.AddConstraint(
            model_name='outgoingstockmovement',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('campaign__isnull', False), models.Q(('non_obr_name', ''), _negated=True)), _negated=True), name='campaign_and_pseudo_campaign_cannot_both_have_value'),
        ),
    ]
