# Generated by Django 4.2.21 on 2025-06-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0233_outgoingstockmovement_non_obr_name_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="outgoingstockmovement",
            constraint=models.CheckConstraint(
                check=models.Q(("campaign__isnull", False), ("non_obr_name__isnull", False), _negated=True),
                name="campaign_and_pseudo_campaign_cannot_both_have_value",
            ),
        ),
    ]
