# Generated by Django 4.2.17 on 2025-07-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0235_auto_20250129_1557"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationimport",
            name="file",
            field=models.FileField(upload_to="uploads/polio_notifications/%Y-%m-%d-%H-%M/"),
        ),
    ]
