# Generated by Django 4.2.23 on 2025-07-28 10:17

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0335_remove_group_domain"),
        ("polio", "0236_alter_notificationimport_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="group",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaigns",
                to="iaso.group",
            ),
        ),
    ]
