# Generated by Django 4.2.23 on 2025-08-07 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iaso', '0337_featureflag_category_featureflag_is_dangerous_and_more'),
        ('polio', '0237_alter_campaign_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='LqasRoundDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lqas_failed', models.IntegerField()),
                ('lqas_passed', models.IntegerField()),
                ('lqas_no_data', models.IntegerField()),
                ('status', models.CharField(choices=[('1lqasOK', '1lqasOK'), ('2lqasDisqualified', '2lqasDisqualified'), ('3lqaspoor', '3lqaspoor'), ('3lqasverypoor', '3lqasverypoor'), ('3lqasFail', '3lqasFail'), ('3lqasmoderate', '3lqasmoderate'), ('3lqasundersampled', '3lqasundersampled'), ('3lqasoversampled', '3lqasoversampled'), ('inScope', 'inScope')], default='inScope', max_length=20)),
                ('nfm_other', models.IntegerField()),
                ('nfm_child_absent', models.IntegerField()),
                ('nfm_non_compliance', models.IntegerField()),
                ('nfm_child_was_asleep', models.IntegerField()),
                ('nfm_house_not_visited', models.IntegerField()),
                ('nfm_child_is_a_visitor', models.IntegerField()),
                ('nfm_vaccinated_but_not_fm', models.IntegerField()),
                ('abs_farm', models.IntegerField()),
                ('abs_other', models.IntegerField()),
                ('abs_market', models.IntegerField()),
                ('abs_school', models.IntegerField()),
                ('abs_travelled', models.IntegerField()),
                ('abs_in_playground', models.IntegerField()),
                ('abs_unknown', models.IntegerField()),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polio.round')),
                ('subactivity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polio.subactivity')),
            ],
            options={
                'verbose_name': 'LQAS Round Data',
                'verbose_name_plural': 'LQAS Round Data',
            },
        ),
        migrations.CreateModel(
            name='LqasDistrictDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_children_fmd', models.IntegerField()),
                ('total_children_checked', models.IntegerField()),
                ('total_sites_visited', models.IntegerField()),
                ('status', models.CharField(choices=[('1lqasOK', '1lqasOK'), ('2lqasDisqualified', '2lqasDisqualified'), ('3lqaspoor', '3lqaspoor'), ('3lqasverypoor', '3lqasverypoor'), ('3lqasFail', '3lqasFail'), ('3lqasmoderate', '3lqasmoderate'), ('3lqasundersampled', '3lqasundersampled'), ('3lqasoversampled', '3lqasoversampled'), ('inScope', 'inScope')], default='inScope', max_length=20)),
                ('cg_ratio', models.FloatField()),
                ('cg_best_info_source', models.CharField()),
                ('cg_best_info_ratio', models.FloatField()),
                ('cg_caregivers_informed', models.IntegerField()),
                ('cg_caregivers_informed_ratio', models.FloatField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iaso.orgunit')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polio.round')),
                ('subactivity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polio.subactivity')),
            ],
            options={
                'verbose_name': 'LQAS Entry',
                'verbose_name_plural': 'LQAS Entries',
            },
        ),
        migrations.AddConstraint(
            model_name='lqasrounddatamodel',
            constraint=models.UniqueConstraint(condition=models.Q(('subactivity__isnull', False)), fields=('round', 'subactivity'), name='unique_lqasactivitystats_round_subactivity'),
        ),
        migrations.AddConstraint(
            model_name='lqasrounddatamodel',
            constraint=models.UniqueConstraint(condition=models.Q(('subactivity__isnull', True)), fields=('round',), name='unique_lqasactivitystats_round_no_subactivity'),
        ),
        migrations.AddConstraint(
            model_name='lqasdistrictdatamodel',
            constraint=models.UniqueConstraint(condition=models.Q(('subactivity__isnull', False)), fields=('round', 'subactivity', 'district'), name='unique_lqasentry_round_subactivity_district'),
        ),
        migrations.AddConstraint(
            model_name='lqasdistrictdatamodel',
            constraint=models.UniqueConstraint(condition=models.Q(('subactivity__isnull', True)), fields=('round', 'district'), name='unique_lqasentry_round_district_no_subactivity'),
        ),
    ]
