# Generated by Django 4.2.23 on 2025-08-05 13:26

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0337_featureflag_category_featureflag_is_dangerous_and_more"),
        ("polio", "0237_alter_campaign_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="LqasNoMarkStats",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("other", models.IntegerField()),
                ("child_absent", models.IntegerField()),
                ("non_compliance", models.IntegerField()),
                ("child_was_asleep", models.IntegerField()),
                ("house_not_visited", models.IntegerField()),
                ("child_is_a_visitor", models.IntegerField()),
                ("vaccinated_but_not_fm", models.IntegerField()),
                ("round", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="polio.round")),
                (
                    "subactivity",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="polio.subactivity"
                    ),
                ),
            ],
            options={
                "verbose_name": "LQAS No Finger Mark Statistics",
                "verbose_name_plural": "LQAS No Finger Mark Statistics",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LqasEntry",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("total_children_fmd", models.IntegerField()),
                ("total_children_checked", models.IntegerField()),
                ("total_sites_visited", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("1lqasOK", "1lqasOK"),
                            ("2lqasDisqualified", "2lqasDisqualified"),
                            ("3lqaspoor", "3lqaspoor"),
                            ("3lqasverypoor", "3lqasverypoor"),
                            ("3lqasFail", "3lqasFail"),
                            ("3lqasmoderate", "3lqasmoderate"),
                            ("3lqasundersampled", "3lqasundersampled"),
                            ("3lqasoversampled", "3lqasoversampled"),
                            ("inScope", "inScope"),
                        ],
                        default="inScope",
                        max_length=20,
                    ),
                ),
                ("district", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="iaso.orgunit")),
                ("round", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="polio.round")),
                (
                    "subactivity",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="polio.subactivity"
                    ),
                ),
            ],
            options={
                "verbose_name": "LQAS Entry",
                "verbose_name_plural": "LQAS Entries",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LqasCareGiverStats",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ratio", models.FloatField()),
                ("best_info_source", models.CharField()),
                ("best_info_ratio", models.FloatField()),
                ("caregivers_informed", models.IntegerField()),
                ("caregivers_informed_ratio", models.FloatField()),
                (
                    "lqas_entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caregiver_stats",
                        to="polio.lqasentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "LQAS Care Giver Statistics",
            },
        ),
        migrations.CreateModel(
            name="LqasActivityStats",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("lqas_failed", models.IntegerField()),
                ("lqas_passed", models.IntegerField()),
                ("lqas_no_data", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("1lqasOK", "1lqasOK"),
                            ("2lqasDisqualified", "2lqasDisqualified"),
                            ("3lqaspoor", "3lqaspoor"),
                            ("3lqasverypoor", "3lqasverypoor"),
                            ("3lqasFail", "3lqasFail"),
                            ("3lqasmoderate", "3lqasmoderate"),
                            ("3lqasundersampled", "3lqasundersampled"),
                            ("3lqasoversampled", "3lqasoversampled"),
                            ("inScope", "inScope"),
                        ],
                        default="inScope",
                        max_length=20,
                    ),
                ),
                ("round", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="polio.round")),
                (
                    "subactivity",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="polio.subactivity"
                    ),
                ),
            ],
            options={
                "verbose_name": "LQAS Activity Statistics",
                "verbose_name_plural": "LQAS Activity Statistics",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LqasAbsenceStats",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("farm", models.IntegerField()),
                ("other", models.IntegerField()),
                ("market", models.IntegerField()),
                ("school", models.IntegerField()),
                ("travelled", models.IntegerField()),
                ("in_playground", models.IntegerField()),
                ("unknown", models.IntegerField()),
                ("round", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="polio.round")),
                (
                    "subactivity",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="polio.subactivity"
                    ),
                ),
            ],
            options={
                "verbose_name": "LQAS Absent Children Statistics",
                "verbose_name_plural": "LQAS Absent Children Statistics",
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="lqasnomarkstats",
            constraint=models.UniqueConstraint(
                condition=models.Q(("subactivity__isnull", False)),
                fields=("round", "subactivity"),
                name="unique_lqasnomarkstats_round_subactivity",
            ),
        ),
        migrations.AddConstraint(
            model_name="lqasnomarkstats",
            constraint=models.UniqueConstraint(
                condition=models.Q(("subactivity__isnull", True)),
                fields=("round",),
                name="unique_lqasnomarkstats_round_no_subactivity",
            ),
        ),
        migrations.AddConstraint(
            model_name="lqasentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("subactivity__isnull", False)),
                fields=("round", "subactivity", "district"),
                name="unique_lqasentry_round_subactivity_district",
            ),
        ),
        migrations.AddConstraint(
            model_name="lqasentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("subactivity__isnull", True)),
                fields=("round", "district"),
                name="unique_lqasentry_round_district_no_subactivity",
            ),
        ),
        migrations.AddConstraint(
            model_name="lqasactivitystats",
            constraint=models.UniqueConstraint(
                condition=models.Q(("subactivity__isnull", False)),
                fields=("round", "subactivity"),
                name="unique_lqasactivitystats_round_subactivity",
            ),
        ),
        migrations.AddConstraint(
            model_name="lqasactivitystats",
            constraint=models.UniqueConstraint(
                condition=models.Q(("subactivity__isnull", True)),
                fields=("round",),
                name="unique_lqasactivitystats_round_no_subactivity",
            ),
        ),
        migrations.AddConstraint(
            model_name="lqasabsencestats",
            constraint=models.UniqueConstraint(
                condition=models.Q(("subactivity__isnull", False)),
                fields=("round", "subactivity"),
                name="unique_lqasabsencestats_round_subactivity",
            ),
        ),
        migrations.AddConstraint(
            model_name="lqasabsencestats",
            constraint=models.UniqueConstraint(
                condition=models.Q(("subactivity__isnull", True)),
                fields=("round",),
                name="unique_lqasabsencestats_round_no_subactivity",
            ),
        ),
    ]
