# Generated by Django 4.2.23 on 2025-08-04 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iaso', '0336_merge_20250731_0902'),
        ('polio', '0237_alter_campaign_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='LqasEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_children_fmd', models.IntegerField()),
                ('total_children_checked', models.IntegerField()),
                ('total_sites_visited', models.IntegerField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iaso.orgunit')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polio.round')),
                ('subactivity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polio.subactivity')),
            ],
            options={
                'verbose_name': 'LQAS Entry',
                'verbose_name_plural': 'LQAS Entries',
                'abstract': False,
                'unique_together': {('round', 'subactivity', 'district')},
            },
        ),
        migrations.CreateModel(
            name='LqasCareGiverStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.FloatField()),
                ('best_info_source', models.CharField()),
                ('best_info_ratio', models.FloatField()),
                ('caregivers_informed', models.IntegerField()),
                ('caregivers_informed_ratio', models.FloatField()),
                ('lqas_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_stats', to='polio.lqasentry')),
            ],
            options={
                'verbose_name': 'LQAS Care Giver Statistics',
            },
        ),
        migrations.CreateModel(
            name='LqasNoMarkStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other', models.IntegerField()),
                ('child_absent', models.IntegerField()),
                ('non_compliance', models.IntegerField()),
                ('child_was_asleep', models.IntegerField()),
                ('house_not_visited', models.IntegerField()),
                ('child_is_a_visitor', models.IntegerField()),
                ('vaccinated_but_not_fm', models.IntegerField()),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polio.round')),
                ('subactivity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polio.subactivity')),
            ],
            options={
                'verbose_name': 'LQAS No Finger Mark Statistics',
                'verbose_name_plural': 'LQAS No Finger Mark Statistics',
                'abstract': False,
                'unique_together': {('round', 'subactivity')},
            },
        ),
        migrations.CreateModel(
            name='LqasActivityStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lqas_failed', models.IntegerField()),
                ('lqas_passeded', models.IntegerField()),
                ('lqas_no_data', models.IntegerField()),
                ('status', models.CharField(choices=[('1lqasOK', '1lqasOK'), ('2lqasDisqualified', '2lqasDisqualified'), ('3lqaspoor', '3lqaspoor'), ('3lqasmoderate', '3lqasmoderate'), ('3lqasundersampled', '3lqasundersampled'), ('3lqasoversampled', '3lqasoversampled'), ('inScope', 'inScope')], default='inScope', max_length=20)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polio.round')),
                ('subactivity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polio.subactivity')),
            ],
            options={
                'verbose_name': 'LQAS Activity Statistics',
                'verbose_name_plural': 'LQAS Activity Statistics',
                'abstract': False,
                'unique_together': {('round', 'subactivity')},
            },
        ),
        migrations.CreateModel(
            name='LqasAbsenceStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm', models.IntegerField()),
                ('other', models.IntegerField()),
                ('market', models.IntegerField()),
                ('school', models.IntegerField()),
                ('travelled', models.IntegerField()),
                ('in_playground', models.IntegerField()),
                ('unknown', models.IntegerField()),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polio.round')),
                ('subactivity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polio.subactivity')),
            ],
            options={
                'verbose_name': 'LQAS Absent Children Statistics',
                'verbose_name_plural': 'LQAS Absent Children Statistics',
                'abstract': False,
                'unique_together': {('round', 'subactivity')},
            },
        ),
    ]
