# Generated by Django 4.2.23 on 2025-08-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polio', '0238_lqasnomarkstats_lqasentry_lqascaregiverstats_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lqasentry',
            index=models.Index(fields=['district', 'round'], name='polio_lqase_distric_6a5d18_idx'),
        ),
        migrations.AddIndex(
            model_name='lqasentry',
            index=models.Index(fields=['subactivity', 'round'], name='polio_lqase_subacti_6eb7e8_idx'),
        ),
        migrations.AddIndex(
            model_name='lqasentry',
            index=models.Index(fields=['district', 'round', 'subactivity'], name='polio_lqase_distric_69f548_idx'),
        ),
    ]
