# Generated by Django 4.2.17 on 2025-09-12 15:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0238_lqasrounddata_lqasdistrictdata_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="poliopermissionsupport",
            options={
                "default_permissions": [],
                "managed": False,
                "permissions": [
                    ("iaso_polio", "Polio"),
                    ("iaso_polio_budget", "Budget Polio"),
                    ("iaso_polio_budget_admin", "Budget Polio Admin"),
                    ("iaso_polio_config", "Polio config"),
                    ("iaso_polio_chronogram", "Polio chronogram"),
                    (
                        "iaso_polio_chronogram_restricted_write",
                        "Polio chronogram user (restricted write)",
                    ),
                    ("iaso_polio_notifications", "Polio notifications"),
                    (
                        "iaso_polio_vaccine_authorizations_admin",
                        "Polio Vaccine Authorizations Admin",
                    ),
                    (
                        "iaso_polio_vaccine_authorizations_read_only",
                        "Polio Vaccine Authorizations Read Only",
                    ),
                    (
                        "iaso_polio_vaccine_stock_earmarks_admin",
                        "Polio Vaccine Stock Earmarks Admin",
                    ),
                    (
                        "iaso_polio_vaccine_stock_earmarks_nonadmin",
                        "Polio Vaccine Stock Earmarks Non Admin",
                    ),
                    (
                        "iaso_polio_vaccine_stock_earmarks_read_only",
                        "Polio Vaccine Stock Earmarks Read Only",
                    ),
                    (
                        "iaso_polio_vaccine_stock_management_read",
                        "Polio Vaccine Stock Management Read",
                    ),
                    (
                        "iaso_polio_vaccine_stock_management_read_only",
                        "Polio Vaccine Stock Management Read Only",
                    ),
                    (
                        "iaso_polio_vaccine_stock_management_write",
                        "Polio Vaccine Stock Management Write",
                    ),
                    (
                        "iaso_polio_vaccine_supply_chain_read",
                        "Polio Vaccine Supply Chain Read",
                    ),
                    (
                        "iaso_polio_vaccine_supply_chain_read_only",
                        "Polio Vaccine Supply Chain Read Only",
                    ),
                    (
                        "iaso_polio_vaccine_supply_chain_write",
                        "Polio Vaccine Supply Chain Write",
                    ),
                ],
            },
        ),
    ]
