# Generated by Django 4.2.23 on 2025-08-12 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polio', '0239_lqasdistrictdata_polio_lqasd_distric_c33190_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lqasdistrictdata',
            name='polio_lqasd_distric_c33190_idx',
        ),
    ]
