# Generated by Django 4.2.25 on 2025-10-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0240_auto_20251014_0943"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vaccinearrivalreport",
            name="doses_per_vial",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="vaccineprealert",
            name="doses_per_vial",
            field=models.PositiveIntegerField(),
        ),
    ]
