# Generated by Django 4.2.25 on 2025-10-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0241_alter_vaccinearrivalreport_doses_per_vial_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="destructionreport",
            name="doses_per_vial",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="doses_per_vial",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="outgoingstockmovement",
            name="doses_per_vial",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
