# Generated by Django 4.2.25 on 2025-10-24 11:33

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0244_alter_destructionreport_doses_per_vial_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="integrated_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="integrated_campaigns",
                to="polio.campaign",
            ),
        ),
    ]
