# Generated by Django 4.2.25 on 2025-10-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polio', '0244_alter_destructionreport_doses_per_vial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='earmarkedstock',
            name='doses_per_vial',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
