# Generated by Django 4.2.25 on 2025-10-24 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0245_campaign_integrated_to"),
        ("polio", "0245_campaign_is_planned_round_is_planned_and_more"),
    ]

    operations = []
