# Generated by Django 4.2.25 on 2025-10-15 14:34

from django.db import migrations


DOSES_PER_VIAL = {
    "mOPV2": 20,
    "nOPV2": 50,
    "bOPV": 20,
}


def add_doses_per_vial(apps, schema_editor):
    EarmarkedStock = apps.get_model("polio", "EarmarkedStock")

    earmarked_stocks = EarmarkedStock.objects.filter(doses_per_vial__isnull=True).prefetch_related("vaccine_stock")

    for stock in earmarked_stocks:
        doses_per_vial = DOSES_PER_VIAL.get(stock.vaccine_stock.vaccine, 20)
        stock.doses_per_vial = doses_per_vial
        stock.save()


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0245_earmarkedstock_doses_per_vial"),
    ]

    operations = [migrations.RunPython(add_doses_per_vial, migrations.RunPython.noop)]
