# Generated by Django 4.2.26 on 2025-12-03 15:52

from django.db import migrations


def transfer_permission(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Permission = apps.get_model("auth", "Permission")
    admin_permissions = ["iaso_polio_vaccine_stock_earmarks_admin", "iaso_polio_vaccine_stock_management_write"]
    non_admin_permissions = ["iaso_polio_vaccine_stock_earmarks_nonadmin", "iaso_polio_vaccine_stock_management_read"]
    read_only_permissions = [
        "iaso_polio_vaccine_stock_earmarks_read_only",
        "iaso_polio_vaccine_stock_management_read_only",
    ]
    admin_perm = Permission.objects.get(codename="iaso_polio_performance_admin")
    non_admin_perm = Permission.objects.get(codename="iaso_polio_performance_non_admin")
    read_only_perm = Permission.objects.get(codename="iaso_polio_performance_read_only")
    admin_users = User.objects.filter(user_permissions__codename__in=admin_permissions).distinct()
    non_admin_users = User.objects.filter(user_permissions__codename__in=non_admin_permissions).distinct()
    read_only_users = User.objects.filter(user_permissions__codename__in=read_only_permissions).distinct()
    for user in admin_users:
        user.user_permissions.add(admin_perm)
    for user in non_admin_users:
        user.user_permissions.add(non_admin_perm)
    for user in read_only_users:
        user.user_permissions.add(read_only_perm)


def remove_permission(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Permission = apps.get_model("auth", "Permission")
    admin_perm = Permission.objects.get(codename="iaso_polio_performance_admin")
    non_admin_perm = Permission.objects.get(codename="iaso_polio_performance_non_admin")
    read_only_perm = Permission.objects.get(codename="iaso_polio_performance_read_only")
    admin_users = User.objects.filter(user_permissions__codename="iaso_polio_performance_admin").distinct()
    non_admin_users = User.objects.filter(user_permissions__codename="iaso_polio_performance_non_admin").distinct()
    read_only_users = User.objects.filter(user_permissions__codename="iaso_polio_performance_read_only").distinct()
    for user in admin_users:
        user.user_permissions.remove(admin_perm)
    for user in non_admin_users:
        user.user_permissions.remove(non_admin_perm)
    for user in read_only_users:
        user.user_permissions.remove(read_only_perm)


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0247_alter_poliopermissionsupport_options_and_more"),
    ]

    operations = [
        migrations.RunPython(transfer_permission, remove_permission),
    ]
