# Generated by Django 4.2.27 on 2025-12-09 09:52

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0355_merge_20251125_1555"),
        ("polio", "0247_alter_poliopermissionsupport_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountryPlan",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("commented", "Commented"), ("final", "Final")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "vaccine",
                    models.CharField(
                        choices=[
                            ("mOPV2", "mOPV2"),
                            ("nOPV2", "nOPV2"),
                            ("bOPV", "bOPV"),
                            ("nOPV2 & bOPV", "nOPV2 & bOPV"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="country_plans", to="iaso.account"
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="country_plans", to="iaso.orgunit"
                    ),
                ),
            ],
            options={
                "verbose_name": "Performance Dashboard",
                "ordering": ["-date", "country__name"],
            },
        ),
        migrations.CreateModel(
            name="PerformanceThresholds",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("indicator", models.CharField(max_length=200)),
                ("fail_threshold", models.JSONField()),
                ("warning_threshold", models.JSONField()),
                ("success_threshold", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_thresholds",
                        to="iaso.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Performance Threshold",
                "verbose_name_plural": "Performance Thresholds",
                "ordering": ["indicator"],
            },
        ),
        migrations.AlterModelOptions(
            name="poliopermissionsupport",
            options={
                "default_permissions": [],
                "managed": False,
                "permissions": [
                    ("iaso_polio", "Polio"),
                    ("iaso_polio_budget", "Budget Polio"),
                    ("iaso_polio_budget_admin", "Budget Polio Admin"),
                    ("iaso_polio_config", "Polio config"),
                    ("iaso_polio_chronogram", "Polio chronogram"),
                    ("iaso_polio_chronogram_restricted_write", "Polio chronogram user (restricted write)"),
                    ("iaso_polio_notifications", "Polio notifications"),
                    ("iaso_polio_vaccine_authorizations_admin", "Polio Vaccine Authorizations Admin"),
                    ("iaso_polio_vaccine_authorizations_read_only", "Polio Vaccine Authorizations Read Only"),
                    ("iaso_polio_vaccine_stock_earmarks_admin", "Polio Vaccine Stock Earmarks Admin"),
                    ("iaso_polio_vaccine_stock_earmarks_nonadmin", "Polio Vaccine Stock Earmarks Non Admin"),
                    ("iaso_polio_vaccine_stock_earmarks_read_only", "Polio Vaccine Stock Earmarks Read Only"),
                    ("iaso_polio_vaccine_stock_management_read", "Polio Vaccine Stock Management Read"),
                    ("iaso_polio_vaccine_stock_management_read_only", "Polio Vaccine Stock Management Read Only"),
                    ("iaso_polio_vaccine_stock_management_write", "Polio Vaccine Stock Management Write"),
                    ("iaso_polio_vaccine_supply_chain_read", "Polio Vaccine Supply Chain Read"),
                    ("iaso_polio_vaccine_supply_chain_read_only", "Polio Vaccine Supply Chain Read Only"),
                    ("iaso_polio_vaccine_supply_chain_write", "Polio Vaccine Supply Chain Write"),
                    ("iaso_polio_country_plan_read_only", "Polio Country Plan Read Only"),
                    ("iaso_polio_country_plan_non_admin", "Polio Country Plan Non Admin"),
                    ("iaso_polio_country_plan_admin", "Polio Country Plan Admin"),
                ],
            },
        ),
        migrations.DeleteModel(
            name="PerformanceDashboard",
        ),
        migrations.AddIndex(
            model_name="performancethresholds",
            index=models.Index(fields=["account"], name="polio_perfo_account_5297b8_idx"),
        ),
        migrations.AddIndex(
            model_name="performancethresholds",
            index=models.Index(fields=["indicator"], name="polio_perfo_indicat_bd050f_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="performancethresholds",
            unique_together={("account", "indicator")},
        ),
        migrations.AddIndex(
            model_name="countryplan",
            index=models.Index(fields=["account"], name="polio_count_account_1a08c3_idx"),
        ),
        migrations.AddIndex(
            model_name="countryplan",
            index=models.Index(fields=["country"], name="polio_count_country_5f972e_idx"),
        ),
    ]
