# Generated by Django 4.2.26 on 2025-12-03 11:04

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iaso", "0355_merge_20251125_1555"),
        ("polio", "0247_alter_poliopermissionsupport_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceThresholds",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("indicator", models.CharField(max_length=200)),
                ("fail_threshold", models.JSONField()),
                ("warning_threshold", models.JSONField()),
                ("success_threshold", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_thresholds",
                        to="iaso.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Performance Threshold",
                "verbose_name_plural": "Performance Thresholds",
                "ordering": ["indicator"],
                "indexes": [
                    models.Index(fields=["account"], name="polio_perfo_account_5297b8_idx"),
                    models.Index(fields=["indicator"], name="polio_perfo_indicat_bd050f_idx"),
                ],
                "unique_together": {("account", "indicator")},
            },
        ),
    ]
