# Generated by Django 4.2.26 on 2025-12-04 16:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0248_performancethresholds"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="performancedashboard",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="performancedashboard",
            name="updated_by",
        ),
    ]
