# Generated by Django 4.2.30 on 2026-04-15 17:09

from django.db import migrations, models


def mark_existing_form_as_received(apps, schema_editor):
    OutgoingStockMovement = apps.get_model("polio", "OutgoingStockMovement")
    OutgoingStockMovement.objects.all().update(status="received")


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0252_alter_incidentreport_stock_correction"),
    ]

    operations = [
        migrations.AddField(
            model_name="outgoingstockmovement",
            name="status",
            field=models.CharField(
                choices=[("temporary", "Temporary"), ("received", "Received")], default="received", max_length=20
            ),
        ),
        migrations.RunPython(mark_existing_form_as_received, noop_reverse),
        migrations.AlterField(
            model_name="outgoingstockmovement",
            name="form_a_reception_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
