# Generated by Django 4.2.30 on 2026-07-03 14:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0254_remove_round_date_destruction_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="approval_confirmed_at_WFEDITABLE",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="approved_at_WFEDITABLE",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="approved_by_unicef_at_WFEDITABLE",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="approved_by_who_at_WFEDITABLE",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="feedback_sent_to_gpei_at_WFEDITABLE",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="feedback_sent_to_orpg_operations_unicef_at_WFEDITABLE",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="feedback_sent_to_orpg_operations_who_at_WFEDITABLE",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="feedback_sent_to_rrt1_at_WFEDITABLE",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="feedback_sent_to_rrt2_at_WFEDITABLE",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="gpei_consolidated_budgets_at_WFEDITABLE",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="ra_completed_at_WFEDITABLE",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="re_submitted_to_orpg_operations1_at_WFEDITABLE",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="re_submitted_to_orpg_operations2_at_WFEDITABLE",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="re_submitted_to_rrt_at_WFEDITABLE",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="submitted_for_approval_at_WFEDITABLE",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="submitted_to_orpg_operations1_at_WFEDITABLE",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="submitted_to_orpg_operations2_at_WFEDITABLE",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="submitted_to_orpg_wider_at_WFEDITABLE",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="submitted_to_rrt_at_WFEDITABLE",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="unicef_sent_budget_at_WFEDITABLE",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="who_sent_budget_at_WFEDITABLE",
        ),
    ]
