# Generated by Django 4.2.28 on 2026-09-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polio", "0256_backfill_modelwithfile_md5"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vaccinerequestform",
            name="vaccine_type",
            field=models.CharField(
                choices=[("mOPV2", "mOPV2"), ("nOPV2", "nOPV2"), ("bOPV", "bOPV"), ("IPV", "IPV")],
                max_length=30,
            ),
        ),
    ]
