import { SxStyles } from '../../../../../../hat/assets/js/apps/Iaso/types/general';

const absoluteStyle = {
    boxSizing: 'border-box',
    position: 'absolute',
    borderRadius: '100%',
};

const boxRadius = '30px';
const fontFamily = 'Work Sans, sans-serif';

export const styles: SxStyles = {
    background: {
        position: 'fixed',
        width: '100vw',
        height: '120vh',
        background: '#F1F3F8',
        zIndex: 1,
    },
    ellipse1: {
        ...absoluteStyle,
        width: '1583px',
        height: '1583px',
        left: '-638px',
        top: '-690px',
        border: '1px solid rgba(95, 28, 74, 0.1)',
    },
    ellipse2: {
        ...absoluteStyle,
        width: '499px',
        height: '499px',
        left: '-96px',
        top: '-148px',
        border: '1px solid #E0EBEE',
    },
    ellipse3: {
        ...absoluteStyle,
        width: '2139px',
        height: '2139px',
        left: '-916px',
        top: '-968px',
        border: '1px solid rgba(255, 255, 255, 0.8)',
    },
    ellipse4: {
        ...absoluteStyle,
        width: '1059px',
        height: '1059px',
        left: '-376px',
        top: '-428px',
        border: '27px solid #E4F3FE',
        filter: 'blur(17px)',
    },
    ellipse5: {
        ...absoluteStyle,
        width: '725px',
        height: '725px',
        left: '-209px',
        top: '-261px',
        border: '1px solid #E0EBEE',
    },
    round1: {
        ...absoluteStyle,
        width: '12px',
        height: '12px',
        left: '20px',
        top: '310px',
        background: '#86386E',
    },
    round2: {
        ...absoluteStyle,
        width: '12px',
        height: '12px',
        left: '474px',
        top: '255px',
        background: '#E38061',
    },
    round3: {
        ...absoluteStyle,
        width: '12px',
        height: '12px',
        left: '389px',
        top: '33px',
        background: '#0B9BF9',
    },
    container: {
        position: 'relative',
        width: '100vw',
        height: '100vh',
        zIndex: 2,
        overflow: 'auto',
    },
    blueBox: {
        background: '#0B9BF9',
        width: '100%',
        padding: '4vw 6vw 0 8vw',
        fontSize: '1.95vw',
        lineHeight: '1.3',
        borderRadius: boxRadius,
        color: '#fff',
        fontWeight: 400,
        fontFamily,
    },
    whiteBox: {
        background: '#fff',
        width: '100%',
        padding: '4vw 8vw',
        borderRadius: boxRadius,
        fontFamily,
        fontSize: '1.35vw',
        lineHeight: '1.3',
    },
    title: {
        fontSize: '5.7vw',
        fontWeight: 500,
        lineHeight: '1',
        color: '#1C3B5F',
        fontFamily,
    },
    link: {
        display: 'block',
        padding: '4vw 0',
        '& a': {
            color: '#fff',
            borderRadius: '25px',
            textDecoration: 'none',
            padding: '14px 20px',
            width: 'fit-content',
            fontSize: '1.35vw',
            lineHeight: '1.3',
            background: '#E36178',
            transition: 'background-color 0.3s ease',
            display: 'flex',
            alignItems: 'center',
            '&:hover': {
                background: '#cc556a',
            },
        },
    },
    arrow: {
        marginLeft: '10px',
        fontSize: '2.4vw',
    },
    logoContainer: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'flex-start',
        paddingBottom: '4vw',
        '& span': {
            fontFamily,
            fontSize: '0.97vw',
            fontStyle: 'italic',
            fontWeight: 400,
            lineHeight: '24px',
            textAlign: 'left',
        },
    },
    logo: {
        width: '120px',
        height: '120px',
        borderRadius: '30px',
        overflow: 'hidden',
        backgroundColor: '#f7f7f7',
        boxShadow: '0px 4px 10px rgba(0, 0, 0, 0.1)',
        marginRight: '20px',
        flexShrink: 0,
        flexGrow: 0,
        aspectRatio: '1 / 1',
        '& img': {
            width: '100%',
            height: '100%',
            objectFit: 'contain',
        },
    },
    content: {
        width: '100%',
        padding: '5vw',
    },
    footer: {
        background: '#fff',
        width: '100%',
        padding: '4vw 6vw',
    },
    footerText: {
        fontFamily: 'Work Sans',
        fontSize: '0.97vw',
        fontWeight: 400,
        lineHeight: '24px',
        textAlign: 'left',
        color: '#111111',
        width: '19vw',
        '& a': {
            color: '#111111',
            textDecoration: 'underline',
            marginLeft: '10px',
        },
    },
};
