/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Iaso
 * Iaso Swagger
 * OpenAPI spec version: v1
 */
import { faker } from '@faker-js/faker';

import { HttpResponse, delay, http } from 'msw';
import type { RequestHandlerOptions } from 'msw';

import { ModulesEnum } from '../../models';
import type {
    AccountCustomTranslations,
    AccountRetrieve,
    AccountRetrieveAIApiKey,
    AccountRetrieveCurrent,
    PaginatedAccountListList,
} from '../../models';

export const getApiAccountsListResponseMock = (
    overrideResponse: Partial<Extract<PaginatedAccountListList, object>> = {},
): PaginatedAccountListList =>
    faker.helpers.arrayElement([
        {
            count: faker.helpers.arrayElement([faker.number.int(), undefined]),
            has_next: faker.helpers.arrayElement([
                faker.datatype.boolean(),
                undefined,
            ]),
            has_previous: faker.helpers.arrayElement([
                faker.datatype.boolean(),
                undefined,
            ]),
            limit: faker.helpers.arrayElement([faker.number.int(), undefined]),
            page: faker.helpers.arrayElement([faker.number.int(), undefined]),
            pages: faker.helpers.arrayElement([faker.number.int(), undefined]),
            results: faker.helpers.arrayElement([
                Array.from(
                    { length: faker.number.int({ min: 1, max: 10 }) },
                    (_, i) => i + 1,
                ).map(() => ({
                    id: faker.number.int(),
                    name: faker.string.alpha({ length: { min: 1, max: 20 } }),
                    created_at:
                        faker.date.past().toISOString().slice(0, 19) + 'Z',
                    updated_at:
                        faker.date.past().toISOString().slice(0, 19) + 'Z',
                })),
                undefined,
            ]),
            ...overrideResponse,
        },
        {
            count: faker.helpers.arrayElement([faker.number.int(), undefined]),
            has_next: faker.helpers.arrayElement([
                faker.datatype.boolean(),
                undefined,
            ]),
            has_previous: faker.helpers.arrayElement([
                faker.datatype.boolean(),
                undefined,
            ]),
            limit: faker.helpers.arrayElement([faker.number.int(), undefined]),
            page: faker.helpers.arrayElement([faker.number.int(), undefined]),
            pages: faker.helpers.arrayElement([faker.number.int(), undefined]),
            results: faker.helpers.arrayElement([
                Array.from(
                    { length: faker.number.int({ min: 1, max: 10 }) },
                    (_, i) => i + 1,
                ).map(() => ({
                    id: faker.number.int(),
                    name: faker.string.alpha({ length: { min: 1, max: 20 } }),
                    created_at:
                        faker.date.past().toISOString().slice(0, 19) + 'Z',
                    updated_at:
                        faker.date.past().toISOString().slice(0, 19) + 'Z',
                })),
                undefined,
            ]),
            ...overrideResponse,
        },
    ]);

export const getApiAccountsRetrieveResponseMock = (
    overrideResponse: Partial<Extract<AccountRetrieve, object>> = {},
): AccountRetrieve =>
    faker.helpers.arrayElement([
        {
            id: faker.number.int(),
            name: faker.string.alpha({ length: { min: 10, max: 20 } }),
            created_at: faker.date.past().toISOString().slice(0, 19) + 'Z',
            user_manual_path: faker.helpers.arrayElement([
                faker.string.alpha({ length: { min: 10, max: 20 } }),
                null,
            ]),
            forum_path: faker.helpers.arrayElement([
                faker.string.alpha({ length: { min: 10, max: 20 } }),
                null,
            ]),
            modules: faker.helpers.arrayElement([
                faker.helpers.arrayElements(Object.values(ModulesEnum)),
                null,
            ]),
            enforce_password_validation: faker.datatype.boolean(),
            feature_flags: faker.helpers.arrayElement([
                Array.from(
                    { length: faker.number.int({ min: 1, max: 10 }) },
                    (_, i) => i + 1,
                ).map(() => ({
                    name: faker.string.alpha({ length: { min: 10, max: 255 } }),
                    code: faker.string.alpha({ length: { min: 10, max: 255 } }),
                })),
                null,
            ]),
            ...overrideResponse,
        },
        {
            id: faker.number.int(),
            name: faker.string.alpha({ length: { min: 10, max: 20 } }),
            created_at: faker.date.past().toISOString().slice(0, 19) + 'Z',
            user_manual_path: faker.helpers.arrayElement([
                faker.string.alpha({ length: { min: 10, max: 20 } }),
                null,
            ]),
            forum_path: faker.helpers.arrayElement([
                faker.string.alpha({ length: { min: 10, max: 20 } }),
                null,
            ]),
            modules: faker.helpers.arrayElement([
                faker.helpers.arrayElements(Object.values(ModulesEnum)),
                null,
            ]),
            enforce_password_validation: faker.datatype.boolean(),
            feature_flags: faker.helpers.arrayElement([
                Array.from(
                    { length: faker.number.int({ min: 1, max: 10 }) },
                    (_, i) => i + 1,
                ).map(() => ({
                    name: faker.string.alpha({ length: { min: 10, max: 255 } }),
                    code: faker.string.alpha({ length: { min: 10, max: 255 } }),
                })),
                null,
            ]),
            ...overrideResponse,
        },
    ]);

export const getApiAccountsAiApiKeyRetrieveResponseMock = (
    overrideResponse: Partial<Extract<AccountRetrieveAIApiKey, object>> = {},
): AccountRetrieveAIApiKey =>
    faker.helpers.arrayElement([
        {
            anthropic_api_key: faker.helpers.arrayElement([
                faker.string.alpha({ length: { min: 10, max: 20 } }),
                null,
            ]),
            ...overrideResponse,
        },
        {
            anthropic_api_key: faker.helpers.arrayElement([
                faker.string.alpha({ length: { min: 10, max: 20 } }),
                null,
            ]),
            ...overrideResponse,
        },
    ]);

export const getApiAccountsCustomTranslationsRetrieveResponseMock = (
    overrideResponse: Partial<Extract<AccountCustomTranslations, object>> = {},
): AccountCustomTranslations =>
    faker.helpers.arrayElement([
        {
            custom_translations: faker.helpers.arrayElement([{}, null]),
            ...overrideResponse,
        },
        {
            custom_translations: faker.helpers.arrayElement([{}, null]),
            ...overrideResponse,
        },
    ]);

export const getApiAccountsMeRetrieveResponseMock = (
    overrideResponse: Partial<Extract<AccountRetrieveCurrent, object>> = {},
): AccountRetrieveCurrent =>
    faker.helpers.arrayElement([
        {
            id: faker.number.int(),
            name: faker.string.alpha({ length: { min: 10, max: 20 } }),
            default_version: faker.helpers.arrayElement([
                {
                    ...{
                        id: faker.number.int(),
                        data_source: {
                            ...{
                                id: faker.number.int(),
                                url: faker.helpers.arrayElement([
                                    faker.string.alpha({
                                        length: { min: 10, max: 20 },
                                    }),
                                    null,
                                ]),
                                name: faker.string.alpha({
                                    length: { min: 10, max: 20 },
                                }),
                                tree_config_status_fields: Array.from(
                                    {
                                        length: faker.number.int({
                                            min: 1,
                                            max: 10,
                                        }),
                                    },
                                    (_, i) => i + 1,
                                ).map(() =>
                                    faker.string.alpha({
                                        length: { min: 10, max: 30 },
                                    }),
                                ),
                            },
                        },
                        number: faker.number.int(),
                    },
                },
                null,
            ]),
            other_accounts: faker.helpers.arrayElement([
                Array.from(
                    { length: faker.number.int({ min: 1, max: 10 }) },
                    (_, i) => i + 1,
                ).map(() => ({
                    id: faker.number.int(),
                    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
                })),
                null,
            ]),
            modules: faker.helpers.arrayElement([
                faker.helpers.arrayElements(Object.values(ModulesEnum)),
                null,
            ]),
            feature_flags: faker.helpers.arrayElement([
                Array.from(
                    { length: faker.number.int({ min: 1, max: 10 }) },
                    (_, i) => i + 1,
                ).map(() => ({
                    name: faker.string.alpha({ length: { min: 10, max: 255 } }),
                    code: faker.string.alpha({ length: { min: 10, max: 255 } }),
                })),
                undefined,
            ]),
            user_manual_path: faker.helpers.arrayElement([
                faker.string.alpha({ length: { min: 10, max: 20 } }),
                null,
            ]),
            forum_path: faker.helpers.arrayElement([
                faker.string.alpha({ length: { min: 10, max: 20 } }),
                null,
            ]),
            ...overrideResponse,
        },
        {
            id: faker.number.int(),
            name: faker.string.alpha({ length: { min: 10, max: 20 } }),
            default_version: faker.helpers.arrayElement([
                {
                    ...{
                        id: faker.number.int(),
                        data_source: {
                            ...{
                                id: faker.number.int(),
                                url: faker.helpers.arrayElement([
                                    faker.string.alpha({
                                        length: { min: 10, max: 20 },
                                    }),
                                    null,
                                ]),
                                name: faker.string.alpha({
                                    length: { min: 10, max: 20 },
                                }),
                                tree_config_status_fields: Array.from(
                                    {
                                        length: faker.number.int({
                                            min: 1,
                                            max: 10,
                                        }),
                                    },
                                    (_, i) => i + 1,
                                ).map(() =>
                                    faker.string.alpha({
                                        length: { min: 10, max: 30 },
                                    }),
                                ),
                            },
                        },
                        number: faker.number.int(),
                    },
                },
                null,
            ]),
            other_accounts: faker.helpers.arrayElement([
                Array.from(
                    { length: faker.number.int({ min: 1, max: 10 }) },
                    (_, i) => i + 1,
                ).map(() => ({
                    id: faker.number.int(),
                    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
                })),
                null,
            ]),
            modules: faker.helpers.arrayElement([
                faker.helpers.arrayElements(Object.values(ModulesEnum)),
                null,
            ]),
            feature_flags: faker.helpers.arrayElement([
                Array.from(
                    { length: faker.number.int({ min: 1, max: 10 }) },
                    (_, i) => i + 1,
                ).map(() => ({
                    name: faker.string.alpha({ length: { min: 10, max: 255 } }),
                    code: faker.string.alpha({ length: { min: 10, max: 255 } }),
                })),
                undefined,
            ]),
            user_manual_path: faker.helpers.arrayElement([
                faker.string.alpha({ length: { min: 10, max: 20 } }),
                null,
            ]),
            forum_path: faker.helpers.arrayElement([
                faker.string.alpha({ length: { min: 10, max: 20 } }),
                null,
            ]),
            ...overrideResponse,
        },
    ]);

export const getApiAccountsListMockHandler = (
    overrideResponse?:
        | PaginatedAccountListList
        | ((
              info: Parameters<Parameters<typeof http.get>[1]>[0],
          ) => Promise<PaginatedAccountListList> | PaginatedAccountListList),
    options?: RequestHandlerOptions,
) => {
    return http.get(
        '*/api/accounts/',
        async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
            await delay(
                (() =>
                    process.env?.MSW_DELAY
                        ? parseInt(process.env.MSW_DELAY)
                        : 0)(),
            );

            return HttpResponse.json(
                overrideResponse !== undefined
                    ? typeof overrideResponse === 'function'
                        ? await overrideResponse(info)
                        : overrideResponse
                    : getApiAccountsListResponseMock(),
                { status: 200 },
            );
        },
        options,
    );
};

export const getApiAccountsRetrieveMockHandler = (
    overrideResponse?:
        | AccountRetrieve
        | ((
              info: Parameters<Parameters<typeof http.get>[1]>[0],
          ) => Promise<AccountRetrieve> | AccountRetrieve),
    options?: RequestHandlerOptions,
) => {
    return http.get(
        '*/api/accounts/:id/',
        async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
            await delay(
                (() =>
                    process.env?.MSW_DELAY
                        ? parseInt(process.env.MSW_DELAY)
                        : 0)(),
            );

            return HttpResponse.json(
                overrideResponse !== undefined
                    ? typeof overrideResponse === 'function'
                        ? await overrideResponse(info)
                        : overrideResponse
                    : getApiAccountsRetrieveResponseMock(),
                { status: 200 },
            );
        },
        options,
    );
};

export const getApiAccountsUpdateMockHandler = (
    overrideResponse?:
        | void
        | ((
              info: Parameters<Parameters<typeof http.put>[1]>[0],
          ) => Promise<void> | void),
    options?: RequestHandlerOptions,
) => {
    return http.put(
        '*/api/accounts/:id/',
        async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {
            await delay(
                (() =>
                    process.env?.MSW_DELAY
                        ? parseInt(process.env.MSW_DELAY)
                        : 0)(),
            );
            if (typeof overrideResponse === 'function') {
                await overrideResponse(info);
            }

            return new HttpResponse(null, { status: 204 });
        },
        options,
    );
};

export const getApiAccountsPartialUpdateMockHandler = (
    overrideResponse?:
        | void
        | ((
              info: Parameters<Parameters<typeof http.patch>[1]>[0],
          ) => Promise<void> | void),
    options?: RequestHandlerOptions,
) => {
    return http.patch(
        '*/api/accounts/:id/',
        async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
            await delay(
                (() =>
                    process.env?.MSW_DELAY
                        ? parseInt(process.env.MSW_DELAY)
                        : 0)(),
            );
            if (typeof overrideResponse === 'function') {
                await overrideResponse(info);
            }

            return new HttpResponse(null, { status: 200 });
        },
        options,
    );
};

export const getApiAccountsAiApiKeyRetrieveMockHandler = (
    overrideResponse?:
        | AccountRetrieveAIApiKey
        | ((
              info: Parameters<Parameters<typeof http.get>[1]>[0],
          ) => Promise<AccountRetrieveAIApiKey> | AccountRetrieveAIApiKey),
    options?: RequestHandlerOptions,
) => {
    return http.get(
        '*/api/accounts/:id/ai-api-key/',
        async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
            await delay(
                (() =>
                    process.env?.MSW_DELAY
                        ? parseInt(process.env.MSW_DELAY)
                        : 0)(),
            );

            return HttpResponse.json(
                overrideResponse !== undefined
                    ? typeof overrideResponse === 'function'
                        ? await overrideResponse(info)
                        : overrideResponse
                    : getApiAccountsAiApiKeyRetrieveResponseMock(),
                { status: 200 },
            );
        },
        options,
    );
};

export const getApiAccountsAiApiKeyUpdateMockHandler = (
    overrideResponse?:
        | void
        | ((
              info: Parameters<Parameters<typeof http.put>[1]>[0],
          ) => Promise<void> | void),
    options?: RequestHandlerOptions,
) => {
    return http.put(
        '*/api/accounts/:id/ai-api-key/',
        async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {
            await delay(
                (() =>
                    process.env?.MSW_DELAY
                        ? parseInt(process.env.MSW_DELAY)
                        : 0)(),
            );
            if (typeof overrideResponse === 'function') {
                await overrideResponse(info);
            }

            return new HttpResponse(null, { status: 204 });
        },
        options,
    );
};

export const getApiAccountsAiApiKeyDestroyMockHandler = (
    overrideResponse?:
        | void
        | ((
              info: Parameters<Parameters<typeof http.delete>[1]>[0],
          ) => Promise<void> | void),
    options?: RequestHandlerOptions,
) => {
    return http.delete(
        '*/api/accounts/:id/ai-api-key/',
        async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
            await delay(
                (() =>
                    process.env?.MSW_DELAY
                        ? parseInt(process.env.MSW_DELAY)
                        : 0)(),
            );
            if (typeof overrideResponse === 'function') {
                await overrideResponse(info);
            }

            return new HttpResponse(null, { status: 204 });
        },
        options,
    );
};

export const getApiAccountsCustomTranslationsRetrieveMockHandler = (
    overrideResponse?:
        | AccountCustomTranslations
        | ((
              info: Parameters<Parameters<typeof http.get>[1]>[0],
          ) => Promise<AccountCustomTranslations> | AccountCustomTranslations),
    options?: RequestHandlerOptions,
) => {
    return http.get(
        '*/api/accounts/:id/custom-translations/',
        async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
            await delay(
                (() =>
                    process.env?.MSW_DELAY
                        ? parseInt(process.env.MSW_DELAY)
                        : 0)(),
            );

            return HttpResponse.json(
                overrideResponse !== undefined
                    ? typeof overrideResponse === 'function'
                        ? await overrideResponse(info)
                        : overrideResponse
                    : getApiAccountsCustomTranslationsRetrieveResponseMock(),
                { status: 200 },
            );
        },
        options,
    );
};

export const getApiAccountsSetDefaultVersionUpdateMockHandler = (
    overrideResponse?:
        | void
        | ((
              info: Parameters<Parameters<typeof http.put>[1]>[0],
          ) => Promise<void> | void),
    options?: RequestHandlerOptions,
) => {
    return http.put(
        '*/api/accounts/:id/set-default-version/',
        async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {
            await delay(
                (() =>
                    process.env?.MSW_DELAY
                        ? parseInt(process.env.MSW_DELAY)
                        : 0)(),
            );
            if (typeof overrideResponse === 'function') {
                await overrideResponse(info);
            }

            return new HttpResponse(null, { status: 204 });
        },
        options,
    );
};

export const getApiAccountsSetDefaultVersionPartialUpdateMockHandler = (
    overrideResponse?:
        | void
        | ((
              info: Parameters<Parameters<typeof http.patch>[1]>[0],
          ) => Promise<void> | void),
    options?: RequestHandlerOptions,
) => {
    return http.patch(
        '*/api/accounts/:id/set-default-version/',
        async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
            await delay(
                (() =>
                    process.env?.MSW_DELAY
                        ? parseInt(process.env.MSW_DELAY)
                        : 0)(),
            );
            if (typeof overrideResponse === 'function') {
                await overrideResponse(info);
            }

            return new HttpResponse(null, { status: 204 });
        },
        options,
    );
};

export const getApiAccountsMeRetrieveMockHandler = (
    overrideResponse?:
        | AccountRetrieveCurrent
        | ((
              info: Parameters<Parameters<typeof http.get>[1]>[0],
          ) => Promise<AccountRetrieveCurrent> | AccountRetrieveCurrent),
    options?: RequestHandlerOptions,
) => {
    return http.get(
        '*/api/accounts/me/',
        async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
            await delay(
                (() =>
                    process.env?.MSW_DELAY
                        ? parseInt(process.env.MSW_DELAY)
                        : 0)(),
            );

            return HttpResponse.json(
                overrideResponse !== undefined
                    ? typeof overrideResponse === 'function'
                        ? await overrideResponse(info)
                        : overrideResponse
                    : getApiAccountsMeRetrieveResponseMock(),
                { status: 200 },
            );
        },
        options,
    );
};

export const getApiAccountsSwitchCreateMockHandler = (
    overrideResponse?:
        | void
        | ((
              info: Parameters<Parameters<typeof http.post>[1]>[0],
          ) => Promise<void> | void),
    options?: RequestHandlerOptions,
) => {
    return http.post(
        '*/api/accounts/switch/',
        async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
            await delay(
                (() =>
                    process.env?.MSW_DELAY
                        ? parseInt(process.env.MSW_DELAY)
                        : 0)(),
            );
            if (typeof overrideResponse === 'function') {
                await overrideResponse(info);
            }

            return new HttpResponse(null, { status: 204 });
        },
        options,
    );
};
export const getAccountMock = () => [
    getApiAccountsListMockHandler(),
    getApiAccountsRetrieveMockHandler(),
    getApiAccountsUpdateMockHandler(),
    getApiAccountsPartialUpdateMockHandler(),
    getApiAccountsAiApiKeyRetrieveMockHandler(),
    getApiAccountsAiApiKeyUpdateMockHandler(),
    getApiAccountsAiApiKeyDestroyMockHandler(),
    getApiAccountsCustomTranslationsRetrieveMockHandler(),
    getApiAccountsSetDefaultVersionUpdateMockHandler(),
    getApiAccountsSetDefaultVersionPartialUpdateMockHandler(),
    getApiAccountsMeRetrieveMockHandler(),
    getApiAccountsSwitchCreateMockHandler(),
];
