# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField(choices=[('backup_import', 'Mobile backup'), ('csv_import', 'Testing'), ('historic_import', 'Historic'), ('locations_areas_import', 'Health areas'), ('locations_import', 'Locations'), ('pv_import', 'Pharmacovigilance'), ('reconciled_import', 'Reconciled data'), ('sync_import', 'Synced device'), ('merge_import', 'Merge duplicates'), ('import_error', 'Error')], null=True)),
                ('stamp', models.DateTimeField(auto_now_add=True)),
                ('num_total', models.PositiveIntegerField(default=0)),
                ('num_created', models.PositiveIntegerField(default=0)),
                ('num_updated', models.PositiveIntegerField(default=0)),
                ('num_deleted', models.PositiveIntegerField(default=0)),
                ('extra_stats', models.TextField(null=True)),
                ('filename', models.TextField(unique=True, null=True)),
                ('file_hash', models.TextField(unique=True, null=True)),
                ('content', models.BinaryField(null=True)),
                ('mimetype', models.TextField(null=True)),
                ('documents', models.TextField(null=True)),
                ('device_id', models.TextField(null=True)),
            ],
        ),
    ]
