# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_export', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportLog',
        ),
    ]
