CATT = 'CATT'
PG = 'PG'
PL = 'PL'
CTCWOO = 'CTCWOO'
MAECT = 'MAECT'
RDT = 'RDT'

TEST_TYPE_CHOICES = (
    (CATT, 'CATT'),
    (PG, 'PG'),
    (PL, 'PL'),
    (CTCWOO, 'CTCWOO'),
    (MAECT, 'MAECT'),
    (RDT, 'RDT')
)
TYPES_CONFIRMATION = set([PG, CTCWOO, MAECT, PL])
TYPES_WITH_IMAGES = set([CATT, RDT])
TYPES_WITH_VIDEOS = set([PG, CTCWOO, MAECT, PL])
