/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Iaso
 * Iaso Swagger
 * OpenAPI spec version: v1
 */
import { faker } from '@faker-js/faker';

import { HttpResponse, delay, http } from 'msw';
import type { RequestHandlerOptions } from 'msw';

import { OpEnum } from '../../models';
import type { PaginatedInstanceModificationList } from '../../models';

export const getApiDiffInstancesListResponseMock = (
    overrideResponse: Partial<
        Extract<PaginatedInstanceModificationList, object>
    > = {},
): PaginatedInstanceModificationList =>
    faker.helpers.arrayElement([
        {
            count: faker.helpers.arrayElement([faker.number.int(), undefined]),
            has_next: faker.helpers.arrayElement([
                faker.datatype.boolean(),
                undefined,
            ]),
            has_previous: faker.helpers.arrayElement([
                faker.datatype.boolean(),
                undefined,
            ]),
            limit: faker.helpers.arrayElement([faker.number.int(), undefined]),
            page: faker.helpers.arrayElement([faker.number.int(), undefined]),
            pages: faker.helpers.arrayElement([faker.number.int(), undefined]),
            results: faker.helpers.arrayElement([
                Array.from(
                    { length: faker.number.int({ min: 1, max: 10 }) },
                    (_, i) => i + 1,
                ).map(() => ({
                    created_at:
                        faker.date.past().toISOString().slice(0, 19) + 'Z',
                    content_type: faker.string.alpha({
                        length: { min: 10, max: 20 },
                    }),
                    object_id: faker.string.alpha({
                        length: { min: 10, max: 20 },
                    }),
                    diff: Array.from(
                        { length: faker.number.int({ min: 1, max: 10 }) },
                        (_, i) => i + 1,
                    ).map(() => ({
                        op: faker.helpers.arrayElement(Object.values(OpEnum)),
                        path: faker.string.alpha({
                            length: { min: 10, max: 20 },
                        }),
                        value: faker.helpers.arrayElement([{}, undefined]),
                        from: faker.helpers.arrayElement([
                            faker.string.alpha({
                                length: { min: 10, max: 20 },
                            }),
                            undefined,
                        ]),
                    })),
                    past_value: {},
                    new_value: {},
                    files: {
                        [faker.string.alphanumeric(5)]: faker.internet.url(),
                    },
                    possible_fields: Array.from(
                        { length: faker.number.int({ min: 1, max: 10 }) },
                        (_, i) => i + 1,
                    ).map(() => ({})),
                    form_descriptor: faker.helpers.arrayElement([{}, null]),
                })),
                undefined,
            ]),
            ...overrideResponse,
        },
        {
            count: faker.helpers.arrayElement([faker.number.int(), undefined]),
            has_next: faker.helpers.arrayElement([
                faker.datatype.boolean(),
                undefined,
            ]),
            has_previous: faker.helpers.arrayElement([
                faker.datatype.boolean(),
                undefined,
            ]),
            limit: faker.helpers.arrayElement([faker.number.int(), undefined]),
            page: faker.helpers.arrayElement([faker.number.int(), undefined]),
            pages: faker.helpers.arrayElement([faker.number.int(), undefined]),
            results: faker.helpers.arrayElement([
                Array.from(
                    { length: faker.number.int({ min: 1, max: 10 }) },
                    (_, i) => i + 1,
                ).map(() => ({
                    created_at:
                        faker.date.past().toISOString().slice(0, 19) + 'Z',
                    content_type: faker.string.alpha({
                        length: { min: 10, max: 20 },
                    }),
                    object_id: faker.string.alpha({
                        length: { min: 10, max: 20 },
                    }),
                    diff: Array.from(
                        { length: faker.number.int({ min: 1, max: 10 }) },
                        (_, i) => i + 1,
                    ).map(() => ({
                        op: faker.helpers.arrayElement(Object.values(OpEnum)),
                        path: faker.string.alpha({
                            length: { min: 10, max: 20 },
                        }),
                        value: faker.helpers.arrayElement([{}, undefined]),
                        from: faker.helpers.arrayElement([
                            faker.string.alpha({
                                length: { min: 10, max: 20 },
                            }),
                            undefined,
                        ]),
                    })),
                    past_value: {},
                    new_value: {},
                    files: {
                        [faker.string.alphanumeric(5)]: faker.internet.url(),
                    },
                    possible_fields: Array.from(
                        { length: faker.number.int({ min: 1, max: 10 }) },
                        (_, i) => i + 1,
                    ).map(() => ({})),
                    form_descriptor: faker.helpers.arrayElement([{}, null]),
                })),
                undefined,
            ]),
            ...overrideResponse,
        },
    ]);

export const getApiDiffInstancesListMockHandler = (
    overrideResponse?:
        | PaginatedInstanceModificationList
        | ((
              info: Parameters<Parameters<typeof http.get>[1]>[0],
          ) =>
              | Promise<PaginatedInstanceModificationList>
              | PaginatedInstanceModificationList),
    options?: RequestHandlerOptions,
) => {
    return http.get(
        '*/api/diff/instances/:instanceId/',
        async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
            await delay(
                (() =>
                    process.env?.MSW_DELAY
                        ? parseInt(process.env.MSW_DELAY)
                        : 0)(),
            );

            return HttpResponse.json(
                overrideResponse !== undefined
                    ? typeof overrideResponse === 'function'
                        ? await overrideResponse(info)
                        : overrideResponse
                    : getApiDiffInstancesListResponseMock(),
                { status: 200 },
            );
        },
        options,
    );
};
export const getSubmissionDiffMock = () => [
    getApiDiffInstancesListMockHandler(),
];
