MODULE_PERMISSIONS = {
    "DATA_COLLECTION_FORMS": [
        "iaso_forms",
        "iaso_update_submission",
        "iaso_submissions",
        "iaso_completeness",
        "iaso_completeness_stats",
    ],
    "DEFAULT": [
        "iaso_org_units",
        "iaso_org_unit_types",
        "iaso_org_unit_groups",
        "iaso_sources",
        "iaso_write_sources",
        "iaso_links",
        "iaso_data_tasks",
        "iaso_reports",
        "iaso_projects",
        "iaso_users",
        "iaso_user_roles",
        "iaso_teams",
        "iaso_modules",
    ],
    "DHIS2_MAPPING": ["iaso_mappings"],
    "EMBEDDED_LINKS": ["iaso_pages", "iaso_page_write"],
    "ENTITIES": [
        "iaso_entities",
        "iaso_workflows",
        "iaso_entity_duplicates_write",
        "iaso_entity_duplicates_read",
        "iaso_entity_type_write",
    ],
    "EXTERNAL_STORAGE": ["iaso_storages"],
    "PLANNING": ["iaso_assignments", "iaso_planning"],
    "POLIO_PROJECT": [
        "iaso_polio_config",
        "iaso_polio",
        "iaso_polio_budget_admin",
        "iaso_polio_budget",
        "iaso_polio_vaccine_supply_chain_read",
        "iaso_polio_vaccine_supply_chain_write",
        "iaso_polio_vaccine_stock_management_read",
        "iaso_polio_vaccine_stock_management_write",
        "iaso_polio_notifications",
        "iaso_polio_vaccine_authorizations_read_only",
        "iaso_polio_vaccine_authorizations_admin",
    ],
    "REGISTRY": ["iaso_registry", "iaso_org_unit_change_request_review"],
    "TRYPELIM_PROJECT": [
        "iaso_trypelim_anonymous",
        "iaso_trypelim_case_analysis",
        "iaso_trypelim_case_cases",
        "iaso_trypelim_case_reconciliation",
        "iaso_trypelim_datas_download",
        "iaso_trypelim_datasets_datauploads",
        "iaso_trypelim_datasets_villageuploads",
        "iaso_trypelim_datas_patient_edition",
        "iaso_trypelim_duplicates",
        "iaso_trypelim_lab",
        "iaso_trypelim_labupload",
        "iaso_trypelim_locator",
        "iaso_trypelim_management_areas",
        "iaso_trypelim_management_coordinations",
        "iaso_trypelim_management_devices",
        "iaso_trypelim_management_edit_areas",
        "iaso_trypelim_management_edit_shape_areas",
        "iaso_trypelim_management_edit_shape_zones",
        "iaso_trypelim_management_edit_zones",
        "iaso_trypelim_management_health_structures",
        "iaso_trypelim_management_plannings",
        "iaso_trypelim_management_plannings_template",
        "iaso_trypelim_management_teams",
        "iaso_trypelim_management_users",
        "iaso_trypelim_management_villages",
        "iaso_trypelim_management_workzones",
        "iaso_trypelim_management_zones",
        "iaso_trypelim_modifications",
        "iaso_trypelim_plannings_macroplanning",
        "iaso_trypelim_plannings_microplanning",
        "iaso_trypelim_plannings_routes",
        "iaso_trypelim_qualitycontrol",
        "iaso_trypelim_stats_graphs",
        "iaso_trypelim_stats_reports",
        "iaso_trypelim_vectorcontrol",
        "iaso_trypelim_vectorcontrolupload",
    ],
}

MODULES = [
    {"name": "Data collection - Forms", "codename": "DATA_COLLECTION_FORMS"},
    {"name": "Default", "codename": "DEFAULT"},
    {"name": "DHIS2 mapping", "codename": "DHIS2_MAPPING"},
    {"name": "Embedded links", "codename": "EMBEDDED_LINKS"},
    {"name": "Entities", "codename": "ENTITIES"},
    {"name": "External storage", "codename": "EXTERNAL_STORAGE"},
    {"name": "Planning", "codename": "PLANNING"},
    {"name": "Polio project", "codename": "POLIO_PROJECT"},
    {"name": "Registry", "codename": "REGISTRY"},
    {"name": "Trypelim project", "codename": "TRYPELIM_PROJECT"},
]
