
name: deploy test

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Iaso-playground, Iaso-staging, or Iaso-env (prod)
        required: true
      slack_channel:
        description: Slack Channel for notification (iasops by default)
        required: false
        default: iasops
# Branch is chosen by default in github manual actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Use node.js 10
        uses: actions/setup-node@v1
        with:
                node-version: 10

      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Setup beanstalk
        run: |
           cp .elasticbeanstalk/config.github.yml .elasticbeanstalk/config.yml
           pip install awsebcli --upgrade
