name: deploy_docker_manual

on:
  push:
    branches:
      - IA-4812-clean-and-optimize-c-is-to-build-images-for-deployment-rebase
  workflow_dispatch:
    inputs:
      image_tag:
        description: Tag to deploy (without the "blsq/iaso:" prefix, e.g. "develop", "IA-4856", or "v2026.06.01")
        required: true
        type: string
      branch:
        description: Branch to deploy
        required: true
        default: main
      environment:
        description: playground, staging, demo or prod for worker and web or exact Env name like iaso-stg-worker. Using `upgrade` for now to test
        required: true
        default: upgrade
      slack_channel:
        description: Slack Channel for notification (iasops by default)
        required: false
        default: cloud-alerts

permissions:
  contents: read
  packages: read

jobs:
  deploy:
    uses: ./.github/workflows/wc_docker_deploy.yml
    with:
      image_tag: ${{ github.event.inputs.image_tag }}
      branch: ${{ github.event.inputs.branch }}
      environment: ${{ github.event.inputs.environment }}
      slack_channel: ${{ github.event.inputs.slack_channel }}
    secrets: inherit
