name: Iaso develop branch

on:
  push:
    branches:
      - develop-test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: read

jobs:
  config:
    uses: ./.github/workflows/wc_config.yml
    permissions:
      pull-requests: write
      contents: read
    with:
#      branch: develop
      branch: develop-test
      pr_title: ${{ github.event.pull_request.title }}

  build_and_push_image:
    needs: config
    uses: ./.github/workflows/wc_docker_build.yml
    with:
#      branch: develop
      branch: develop-test
      image_tags: ${{ needs.config.outputs.image_tags }}
    secrets: inherit

  tests:
    uses: ./.github/workflows/wc_tests.yml
    with:
      branch: ${{ github.head_ref || github.ref_name }}

  deploy_on_staging:
#    needs: [ build_and_push_image, tests ]
    needs: [ build_and_push_image ]
    uses: ./.github/workflows/wc_docker_deploy.yml
    with:
#      branch: develop
      branch: develop-test
#      environment: staging
      environment: upgrade
      image_tag: develop-test
#      image_tag: develop
#      slack_channel: iasops
    secrets: inherit
