name: Iaso develop branch

on:
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: read

jobs:
  config:
    uses: BLSQ/iaso-ci/.github/workflows/config.yml@IA-5227-decouple-ci-actions-into-dedicated-repo
    permissions:
      pull-requests: write
      contents: read
    with:
      branch: develop
      pr_title: ${{ github.event.pull_request.title }}

  build_and_push_image:
    needs: config
    uses: BLSQ/iaso-ci/.github/workflows/docker_build.yml@IA-5227-decouple-ci-actions-into-dedicated-repo
    with:
      iaso_branch: develop
      image_tags: ${{ needs.config.outputs.image_tags }}
    secrets: inherit

  tests:
    uses: BLSQ/iaso-ci/.github/workflows/tests.yml@IA-5227-decouple-ci-actions-into-dedicated-repo
    with:
      iaso_branch: develop

  deploy_on_staging:
    needs: [ build_and_push_image, tests ]
    uses: BLSQ/iaso-ci/.github/workflows/docker_deploy.yml@IA-5227-decouple-ci-actions-into-dedicated-repo
    with:
      iaso_branch: develop
#      environment: staging
      environment: migration
      image_tag: develop
    secrets: inherit
