name: Iaso main branch
on:
  push:
    tags:
      - v*

permissions:
  contents: read
  packages: read

jobs:
  check_on_main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Check if tag is part of main
        run: |
          git fetch origin main
          if git merge-base --is-ancestor ${{ github.sha }} origin/main; then
            echo "Tag is on main, proceeding."
          else
            echo "Tag is not on main, stopping."
            exit 1
          fi

  tests:
    needs: [ check_on_main ]
    uses: BLSQ/iaso-ci/.github/workflows/tests.yml@main
    with:
      iaso_branch: main

  build_and_push_image:
    needs: [ check_on_main, tests ]
    uses: BLSQ/iaso-ci/.github/workflows/docker_build.yml@main
    with:
      iaso_branch: main-test
      image_tags: ${{ github.ref_name }},main
    secrets: inherit
