name: Automated CI testing
# This workflow run automatically for every commit on github it checks the syntax and launch the tests.
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: mdillon/postgis:10
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a health check
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Test of ${{ github.ref }} on ${{ github.event.inputs.environment }}
        run: |
          echo "Deployment of ${{ env.GITHUB_REF }}"
          echo "Deployment of ${{ env.GITHUB_SHA }}"
          echo "Deployment of $GITHUB_REF"
          echo "Deployment of $GITHUB_JOB"
          echo ${GITHUB_REF##*heads/}
          export GITHUB_BRANCH=${GITHUB_REF##*heads/}
          echo $GITHUB_BRANCH
          echo ${{ github.event.inputs }}

