name: Iaso pull requests

on:
  pull_request:
    types: [ opened, synchronize, ready_for_review ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: read

jobs:
  config:
    uses: BLSQ/iaso-ci/.github/workflows/config.yml@main
    permissions:
      pull-requests: write
      contents: read
    with:
      branch: ${{ github.head_ref || github.ref_name }}
      pr_title: ${{ github.event.pull_request.title }}

  build_and_push_image:
    needs: config
    uses: BLSQ/iaso-ci/.github/workflows/docker_build.yml@main
    with:
      iaso_branch: ${{ github.head_ref || github.ref_name }}
      image_tags: ${{ needs.config.outputs.image_tags }}
    secrets: inherit

  tests:
    uses: BLSQ/iaso-ci/.github/workflows/tests.yml@main
    with:
      iaso_branch: ${{ github.head_ref || github.ref_name }}
