name: smoke_tests

on:
  workflow_dispatch:
    inputs:
      GIT_TAG:
        type: string
        description: Git tag expected by health check endpoints to verify the deployed version.
        required: false
      SAVE_SMOKE_TEST_SCREENSHOT:
        type: boolean
        description: When enabled, smoke tests will capture and store screenshots (useful for debugging, as Playwright already captures screenshots automatically on test failures).
        required: false
      SMOKE_TEST_MONITOR_CONSOLE_ERRORS:
        type: boolean
        description: When enabled, tests will fail if any console.error is detected in the browser.
        required: false
      HEALTH_ENV:
        description: List of environments to run health checks against. If not provided, all environments will be checked by default.
        required: false

env:
  GIT_TAG: ${{ github.ref_type == 'tag' && github.ref_name || github.event.inputs.GIT_TAG }}
  SAVE_SMOKE_TEST_SCREENSHOT: ${{ github.event.inputs.SAVE_SMOKE_TEST_SCREENSHOT}}
  SMOKE_TEST_MONITOR_CONSOLE_ERRORS: ${{ github.event.inputs.SMOKE_TEST_MONITOR_CONSOLE_ERRORS }}
  HEALTH_ENV: ${{ github.event.inputs.HEALTH_ENV }}
  CI: true

jobs:
  smoke_test:
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    steps:
      - name: Configuration output
        run: |
          echo "GIT_TAG: $GIT_TAG"
          echo "SAVE_SMOKE_TEST_SCREENSHOT: $SAVE_SMOKE_TEST_SCREENSHOT"
          echo "SMOKE_TEST_MONITOR_CONSOLE_ERRORS: $SMOKE_TEST_MONITOR_CONSOLE_ERRORS"

      - name: Use node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: upgrade npm
        run: |
          npm install -g npm@11.13.0

      - name: install dependencies
        run: npm ci

      - name: install playwright
        run: npx playwright install --with-deps

      - name: run tests
        run: npm run test:smoke

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: |
            playwright-report/
            test-results/
          retention-days: 15


